# -*- coding: utf-8 -*-
from og_data_oabt_d import expand, F

TOPICS = []

def add(ders, prefix, rows):
    for title, trap, pts, qas in rows:
        TOPICS.append(expand(ders, prefix, title, trap, pts, qas))


add("ÖABT Sınıf Öğretmenliği", "oabt_sinif", [
    ("İlkokulda Temel Matematik",
     "İşlem ezberi sayı hissinin yerine geçmez. 2026'da 30 alan bilgisi + 20 alan eğitimi = 50 soru.",
     ["**Sayı hissi** basamak, tahmin, esnek işlem.",
      "**Toplama-çıkarma** parça-bütün; **çarpma** tekrarlı toplama.",
      "**Kesir** parça-bütün ve sayı doğrusu.",
      "**Ölçme** standart-standart olmayan birim.",
      "**Geometri** şekil, simetri, çevre-alan ilkokul düzeyinde.",
      "**Problem** 4 işlem gerçek hayat.",
      "**Örüntü** cebirsel düşüncenin tohumu.",
      "**Veri** nesne grafiği, sıklık.",
      "**Hata analizi** basamak değeri yanılgısı.",
      "**Somut-yarı somut-soyut** (CRA).",
      "İlkokul matematiği **işlem hızı yarışı** değildir.",
      "Sıfır ve basamak **yer değeri** tuzakları.",
      "Eşit işaret **denge** anlamındadır, 'sonuç' değil.",
      "TYMM **matematiksel okuryazarlık**.",
      "Sınav: kavram + yanılgı."],
     [F("Sayı hissi nedir?", "Sayıları esnek kullanma ve tahmin yeterliği", ["Yalnızca ezber çarpım tablosu", "Yalnızca cetvel", "Yalnızca IQ", "Yalnızca yarış"], "Number sense."),
      F("CRA yaklaşımı nedir?", "Somut, yarı somut, soyut sıra", ["Soyuttan başlamak zorunlu", "Yalnızca formül", "Yalnızca yarış", "Yalnızca test"], "Bruner hattı."),
      F("Eşit işaretinin doğru anlamı nedir?", "Denge / eşitlik", ["İşlemin sonu her zaman", "Topla demek", "Eşittir yazma yasağı", "Çarpı"], "Relational."),
      F("Kesir öğretiminde ilk model hangisidir?", "Parça-bütün", ["Karmaşık denklem", "Türev", "Matris", "Logaritma"], "Pizza-çubuk."),
      F("Basamak değeri yanılgısı örneği nedir?", "23'ü 2+3 sanmak", ["23'ü 20+3 görmek", "Tahmin", "Örüntü", "Grafik"], "Place value."),
      F("İlkokulda alan kavramına giriş nasıl olur?", "Birim karelerle kaplama", ["İntegral", "Heron", "Kosinüs", "Determinant"], "Ölçme."),
      F("Örüntü neden önemlidir?", "Cebirsel düşünceyi hazırlar", ["Süs içindir yalnızca", "Müzik yasağı", "Resim yasağı", "Oyun yasağı"], "Pattern."),
      F("2026 Sınıf ÖABT soru yapısı nedir?", "30 alan bilgisi + 20 alan eğitimi", ["80 AGS", "50 AGS tek", "10+10", "100 test"], "50 soru.")]),
    ("İlkokulda Temel Fen Bilimleri",
     "Fen ezber tanım değil; gözlem, tahmin, deney. Canlı-cansız ve madde halleri klasikleridir.",
     ["**Bilimsel süreç**: gözlem, sınıflama, ölçme, çıkarım.",
      "**Canlıların ortak özellikleri** ve çeşitlilik.",
      "**Madde** hal değişimi, karışım-element basitleştirilmiş.",
      "**Kuvvet ve hareket** itme-çekme.",
      "**Işık-ses** kaynak ve yayılma ilkokul.",
      "**Dünya-güneş-ay** gece gündüz, mevsim.",
      "**Besin zinciri** üretici-tüketici.",
      "**Çevre** geri dönüşüm, tasarruf.",
      "**Güvenlik** deney kuralları.",
      "**Yanılgı** 'bitkiler gece ölür', 'kalın cisim batar'.",
      "Sınıf deneyi **basit malzeme**.",
      "Fen defteri **çizim+cümle**.",
      "TYMM **fen okuryazarlığı**.",
      "Doğa gözlemi **okul bahçesi**.",
      "Sınav: süreç + yanılgı."],
     [F("Bilimsel süreç becerisi örneği nedir?", "Gözlem ve sınıflama", ["Ezber tanım tek", "Kopya", "Ceza", "Yoklama"], "Inquiry."),
      F("Gece-gündüzün temel nedeni nedir?", "Dünya'nın kendi ekseni etrafında dönmesi", ["Güneş'in sönmesi", "Ay'ın düşmesi", "Bulutların rengi", "Rüzgar"], "Astronomi."),
      F("Batma-yüzme yanılgısı nedir?", "Kalın her cisim batar sanmak", ["Yoğunluk farkı", "Kuvvet", "Hacim", "Sıvı"], "Kavram yanılgısı."),
      F("Besin zincirinde üretici kimdir?", "Bitkiler (fotosentez)", ["Aslan", "Kartal", "İnsan yalnızca", "Mantar tüketici tek"], "Enerji girişi."),
      F("İlkokul deneyinde güvenlik kuralı nedir?", "Öğretmen denetimi ve malzeme kontrolü", ["Asit içmek", "Ateş serbest", "Camı kırmak", "Gözlüksüz kimyasal"], "Güvenlik."),
      F("Kuvvet ilkokulda nasıl tanıtılır?", "İtme ve çekme etkisi", ["Newton yasası formül ezberi zorunlu", "Türev", "Vektör uzayı", "Relativite"], "Fen 3-4."),
      F("Hal değişimi örneği nedir?", "Buzun erimesi", ["Kesir toplama", "Fiil çekimi", "Harita", "Ritim"], "Madde."),
      F("Fen okuryazarlığı ne ister?", "Günlük olayı bilimsel bakışla açıklama", ["Ansiklopedi ezberi", "Latin isim yarışı", "Sınav korkusu", "Laboratuvar yasağı"], "PISA hattı.")]),
    ("Türk Dili",
     "Ses-harf-hece-sözcük-cümle basamakları atlanmaz. İlkokul Türkçesi dil bilgisi yarışı değildir.",
     ["**Ses farkındalığı** okuma yazmanın önkoşulu.",
     "**Büyük ünlü uyumu** ve yazım.",
     "**Noktalama** anlamı değiştirir.",
     "**Sözcük türleri** işlevle tanıtılır.",
     "**Cümlede anlam** yargı.",
     "**Metin türleri** öykü, şiir, bilgilendirici.",
     "**Anlama** ana fikir, başlık.",
     "**Anlatma** sözlü-yazılı.",
     "**Deyim-atasözü** bağlam.",
     "**Yazım kılavuzu** ilkokul düzeyinde.",
     "Ağız özelliği **yanlış sayılmaz hemen**.",
     "Okuma **akıcı+anlamlı**.",
     "Yazma **süreç** (taslak-düzeltme).",
     "Söz varlığı **bağlam içinde**.",
     "Sınav: dil bilgisi + anlam."],
     [F("Ses farkındalığı neden kritiktir?", "Okuma yazma önkoşulu olması", ["Noktalama tek", "Roman tahlili", "Divan edebiyatı", "Aruz"], "Phonemic."),
      F("Akıcı okuma neyi birleştirir?", "Hız, doğruluk ve prozodi", ["Yalnızca hız yarışı", "Yalnızca hecelemeyi", "Yalnızca ezberi", "Yalnızca sesli harf"], "Fluency."),
      F("Yazma öğretiminde süreç nedir?", "Taslak, düzeltme, yayımlama", ["Tek sefer temize zorunlu hatasız", "Kopya", "Dikte tek", "İmla tek"], "Process."),
      F("Ana fikir ilkokulda nasıl aranır?", "Metnin savunduğu temel yargı", ["İlk sözcük", "En uzun cümle", "Başlık fontu", "Yazar adı"], "Anlama."),
      F("Deyim öğretiminde bağlam neden şarttır?", "Mecazın cümlede çözülmesi", ["Sözlük ezberi yeter", "Harf sayısı", "Hece sayısı", "Nokta sayısı"], "Anlam."),
      F("Büyük ünlü uyumu nedir?", "Ünlülerin kalınlık-incelik uyumu", ["Ünsüz benzeşmesi", "Kaynaştırma", "Ünlü düşmesi", "Ulama"], "Yazım."),
      F("Bilgilendirici metnin amacı nedir?", "Bilgi vermek", ["Olay anlatmak zorunlu", "Duygu şöleni tek", "Tartışma tek", "Oyun tek"], "Tür."),
      F("Ağız özelliğine ilk tepki ne olmamalıdır?", "Hemen hata damgası", ["Dinleme", "Standart dile nazik geçiş", "Zenginliği konuşma", "Metinle karşılaştırma"], "Dil farkındalığı.")]),
    ("Türk Tarihi ve Kültürü",
     "İlkokul tarihi kahraman ezberi + somut kültür (bayram, motif, müze) ister. Kronoloji yetişkin ÖABT Tarih kadar ince değildir.",
     ["**Milli mücadele** çocuk düzeyinde bağımsızlık öyküsü.",
      "**Cumhuriyet değerleri** bayrak, İstiklal Marşı, 23 Nisan.",
      "**Atatürk** çocukluk, eğitim, inkılap somut örnekleri.",
      "**Anadolu uygarlıkları** somut miras (Hitit, Frig, vb. ad düzeyinde).",
      "**Osmanlıdan Cumhuriyete** süreklilik-kopuş sade.",
      "**Halk kültürü** masal, türkü, el sanatı.",
      "**Müze ve ören yeri** kanıt temelli sosyal bilgiler geçişi.",
      "**Somut olmayan miras**.",
      "**Birlikte yaşama** kültür çeşitliliği.",
      "**Kronoloji şeridi** önce-sonra.",
      "Kahramanlık **nefret dili olmadan**.",
      "Yerel tarih **aile ve mahalle**.",
      "Kaynak **görsel ve nesne**.",
      "TYMM **millî-manevi değer**.",
      "Sınav: değer + somut örnek."],
     [F("23 Nisan ilkokulda hangi değeri taşır?", "Egemenliğin millete ait oluşu ve çocuklara armağan", ["Savaş övgüsü tek", "Bayram tatili tek", "Sınav günü", "Kış günü"], "Ulusal egemenlik."),
      F("İlkokulda tarih öğretiminin aracı nedir?", "Öykü, nesne, müze, görsel", ["Arşiv paleografisi zorunlu", "Osmanlıca metin", "Monografi", "Dipnot"], "Yaşa uygun."),
      F("Kronoloji şeridi ne işe yarar?", "Önce-sonra ilişkisini somutlamak", ["Harita projeksiyonu", "Kesir", "Ritim", "Isınma"], "Zaman."),
      F("Somut olmayan kültürel miras örneği nedir?", "Masal, türkü, geleneksel zanaat bilgisi", ["Sadece kale duvarı", "Sadece maden", "Sadece fay", "Sadece baraj"], "UNESCO hattı."),
      F("Atatürk öğretiminde ölçüt nedir?", "Çocukluk ve inkılapların yaşantıya bağlı öyküsü", ["Kişilik kültü nefret", "Tarih dışı efsane yığın", "Siyasi polemik", "Ezber nutuk yarışı"], "Tarihsel düşünme."),
      F("Yerel tarihin katkısı nedir?", "Aidiyet ve kanıt toplama", ["Ulusal tarihi iptal", "Coğrafyayı iptal", "Matematiği iptal", "Feni iptal"], "Yakın çevre."),
      F("Milli mücadele anlatısında durulması gereken nedir?", "Bağımsızlık ve millet iradesi", ["Düşman millet nefreti tek amaç", "Savaş oyunu şiddet", "Ezber tarih", "Uydurma kahraman"], "Değer."),
      F("Kültür çeşitliliği ilkokulda nasıl işlenir?", "Birlikte yaşama ve saygı", ["Asimilasyon baskısı", "Dışlama", "Alay", "Tek tip dayatma şiddeti"], "Halkçılık.")]),
    ("Türkiye Coğrafyası ve Jeopolitiği",
     "İlkokul coğrafyası harita becerisi + yaşanan mekân + sade jeopolitik (köprü, komşu, boğaz) ister.",
     ["**Harita** yön, lejant, ölçek sade.",
      "**Yer şekilleri** dağ, ova, plato çocuk dili.",
      "**İklim ve yaşam** giysi-tarım-konut bağları.",
      "**Nüfus ve yerleşme** köy-kent.",
      "**Doğal afet** deprem çantası, toplanma.",
      "**Bölgeler** yedi coğrafi bölge tanışık.",
      "**Komşular ve denizler**.",
      "**Boğazlar** jeopolitik sade.",
      "**Kaynaklar** su, toprak, maden çocuk düzeyinde.",
      "**Sürdürülebilirlik** tasarruf.",
      "Mekân **yakından uzağa**.",
      "Jeopolitik **nefret coğrafyası değil**.",
      "Gözlem **pencere-bahçe-mahalle**.",
      "TYMM **mekânsal düşünme**.",
      "Sınav: beceri + afet + konum."],
     [F("Haritada lejant ne işe yarar?", "Sembollerin anlamını vermek", ["Kuzeyi bozmak", "Ölçeği silmek", "Rengi yasaklamak", "İklimi değiştirmek"], "Okuryazarlık."),
      F("Yakından uzağa ilkesi nedir?", "Önce mahalle sonra ülke-dünya", ["Önce kıta sonra ev", "Önce kutup sonra sınıf", "Önce okyanus sonra bahçe", "Önce uzay sonra sıra"], "Pedagoji."),
      F("Deprem öğretiminde öncelik nedir?", "Güvenli davranış ve hazırlık", ["Korku hikâyesi", "Alay", "Gizleme", "Kaçış paniği oyunu"], "Afet."),
      F("Türkiye'nin jeopolitik konumuna sade örnek nedir?", "Boğazlar ve kıtalar arası köprü", ["Kutup ülkesi oluşu", "Ada okyanus oluşu", "Çöl ülkesi tek", "Buzul kıtası"], "Konum."),
      F("İklim-yaşam bağı örneği nedir?", "Karadeniz'de yağışlı tarım, Akdeniz'de yaz kuraklığı", ["İklimin notu", "İklimin karnesi", "İklimin düdüğü", "İklimin 1RM"], "Beşeri."),
      F("Yedi coğrafi bölge ilkokulda nasıl işlenir?", "Tanışık özellik ve yaşam farkı", ["Ezber il plaka yarışı tek", "Fay formülü", "Köppen tam", "CBS yazılım"], "Bölge."),
      F("Kent-köy karşılaştırması neyi öğretir?", "Yerleşme ve ekonomik faaliyet farkı", ["Düşmanlık", "Aşağılama", "Nefret", "Alay"], "Beşeri."),
      F("Su tasarrufu hangi temaya bağlanır?", "Sürdürülebilirlik", ["Doping", "1RM", "Aruz", "Kapitülasyon"], "Çevre.")]),
    ("Çocuk Edebiyatı",
     "Çocuk edebiyatı sade dil + edebi değer + yaş uygunluğu ister. Didaktik vaaz tek başına edebiyat değildir.",
     ["**Yaşa uygunluk** tema, dil, görsel.",
      "**Resimli kitap** metin-görsel ilişki.",
      "**Masal-fabl-öykü-şiir-çizgi roman** türleri.",
      "**Çocuk gerçekliği** (child's sense).",
      "**Sansür ve korkutma** dengesi.",
      "**Çeviri ve yerli** eser çeşitliliği.",
      "**Eleştirel okuma** kalıp yargı.",
      "**Okuma kültürü** sınıf kitaplığı.",
      "**Yazar-çizer** atölyesi.",
      "**Değer** öykü içinde, vaaz değil.",
      "Kahraman **özdeşim**.",
      "Korku teması **yaş**.",
      "Şiir **ritim ve img**e.",
      "Drama **metni canlandırma**.",
      "Sınav: ölçüt + tür + pedagoji."],
     [F("Resimli kitapta görsel ne yapar?", "Anlamı tamamlar, süs değildir", ["Yalnızca süs", "Metni iptal eder her zaman", "Okumayı yasaklar", "Yazıyı siler"], "İkonometin."),
      F("Yaşa uygunluğun ölçütü nedir?", "Dil, tema ve korku dozunun gelişime uyması", ["Sayfa sayısı tek", "Fiyat", "Yayınevi lüksü", "Kapak parlaklığı"], "Gelişim."),
      F("Didaktik vaaz neden zayıf edebiyattır?", "Sanatsal yaşantı yerine öğüt basması", ["Değer yokluğu", "Ritim yokluğu zorunlu", "Kahraman yokluğu zorunlu", "Görsel yokluğu zorunlu"], "Estetik."),
      F("Fablın klasik özelliği nedir?", "Hayvan kişileştirmesi ve kıssadan hisse", ["Tarih belgesi", "Fen raporu", "Harita", "Denklem"], "Tür."),
      F("Sınıf kitaplığının işlevi nedir?", "Serbest okuma ve çeşitlilik", ["Ceza köşesi", "Toz deposu", "Yasak dolabı", "Not kırma yeri"], "Kültür."),
      F("Kalıp yargı içeren kitapta öğretmen ne yapar?", "Eleştirel konuşma yürütür", ["Körü körüne okutur", "Yakar", "Gizler hiç konuşmadan her zaman", "Alay eder"], "Medya okuryazarlığı."),
      F("Çocuk gerçekliği ne demektir?", "Olayların çocuğun algı ve mantığıyla verilmesi", ["Yetişkin ironisi tek", "Osmanlıca", "Akademik makale", "Resmi rapor"], "Yazarlık."),
      F("Şiirin ilkokuldaki gücü nedir?", "Ritim, imge ve dil zevki", ["Aruz ezberi zorunlu", "Redif sınavı", "Divan tahlili", "Belagat"], "Estetik.")]),
    ("Hayat Bilgisi Öğretimi",
     "Hayat bilgisi 1-3. sınıf bütüncük derstir; sosyal+fen+değer yakından uzağa işlenir.",
     ["**Yakından uzağa, bilinenden bilinmeyene**.",
      "**Tema** ben, aile, okul, yurdum.",
      "**Beceri** öz bakım, iletişim, güvenlik.",
      "**Değer** saygı, sorumluluk, dürüstlük.",
      "**Etkinlik** gezi, gözlem, oyun, drama.",
      "**Atatürkçülük** yaşantıya gömülü.",
      "**Afet ve trafik**.",
      "**Sağlık ve temizlik**.",
      "**Doğa ve canlılar** sade fen.",
      "**Ölçme** gözlem, ürün, öz değerlendirme.",
      "Ders **hayatın kendisi**.",
      "Aile katılımı **ödev değil ortaklık**.",
      "Kaynaştırma **görsel destek**.",
      "TYMM **hayat yeterlikleri**.",
      "Sınav: ilke + tema + yöntem."],
     [F("Hayat bilgisi hangi sınıflardadır?", "1-3. sınıflar", ["Yalnızca lise", "Yalnızca 8. sınıf", "Yalnızca anaokulu zorunlu tek", "Üniversite"], "Program."),
      F("Temel öğretim ilkesi hangisidir?", "Yakından uzağa", ["Uzaktan yakına zorunlu", "Soyuttan somuta zorunlu her zaman", "Formülden oyuna", "Ezberden geziye yasak"], "Pedagoji."),
      F("Hayat bilgisi neden bütüncüldür?", "Sosyal, fen ve değer konularını birleştirir", ["Yalnızca tarih", "Yalnızca matematik", "Yalnızca spor", "Yalnızca müzik"], "Entegre."),
      F("Trafik eğitimi nerede durur?", "Güvenlik teması içinde yaşantı", ["Yalnızca ehliyet kursu", "Yalnızca lise", "Yasak konu", "ÖABT fizik"], "Yaşam."),
      F("Ölçmede uygun araç hangisidir?", "Gözlem formu ve ürün dosyası", ["Yalnızca 80 maddelik test", "LGS", "ALES", "YKS"], "Yaş."),
      F("Aile katılımı nasıl olmalıdır?", "Süreç ortaklığı", ["Ceza ortağı", "Not satışı", "Gizleme", "Yok sayma"], "Okul-aile."),
      F("Atatürkçülük bu derste nasıl işlenir?", "Günlük yaşantı ve somut örnekle", ["Nutuk ezberi yarışı", "Nefret", "Siyaset polemiği", "Boş bırakma"], "Değer."),
      F("Öz bakım becerisi örneği nedir?", "Temizlik, eşya düzeni, zaman", ["Türev", "Osmanlıca", "VO2max", "Kapitülasyon"], "Bağımsızlık.")]),
    ("Sosyal Bilgiler Öğretimi",
     "İlkokul 4. sınıf sosyal bilgiler kanıt, mekân, zaman, kimlik becerileridir; ansiklopedi ezberi değil.",
     ["**NCSS benzeri** zaman, süreklilik, mekân, üretim, kimlik, güç.",
      "**Kanıt** fotoğraf, nesne, tanık.",
      "**Harita ve grafiği** okuma.",
      "**Kimlik** birey-aile-millet dengesi.",
      "**Vatandaşlık** hak-ödev.",
      "**Ekonomi** ihtiyaç-kaynak sade.",
      "**Küresel bağlantı** göç, ticaret çocuk dili.",
      "**Tartışma** saygılı.",
      "**Proje** sınıf araştırması.",
      "**Değer** adalet, sorumluluk.",
      "Tarih **tek kahraman**a indirgenmez.",
      "Coğrafya **yalnızca il ezberi** değildir.",
      "Güncel olay **yaşa uygun**.",
      "TYMM **sosyal okuryazarlık**.",
      "Sınav: beceri + yöntem."],
     [F("Kanıt temelli tarih ne kullanır?", "Nesne, görsel, tanıklık", ["Yalnızca efsane", "Yalnızca ezber yıl", "Yalnızca slogan", "Yalnızca nefret"], "Inquiry."),
      F("Vatandaşlık öğretiminin özü nedir?", "Hak ve ödev dengesi", ["İtaat tek", "Hak yok ödev var", "Ödev yok hak var", "Kaygı"], "Yurttaş."),
      F("Sosyal bilgiler 4. sınıfta neden ayrı derstir?", "Hayat bilgisinden sonra disiplinlerarası sosyal bilimlere geçiş", ["Matematiğin yerine", "Fenin yerine", "Türkçenin yerine", "BE yerine"], "Program."),
      F("Mekân becerisi örneği nedir?", "Harita ve kroki okuma", ["Kesir çarpma", "Fiil çekimi", "Isınma", "Nota"], "Coğrafya."),
      F("Sınıf araştırması nasıl yürütülür?", "Soru, veri, sunum", ["Kopya ansiklopedi tek", "Uydurma", "Ezber slogan", "Sessizlik"], "Proje."),
      F("Kimlik öğretiminde denge nedir?", "Birey, yerel ve milli aidiyetin birlikte verilmesi", ["Tek boyutlu düşman", "Aidiyetsizlik dayatması", "Nefret", "Alay"], "Kimlik."),
      F("Güncel olay seçiminde ölçüt nedir?", "Yaşa uygunluk ve travmasız tartışma", ["En şiddetli haber", "Sansasyon", "Gizleme her zaman", "Parti propagandası"], "Etik."),
      F("Ekonomi teması ilkokulda nasıl somutlanır?", "İhtiyaç, kaynak, tasarruf, meslek", ["Borsa spekülasyonu", "NAIRU", "Kapitülasyon", "Keynes tam"], "Hayat.")]),
    ("Fen Bilimleri Öğretimi",
     "İlkokul fen öğretimi kavram yanılgısını kırmak için deney ve tartışma ister.",
     ["**5E** girme, keşfetme, açıklama, derinleştirme, değerlendirme.",
      "**Kavram yanılgısı** tespit-çürütme.",
      "**Argümantasyon** iddia-kanıt.",
      "**Laboratuvar güvenliği**.",
      "**STEM / tasarım** sade.",
      "**Doğa defteri**.",
      "**Model** (güneş sistemi) sınırlılıkları konuşulur.",
      "**Soru sorma** öğretmenin asıl aracı.",
      "**İşbirlikli deney**.",
      "**Değerlendirme** süreç+ürün.",
      "Ezber tanım **anlamayı göstermez**.",
      "Öğretmen **kolaylaştırıcı**.",
      "Malzeme **ucuz ve güvenli**.",
      "TYMM **fen yetkinliği**.",
      "Sınav: 5E + yanılgı."],
     [F("5E'nin ilk E'si nedir?", "Engage (girme / dikkat çekme)", ["Examine zorunlu ad", "Erase", "Exit", "Exam"], "Bybee."),
      F("Kavram yanılgısı nasıl kırılır?", "Tahmin-gözlem-açıklama ile çelişki yaratmak", ["Bağırmak", "Ezberletmek daha çok", "Cezalandırmak", "Konuyu atlamak"], "Cognitive conflict."),
      F("Argümantasyonda kanıt nedir?", "Gözlem veya veri", ["Öğretmenin sesi tek", "İnternet uydurması", "Arkadaş baskısı", "Kura"], "CER."),
      F("Modelin sınırlılığı neden konuşulur?", "Güneş sistemi maketi gerçek ölçek değildir", ["Model yasaktır", "Fen bitmiştir", "Ölçme yasaktır", "Soru yasaktır"], "Doğa bilim." ),
      F("Fen değerlendirmesinde süreç ne işe yarar?", "Beceri ve tutumu görmek", ["Yalnızca doğru şık", "Yalnızca yazı güzelliği", "Yalnızca sessizlik", "Yalnızca hız"], "Formative."),
      F("STEM tasarımı ilkokulda nasıl sadeleşir?", "Basit problem-çözüm-deneme", ["Üniversite mühendisliği", "CAD zorunlu", "Kodlama tek başına yeter", "Robot yasağı"], "Tasarım."),
      F("İşbirlikli deneyin kuralı nedir?", "Rol ve güvenlik", ["Kalabalık gürültü", "Tek kişi yapar diğer bakar her zaman", "Malzemeyi savurmak", "Raporu uydurmak"], "Grup."),
      F("Öğretmen sorusunun niteliği nasıl olmalıdır?", "Düşünmeyi açan, tek kelimelik kapalıdan zengin", ["Evet-hayır tek", "Cezalandıran", "Alay", "Yanlışı teşhir"], "Questioning.")]),
    ("Matematik Öğretimi",
     "İşlem öğretimi problem ve temsil çeşitliliği ister. Tek algoritma dayatması yanılgı üretir.",
     ["**Çoklu temsil** nesne, resim, sembol, dil.",
      "**Problem çözme** Polya sade: anla-planla-uygula-kontrol.",
      "**Hata analizi** öğretim verisi.",
      "**Oyun ve manipülatif**.",
      "**Sınıf tartışması** (number talk).",
      "**Farklılaştırma**.",
      "**Değerlendirme** zihin fotoğrafı.",
      "**Dil** matematik cümlesi.",
      "**Gerçek hayat** bağlamı sahici olsun.",
      "**Kaynaştırma** somut materyal.",
      "Hız yarışı **kaygı** üretir.",
      "Kız-erkek **kalıp yargı** kırılır.",
      "Ev ödevi **kısa ve anlamlı**.",
      "TYMM **matematik okuryazarlığı**.",
      "Sınav: temsil + yanılgı + yöntem."],
     [F("Polya'nın ilk adımı nedir?", "Problemi anlamak", ["Hemen işlem", "Sonucu uydurmak", "Hesap makinesi", "Kopya"], "Understand."),
      F("Number talk ne işe yarar?", "Zihinden esnek strateji paylaşımı", ["Sessiz yarış", "Cezalı süre", "Tek algoritma", "Ezber tablo"], "Sınıf söylemi."),
      F("Çoklu temsil neden şarttır?", "Aynı kavramın farklı görünümlerini bağlamak", ["Süs", "Zaman doldurma", "Velisiz gezi", "Not kırma"], "Anlam."),
      F("Hata analizi öğretmenin neyidir?", "Öğretim kararı için veri", ["Teşhir malzemesi", "Ceza gerekçesi tek", "Alay", "Karnede hakaret"], "Formative."),
      F("Matematik kaygısını ne artırır?", "Hız yarışı ve utandırma", ["Oyun", "Somut materyal", "Tartışma", "Zaman tanıma"], "Duyuş."),
      F("Manipülatif ne zaman bırakılır?", "Kavram içselleşince yarı somuta geçilir", ["Hiçbir zaman", "İlk günden yasak", "Yalnızca lisede", "Yalnızca üstün zekâlıda"], "CRA."),
      F("Sahici bağlam örneği nedir?", "Sınıfın gerçek ölçüleriyle alan", ["Uçak bileti 1. sınıf çocuğa borsa", "Türev", "Kredi temerrüdü", "NAIRU"], "Hayat."),
      F("Kaynaştırmada matematik uyarlaması nedir?", "Somut araç, ek süre, az madde", ["Konuyu silmek", "Not sıfır", "Dışarı çıkarmak", "Ezberi artırmak"], "Erişim.")]),
    ("Türkçe Öğretimi",
     "Dört beceri birlikte gelişir. Dil bilgisi metinden kopuk işlenmez.",
     ["**Dinleme, konuşma, okuma, yazma** entegrasyonu.",
      "**Strateji öğretimi** tahmin, özet, soru.",
      "**Metin seçimi** yaş ve çeşit.",
      "**Söylem** sınıf içi konuşma kuralları.",
      "**Dil bilgisi** işlevsel.",
      "**Değerlendirme** rubrik.",
      "**İkinci dil / şive** duyarlığı.",
      "**Dijital okuma** güvenli internet.",
      "**Yazım ve noktalama** anlam için.",
      "**Kütüphane saati**.",
      "Sesli okuma **tek yöntem değildir**.",
      "Yazma **otantik alıcı** (sınıf gazetesi).",
      "Anlama **çıkarım**.",
      "TYMM **dil yetkinliği**.",
      "Sınav: beceri + strateji."],
     [F("Dört temel dil becerisi hangileridir?", "Dinleme, konuşma, okuma, yazma", ["Ezber, kopya, ceza, test", "Aruz, redif, kafiye, gazel", "VO2, 1RM, FITT, EPOC", "m.1, m.2, m.3, m.4"], "Entegre."),
      F("Okuma stratejisi örneği nedir?", "Tahmin, özet, soru üretme", ["Hece yarışı tek", "Parmakla vurma tek", "Bağırma", "Cezalı okuma"], "Strateji."),
      F("İşlevsel dil bilgisi nasıl işlenir?", "Metindeki göreviyle", ["Liste ezberi kopuk", "Tablodan bağımsız 50 kural", "Osmanlıca", "Belagat"], "Bağlam."),
      F("Yazma rubriği neyi gösterir?", "Ölçütleri öğrenciye önceden", ["Öğretmenin keyfini", "Gizli notu", "Velinin öfkesini", "Kura"], "Şeffaflık."),
      F("Dijital okumada ek kazanım nedir?", "Kaynak sorgulama ve güvenlik", ["Kopyala yapıştır", "Reklam tıklama", "Şifre paylaşma", "Zorbalık"], "Medya."),
      F("Otantik yazma örneği nedir?", "Sınıf gazetesi, mektup, davetiye", ["Anlamsız 10 satır ceza", "Dikte tek", "İmla listesi tek", "Kopya"], "Alıcı."),
      F("Konuşma öğretiminde iklim nasıl olmalıdır?", "Dinleme ve saygı", ["Alay", "Susturma", "Teşhir", "Bağırma yarışı"], "Söylem."),
      F("Sesli okuma neden tek yöntem olmamalıdır?", "Anlama ve sessiz okuma da gelişmeli", ["Yasak olduğu için", "MEB yasakladı diye uydurma", "Göz bozar efsane tek gerekçe", "Veliler istemez tek"], "Denge.")]),
    ("İlk Okuma ve Yazma Öğretimi",
     "Ses temelli cümle yöntemi Türkiye'de resmi yaklaşımdır. Harf-ses eşlemesi atlanmaz.",
     ["**Ses temelli cümle yöntemi** ses-harf-hece-sözcük-cümle.",
      "**Hazırlık** görsel, işitsel, motor, dil.",
      "**Bitişik eğik / dik temel** yazı tartışması program dönemine göre.",
      "**İlk okuma** anlam odaklı olsun, heceleme takılı kalmasın.",
      "**Değerlendirme** harf-ses, hece, sözcük, cümle, metin.",
      "**Geri kalma** erken müdahale, disleksi şüphesi yönlendirme.",
      "**Aile** evde baskısız dinleme.",
      "**Çoklu duyus** (görme-dokunma-işitme).",
      "**Cümle üretme** ilk günden anlam.",
      "**Yazma motoru** kalem tutuş, satır.",
      "Hata: **alfabeyi sırayla bitirmeden anlam yok** sanmak.",
      "Hata: **cezalı yazı**.",
      "Sınıf **yazı köşesi**.",
      "TYMM **okuryazarlık**.",
      "Sınav: yöntem adı + basamak."],
     [F("Türkiye'de resmi ilk okuma yaklaşımı nedir?", "Ses temelli cümle yöntemi", ["Cümle yöntemi 1960 tek", "Alfabe yöntemi zorunlu tek", "Küresel kelime tek", "Osmanlıca elifba"], "MEB."),
      F("Yöntemin doğru sırası nedir?", "Ses, harf, hece, sözcük, cümle", ["Cümle, roman, ses", "Harf sırası A'dan Z'ye zorunlu anlam yok", "Nokta, virgül, ses", "Şiir, ses, harf"], "Basamak."),
      F("Hazırbulunuşlukta motor alan neden vardır?", "Yazı için kalem ve yön gelişimi", ["VO2max", "1RM", "Doping", "WADA"], "Hazırlık."),
      F("Disleksi şüphesinde öğretmen ne yapar?", "Erken destek ve uzmana yönlendirme", ["Tembellik damgası", "Ceza ödevi", "Sınıf tekrarı tehdidi tek", "Alay"], "Müdahale."),
      F("Anlam odaklı ilk okuma ne demektir?", "Çözülen sözcüğün cümlede işe yaraması", ["Hece robotu", "Hız yarışı", "Noktasız metin", "Anlamsız dizi"], "Anlam."),
      F("Çoklu duyusal öğretim örneği nedir?", "Sesi görmek, duymak, dokunmak", ["Yalnızca bakmak", "Yalnızca ezber listesi", "Yalnızca ceza", "Yalnızca test"], "VAKT."),
      F("Aileye doğru mesaj nedir?", "Baskısız dinleme ve model okuma", ["Gece yarısı dikte cezası", "Kıyas", "Hakaret", "Yarış"], "Ev."),
      F("Yazı öğretiminde kalem tutuş neden önemlidir?", "Akıcılık ve yorgunluk", ["Notu yükseltir sihirle", "Zekâyı artırır", "Disleksiyi yok eder tek başına", "MEB puanı"], "Motor.")]),
    ("Drama",
     "Drama ürün tiyatro oyunu olmak zorunda değildir; süreçte rol ve doğaçlama öğrenme aracıdır.",
     ["**Eğitici drama** süreç; **tiyatro** ürün olabilir.",
      "**Isınma, canlandırma, değerlendirme**.",
      "**Rol kartı, donuk imge, bilinç koridoru** teknikleri.",
      "**Güven ve gönüllülük**.",
      "**Değer ve empati**.",
      "**Dil gelişimi** diyalog.",
      "**Kaynaştırma** sözsüz rol.",
      "**Değerlendirme** süreç, ürün değil tek not.",
      "**Mekân** daire düzeni.",
      "**Öğretmen** kolaylaştırıcı.",
      "Zorla rol **travma** riski.",
      "Alay **yasak iklim**.",
      "Müfredat **hayat bilgisi-sosyal-Türkçe** ile bağ.",
      "Kostüm **şart değil**.",
      "Sınav: süreç + teknik ad."],
     [F("Eğitici dramanın özü nedir?", "Süreçte yaşayarak öğrenme", ["Sahne dekoru zorunlu", "Biletli oyun zorunlu", "Ezber tirat zorunlu", "Jüri"], "Pedagoji."),
      F("Donuk imge nedir?", "Anı dondurulmuş beden tablosu", ["Fotoğraf yasağı", "Heykel sanatı tek", "Yoga", "1RM"], "Teknik."),
      F("Drama dairesi neden kullanılır?", "Eşit katılım ve göz teması", ["Ceza halkası", "Yarış pisti", "Sınav sırası", "Kantin"], "Düzen."),
      F("Gönüllülük neden ilkedir?", "Zorla rolün kaygı ve travma riski", ["MEB yasakladı diye uydurma tek", "Kostüm yokluğu", "Sahne yokluğu", "Müzik yokluğu"], "Etik."),
      F("Bilinç koridoru ne işe yarar?", "Karar anında iç sesleri duyurmak", ["Matematik koridoru", "Teneffüs", "Nöbet", "Servis"], "Düşünme."),
      F("Kaynaştırmada drama nasıl uyarlanır?", "Sözsüz rol, eşli katılım", ["Dışarı çıkarma", "İzleyici zorunlu her zaman", "Alay", "Not sıfır"], "Erişim."),
      F("Değerlendirme nasıl olmalıdır?", "Süreç gözlemi ve öz yansıma", ["Tek final oyunu notu", "En iyi aktör yarışı", "Velilerin alkışı", "Kostüm lüksü"], "Formative."),
      F("Öğretmen rolü nedir?", "Kolaylaştırıcı ve güven sağlayıcı", ["Yönetmen diktatör", "Jüri", "Eleştirmen aşağılayan", "İzleyici yok"], "Facilitator.")]),
    ("Görsel Sanatlar",
     "Görsel sanatlar ürün güzelliği değil görsel dil ve süreçtir. Öğretmen modeli kopyalatmak sanat eğitimi değildir.",
     ["**Çizgi, renk, doku, biçim, kompozisyon** elemanları.",
      "**Süreç** tasarım döngüsü.",
      "**Çocuk resmi gelişimi** karalama-şema-gerçekçilik.",
      "**Müze ve çevre** görsel kültür.",
      "**Geri dönüşüm malzeme**.",
      "**Eleştiri** betimle-çözümle-yorumla.",
      "**Kaynaştırma** kalın fırça, büyük yüzey.",
      "**Değer** kültürel motif saygısı.",
      "**Disiplinlerarası** hayat bilgisi-matematik simetri.",
      "**Sergi** otantik alıcı.",
      "Kopya boyama **tek etkinlik olmamalı**.",
      "Not **yetenek yarışı değil gelişim**.",
      "Güvenlik **makas, boya**.",
      "TYMM **sanat yetkinliği**.",
      "Sınav: eleman + gelişim basamağı."],
     [F("Karalama dönemi neyi gösterir?", "Motor ve ifade başlangıcı", ["Yeteneksizlik", "Boşa zaman", "Disiplin sorunu", "Geri zekâ efsanesi"], "Lowenfeld hattı."),
      F("Görsel eleman örneği nedir?", "Çizgi, renk, doku", ["1RM", "VO2", "m.42", "Ofsayt"], "Eleman."),
      F("Kopya kalıp boyama neden tek yöntem olmamalıdır?", "Yaratıcılığı ve karar vermeyi kısar", ["MEB yasakladı uydurma tek gerekçe", "Boya biter", "Kâğıt biter", "Zaman biter"], "Yaratıcılık."),
      F("Sanat eleştirisinde ilk adım nedir?", "Betimleme", ["Hakaret", "Not", "Kıyas", "Yırtma"], "Feldman sade."),
      F("Kaynaştırma uyarlaması nedir?", "Kalın araç, büyük zemin, ek süre", ["Dersten alma", "Beyaz kâğıt yasağı", "Siyah boya yasağı", "Sergiden dışlama"], "Erişim."),
      F("Serginin pedagojik işlevi nedir?", "Otantik alıcı ve özgüven", ["Yarışma nefreti", "Velileri utandırma", "Not teşhiri", "Satış"], "Alıcı."),
      F("Simetri etkinliği hangi dersle bağlanır?", "Matematik", ["Doping", "WADA", "Kapitülasyon", "Tımar"], "Disiplinlerarası."),
      F("Değerlendirme ölçütü ne olmalıdır?", "Süreç, çaba, görsel dil kullanımı", ["En gerçekçi kopya", "En pahalı malzeme", "En hızlı bitirme", "En sessiz çocuk"], "Rubrik.")]),
    ("Müzik",
     "İlkokul müziği nota yarışı değil ritim, ses, şarkı ve dinleme kültürüdür.",
     ["**Ritim, ezgi, dinamik, timbre** elemanları.",
      "**Orff-Kodaly-Dalcroze** yaklaşımları sade.",
      "**Şarkı dağarcığı** milli ve dünya.",
      "**Çalgı** ritim çalgıları, blok flüt okulda.",
      "**Dinleme** tür çeşitliliği.",
      "**Yaratma** rondo, soru-cevap ezgi.",
      "**İstiklal Marşı** saygı protokolü.",
      "**Kaynaştırma** titreşim, görsel ritim.",
      "**Ses sağlığı** bağırmadan şarkı.",
      "**Disiplinlerarası** şiir, oyun, dans.",
      "Ezgi **kulakla** önce.",
      "Nota **araç**.",
      "Alay **yasak**.",
      "TYMM **müzik yetkinliği**.",
      "Sınav: yaklaşım + eleman + değer."],
     [F("Orff yaklaşımının özü nedir?", "Konuşma, ritim, hareket ve basit çalgı", ["Yalnızca Paganini", "Yalnızca opera ezberi", "Yalnızca nota yarışı", "Yalnızca piyano sınavı"], "Elementer."),
      F("Kodaly'de temel araç nedir?", "Şarkı ve solfej / el işaretleri", ["Sadece davul", "Sadece DJ", "Sadece kulak tıkacı", "Sadece metronom cezası"], "Macar."),
      F("Dalcroze neyi bağlar?", "Müzik ve beden (eurhythmics)", ["Müzik ve vergi", "Müzik ve fay", "Müzik ve doping", "Müzik ve tımar"], "Hareket."),
      F("İstiklal Marşı öğretiminde asıl olan nedir?", "Anlam, saygı ve doğru duruş", ["Hız yarışı", "Bağırma", "Alay", "Unutturma"], "Değer."),
      F("Ses sağlığı kuralı nedir?", "Bağırmadan nefes ve duruş", ["Fısıltı yasak her zaman", "Bağırarak güçlü ol", "Boğazı zorla", "Su içme"], "Sağlık."),
      F("Kaynaştırmada müzik uyarlaması nedir?", "Titreşim, görsel ritim, sade partisyon", ["Dışarı çıkarma", "Sessizlik cezası", "Kulak tıkama alayı", "Not sıfır"], "Erişim."),
      F("Nota okuma neden tek amaç değildir?", "Müzikal yaşantı kulak ve ritimle de gelişir", ["Nota yasaktır", "MEB notayı sildi uydurma", "Çalgı yasaktır", "Şarkı yasaktır"], "Denge."),
      F("Dinleme etkinliğinin kazanımı nedir?", "Tür farkı ve saygılı dinleme", ["Uyuma", "Konuşma", "Yarış", "Alay"], "Kültür.")]),
    ("Beden Eğitimi",
     "Sınıf öğretmeni beden eğitiminde güvenlik, oyun ve temel hareket yeterliği öğretir; elit antrenör değildir.",
     ["**Temel hareket** lokomotor, duruş, nesne kontrolü.",
      "**Oyun** kurala uyma ve katılım.",
      "**Sağlık** ısınma, su, kıyafet.",
      "**Fair play**.",
      "**Kaynaştırma** uyarlanmış oyun.",
      "**Değerlendirme** çaba ve gelişim.",
      "**Güvenlik** saha taraması.",
      "**Ritim ve dans**.",
      "**Doğa yürüyüşü** izinli.",
      "**Kız-erkek eşit katılım**.",
      "Ders **serbest bırakıp kaçmak** değildir.",
      "Not **en hızlı** değildir.",
      "Sakatlıkta **ilk yardım+yönlendirme**.",
      "TYMM **hareket yetkinliği**.",
      "Sınav: güvenlik + oyun + kapsayıcılık."],
     [F("Lokomotor hareket örneği nedir?", "Koşma, galop, sıçrama", ["Yazı yazma", "Düşünme", "Dinleme", "Boyama"], "Hareket."),
      F("Sınıf öğretmeninin BE rolü nedir?", "Güvenli oyun ve temel yeterlik öğretimi", ["Milli takım koçluğu", "Doping", "1RM testi zorunlu", "WADA"], "Pedagoji."),
      F("Uyarlanmış oyuna örnek nedir?", "Yavaş top, büyük hedef, eşli koşu", ["Oturma cezası", "İzleyici zorunlu", "Dışarı", "Alay"], "Kaynaştırma."),
      F("Fair play ilkokulda nasıl yaşanır?", "Kural, sıra, kaybedene saygı", ["Hile", "Hakaret", "İtme", "Dışlama"], "Değer."),
      F("Saha taraması neden yapılır?", "Cam, taş, ıslak zemin riski", ["Estetik", "Fotoğraf", "Gölge", "WiFi"], "Güvenlik."),
      F("Değerlendirmede yanlış nedir?", "Yalnızca doğal sürati notlamak", ["Gelişim", "Çaba", "Kurala uyma", "İşbirliği"], "Adalet."),
      F("Isınma neden vardır?", "Doku ve dikkat hazırlığı", ["Zaman doldurma", "Ceza", "Yarış", "Teşhir"], "Sağlık."),
      F("Kızların katılımı nasıl desteklenir?", "Güvenli soyunma, karışık oyun, rol model", ["Muaf tutup unutmak", "Alay", "Ayrımcılık", "Zorunlu yarış utancı"], "Eşitlik.")]),
    ("Din Kültürü ve Ahlak Bilgisi",
     "İlkokul DKAB anayasa m.24 çerçevesinde; nefret ve tekfir dili yasaktır. Ahlak evrensel değerle örtüşür.",
     ["**Anayasa m.24** din kültürü ve ahlak öğretimi.",
      "**İnanç, ibadet, ahlak** yaş düzeyinde.",
      "**Peygamber** ahlak modeli (sade siyer).",
      "**Dua ve ibadet** bilgi, pratik dayatma değil her öğrencide.",
      "**Diğer dinler** saygı.",
      "**Aile ve komşu** ahlak.",
      "**Çevre ahlakı** emanettir dünya.",
      "**Birlikte yaşama**.",
      "**Değer** dürüstlük, merhamet.",
      "**Ölçme** bilgi+tutum, inanç yoklaması değil.",
      "Muafiyet **idari prosedür**.",
      "Öğretmen **mezhep polemiği yapmaz**.",
      "Hikâye **kıssa** yaş uygun.",
      "TYMM **değer-erdem**.",
      "Sınav: hak + ahlak + yöntem."],
     [F("DKAB'nin anayasal dayanağı hangisidir?", "m.24", ["m.1", "m.4", "m.128", "1739 tek başına"], "Zorunlu ders hükmü."),
      F("Ölçmede etik olmayan nedir?", "Öğrencinin inancını notla yoklamak", ["Bilgi sorusu", "Ahlak ikilemi tartışması", "Metin anlama", "Kavram tanımı"], "Vicdan."),
      F("Diğer dinler nasıl işlenir?", "Bilgi ve saygı", ["Tekfir", "Alay", "Düşmanlık", "Yok sayma her zaman"], "Dinler tarihi sade."),
      F("Ahlak öğretiminin yolu nedir?", "Öykü, ikilem, örnek yaşantı", ["Bağırma", "Ezber tek", "Ceza tek", "Tehdit"], "Değer."),
      F("Muafiyet konusunda öğretmen ne yapar?", "Mevzuata göre idareye yönlendirir", ["Sınıfta tartışıp teşhir eder", "Notla cezalandırır", "Aileyi küçük düşürür", "Dersi iptal eder tüm sınıf için"], "Hukuk."),
      F("Çevre ahlakı nasıl bağlanır?", "Emanet ve tasarruf", ["Doping", "1RM", "Ofsayt", "Kapitülasyon"], "Değer."),
      F("Siyer ilkokulda nasıl verilmelidir?", "Ahlak öyküsü, savaş ayrıntısı yığmadan", ["Gazve listesi ezberi", "Nefret", "Tekfir", "Polemik"], "Yaş."),
      F("Birlikte yaşama kazanımı nedir?", "Farklı inanç ve kültürle saygılı hayat", ["Asimilasyon baskısı", "Dışlama", "Alay", "Zorla ibadet"], "Yurttaşlık.")]),
])
