# -*- coding: utf-8 -*-
from og_data_oabt_d import expand, F

TOPICS = []

def add(ders, prefix, rows):
    for title, trap, pts, qas in rows:
        TOPICS.append(expand(ders, prefix, title, trap, pts, qas))


add("ÖABT Okul Öncesi", "oabt_okul", [
    ("Çocuk Gelişimi",
     "Gelişim alanları iç içedir; motor gecikme dil gecikmesiyle birlikte okunur. 2026 ÖABT 30+20=50.",
     ["**Fiziksel, bilişsel, dil, sosyal-duygusal** alanlar.",
      "**Kritik/duyarlı dönem**.",
      "**Bireysel tempo**.",
      "**Olgunlaşma ve öğrenme**.",
      "**Piaget işlem öncesi** egosantrizm, animizm.",
      "**Vygotsky ZPD ve oyun**.",
      "**Bağlanma** güvenli temel.",
      "**Öz düzenleme** erken çocukluk hedefi.",
      "**Oyun** gelişimin dili.",
      "**Gözlem** gelişim tarama.",
      "Karşılaştırma **norm değil çocuk kendisi**.",
      "Gecikmede **yönlendirme**.",
      "Cinsiyet kalıbı **kırılır**.",
      "TYMM **bütüncül gelişim**.",
      "Sınav: alan + kuram + tarama."],
     [F("İşlem öncesi dönemin klasiği nedir?", "Egosantrizm ve sembolik oyun", ["Soyut hipotez", "Korunum kesin", "Meslek kimliği", "Üretkenlik"], "Piaget."),
      F("ZPD okul öncesinde nasıl görünür?", "Yetişkin veya akran iskelesiyle yapılan iş", ["Tek başına her şey", "Ceza", "İhmal", "Yarış"], "Vygotsky."),
      F("Güvenli bağlanma ne sağlar?", "Keşif için güvenli liman", ["Bağımlılık hastalığı", "Özerklik yokluğu zorunlu", "Dil yokluğu", "Motor yokluğu"], "Bowlby."),
      F("Öz düzenleme örneği nedir?", "Sıra bekleme ve duyguyu yatıştırma", ["Türev", "1RM", "Ofsayt", "m.4"], "Yürütücü işlev."),
      F("Gelişim taramasında öğretmen ne yapar?", "Gözlemler ve şüphede yönlendirir", ["Tanı koyar DSM", "İlaç yazar", "Etiket yapıştırır sınıfa", "Aileyi suçlar"], "Tarama."),
      F("Oyun neden gelişim göstergesidir?", "Dil, motor ve sosyal beceriyi bir arada taşır", ["Zaman kaybıdır", "Süs", "Ceza", "Yarış"], "Araç."),
      F("Bireysel tempo ilkesi ne der?", "Her çocuk kendi takviminde ilerler", ["Hepsi aynı ayda okur", "Kızlar geri efsane", "Erkekler geç konuşur kader", "Norm tek çocuk"], "Fark."),
      F("2026 Okul Öncesi ÖABT yapısı nedir?", "30 alan bilgisi + 20 alan eğitimi", ["80 AGS", "50 AGS", "100 soru", "10 soru"], "50 soru.")]),
    ("Erken Çocukluk Eğitimi",
     "Erken çocukluk 0-8; okul öncesi kurum 36-68 ay ağırlıklıdır. Bakım ile eğitim ayrılmaz.",
     ["**Erken çocukluk** bakım+eğitim.",
      "**Kalite** yetişkin-çocuk etkileşimi.",
      "**Oyun temelli** program.",
      "**Kapsayıcılık**.",
      "**Aile merkezlilik**.",
      "**Geçiş** ev-okul-ilkokul.",
      "**Öğretmen nitelikleri** duyarlı-yanıtlayıcı.",
      "**Ortam** merkezler ve köşeler.",
      "**Rutin** güvenlik duygusu.",
      "**Dökümantasyon**.",
      "Akademik baskı **erken okuma yarışı** zararlı olabilir.",
      "Kalite **mobilya lüksü değildir**.",
      "UNESCO **erken yatırım**.",
      "TYMM **erken yıllar**.",
      "Sınav: kalite + oyun + geçiş."],
     [F("Erken çocukluk eğitiminin kalite göstergesi nedir?", "Duyarlı yetişkin-çocuk etkileşimi", ["Lüks bina tek", "Üniforma tek", "Test puanı 5 yaş", "Sessizlik"], "Process quality."),
      F("Oyun temelli yaklaşım neyi reddeder?", "Masa başı akademik yarışı tek yöntem saymayı", ["Oyunu", "Aileyi", "Rutini", "Şarkıyı"], "Pedagoji."),
      F("Geçiş çalışması neden önemlidir?", "Okul uyum kaygısını azaltmak", ["Notu yükseltmek sihirle", "MEB puanı", "AGS", "Doping"], "Transition."),
      F("Bakım ve eğitim neden ayrılamaz?", "Güvenlik ve öğrenmenin aynı anda yürümesi", ["Bakım yasaktır", "Eğitim 6 yaşta başlar efsane", "Öğretmen bakmaz", "Aile bakmaz"], "ECEC."),
      F("Köşe düzeni ne işe yarar?", "Seçim, derinleşme ve küçük grup", ["Ceza köşesi", "Teşhir", "Yarış pisti", "Depo"], "Ortam."),
      F("Dökümantasyon nedir?", "Öğrenme sürecinin kanıtla görünür kılınması", ["İhbar dosyası", "Ceza defteri", "Not listesi tek", "Gizli etiket"], "Reggio hattı."),
      F("Kapsayıcı erken eğitim nedir?", "Farkı olan çocuğun genel grupta desteklenmesi", ["Ayrı kapalı kurum zorunlu her çocuk", "Dışlama", "Red", "Gizleme"], "Inclusion."),
      F("Akademik baskının riski nedir?", "Oyunu ve öz düzenlemeyi zedelemek", ["IQ patlaması garantisi", "Disleksi tedavisi", "Üstün zekâ üretimi", "AGS birinciliği"], "Gelişim.")]),
    ("Çocuk Sağlığı",
     "Öğretmen tanı koymaz; tarama, hijyen, bulaş ve acil yönlendirme yapar.",
     ["**Büyüme izlemi** boy-kilo eğrisi aile-sağlıkla.",
      "**Aşı takvimi** bilgi, zorunluluk mevzuatı.",
      "**Bulaşıcı hastalık** okuldan uzak süresi.",
      "**Hijyen** el, tuvalet, diş.",
      "**Beslenme** öğün, alerji, şeker.",
      "**Uyku ve dinlenme**.",
      "**Güvenli ortam** priz, temizlik maddesi.",
      "**İlk yardım** yanık, düşme, havale.",
      "**İstismar belirtisi** bildirim yükümlülüğü.",
      "**Ağız-diş ve görme-işitme tarama** işbirliği.",
      "İlaç **veli onamı ve sağlıkçı**.",
      "Ateş **eve gönderme protokolü**.",
      "Alerji **acil eylem planı**.",
      "TYMM **sağlıklı yaşam**.",
      "Sınav: protokol + etik."],
     [F("Öğretmen ilaç konusunda ne yapmaz?", "Kendi inisiyatifiyle ilaç vermek", ["Onaylı protokolü uygulamak", "Aileyi aramak", "Sağlıkçıya yönlendirmek", "Kayıt tutmak"], "Yetkinlik."),
      F("İstismar şüphesinde yükümlülük nedir?", "Mevzuata göre bildirim", ["Gizlemek", "Sınıfta teşhir", "Aileyi mahkemesiz cezalandırmak", "Sosyal medya"], "Koruma."),
      F("Bulaşıcı hastalıkta okulun işi nedir?", "Protokole göre uzaklaştırma ve hijyen", ["Teşhis koymak", "Antibiyotik yazmak", "Aşı yapmak zorunlu hekim gibi", "İhmalkâr bırakmak"], "Halk sağlığı."),
      F("Alerjide sınıf düzeni nasıl olur?", "Etiket, çapraz bulaş yasağı, acil plan", ["Fıstığı ödül yapmak", "Gizlemek", "Deneme yanılma", "Paylaşmaya zorlamak"], "Güvenlik."),
      F("El yıkama ne zaman şarttır?", "Yemek ve tuvalet öncesi-sonrası", ["Ayda bir", "Yalnızca denetimde", "Yalnızca ziyarette", "Hiç"], "Hijyen."),
      F("Havale anında ilk iş nedir?", "Güvenli yan yatırıp süresi izlemek, zorla ağız açmamak", ["Dil tutmak", "Su içirmek", "Sarsmak", "İlaç ezmek"], "İlk yardım."),
      F("Uyku saatinin gelişimsel gerekçesi nedir?", "Beyin ve bağışıklık onarımı", ["Öğretmen molası tek amaç", "Ceza", "Sessizlik notu", "Velisiz kaçış"], "Sağlık."),
      F("Görme tarama şüphesinde ne yapılır?", "Aile ve sağlık kurumuna yönlendirme", ["Gözlük yazmak", "En arka sıraya cezalı oturtmak", "Alay", "İhmal"], "Tarama.")]),
    ("Çocuk Ruh Sağlığı",
     "Mizaç farkı tanıdır; her hareket ADHD değildir. Travmada öğretmen terapist değildir.",
     ["**Mizaç** (Thomas-Chess) kolay-zor-yavaş ısınan.",
      "**Duygu düzenleme** co-regulation.",
      "**Ayrılık kaygısı** uyum dönemi.",
      "**Öfke** sınır+empati.",
      "**İçe kapanma** gözlem.",
      "**Travma bilgili okul**.",
      "**Oyun terapisi** uzman işi; öğretmen oyunla destekler.",
      "**Akran zorbalığı** erken müdahale.",
      "**Ekran ve uyku** ruh sağlığı.",
      "**Yönlendirme** PDR/RAM/sağlık.",
      "Etiket **yapıştırılmaz**.",
      "Aile **suçlanmaz**.",
      "Sırlar **istismar sınırında kırılır**.",
      "TYMM **sosyal-duygusal**.",
      "Sınav: mizaç + etik + yönlendirme."],
     [F("Co-regulation nedir?", "Yetişkinin sakinliğiyle çocuğun duyguyu düzenlemesine yardım", ["Cezayla bastırma", "Görmezden gelme her zaman", "Teşhir", "Kıyas"], "Duygu."),
      F("Uyum döneminde ayrılık kaygısı nasıl karşılanır?", "Kısa vedalaşma ve tutarlı rutin", ["Gizlice kaçmak her gün", "Alay", "Saatlerce koridorda bekletmek cezalı", "Aileyi yasaklamak"], "Bağlanma."),
      F("Her hareketlilik ADHD midir?", "Hayır, gelişim ve ortam da hareket üretir", ["Evet her zaman", "Evet erkeklerde kader", "Evet şekerden", "Evet aşıdan efsane"], "Tanı uzman işi."),
      F("Zorbalıkta öğretmen ne yapar?", "Güvenli müdahale, kayıt, aile-PDR", ["İzle eğlen", "Mağduru suçla", "Gizle", "Canlı yayın"], "Koruma."),
      F("Travma bilgili yaklaşım nedir?", "Tetikleyiciyi azaltıp güven ve seçim sunmak", ["Zorla anlattırmak", "Cezalandırmak", "İnanmamak", "Teşhir"], "Trauma-informed."),
      F("İçe kapanık çocukta hata nedir?", "Sessiz diye yok saymak", ["Gözlem", "Küçük grup daveti", "Aile görüşmesi", "Oyun temelli katılım"], "İhmal."),
      F("Öfke nöbetinde ilk adım nedir?", "Güvenli ortam ve sakin dil", ["Bağırarak bastırmak", "Utandırmak", "Kıyas", "Kapıyı kilitleyip bırakmak"], "Düzenleme."),
      F("Ruh sağlığı yönlendirmesi kime yapılır?", "PDR, RAM veya sağlık kurumu", ["Sosyal medya", "Komşu", "Bahçıvan", "Kantinci"], "Yetkinlik.")]),
    ("Oyun",
     "Oyun çocuğun işidir; boş zaman doldurma veya ödül-ceza aracı değildir.",
     ["**Parten** yalnız, paralel, birleşik, işbirlikli.",
      "**Piaget** alıştırma, sembolik, kurallı.",
      "**Vygotsky** oyun ZPD.",
      "**Serbest oyun** seçim.",
      "**Öğretmen katılımlı oyun** iskele.",
      "**Riskli oyun** kontrollü.",
      "**Dijital oyun** süre ve içerik.",
      "**Oyuncak** açık uçlu.",
      "**Toplumsal cinsiyet** oyuncak kalıbı kırılır.",
      "**Gözlem** gelişim verisi.",
      "Oyunu kesmek **geçiş rutini** ister.",
      "Oyun saati **iptal cezası olmamalı**.",
      "Mekân **iç-dış**.",
      "TYMM **oyun**.",
      "Sınav: kuram + tür + etik."],
     [F("Paralel oyun nedir?", "Yan yana aynı iş, etkileşim az", ["Takım stratejisi", "Kurallı spor", "Yalnız odada kilit", "Ders anlatımı"], "Parten."),
      F("Sembolik oyun neyi gösterir?", "Hayal ve dilde temsil", ["Motor gerilik", "Yalan hastalığı", "ADHD her zaman", "İstismar her zaman"], "Piaget."),
      F("Açık uçlu oyuncak örneği nedir?", "Blok, kumaş, karton", ["Tek düğmeli ışıklı oyuncak tek işlev", "Tablo ezberi", "Test kitabı", "Cezalı yazı"], "Açık uç."),
      F("Oyunu ceza ile kesmek neden yanlıştır?", "Oyunun gelişim hakkı olması", ["MEB yasakladı uydurma tek", "Oyuncak pahalı", "Zaman yok efsane her zaman", "Veliler istemez tek"], "Hak."),
      F("Öğretmen oyuna nasıl girer?", "Rol isteyerek iskele kurar, ele geçirmez", ["Oyunu öğretmen dersine çevirir hemen", "Yasaklar", "Alay eder", "Filmar"], "İskele."),
      F("Kontrollü riskli oyun ne kazandırır?", "Risk değerlendirme ve motor cesaret", ["Sakatlık garantisi", "İhmal", "Dava isteği", "Kaos"], "Outdoor."),
      F("Cinsiyetçi oyuncak köşesi neyi üretir?", "Kalıp yargı", ["Eşitlik", "ZPD", "Güvenli bağlanma", "Fonolojik farkındalık"], "Gizli müfredat."),
      F("Oyun gözlemi ne işe yarar?", "Gelişim ve sosyal ilişki verisi", ["İhbar", "Not kırma", "Teşhir", "Kıyas listesi"], "Değerlendirme.")]),
    ("Çocuk Edebiyatı",
     "Okul öncesi edebiyat dinleme, görsel okuma ve tekrar zevkidir; ilkokul romanı dayatılmaz.",
     ["**Resimli kitap** yaş 0-6.",
      "**Tekrarlı kalıp** dil.",
      "**Ninni, tekerleme, masal**.",
      "**Görsel okuma**.",
      "**Kitap seçimi** korku dozu.",
      "**Etkileşimli okuma** soru.",
      "**Yazarlık köşesi** karalama.",
      "**Kütüphane rutini**.",
      "**Çeviri eser** çeşit.",
      "**Değer** öyküde.",
      "Ezber vaaz **edebiyat değil**.",
      "Kitabı ödül-ceza **yapma**.",
      "Ses **ton ve jest**.",
      "TYMM **dil ve kültür**.",
      "Sınav: etkileşimli okuma + yaş."],
     [F("Etkileşimli okuma nedir?", "Metin sırasında soru ve çocuğun sözü", ["Tek taraflı sesli okuma bitene kadar sus", "Ezber", "Test", "Ceza"], "Dialogic."),
      F("Tekerlemenin dil katkısı nedir?", "Fonolojik farkındalık ve ritim", ["Türev", "1RM", "m.42", "Ofsayt"], "Ses."),
      F("Okul öncesi kitapta görsel neden merkezidir?", "Henüz çözücü okur olmaması", ["Yazı yasaktır", "MEB yazıyı sildi uydurma", "Görsel süs", "Yayınevi kaprisi"], "Gelişim."),
      F("Korku dozunda ölçüt nedir?", "Yaş ve çocuğun tepkisi", ["Ne kadar korkunç o kadar iyi", "Korku yasak her zaman", "Yalnızca yetişkin gerilim", "Haber videosu"], "Uygunluk."),
      F("Kitabı ceza yapmak neden yanlıştır?", "Okuma sevgisini zedelemesi", ["Kağıt biter", "Zaman biter", "Raf biter", "Lamba biter"], "Duyuş."),
      F("Karalama yazarlık sayılır mı?", "Evet, yazılı dile giden ifadedir", ["Hayır tembellik", "Hayır kir", "Hayır disiplin sorunu", "Hayır zeka geriliği"], "Süreç."),
      F("Ninni hangi alanı destekler?", "Bağlanma ve işitsel dil", ["VO2max", "Doping", "WADA", "Kapitülasyon"], "Erken dil."),
      F("Sınıf kütüphanesi nasıl kullanılır?", "Serbest seçim ve tekrar okuma hakkı", ["Cam dolap yasak", "Öğretmen kalesi", "Ceza köşesi", "Toz"], "Kültür.")]),
    ("Aile Eğitimi",
     "Aile düşman değil ortaktır. Ev ziyareti mahremiyet ve gönüllülük ister.",
     ["**Aile çeşitliliği** tek ebeveyn, geniş, koruma.",
      "**Güçlü yön** yaklaşımı.",
      "**İletişim** günlük not, dijital sınır.",
      "**Katılım** karar, etkinlik, gönüllü.",
      "**Ev ziyareti** etik.",
      "**Ebeveynlik stilleri** (Baumrind) bilgi.",
      "**Tutarsız ev-okul kuralı** çocukta karmaşa.",
      "**Mahremiyet** çocuk dosyası.",
      "**Kriz** (boşanma, göç) duyarlılık.",
      "**Toplantı** dinleme ağırlıklı.",
      "Suçlama **işbirliğini bitirir**.",
      "Ödev **aileye öğretmenlik yüklemek değildir**.",
      "Dil **çeviri desteği**.",
      "TYMM **aile**.",
      "Sınav: etik + katılım + çeşitlilik."],
     [F("Güçlü yön yaklaşımı nedir?", "Ailenin kaynaklarını merkeze almak", ["Eksik listesi okumak", "Suçlamak", "Tehdit", "Kıyas"], "Partnership."),
      F("Ev ziyaretinde etik kural nedir?", "Rıza, mahremiyet, yargılamama", ["Teftiş", "Fotoğraf teşhiri", "Komşuya anlatma", "Zorla girme"], "Etik."),
      F("Baumrind'in yetkili (authoritative) stili nedir?", "Sıcaklık + net sınır", ["İhmal", "Baskı tek", "Serbestlik sınırsız", "Alay"], "Ebeveynlik."),
      F("Dosya mahremiyeti kime aittir?", "Çocuk ve yasal temsilci çerçevesinde kurum kuralı", ["Tüm WhatsApp grubu", "Komşu", "Servis şoförü", "Diğer veliler"], "KVKK."),
      F("Dil desteği neden gerekir?", "Göçmen/azınlık ailenin katılım hakkı", ["Asimilasyon dayatması", "Cezalı Türkçe", "Yok sayma", "Alay"], "Kapsayıcılık."),
      F("Toplantıda öğretmenin ilk işi nedir?", "Dinlemek ve somut örnek vermek", ["Suç listesi", "Bağırma", "Not tehdidi", "Kıyas"], "İletişim."),
      F("Tutarsız kural çocuğu nasıl etkiler?", "Kaygı ve sınır belirsizliği", ["Hızlı olgunluk garantisi", "IQ artışı", "Motor sıçrama", "Mükemmel itaat"], "Tutarlılık."),
      F("Aileye öğretmenlik yüklemek neden yanlıştır?", "Pedagojik sorumluluğun kurumda kalması", ["Aile yasal öğretmen", "MEB aileye devretti uydurma", "Ödev sihirdir", "Ceza evde biter"], "Rol.")]),
    ("Okul Öncesi Eğitim Programları",
     "Güncel MEB okul öncesi programı oyun, merkez ve kazanım dilindedir; 2024 TYMM ile hizalanır.",
     ["**Kazanım-gösterge**.",
      "**Günlük eğitim akışı**.",
      "**Aylık-günlük plan**.",
      "**Merkezler**.",
      "**Esneklik** çocuk ilgisinden sapma.",
      "**Değerlendirme** gelişim gözlem formu.",
      "**Kaynaştırma BEP** ile program.",
      "**Aile katılım etkinliği**.",
      "**Özel günler** aşırı akademik gösteriye indirgenmez.",
      "**MEB program tarihi** (2013 ve sonrası güncellemeler) ezbere yıl tuzağı.",
      "Program **kitap adedi değildir**.",
      "Öğretmen **tasarımcı**.",
      "Rutin **öğrenme zamanıdır**.",
      "TYMM **erken yıllar yetkinliği**.",
      "Sınav: plan + gözlem + esneklik."],
     [F("Gösterge ne işe yarar?", "Kazanımın gözlenebilir işaretini vermek", ["Cezayı artırmak", "Notu 100 yapmak", "MEB teftiş korkusu", "Veli şikâyeti"], "Program."),
      F("Günlük akışta rutin neden vardır?", "Güven ve geçiş kolaylığı", ["Askeri disiplin tek amaç", "Öğretmen keyfi", "Zaman doldurma", "Sessizlik notu"], "Rutin."),
      F("Çocuk ilgisinden sapmak program ihlali midir?", "Hayır, esnek plan kalitesidir", ["Evet suçtur", "Evet 1739 ihlali", "Evet anayasa ihlali", "Evet AİHM ihlali"], "Emergent."),
      F("Gelişim gözlem formu neyin aracıdır?", "Değerlendirme ve planlama", ["Etiket", "İhraç", "Teşhir", "Kıyas listesi sosyal medya"], "Formative."),
      F("BEP ile okul öncesi program nasıl yürür?", "Kazanımlar uyarlanarak aynı grupta", ["Ayrı program yok sayma", "Dersten çıkarma", "Bekletme", "Red"], "Kaynaştırma."),
      F("Gösteri gününün riski nedir?", "Ezber sahne kaygısı ve aile rekabeti", ["Oyun", "Şarkı", "Aile sevinci sağlıklı", "Paylaşım"], "Duyuş."),
      F("Öğretmenin program rolü nedir?", "Kazanımı yaşantıya çeviren tasarımcı", ["Kitabı okuyan robot", "Bekçi", "Aşçı tek", "Temizlikçi tek"], "Agency."),
      F("TYMM erken çocuklukta neyi vurgular?", "Yetkinlik, değer ve oyunla bütüncül gelişim", ["Erken LGS", "Erken AGS", "Erken 1RM", "Erken doping"], "Model.")]),
    ("Türkçe Dil Etkinlikleri",
     "Dil etkinliği sohbet, öykü, şiir, drama ve yazıya giden karalamadır; sessiz sıra değil.",
     ["**Alıcı ve ifade edici dil**.",
      "**Sohbet çemberi**.",
      "**Öykü anlatma ve tamamlama**.",
      "**Fonolojik farkındalık** oyunları.",
      "**Sözcük dağarcığı** bağlam.",
      "**İki dilli çocuk** destek.",
      "**Soru türleri** açık uç.",
      "**Dinleme kuralları**.",
      "**Yazı farkındalığı** yön, isim.",
      "**Tiyatro köşesi**.",
      "Düzeltme **modelleyerek**.",
      "Kesintisiz **çocuğun sözü**.",
      "Ekran **dilin yerine geçmez**.",
      "TYMM **iletişim**.",
      "Sınav: alıcı-ifade + oyun."],
     [F("Alıcı dil nedir?", "Anlama", ["Konuşma üretimi", "Yazı motoru", "VO2", "1RM"], "Receptive."),
      F("İfade edici dil nedir?", "Konuşarak/jestle üretme", ["Yalnızca duyma", "Yalnızca bakma", "Yalnızca uyuma", "Yalnızca koşma"], "Expressive."),
      F("Fonolojik farkındalık oyunu örneği nedir?", "Uyak ve ilk ses avı", ["Türev", "Kesir", "Ofsayt", "m.42"], "Okuma hazırlık."),
      F("İki dilli çocukta yaklaşım nedir?", "Ana dili değerli kılıp Türkçeyi desteklemek", ["Ana dili yasaklamak", "Alay", "Geç konuşur damgası", "Ayrı odada cezalı"], "Kapsayıcılık."),
      F("Yanlış konuşmayı düzeltme yolu nedir?", "Doğru modeli cümlede sunmak", ["Kesip azarlamak", "Taklit ederek alay", "Yazı cezası", "Susturmak"], "Recast."),
      F("Sohbet çemberinin kuralı nedir?", "Sıra, göz teması, dinleme", ["Öğretmen monoloğu", "Bağırma", "Test", "Sessizlik notu"], "Söylem."),
      F("Yazı farkındalığı örneği nedir?", "Kitabın yönü ve ismin harfleri", ["Roman tahlili", "Divan", "Aruz", "Redif"], "Print awareness."),
      F("Ekranın dil gelişimindeki riski nedir?", "Karşılıklı konuşmayı azaltması", ["Kelimeyi sihirle artırması her içerikte", "ZPD üretmesi her uygulama", "Bağlanma artışı her video", "Fonoloji sihri"], "Etkileşim.")]),
    ("Matematik Etkinlikleri",
     "Okul öncesi matematik sayma şarkısından ibaret değildir; sınıflama, örüntü, mekân, ölçme vardır.",
     ["**Sınıflama ve eşleme**.",
      "**Örüntü**.",
      "**Sayma ilkeleri** (Gelman-Gallistel) sade.",
      "**Kardinalite** son sayının nicelik olması.",
      "**Mekân** ön-arka, etrafında.",
      "**Ölçme** uzun, ağır, dolu.",
      "**Geometri** şekil oyunları.",
      "**Problem** paylaşım.",
      "**Manipülatif**.",
      "**Günlük rutin** masa sayısı.",
      "Ezber rakam **anlam değildir**.",
      "Kız-erkek **kalıp yok**.",
      "Hata **öğrenme verisi**.",
      "TYMM **matematik yetkinliği**.",
      "Sınav: ilke + rutin."],
     [F("Kardinalite ilkesi nedir?", "Son sayılan sayının çokluğu göstermesi", ["Ezbere 100'e kadar", "Rakam yazısı güzelliği", "Hız", "Sessizlik"], "Sayma."),
      F("Örüntü etkinliği örneği nedir?", "Kırmızı-mavi-kırmızı dizisi", ["Türev", "Denklem", "Matris", "Logaritma"], "Cebir tohumu."),
      F("Mekân kavramı nasıl gelişir?", "Vücut ve sınıf konum sözcükleriyle", ["Harita projeksiyonu zorunlu", "CBS", "Jeopolitik Heartland", "Köppen"], "Geometri."),
      F("Ölçmede standart olmayan birim örneği nedir?", "Karış, ayak, bardak", ["Metre zorunlu ilk gün", "İntegral", "Newton", "Pascal"], "Ölçme."),
      F("Paylaşım problemi ne öğretir?", "Parça-bütün ve adalet", ["Kesir algoritması 5. sınıf", "Faiz", "Borsa", "NAIRU"], "Problem."),
      F("Rakam ezberi neden yetmez?", "Nicelik anlamı olmadan sembol boş kalır", ["Rakam yasaktır", "MEB rakamı sildi uydurma", "Saymak yasaktır", "Oyun yasaktır"], "Anlam."),
      F("Rutinde matematik örneği nedir?", "Tabak sayısı kadar peçete", ["Yoklama cezası", "Test", "Dikte", "1RM"], "Günlük."),
      F("Hata nasıl karşılanır?", "Materyalle yeniden deneme", ["Utandırma", "Yarış", "Not", "Alay"], "Formative.")]),
    ("Fen Etkinlikleri",
     "Okul öncesi fen merak, duyu ve basit denemedir; laboratuvar önlüğü yarışı değildir.",
     ["**Duyu gözlemi**.",
      "**Canlı-cansız**.",
      "**Bitki bakımı**.",
      "**Hava ve mevsim**.",
      "**Mıknatıs, batma-yüzme, gölge** sade deney.",
      "**Soru sorma** neden-nasıl.",
      "**Doğa yürüyüşü**.",
      "**Sürdürülebilirlik** su, atık.",
      "**Güvenlik** tatmama kuralı.",
      "**Kayıt** resim ve söz.",
      "Açıklama **çocuk kuramı dinlenir**.",
      "Öğretmen **hemen doğru söylemez**.",
      "Canlı **acı çektirilmez**.",
      "TYMM **fen merakı**.",
      "Sınav: duyu + etik + kayıt."],
     [F("Okul öncesi fende asıl yöntem nedir?", "Duyu, merak ve basit deneme", ["Formül ezberi", "Periyodik tablo", "Newton 3 yasa ezberi", "Kimyasal denklem"], "Inquiry."),
      F("Çocuk kuramı neden dinlenir?", "Kavram yanılgısını görmek için", ["Alay için", "Not kırmak için", "Teşhir için", "Cezalandırmak için"], "Fen."),
      F("Güvenlik kuralı örneği nedir?", "Bilinmeyen şeyi tatmama", ["Asit içme deneyi", "Ateş serbest", "Cam kırma", "Priz deneme"], "Sağlık."),
      F("Canlı incelemesinde etik nedir?", "Canlıya zarar vermemek", ["Böceği ezmek", "Kuş yuvasını bozmak", "Çiçeği koparıp atmak yarış", "Hayvanı korkutmak"], "Değer."),
      F("Kayıt nasıl tutulur?", "Resim, fotoğraf (onaylı) ve çocuk sözü", ["Yalnızca test", "Yalnızca rakam", "Yalnızca ceza", "Yalnızca giz"], "Dökümantasyon."),
      F("Batma-yüzme deneyi neyi açar?", "Tahmin-gözlem-açıklama", ["Yoğunluk formülü ezberi zorunlu", "Arşimet ispatı", "Türev", "Pascal yasası tam"], "Süreç."),
      F("Mevsim etkinliği nasıl bağlanır?", "Giysi, doğa ve tarım gözlemi", ["Köppen tam sınıflama", "Cephesel sistem", "ENSO", "Jet stream"], "Hayat."),
      F("Öğretmen neden hemen doğruyu söylemez?", "Keşif ve konuşmayı yaşatmak için", ["Bilmediği için", "MEB yasakladı uydurma", "Zaman yok efsane her zaman", "Veli istemez"], "Pedagoji.")]),
    ("Sanat Etkinlikleri",
     "Ürün duvara asılsın diye model kopyalatmak sanat değildir; süreç ve duyusal keşif esastır.",
     ["**Süreç sanatı** (process art).",
      "**Duyu hamuru, parmak boya**.",
      "**Renk karışımı**.",
      "**Kolaj ve artık malzeme**.",
      "**Üç boyut** kutu heykel.",
      "**Sanat konuşması** betimleme.",
      "**Kaynaştırma** kalın araç.",
      "**Kültür motifleri** saygı.",
      "**Sergi** çocuk seçimi.",
      "**Önlük ve hijyen**.",
      "Model kopya **ara sıra örnek** olabilir, tek yol değil.",
      "Not **en düzgün** değildir.",
      "Zorla bitirme **süreç öldürür**.",
      "TYMM **sanat**.",
      "Sınav: süreç + malzeme + saygı."],
     [F("Süreç sanatı nedir?", "Sonuçtan çok keşif ve karar", ["Kalıp boyama tek", "Öğretmen modeli tek", "Yarış", "En düzgün kopya"], "Process."),
      F("Artık malzeme ne kazandırır?", "Yaratıcılık ve sürdürülebilirlik", ["Pislik", "Disiplinsizlik", "Yoksulluk damgası", "Tehlike her parça"], "Geri dönüşüm."),
      F("Sanat konuşmasında ilk adım nedir?", "Çocuğun ne yaptığını dinlemek", ["Yanlış demek", "Düzeltmek hemen", "Kıyas", "Yırtmak"], "Estetik."),
      F("Kaynaştırma uyarlaması nedir?", "Kalın fırça, büyük zemin", ["Etkinlikten alma", "Beyaz yasak", "Siyah yasak", "Sergiden dışlama"], "Erişim."),
      F("Zorla bitirmek neden yanlıştır?", "Süreç ve özerkliği kesmesi", ["Boya biter", "Kâğıt biter", "Zaman çizelgesi kutsal her saniye", "Veli bekler efsane"], "Özerklik."),
      F("Değerlendirme ölçütü nedir?", "Katılım, keşif, sözelleştirme", ["Gerçekçilik", "Hız", "Sessizlik", "Kopya benzeşim"], "Rubrik."),
      F("Parmak boyanın katkısı nedir?", "Duyu ve omuz-el motoru", ["Kir cezası", "ADHD tedavisi", "IQ sihri", "Disleksi sihri"], "Duyu."),
      F("Çocuk sergi seçimi neden önemlidir?", "Aidiyet ve karar", ["Öğretmen estetiği tek", "Veli yarışı", "Satış", "Teşhir utancı"], "Özerklik.")]),
    ("Müzik",
     "Okul öncesi müzik şarkı, ritim, hareket ve dinlemedir; solfej yarışı değildir.",
     ["**Ninni ve tekerleme**.",
      "**Ritim çalgıları**.",
      "**Hareketle müzik**.",
      "**Ses keşfi** yüksek-alçak.",
      "**Şarkı dağarcığı** kısa tekrarlı.",
      "**Dinleme** kısa parça.",
      "**Doğaçlama**.",
      "**Kültür ezgileri**.",
      "**Kaynaştırma** titreşim.",
      "**Ses sağlığı**.",
      "Bağırma **müzik değildir**.",
      "Performans kaygısı **zorla sahne**.",
      "Müzik **geçiş rutini** aracı.",
      "TYMM **müzik**.",
      "Sınav: ritim + oyun + değer."],
     [F("Okul öncesi müziğin omurgası nedir?", "Şarkı, ritim ve hareket", ["Paganini", "Solfej yarışı", "Nota diktesi", "Konservatuvar sınavı"], "Yaş."),
      F("Ritim çalgısının pedagojik değeri nedir?", "Nabız, sıra ve dinleme", ["Gürültü cezası", "Kulak bozma", "Disiplin sopası", "Yarış"], "Orff sade."),
      F("Yüksek-alçak ses keşfi ne öğretir?", "Pitch farkındalığı", ["Gürültü", "Bağırma", "Fısıltı yasağı", "Sessizlik notu"], "Kulak."),
      F("Zorla sahne riski nedir?", "Kaygı ve müzikten soğuma", ["Virtüözlük garantisi", "IQ artışı", "MEB puanı", "AGS"], "Duyuş."),
      F("Kaynaştırmada titreşim ne işe yarar?", "İşitme yetersizliğinde müziğe erişim", ["Cezalandırma", "Alay", "Dışlama", "Sessizlik"], "Erişim."),
      F("Müzikle geçiş rutini örneği nedir?", "Toplanma şarkısı", ["Düdük hakareti", "Bağırma", "Zil cezası", "Karanlık"], "Rutin."),
      F("Kültür ezgisi neden vardır?", "Aidiyet ve çeşitlilik", ["Tek dil yasağı", "Nefret", "Alay", "Yasak"], "Değer."),
      F("Doğaçlama nasıl başlar?", "Bilinen tekerlemeyi değiştirme", ["Piyano sonatı", "Füg", "Opera aryası", "Dikte"], "Yaratma.")]),
    ("Drama",
     "Okul öncesi drama oyun ve rol; sahne eseri zorunlu değildir.",
     ["**Rol oynama** ev-okul.",
      "**Nesneyle temsil** muz=telefon.",
      "**Donuk imge** sade.",
      "**Masal canlandırma**.",
      "**Gönüllülük**.",
      "**Duygu adlandırma**.",
      "**Çatışma çözme** rolde.",
      "**Kaynaştırma** jest.",
      "**Kostüm sandığı** açık uç.",
      "**Değerlendirme** süreç.",
      "Zorla rol **hayır**.",
      "Alay **iklimi bozar**.",
      "Drama **dil ve sosyal**.",
      "TYMM **iletişim**.",
      "Sınav: gönüllülük + temsil."],
     [F("Sembolik nesne neyi gösterir?", "Temsil düşüncesi", ["Yalan", "Hırsızlık", "ADHD her zaman", "Otizm her zaman"], "Oyun."),
      F("Gönüllülük neden şarttır?", "Kaygı ve mahremiyet", ["Kostüm yok", "Sahne yok", "Müzik yok", "Veli yok"], "Etik."),
      F("Duygu adlandırmanın kazancı nedir?", "Ruh sağlığı ve dil", ["Not", "Ceza", "Yarış", "Teşhir"], "SEL."),
      F("Çatışmayı rolde çözmek ne işe yarar?", "Empati ve alternatif davranış", ["Kavga", "Alay", "Dışlama", "İhmal"], "Sosyal."),
      F("Açık uçlu kostüm nedir?", "Kumaş ve şapkanın çok rol olması", ["Tek süper kahraman lisansı", "Marka oyuncak zorunlu", "Üniforma", "Yasak dolabı"], "Yaratıcılık."),
      F("Kaynaştırmada jest neden yeter?", "Sözsüz katılım hakkı", ["Dil yok sayılır sonsuza", "Konuşma yasak", "Grup dışı", "İzleyici zorunlu"], "Erişim."),
      F("Değerlendirme nasıl olur?", "Gözlem ve fotoğraf (onaylı) süreç", ["En iyi aktör yarışı", "Bilet satışı", "Jüri", "Utandırma"], "Formative."),
      F("Masal canlandırmasında öğretmen ne yapar?", "Anlatır, rol dağıtır, güven sağlar", ["Ezber tirat ister 5 yaşta", "Bağırır", "Kıyaslar", "Filmar teşhir zorunlu"], "Kolaylaştırıcı.")]),
    ("Hareket",
     "Hareket saati serbest bırakıp bahçede kaybolmak değildir; temel hareket yeterliği planlı işlenir.",
     ["**Lokomotor ve duruş**.",
      "**Nesne kontrolü** top, çember.",
      "**Denge**.",
      "**Ritimle hareket**.",
      "**Mekân farkındalığı** kişisel alan.",
      "**Güvenlik**.",
      "**Açık hava**.",
      "**Kaynaştırma**.",
      "**Araç** tünel, denge tahtası.",
      "**Değerlendirme** gözlem.",
      "Yarış **her etkinliğin amacı değil**.",
      "Kıyafet **hareketi kesmesin**.",
      "Su ve gölge **sağlık**.",
      "TYMM **hareket**.",
      "Sınav: yeterlik + güvenlik."],
     [F("Kişisel alan neden öğretilir?", "Çarpışma ve sınır", ["Ceza halkası", "Askeri talim tek", "Sessizlik", "Sıra numarası"], "Güvenlik."),
      F("Denge çalışması örneği nedir?", "Tek ayak, çizgide yürüme", ["1RM", "VO2max testi", "Maraton", "Doping"], "Motor."),
      F("Açık havanın katkısı nedir?", "Gross motor, D vitamini, risk değerlendirme", ["Sadece kir", "Sadece hastalık", "Sadece kaçamak", "Sadece gürültü"], "Outdoor."),
      F("Kaynaştırma uyarlaması nedir?", "Geniş hedef, yavaş top, eş tutma", ["Oturma cezası", "İzleyici", "Dışarı", "Alay"], "APE sade."),
      F("Yarış neden tek yöntem olmamalıdır?", "Kaybeden damgası ve dışlama", ["Hız kutsaldır her yaşta", "Elit üretim", "AGS", "Milli takım"], "Duyuş."),
      F("Planlı hareket saati ne içerir?", "Isınma, yeterlik, oyun, soğuma sade", ["Serbest kaos", "Öğretmen telefonu", "Yoklama tek", "Ceza turu"], "Pedagoji."),
      F("Nesne kontrolü örneği nedir?", "Yuvarlama, yakalama, tekmeleme", ["Yazı", "Kesir", "Harita", "Nota"], "Manipülatif motor."),
      F("Kıyafet kuralının gerekçesi nedir?", "Güvenli ve özgür hareket", ["Moda", "Marka", "Renk cezası", "Üniforma baskısı tek amaç"], "Sağlık.")]),
    ("Alan Eğitimi ve Değerlendirme",
     "Değerlendirme test değil; gözlem, ürün ve aileyle paylaşım. 30+20 yapısında bu başlık alan eğitimidir.",
     ["**Gelişimsel değerlendirme**.",
      "**Otantik kanıt** fotoğraf, iş, söz.",
      "**Portfolyo**.",
      "**Öz değerlendirme** sade (yüz ifadesi).",
      "**Aileyle paylaşım** yargılamadan.",
      "**BEP izleme**.",
      "**Program değerlendirme** öğretmen yansıtması.",
      "**Geçerlik** yaşa uygun araç.",
      "**Güvenirlik** birden fazla an.",
      "**Etik** etiket yapıştırma.",
      "Hazır test **okul öncesine uymaz çoğu**.",
      "Kıyas listesi **zarar**.",
      "Karne **gelişim cümlesi**.",
      "TYMM **yetkinlik kanıtı**.",
      "Sınav: otantik + etik."],
     [F("Otantik değerlendirme nedir?", "Gerçek yaşantıdan kanıt", ["Standart 80 maddelik test", "IQ tek", "Hız yarışı", "Sessizlik notu"], "Authentic."),
      F("Portfolyo neyi gösterir?", "Zaman içindeki gelişimi", ["Tek yanlış", "Tek ceza", "Tek kıyas", "Tek IQ"], "Kanıt."),
      F("Güvenirlik için ne gerekir?", "Birden fazla gözlem anı ve kişi", ["Tek dakikalık bakış", "Dedikodu", "Komşu", "Sosyal medya"], "Tutarlılık."),
      F("Aile paylaşımında dil nasıl olmalıdır?", "Betimleyici ve güçlü yönlü", ["Damgalayıcı", "Kıyasçı", "Tehditkâr", "Alaycı"], "İletişim."),
      F("Hazır akademik test neden uyumsuzdur?", "Yaşa ve oyuna dayalı öğrenmeye ters düşmesi", ["MEB zorunlu LGS 5 yaş uydurma", "PISA 4 yaş", "AGS anaokulu", "YKS"], "Yaş."),
      F("BEP izleme ne sıklıkla anlam taşır?", "Düzenli gözlem ve ekip kararı", ["Yılda bir unutarak", "Hiç", "Yalnızca teftişte", "Yalnızca şikâyette"], "Özel eğitim."),
      F("Öğretmen yansıtması nedir?", "Planın işe yarayıp yaramadığını yazmak", ["İhbar", "Günlük nefret", "Veli dedikodusu", "Selfie"], "Program."),
      F("Etik ihlal örneği nedir?", "Çocuğu gelişim raporuyla teşhir etmek", ["Onaylı portfolyo paylaşımı", "Gizli dosya kuralı", "Aile görüşmesi", "Ekip toplantısı"], "Mahremiyet.")]),
])

add("ÖABT Özel Eğitim", "oabt_ozel", [
    ("Zihin Yetersizliği ve Otizm Spektrum Bozukluğu",
     "OSB spektrumdur; her çocuk aynı değildir. Zihin yetersizliği IQ etiketinden ibaret sosyal-uyum tanımıdır.",
     ["**Zihin yetersizliği** zihinsel işlev ve uyumsal davranışta sınırlılık.",
      "**Hafif-orta-ağır-çok ağır** destek ihtiyacı dili tercih edilir.",
      "**OSB** sosyal iletişim + basmakalıp/tekrarlayan davranış, erken başlangıç.",
      "**DSM-5** spektrum, Asperger ayrı sınıf olarak kalkmıştır.",
      "**Eşlik eden** epilepsi, duyusal fark, DEHB.",
      "**PECS, görsel program, yapılandırılmış öğretim** (TEACCH izleri).",
      "**UDA** problem davranış ve beceri.",
      "**Kaynaştırma/bütünleştirme** destekle.",
      "**Aile** erken tanı stresi.",
      "**Etiket** kişiyi tanımlamaz.",
      "Göz teması **zorlanmaz**.",
      "Özel ilgi **köprü** olabilir.",
      "Sınav: spektrum + uyumsal davranış + yöntem.",
      "Sözel olmayan OSB **anlamaz diye yok sayılmaz**.",
      "Zihin yetersizliğinde **işlevsel akademik**."],
     [F("OSB'nin iki ana alanına ne girer?", "Sosyal iletişim ve basmakalıp/tekrarlayan davranış", ["Yalnızca IQ", "Yalnızca işitme kaybı", "Yalnızca körlük", "Yalnızca disleksi"], "DSM-5."),
      F("Zihin yetersizliği tanısında IQ tek başına yeter mi?", "Hayır, uyumsal davranış da gerekir", ["Evet yalnızca IQ", "Evet yalnızca boy", "Evet yalnızca not", "Evet yalnızca konuşma yaşı"], "AAIDD hattı."),
      F("DSM-5'te Asperger nasıl durur?", "Ayrı kategori olarak kaldırılıp spektruma alındı", ["Hâlâ zorunlu ayrı tanı her raporda", "OSB değildir hiç", "Sadece yetişkinde", "Sadece kızlarda"], "2013 değişimi."),
      F("Göz temasını zorlamak neden yanlıştır?", "Duyusal ve iletişim stresi", ["Tedavi sihri", "İtaat notu", "Aile isteği yeter", "MEB zorunlu uydurma"], "Etik."),
      F("PECS nedir?", "Resim değiş-tokuşuyla iletişim öğretimi", ["İlaç", "Ameliyat", "IQ testi", "Ceza"], "AAC."),
      F("İşlevsel akademik ne demektir?", "Günlük yaşamda işe yarayan okuma-para-saat", ["Türev", "Osmanlıca", "Latince", "Kuantum"], "Uyum."),
      F("Yapılandırılmış öğretim ne sunar?", "Görsel düzen, öngörülebilir rutin", ["Kaos", "Sürpriz ceza", "Belirsiz gün", "Alay"], "TEACCH izi."),
      F("Kaynaştırmada OSB öğrencisi için ilk düzenleme nedir?", "Görsel program ve duyusal uyarlama", ["Dışarı atmak", "Sessizlik cezası", "Göz teması dayatması", "Not sıfır"], "Destek.")]),
    ("Öğrenme Güçlüğü ve Özel Yetenek",
     "Öğrenme güçlüğü zekâ geriliği değildir. Özel yetenek de yalnızca yüksek not değildir.",
     ["**ÖG** okuma (disleksi), yazma (disgrafi), matematik (diskalkuli) özgül.",
      "**Normal veya üzeri zekâ** + beklenmedik düşük başarı.",
      "**Erken tarama** ses farkındalığı.",
      "**Çok duyulu öğretim**, ek süre, az madde.",
      "**Özel yetenek** bilişsel, yaratıcı, liderlik, sanat, psikomotor.",
      "**Zenginleştirme ve hızlandırma**.",
      "**Çift istisnailik** ÖG+üstün.",
      "**Duygusal** mükemmeliyetçilik kaygısı.",
      "**Tanılama** RAM/BİLSEM süreçleri Türkiye bağlamı.",
      "**Sınıf içi** derinleştirme sorusu.",
      "Tembellik **değildir**.",
      "Özel yetenek **kaynaştırma dışı zorunlu değildir**.",
      "Etiket **hizmet içindir**.",
      "Sınav: özgül güçlük + zenginleştirme.",
      "Aile **kıyas** zarar."],
     [F("Disleksi nedir?", "Özgül okuma güçlüğü", ["Zihin yetersizliği", "İşitme kaybı", "Görme kaybı", "OSB zorunlu"], "ÖG."),
      F("ÖG tanısında beklenen profil nedir?", "Zekâ geriliği olmadan akademik alanda beklenmedik güçlük", ["Düşük IQ zorunlu", "Körlük zorunlu", "Sağırlık zorunlu", "Otizm zorunlu"], "Özgül."),
      F("Çift istisnailik nedir?", "Özel yetenek ile öğrenme güçlüğünün birlikteliği", ["İki engel aynı duyu", "İki kardeş", "İki okul", "İki öğretmen"], "Twice exceptional."),
      F("Zenginleştirme nedir?", "Aynı sınıfta derin ve geniş içerik", ["Sınıf atlatmadan başka bir şey yok efsane", "Ceza ödevi", "Ek test", "İhmal"], "Enrichment."),
      F("Diskalkuli nedir?", "Özgül matematik güçlüğü", ["Disleksi özdeş", "Körlük", "OSB", "DEHB zorunlu"], "ÖG."),
      F("BİLSEM ne işe yarar?", "Özel yetenekli öğrenciye destek ve tanılama yolu", ["Zihin yetersizliği okulu", "RAM yerine geçmez tamamen her dosyada", "Cezaevi", "Yurt"], "Türkiye."),
      F("Sınıf içi ÖG uyarlaması nedir?", "Az madde, ek süre, okuyucu, somut araç", ["Not sıfır", "Dışarı", "Alay", "Tembellik damgası"], "Erişim."),
      F("Özel yetenekte kaygı kaynağı nedir?", "Mükemmeliyetçilik ve akran uyumsuzluğu", ["VO2", "1RM", "Ofsayt", "m.4"], "Duyuş.")]),
    ("İşitme ve Görme Yetersizliği",
     "İşitmede dil gecikmesi zekâ geriliği sanılmasın. Görmede Braille tek araç değildir.",
     ["**İşitme kaybı** derece ve tip (iletim-sensörinöral).",
      "**Koklear implant ve cihaz** eğitimle birlikte.",
      "**İşaret dili / toplam iletişim / sözel yaklaşım** aile seçimi+uzman.",
      "**Dudak okuma** tek başına yetmez.",
      "**Görme** az gören, kör.",
      "**Braille, büyütme, kontrast, sesli betimleme**.",
      "**Oryantasyon-mobilite**.",
      "**Beyaz baston** bağımsızlık.",
      "**Sınıf** ışık, sıra, gürültü.",
      "**Aile** erken cihaz.",
      "İşitemeyen **anlamaz değildir**.",
      "Görmeyen **duyarak her şeyi almaz otomatik**.",
      "Güvenlik **tahliye planı**.",
      "Sınav: araç + dil + ortam.",
      "Kaynaştırma **destek eğitim**."],
     [F("İşitme kaybında dil gecikmesi zekâ geriliği midir?", "Hayır, girdi yokluğu dilini etkiler", ["Evet her zaman", "Evet IQ düşer zorunlu", "Evet OSB'dir", "Evet disleksidir"], "Dil."),
      F("Toplam iletişim neyi birleştirir?", "Söz, işaret, jest, yazı", ["Yalnızca konuşma yasağı", "Yalnızca işaret yasağı", "Yalnızca yazı yasağı", "Yalnızca cihaz yasağı"], "Yaklaşım."),
      F("Az gören öğrenci için ilk uyarlama nedir?", "Kontrast, büyüteç, ışık, öne sıra", ["Braille zorunlu her az görende", "Karanlık oda", "Arka sıra", "Yazısız eğitim"], "Görme."),
      F("Oryantasyon-mobilite nedir?", "Mekânda bağımsız ve güvenli hareket eğitimi", ["Braille yazı", "İşaret dili", "IQ testi", "PECS"], "OM."),
      F("Sınıfta işitme yetersizliği için akustik düzenleme nedir?", "Gürültüyü kesmek, yüz görünürlüğü", ["Müzik açık sürekli", "Öğretmen arkası dönük anlatım", "Fısıltı", "Maske+uzak"], "Erişim."),
      F("Braille kimler içindir?", "Braille'e ihtiyaç duyan kör veya ileri görme yetersizliği", ["Tüm gözlüklüler", "Tüm az görenler zorunlu", "Disleksi", "OSB"], "Yazı sistemi."),
      F("Erken cihazlandırmanın gerekçesi nedir?", "Dil penceresi", ["Moda", "Marka", "Estetik", "Ceza"], "Kritik dönem."),
      F("Tahliye planında ne gerekir?", "Dokunsal/işitsel alarm ve rehber akran", ["Yalnızca yazılı tabela", "Yalnızca kırmızı ışık az görene yetersiz kalabilir", "Koşun diye bağırma tek", "Asansör zorunlu yangında"], "Güvenlik.")]),
    ("Erken Çocuklukta Özel Eğitim",
     "0-6 yaş erken müdahale gelişim penceresidir. Bekle gör stratejisi dil ve sosyal kayıp üretebilir.",
     ["**Erken müdahale** aile merkezli.",
      "**Gelişim penceresi** sinaptik.",
      "**Tarama** (gelişim envanteri) tanı değildir.",
      "**IFSP benzeri** aile hizmet planı uluslararası; Türkiye'de RAM-hastane-okul.",
      "**Doğal ortamda öğretim** ev-oyun.",
      "**Ebeveyn koçluğu**.",
      "**Geçiş** okul öncesine.",
      "**Down, serebral palsi, OSB** erken izlem.",
      "**İşitme taraması** yenidoğan.",
      "**Bekle gör** riski.",
      "Aile **yas süreci**.",
      "Hizmet **ekip**.",
      "Oyun **araç**.",
      "Sınav: erken müdahale + aile.",
      "Kurum **tek başına mucize değil**."],
     [F("Erken müdahalenin gerekçesi nedir?", "Gelişim penceresi ve ikincil yetersizliği önleme", ["Geç müdahale daha iyi efsane", "Okul çağı bekle", "İlaç yeter", "Ceza yeter"], "ECI."),
      F("Aile merkezli hizmet ne demektir?", "Önceliklerin aileyle birlikte belirlenmesi", ["Uzmanın dayatması tek", "Çocuğu aileden alma", "Gizleme", "Suçlama"], "Family-centered."),
      F("Doğal ortamda öğretim nedir?", "Ev ve oyun rutininde beceri", ["Yalnızca klinik masa", "Yalnızca test odası", "Yalnızca hastane", "Yalnızca yatakhane"], "Rutin."),
      F("Yenidoğan işitme taraması neden vardır?", "Dil için erken cihaz", ["Moda", "İstatistik süs", "Belediye puanı", "AGS"], "Tarama."),
      F("Bekle gör stratejisinin riski nedir?", "Kaçırılan gelişim zamanı", ["Kendiliğinden her şey düzelir garantisi", "Aile rahatlar yeterli", "Okul çözer 7 yaşta her zaman", "İlaç bekler"], "Pencere."),
      F("Geçiş planı neyi kolaylaştırır?", "Evden kuruma uyum", ["Notu", "MEB puanını", "AGS'yi", "YKS'yi"], "Transition."),
      F("Tarama tanı mıdır?", "Hayır, risk işaretidir", ["Evet mahkeme hükmü", "Evet etiket", "Evet ilaç emri", "Evet BEP zorunlu tek başına"], "Screening."),
      F("Ebeveyn koçluğu ne kazandırır?", "Günlük etkileşim stratejisi", ["Aileyi öğretmen yapmak yükü tek", "Suçluluk", "Teslimiyet", "Kopuş"], "Kapasite.")]),
    ("Uygulamalı Davranış Analizi",
     "UDA ceza bilimi değildir; işlev analizi ve olumlu davranış destekidir. Sönme patlaması bilinmeli.",
     ["**Davranış** gözlenebilir-ölçülebilir.",
      "**ABC** öncül-davranış-sonuç.",
      "**İşlev** dikkat, kaçma, somut, duyusal.",
      "**Pekiştireç** bireye göre.",
      "**Ayırıcı pekiştirme** (DRO, DRA).",
      "**Sönme** kaçış pekiştirecini kesmek.",
      "**Sönme patlaması** geçici artış.",
      "**Beceri öğretimi** davranışın yerine.",
      "**Etik** aversif yöntem son çare ve kurul kararı.",
      "**Veri** grafik.",
      "Ceza **ilk seçenek değildir**.",
      "UDA **yalnızca OSB'ye ait değildir**.",
      "Genelleme **ortam değiştir**.",
      "Sınav: işlev + ABC + etik.",
      "Plan **BEP'e bağlanır**."],
     [F("ABC'de B nedir?", "Behavior (davranış)", ["BEP", "Braille", "BİLSEM", "Bourdieu"], "Zincir."),
      F("Kaçma işlevli davranışta sönme nasıl olur?", "İstenmeyen görevden kaçışı pekiştirmemek + beceri öğretmek", ["Daha çok bağırarak", "Daha çok ceza", "Görevden hep muaf", "Yok sayıp bırakmak tehlikeli her durumda"], "Escape."),
      F("DRA nedir?", "Uygun alternatif davranışı pekiştirme", ["Rastgele ödül", "Sürekli ceza", "Yoklama", "Not kırma"], "Differential."),
      F("Sönme patlaması nedir?", "Pekiştireç kesilince davranışın geçici artışı", ["İyileşme", "Tanı değişimi", "İlaç etkisi", "Deprem"], "Extinction burst."),
      F("Pekiştireç nasıl seçilir?", "Bireyin tercih değerlendirmesiyle", ["Öğretmenin sevdiği şey", "Çikolata herkese", "Alkış herkese", "Para her yaşta"], "Preference."),
      F("UDA etiğinde aversif yöntem nasıl durur?", "Son çare ve sıkı denetim", ["İlk yöntem", "Gizli ceza", "Aileye sormadan elektrik", "Teşhir"], "Etik."),
      F("Veri neden tutulur?", "Müdahalenin işe yarayıp yaramadığını görmek", ["İhbar", "Teşhir", "Not işkencesi", "Velisiz dosya satışı"], "Kanıt."),
      F("Genelleme için ne yapılır?", "Farklı ortam, kişi ve materyalde pratik", ["Tek odada tek kişi sonsuza", "Yalnızca klinik", "Yalnızca test", "Yalnızca ödül odası"], "Transfer.")]),
    ("Bireyselleştirilmiş Eğitim Programları",
     "BEP yasal belgedir; çekmece dosyası değildir. Aile ekip üyesidir.",
     ["**BEP** mevcut performans, yıllık amaç, kısa dönemli amaç, yöntem, süre, değerlendirme, ekip.",
      "**SMART** amaç.",
      "**İşlevsel** amaç günlük yaşam.",
      "**Ekip** öğretmen, özel eğitim, PDR, aile, gerekirse sağlık.",
      "**Gözden geçirme** en az yılda, pratikte daha sık.",
      "**Kaynaştırma planı** destek eğitim odası.",
      "**Uyarlama** içerik-süreç-ürün-ortam.",
      "**Hizmet süresi** çizelge.",
      "**İmza** sorumluluk.",
      "**Geçiş amaçları** kademe.",
      "Kopyala yapıştır BEP **geçersiz pratik**.",
      "Amaç **öğretmenin işini kolaylaştırmaz, öğrencininkini**.",
      "Değerlendirme **amaçla aynı araç**.",
      "Sınav: öge + ekip + uyarlama.",
      "573 sayılı KHK / özel eğitim mevzuatı **çerçeve**."],
     [F("BEP'te mevcut performans ne işe yarar?", "Amaçların başlangıç çizgisi", ["Ceza gerekçesi", "Etiket", "IQ teşhiri", "Aile suçlaması"], "Baseline."),
      F("Kısa dönemli amaç nedir?", "Yıllık amaca giden ölçülebilir basamak", ["Hayal", "Slogan", "Müfredatın tümü", "Öğretmen dileği"], "STO."),
      F("Aile BEP ekibinde neden vardır?", "Hak ve uygulamanın evde sürdürücü", ["İmza makinesi tek", "Suçlu", "İzleyici", "Yok"], "Katılım."),
      F("Uyarlama türlerinden ortam örneği nedir?", "Sıra, ışık, gürültü, süre", ["Müfredatı yok etmek", "Notu silmek", "Arkadaşı silmek", "Okulu kapatmak"], "Access."),
      F("Kopyala yapıştır BEP neden yanlıştır?", "Bireyselleştirme ilkesini bozar", ["Zaman kazandırır meşru her zaman", "MEB ister uydurma", "RAM ister uydurma", "Aile ister uydurma"], "Bireysel."),
      F("Destek eğitim odası neyin parçasıdır?", "Kaynaştırma hizmet sunumu", ["Ceza odası", "Tecrit", "Ödül oda", "Depo"], "Hizmet."),
      F("Amaç ile değerlendirme neden bağlanır?", "Aynı davranışın aynı ölçütle izlenmesi", ["Ayrı evrenler", "Karne notu yeter", "IQ yeter", "Yoklama yeter"], "Hizalama."),
      F("Geçiş amacı ne zaman yazılır?", "Kademe veya kurum değişiminde", ["Yalnızca emeklilikte", "Yalnızca evlenince", "Yalnızca askerde", "Yalnızca üniversitede zorunlu her BEP'te değil ama planlanır"], "Transition.")]),
    ("Özel Eğitimde Değerlendirme",
     "Tanılama tek test değildir; çoklu yöntem ve ekip kararıdır. Test kültürü damgalamasın.",
     ["**Tarama-tanılama-izleme** ayrımı.",
      "**Standart test** sınırlılık (kültür, dil, duyusal).",
      "**Kurum temelli değerlendirme** sınıf gözlemi.",
      "**Portfolyo ve performans**.",
      "**Uyumsal davranış ölçekleri**.",
      "**RAM raporu** eğitim tedbiri.",
      "**Tıbbi tanı ≠ eğitim kararı özdeş**.",
      "**Yeniden değerlendirme**.",
      "**Aileden öykü**.",
      "**Etik** rıza ve geri bildirim dili.",
      "Tek IQ **kader değildir**.",
      "Testi öğrenciye **okuyup şişirmek** geçerliği bozar etik dışı.",
      "İzleme **BEP verisi**.",
      "Sınav: çoklu yöntem + RAM.",
      "Kaynaştırma kararı **ekip**."],
     [F("Tıbbi tanı eğitim yerleştirme kararı mıdır?", "Hayır, eğitim ekibi ihtiyaç ve BEP ile karar verir", ["Evet otomatik ayrı okul", "Evet otomatik evde eğitim", "Evet otomatik muaf", "Evet otomatik üstün"], "Ayrım."),
      F("Kurum temelli değerlendirme nedir?", "Doğal sınıfta gözlem ve iş örneği", ["Yalnızca klinik IQ", "Yalnızca kan tahlili", "Yalnızca MR", "Yalnızca dilekçe"], "Authentic."),
      F("Kültür-dil yanlı testi ne bozar?", "Geçerliği", ["Güvenirliği hiç etkilemez efsane", "Sadece yazı punto", "Sadece kâğıt rengi", "Sadece süre"], "Bias."),
      F("RAM raporunun işlevi nedir?", "Eğitim tedbirini ve yönlendirmeyi belgelemek", ["Mahkûmiyet", "İlaç emri", "Velayet", "Tapu"], "Türkiye."),
      F("İzleme değerlendirmesi ne sıklıkla anlam taşır?", "BEP amaçlarına göre düzenli", ["Mezuniyette bir kez", "Askerde", "Emeklilikte", "Hiç"], "Progress."),
      F("Aile öyküsü neden alınır?", "Gelişim, sağlık ve dil bağlamı", ["Dedikodu", "Suç listesi", "Komşu", "Sosyal medya"], "Anamnez."),
      F("Geri bildirim dili nasıl olmalıdır?", "Güçlü yön + ihtiyaç + hizmet", ["Damga", "Umutsuzluk", "Kıyas", "Tehdit"], "Etik."),
      F("Çoklu yöntem neden şarttır?", "Tek testin hata payını dengelemek", ["Zaman öldürmek", "Kâğıt doldurmak", "Teftiş korkusu", "Puan şişirmek"], "Triangülasyon.")]),
    ("Dil ve İletişim Becerilerinin Desteklenmesi",
     "İletişim konuşmadan ibaret değildir; AAC konuşmayı geciktirmez, destekler.",
     ["**İletişim** davranışla da olur.",
      "**AAC** PECS, cihaz, işaret.",
      "**Ortak dikkat** OSB'de kritik.",
      "**Pragmatik dil** sıra, konu.",
      "**Dil gecikmesi / dil bozukluğu** ayrımı uzman.",
      "**Model olma ve bekleme süresi**.",
      "**Soru yağmuru** dili keser.",
      "**Görsel destek**.",
      "**Yutma/beslenme** ilgiliysa sağlık.",
      "**Aile** evde aynı sistem.",
      "Konuşsun diye AAC **yasaklanmaz**.",
      "Ekolali **anlamsız diye atılmaz**.",
      "Sınıf **dinleme iklimi**.",
      "Sınav: AAC + pragmatik + ortak dikkat.",
      "BEP **iletişim amacı**."],
     [F("AAC konuşmayı geciktirir mi?", "Hayır, araştırmalar destekleyici olduğunu gösterir", ["Evet yasaklanmalı", "Evet tembellik yapar efsane", "Evet dil ölür efsane", "Evet aile reddetmeli"], "Kanıt."),
      F("Ortak dikkat nedir?", "Nesneye birlikte bakış ve paylaşım", ["Göz teması dayatması", "Susturma", "Test", "Ceza"], "OSB."),
      F("Pragmatik dil örneği nedir?", "Sohbette sıra ve konuyu sürdürme", ["Fiil çekimi ezberi", "Harf birleştirme", "Sesletim tek", "Hece"], "Kullanım."),
      F("Bekleme süresi neden vardır?", "İşlemleme ve yanıt üretimi", ["Sessizlik cezası", "İhmal", "Unutma", "Yok sayma"], "Pacing."),
      F("Soru yağmuru neden zararlıdır?", "Çocuğun inisiyatifini kesmesi", ["Dil artışı garantisi", "IQ artışı", "Test başarısı sihri", "İtaat notu"], "Etkileşim."),
      F("Ekolali nasıl okunur?", "İşlevi araştırılır, tamamen anlamsız sayılmaz", ["Alay", "Ceza", "Kesme bağırma", "Yok sayma"], "OSB."),
      F("Görsel destek örneği nedir?", "Program tahtası ve seçim tahtası", ["Yalnızca bağırma", "Yalnızca fısıltı", "Yalnızca ceza", "Yalnızca not"], "Yapı."),
      F("Aile aynı AAC sistemini neden kullanır?", "Genelleme", ["Moda", "Marka", "Teftiş", "Puan"], "Tutarlılık.")]),
    ("Özel Eğitim Politikaları ve Yasal Düzenlemeler",
     "573 sayılı KHK özel eğitimin temel çerçevesidir; BEP ve kaynaştırma yasal haktır. Uydurma madde yazmayın.",
     ["**Anayasa eşitlik ve eğitim hakkı**.",
      "**573 sayılı KHK** özel eğitim.",
      "**Özel eğitim hizmetleri yönetmeliği** uygulama.",
      "**Kaynaştırma/bütünleştirme** öncelik ilkesi.",
      "**RAM** tanılama ve yönlendirme.",
      "**Destek eğitim odası, özel eğitim sınıfı, okulu, evde/hastanede eğitim** kademeli yerler.",
      "**Aile rızası ve tebligat**.",
      "**Engelli hakları sözleşmesi** makul uyarlama.",
      "**7528** öğretmenlik, **1739** sistem.",
      "**Ayrımcılık yasağı**.",
      "Yerleştirme **en az kısıtlayıcı ortam** ilkesine yakındır.",
      "Rapor **gizli**.",
      "İtiraz **idari yol**.",
      "Sınav: yer kademesi + hak.",
      "Politika **kaynak olmadan slogan kalır**."],
     [F("Türkiye'de özel eğitimin çerçeve KHK'si hangisidir?", "573 sayılı KHK", ["2709 tek başına yeter", "222 tek", "7528 tek", "2547 tek"], "Özel eğitim."),
      F("En az kısıtlayıcı ortam ilkesi neyi ister?", "Mümkün olan en genel eğitim ortamını destekle", ["Her zaman ayrı okul", "Her zaman evde eğitim", "Her zaman yatılı", "Her zaman tecrit"], "LRE."),
      F("RAM'ın yasal rolü nedir?", "Eğitsel değerlendirme ve yönlendirme", ["İlaç", "Velayet", "Hapishane", "Tapu"], "Hizmet."),
      F("Makul uyarlama nereden gelir?", "Engelli hakları sözleşmesi / ayrımcılık yasağı", ["Tımar", "Kapitülasyon", "Lonca", "Sened-i İttifak"], "CRPD."),
      F("Destek eğitim odası ayrı okul mudur?", "Hayır, genel okul içi destektir", ["Evet özel eğitim okulu", "Evet evde eğitim", "Evet hastane okulu", "Evet cezaevi"], "Kademe."),
      F("Aile rızası neden önemlidir?", "Yerleştirme ve değerlendirmenin hak boyutu", ["Süs imza", "Teftiş", "Puan", "WhatsApp"], "Hukuk."),
      F("Rapor mahremiyeti kime açıklanır?", "Eğitim-sağlık ihtiyacı olan yetkili ekibe", ["Tüm öğretmen odası sohbeti", "Veliler grubu", "Sosyal medya", "Kantin"], "KVKK."),
      F("Kaynaştırma yasal zorunluluk bağlamında nasıl okunur?", "Öncelikli yerleştirme ilkesi, destek şartıyla", ["Öğretmenin keyfi", "Velinin komşu isteği", "Not ortalaması", "Sıra numarası"], "Politika.")]),
    ("2024 Türkiye Yüzyılı Maarif Modeli Özel Eğitim Programları",
     "TYMM özel eğitim programları 2024'te model diline çekildi. Ezbere madde uydurmayın; yetkinlik, değer, uyarlama vurgusu yeter.",
     ["**TYMM** yetkinlik, erdem-değer-eylem.",
      "**Özel eğitim programları** aynı dilde uyarlanmış kazanım.",
      "**Bireyselleştirme** modelin zorunlu uygulamasıdır.",
      "**İşlevsel akademik ve yaşam becerisi** dengesi.",
      "**Ölçme** süreç kanıtı.",
      "**Aile ve toplum** katılımı.",
      "**Kaynaştırma** genel programla köprü.",
      "**Öğretmen** tasarımcı.",
      "**Dijital erişim**.",
      "**Sürdürülebilirlik ve sağlık** okuryazarlıkları sade.",
      "Model **BEP'i iptal etmez**.",
      "Model **573'ü ilga etmez**.",
      "Kazanım **olduğu gibi kopyalanmaz**.",
      "Sınav: model + BEP ilişkisi.",
      "AGS'de TYMM genel, burada **özel eğitim programı**."],
     [F("TYMM özel eğitim programlarını nasıl etkiler?", "Kazanım dilini yetkinlik ve değerle hizalar", ["BEP'i yasaklar", "573'ü ilga eder", "RAM'ı kapatır", "Kaynaştırmayı kaldırır"], "2024."),
      F("BEP ile TYMM ilişkisi nedir?", "Model genel çerçeve, BEP bireysel uygulama", ["Birbirini yok eder", "Aynı belgedir", "BEP anayasadır model kanun", "Model AİHS'tir"], "Katman."),
      F("Kazanım kopyalamanın sakıncası nedir?", "Bireysel performans çizgisini yok sayması", ["Zaman kazancı meşru her dosyada", "MEB ister uydurma", "Teftiş ister uydurma", "Aile ister uydurma"], "Bireyselleştirme."),
      F("İşlevsel beceri neden modelde durur?", "Bağımsız yaşam yetkinliği", ["Türev", "Osmanlıca", "Kuantum", "NAIRU"], "Uyum."),
      F("Kaynaştırma öğrencisi genel programı nasıl kullanır?", "Uyarlanmış kazanım ve destekle", ["Hiç kullanmaz ayrı evren", "Aynen 80 maddelik test", "Muaf her dersten otomatik", "Sadece resim"], "Köprü."),
      F("Ölçmede model ne ister?", "Yetkinlik kanıtı ve süreç", ["Tek IQ", "Tek kopya test", "Tek sessizlik", "Tek itaat"], "Değerlendirme."),
      F("Öğretmen rolü nedir?", "Programı öğrenciye göre tasarlamak", ["Robot uygulayıcı", "Bekçi", "Katip", "Teslimiyet"], "Agency."),
      F("Erdem-değer-eylem özel eğitimde nasıl okunur?", "Sosyal uyum ve ahlakın yaşantıyla öğretimi", ["Ezber slogan", "Ceza", "İzolasyon", "Nefret"], "TYMM.")]),
    ("Özel Eğitimde Okuma-Yazma Öğretimi",
     "Ses bilgisi temelli, çok duyulu, işlevsel metin. Dislekside ceza yazısı zararlıdır.",
     ["**Fonolojik farkındalık**.",
      "**Harf-ses eşlemesi** sistematik.",
      "**Çok duyulu** (Orton-Gillingham izleri).",
      "**İşlevsel metin** tabela, tarif, isim.",
      "**Braille / AAC yazı** gerektiğinde.",
      "**Akıcılık** tekrarlı okuma utandırmadan.",
      "**Anlama** görsel destek.",
      "**Yazma** motor ve ifade ayrılır.",
      "**Teknoloji** sesli okuma, kelime tahmin.",
      "**Veri** hata türü.",
      "Yaş uygun **onur** (ilkokul kitabı 15 yaşta utandırır, uyarlanmış içerik).",
      "Cezalı kopya **öğretmez**.",
      "Aile **evde kısa pratik**.",
      "Sınav: sistematik + onur + işlev.",
      "BEP **okuma amacı**."],
     [F("Sistematik ses temelli öğretimin gerekçesi nedir?", "Harf-ses bağının açık öğretimi", ["Küresel kelime tek başına her ÖG'de yeter", "Ezber roman", "Ceza diktesi", "Bekle gör"], "Bilim."),
      F("Çok duyulu yöntem ne yapar?", "Görme, işitme, dokunmayı birleştirir", ["Yalnızca bakma", "Yalnızca bağırma", "Yalnızca ceza", "Yalnızca test"], "OG izi."),
      F("İşlevsel metin örneği nedir?", "Otobüs numarası, yemek tarifi, isim yazısı", ["Divan şiiri zorunlu", "Osmanlıca", "Kuantum makale", "Türev"], "Uyum."),
      F("Onurlu yaş uygun metin ne demektir?", "İçerik yaşına uygun, okuma düzeyi uyarlanmış", ["Bebek kitabı 16 yaşa utandırarak", "Aynı sınıf kitabı ne olursa olsun", "Hiç kitap", "Yalnızca test"], "Dignity."),
      F("Cezalı satır yazdırmanın zararı nedir?", "Yazma kaygısı ve kaçınma", ["Disleksi tedavisi", "Motor sihir", "İmla sihri", "Zekâ artışı"], "Duyuş."),
      F("Sesli okuma teknolojisi kopya mıdır?", "Hayır, erişim aracıdır", ["Evet yasak her zaman", "Evet tembellik", "Evet geçerliği bozar her durumda", "Evet aile reddetmeli"], "AT."),
      F("Hata analizi ne işe yarar?", "Öğretilecek ses/örüntüyü seçmek", ["Teşhir", "Not kırma", "Alay", "Kıyas"], "Veri."),
      F("Akıcılık çalışması nasıl yapılır?", "Kısa tekrar, model, utandırmadan", ["Sınıf önünde cezalı", "Kronometre hakareti", "Bağırarak", "Yarış utancı"], "Fluency.")]),
    ("Özel Eğitimde Fen ve Sosyal Bilgiler Öğretimi",
     "Somut, yerel, güvenlik ve vatandaşlık işlevseldir. Soyut ezber ilk hedef değildir.",
     ["**Somut deney ve gezi**.",
      "**Güvenlik fen** (elektrik, temizlik maddesi).",
      "**Sağlık bilgisi** beden mahremiyeti.",
      "**Sosyal** kimlik, kural, para, trafik.",
      "**Harita** basitleştirilmiş.",
      "**Tarih** öykü ve nesne.",
      "**Vatandaşlık** hak-ödev sade.",
      "**Bilimsel süreç** sade tahmin-gözlem.",
      "**Uyarlama** az kavram, çok tekrar.",
      "**Toplum temelli öğretim** market, durak.",
      "Soyut devrim listesi **işlevsel değilse sonraya**.",
      "Laboratuvar **güvenlik**.",
      "Değer **birlikte yaşama**.",
      "Sınav: toplum temelli + güvenlik.",
      "BEP **yaşam bilgisi**."],
     [F("Toplum temelli öğretim nedir?", "Beceriyi gerçek mekânda öğretmek", ["Yalnızca çalışma yaprağı", "Yalnızca video", "Yalnızca sözel tarif", "Yalnızca test"], "Community-based."),
      F("Fen güvenliği örneği nedir?", "Temizlik maddesini tattırmamak", ["Asit deneyi serbest", "Priz deneme", "Ateş yarışı", "Cam kırma"], "Sağlık."),
      F("İşlevsel sosyal bilgiler örneği nedir?", "Para, trafik, kimlik kartı", ["Osmanlı divan ezberi", "Kapitülasyon listesi", "Tımar defteri", "Sened-i İttifak"], "Uyum."),
      F("Az kavram çok tekrar neden vardır?", "Bellek ve genelleme yükü", ["Tembellik", "Zaman doldurma", "Teftiş", "Puan"], "Biliş."),
      F("Mahremiyet öğretimi neden fene bağlanır?", "Beden ve sınır bilgisi", ["Anatomi ezberi üniversite", "Tıp fakültesi", "Ameliyat", "IQ"], "Güvenlik."),
      F("Vatandaşlık sade kazanımı nedir?", "Yardım isteme, kural, hak arama yolu", ["Seçim barajı formülü", "Anayasa mahkemesi usulü tam", "AİHM içtüzük", "NATO"], "Yurttaş."),
      F("Gezi öğretiminde uyarlama nedir?", "Önce görsel hikâye, sonra mekân, sonra tekrar", ["Sürpriz kalabalık", "Kaybolma", "Uyarısız gürültü", "Uzun müze zorunlu"], "Öngörü."),
      F("Tarih öyküsü nasıl seçilir?", "Somut kahraman ve nesne, nefret dili yok", ["Savaş şiddeti yığın", "Ezber yıl", "Nefret", "Uydurma"], "Değer.")]),
    ("Özel Eğitimde Matematik Öğretimi",
     "Para, saat, ölçü işlevsel matematikte öndedir. Diskalkulide utandırma yasaktır.",
     ["**Sayma ve nicelik** somut.",
      "**Para** gerçek madeni.",
      "**Saat** rutin.",
      "**Ölçü** mutfak.",
      "**Basamak** CRA.",
      "**Hesap makinesi** erişim aracı.",
      "**Problem** sahici (otobüs).",
      "**Hata analizi**.",
      "**Az madde ek süre**.",
      "**Grafik** sade.",
      "Ezber çarpım **anlam yoksa işe yaramaz**.",
      "Hesap makinesi **hile değildir** BEP'te.",
      "Kaygı **yanlış azaltır görünür başarıyı**.",
      "Sınav: para-saat + CRA + AT.",
      "BEP **matematik amacı**."],
     [F("İşlevsel matematiğin önceliği nedir?", "Para, saat, ölçü, yön", ["Türev", "İntegral", "Matris", "Logaritma"], "Uyum."),
      F("Gerçek parayla öğretim neden iyidir?", "Genelleme", ["Hırsızlık öğretimi", "İsraf", "Oyun bozma", "Yasak"], "Somut."),
      F("Hesap makinesi BEP'te nedir?", "Erişim teknolojisi", ["Kopya", "Tembellik belgesi", "Yasak araç her zaman", "IQ düşürücü efsane"], "AT."),
      F("CRA sırası nedir?", "Somut, çizim, sembol", ["Sembolden başla zorunlu", "Yalnızca sözel", "Yalnızca yarış", "Yalnızca test"], "Bruner."),
      F("Diskalkulide utandırma ne yapar?", "Kaygı ve kaçınma", ["Tedavi", "Motivasyon sihri", "IQ artışı", "Hız artışı"], "Duyuş."),
      F("Sahici problem örneği nedir?", "İki ekmek alacak parayı seçme", ["Tren problemleri 5 musluk", "Havuz problemleri", "Yaş problemleri soyut", "İşçi problemleri"], "Hayat."),
      F("Az madde ek süre ne sağlar?", "İşlemleme zamanı ve dikkat", ["Hile", "Adaletsizlik efsane her zaman", "Not şişirme", "Tembellik"], "Uyarlama."),
      F("Saat öğretimi neden rutine bağlanır?", "Anlamlı bağlam", ["Estetik", "Duvar süsü", "Teftiş", "Puan"], "İşlev.")]),
    ("Özel Eğitimde Sanatsal Becerilerin Öğretimi",
     "Sanat terapi değildir ama ifade ve motor köprüdür. Ürün yarışı onuru zedeler.",
     ["**İfade** sözsüz iletişim.",
      "**Motor** makas, yapıştırma.",
      "**Duyu** hamur, kum.",
      "**Seçim** renk-araç özerklik.",
      "**Kültür** motif saygısı.",
      "**Kaynaştırma sergisi** onurlu.",
      "**Müzik-görsel-drama** çoklu.",
      "**Uyarlama** kalın sap, büyük zemin.",
      "**Değerlendirme** süreç.",
      "**İletişim** sanatla talep.",
      "Model kopya **tek yol değil**.",
      "Yırtılan iş **değersiz sayılmaz** süreçse.",
      "Aile **evde baskısız**.",
      "Sınav: ifade + uyarlama + onur.",
      "BEP **sanat amacı** olabilir."],
     [F("Sanatın özel eğitimdeki ilk işlevi nedir?", "İfade ve duyusal-motor katılım", ["Terapi unvanı öğretmene", "Yarış", "Teşhir utancı", "Not"], "İletişim."),
      F("Kalın saplı fırça neyin uyarlamasıdır?", "İnce motor güçlüğü", ["Estetik moda", "Lüks", "Ceza", "Yasak ince fırça ideolojisi"], "AT sade."),
      F("Onurlu sergi nasıl olur?", "İzin, isim, akranla yan yana", ["Ayrı acıma köşesi", "İsimsiz", "Alay alt yazısı", "Bebek işi damgası"], "Dignity."),
      F("Seçim sunmak neden önemlidir?", "Özerklik ve iletişim", ["Kaos", "Şımarıklık efsanesi", "Zaman kaybı efsanesi", "Disiplinsizlik"], "Self-determination."),
      F("Duyu hamuru kimler için köprüdür?", "OSB ve motor güçlük dahil birçok öğrenci", ["Yalnızca bebek", "Yalnızca kız", "Yalnızca sanatçı", "Yalnızca üstün zekâlı"], "Duyu."),
      F("Süreç değerlendirmesi nedir?", "Katılım ve kararın belgelenmesi", ["En düzgün kopya", "En hızlı", "En sessiz", "En ucuz"], "Rubrik."),
      F("Sanatla talep örneği nedir?", "Resim kartıyla su isteme", ["Bağırma", "Vurma", "Kaçma tek yol", "Ağlama tek yol"], "AAC izi."),
      F("Yırtılan iş nasıl okunur?", "Duygu veya motor veri olabilir", ["Tembellik", "Nankörlük", "Zekâ geriliği kanıtı", "Disiplin suçu her zaman"], "Gözlem.")]),
    ("Özel Eğitimde Fiziksel Eğitim ve Spor",
     "Uyarlanmış beden eğitimi (APE) haktır. Yarış notu dışlama aracı olamaz.",
     ["**APE** kural, araç, mekân uyarlaması.",
      "**Motor gelişim** kaba-ince.",
      "**Denge ve koordinasyon**.",
      "**Güvenlik** nöbet, nörolojik.",
      "**Tekerlekli sandalye / ortez** saha erişimi.",
      "**Oyun** katılım.",
      "**Sağlık** hekim onayı.",
      "**Duyusal** gürültü-ışık.",
      "**Fair play**.",
      "**Paralimpik farkındalık**.",
      "Kenarda oturtmak **ders değildir**.",
      "Sakatlanma korkusu **tam muafiyet otomatik değildir** (bireysel).",
      "Aile **kıyafet ve cihaz**.",
      "Sınav: APE + güvenlik + katılım.",
      "BEP **motor amacı**."],
     [F("APE nedir?", "Uyarlanmış beden eğitimi", ["Antrenman cezası", "Doping", "WADA", "1RM zorunlu"], "Adapted."),
      F("Kenarda oturtmak neden yanlıştır?", "Hareket hakkını kesmesi", ["Güvenlik her zaman tek çözüm", "Öğretmen rahatı", "Kıyafet bahane her zaman", "Cihaz bahane her zaman"], "Hak."),
      F("Kural uyarlaması örneği nedir?", "İkinci hak, yavaş top, büyük hedef", ["Skoru 0-0 dondurmak utanç", "Oyundan ihraç", "Alay kuralı", "Yoklama"], "Uyarlama."),
      F("Saha erişimi ne ister?", "Rampa, düz zemin, geniş kapı", ["Merdiven tek yol", "Çakıl zorunlu", "Dar kapı", "Kaygan zemin"], "Mekân."),
      F("Duyusal uyarlama örneği nedir?", "Gürültüyü kesmek, kulaklık seçeneği", ["Daha yüksek müzik", "Flaş", "Bağırma", "Islık"], "OSB/işitme."),
      F("Hekim onayı ne zaman kritiktir?", "Kalp, nöbet, ameliyat sonrası", ["Her çocukta olimpiyat", "Hiçbir çocukta", "Yalnızca kızlarda", "Yalnızca erkeklerde"], "Sağlık."),
      F("Fair play özel sporda nedir?", "Kural ve akran saygısı", ["Yenmek için itme", "Alay", "Dışlama", "Hile"], "Değer."),
      F("Motor amaç BEP'te nasıl yazılır?", "Gözlenebilir hareket ve ölçüt", ["Sporcu olsun belirsiz", "Zayıflasın belirsiz", "Koşsun belirsiz", "İyi olsun belirsiz"], "SMART.")]),
    ("Özel Eğitimde Sosyal Uyum Becerilerinin Öğretimi",
     "Sosyal beceri vaazla değil öğretimle gelir: model, prova, pekiştireç, genelleme.",
     ["**Girdi-süreç-çıktı** sosyal öykü, video model.",
      "**Sıra, selam, yardım isteme** işlevsel.",
      "**Duygu tanıma**.",
      "**Çatışma çözme**.",
      "**Gizli müfredat** açık öğretilir.",
      "**Akran aracılı öğretim**.",
      "**Toplum kuralları** market, otobüs.",
      "**Cinsel eğitim / mahremiyet** yaş uygun.",
      "**Zorbalık** koruma.",
      "**Veri** doğal ortam.",
      "Kural ezberi **uygulamasız yetmez**.",
      "Akran **rehber olur, öğretmen yerine geçmez**.",
      "Hata **öğretim fırsatı**.",
      "Sınav: sosyal öykü + mahremiyet + genelleme.",
      "BEP **sosyal amaç**."],
     [F("Sosyal öykü (social story) ne yapar?", "Durumu ve uygun davranışı öyküyle açıklar", ["Ceza yazar", "Teşhir eder", "IQ ölçer", "İlaç önerir"], "Gray hattı."),
      F("Gizli müfredat neden açık öğretilir?", "Örtük kuralın kaçırılması", ["MEB gizlesin", "Aile gizlesin", "Öğrenci tahmin etsin", "Akran alay etsin"], "Açık öğretim."),
      F("Yardım isteme neden işlevseldir?", "Bağımsızlığı ve güvenliği artırır", ["Tembellik", "Bağımlılık efsane her istekte", "Disiplinsizlik", "Şımarıklık"], "İletişim."),
      F("Mahremiyet öğretimi neyi kapsar?", "Beden, özel alan, hayır diyebilme", ["Anatomi üniversite", "Utanç", "Yasak her konuşma", "Gizleyip hiç öğretmeme"], "Güvenlik."),
      F("Akran aracılı öğretimde risk nedir?", "Akranın öğretmen yerine geçip baskı kurması", ["Hiç yarar yok", "Yasak her zaman", "IQ düşüşü", "Dil kaybı"], "Rol."),
      F("Genelleme için sosyal beceri nerede prova edilir?", "Gerçek kuyruk, yemekhane, teneffüs", ["Yalnızca özel oda sonsuza", "Yalnızca test", "Yalnızca sözel tarif", "Yalnızca afiş"], "Doğal."),
      F("Zorbalığa karşı özel eğitim öğrencisi nasıl korunur?", "Açık öğretim, denetim, bildirim", ["Görmezden gelme", "Mağduru suçlama", "Gizleme", "Alay"], "Koruma."),
      F("Video modelin yararı nedir?", "Tekrar izlenebilir doğru örnek", ["Teşhir", "Ceza filmi", "Korkutma", "Reklam"], "ABA/öğretim.")]),
    ("Özel Eğitimde Türkçe Öğretimi",
     "Türkçe işlevsel iletişimdir; dil bilgisi yarışı değildir. AAC Türkçe dersinin parçasıdır.",
     ["**Dinleme-konuşma-okuma-yazma** bireysel ağırlık.",
      "**İşlevsel sözcük** (isim, yardım, dur, daha).",
      "**Görsel destekli metin**.",
      "**Tekrar ve ritim**.",
      "**Anlatı** kısa öykü.",
      "**Yazım** isim ve adres.",
      "**Dil bilgisi** işlevsel cümle kalıbı.",
      "**Değerlendirme** iletişim başarısı.",
      "**İki dilli** aile dili.",
      "**Edebiyat** yaş-onur.",
      "Sessizlik **anlamama sanılmasın**.",
      "Düzeltme **recast**.",
      "Sınıf **söz hakkı**.",
      "Sınav: işlevsel sözcük + AAC + onur.",
      "BEP **Türkçe amacı**."],
     [F("İşlevsel sözcük örneği nedir?", "Yardım, dur, daha, tuvalet", ["Belirteç türleri ezberi", "İsim tamlaması 8 tür", "Aruz", "Redif"], "İletişim."),
      F("Sessiz öğrenci anlamıyor mudur?", "Hayır, üretim ve anlama ayrı ölçülür", ["Evet her zaman", "Evet IQ düşüktür", "Evet OSB değildir başka", "Evet tembeldir"], "Receptive."),
      F("Recast nedir?", "Yanlışı doğru modelle tekrar etmek", ["Azar", "Alay taklit", "Cezalı yazı", "Susturma"], "Dil."),
      F("Görsel destekli metin ne sağlar?", "Anlama ve bağımsız takip", ["Süs", "Bebeksi damga zorunlu", "Yasak", "Kopya"], "Uyarlama."),
      F("Adres yazmak neden Türkçe kazanımıdır?", "Güvenlik ve vatandaşlık", ["Estetik", "İmla yarışı", "Divan", "Gazel"], "İşlev."),
      F("Aile dili neden desteklenir?", "Kimlik ve iletişim temeli", ["Türkçe yasak", "Asimilasyon", "Ceza", "Alay"], "İki dillilik."),
      F("Değerlendirme ölçütü nedir?", "Mesajın iletilmesi", ["Noktasız cümle sıfır", "El yazısı güzelliği tek", "Hız", "Sessizlik"], "İletişim."),
      F("Onurlu edebiyat seçimi nedir?", "İçerik yaşına uygun uyarlanmış metin", ["Bebek masalı utandırarak", "Zorunlu roman aynı sınıf", "Hiç metin", "Yalnızca test"], "Dignity.")]),
    ("Özel Eğitimde Oyun ve Müzik",
     "Oyun ve müzik ödül-ceza kuponu değil öğretim ortamıdır. Pekiştireç olarak sömürülürse oyun hakkı biter.",
     ["**Oyun hakkı**.",
      "**Yapılandırılmış oyun** beceri.",
      "**Serbest oyun** gözlem.",
      "**Müzik** ritim, geçiş, sakinleşme.",
      "**Orff sade**.",
      "**Duyu** ritim titreşim.",
      "**Sosyal oyun** sıra.",
      "**Uyarlama** kural sade.",
      "**Pekiştireç etiği** oyunu tamamen yok etme.",
      "**Aile** ev oyunu.",
      "Oyun saati **iptal cezası olmamalı**.",
      "Müzik **gürültü işkencesi olmamalı**.",
      "Seçim **şarkı**.",
      "Sınav: hak + yapılandırılmış oyun + etik pekiştireç.",
      "BEP **oyun amacı** olabilir."],
     [F("Oyunun özel eğitimdeki yeri nedir?", "Hak ve öğretim ortamı", ["Ceza kuponu", "Lüks", "Tembellik", "Zaman doldurma tek"], "Hak."),
      F("Yapılandırılmış oyun örneği nedir?", "Sıra alma pratikli loto", ["Kaos", "Yarış utancı", "Alay", "İhmal"], "Beceri."),
      F("Müzikle sakinleşme nasıl olur?", "Bilinen kısa ezgi ve ritim", ["Yüksek bas", "Ani flaş+ses", "Bağırma", "Kulak tıkama alayı"], "Düzenleme."),
      F("Oyunu tamamen pekiştireç yapmanın riski nedir?", "Oyunun hakkı bitip rüşvete dönüşmesi", ["Motivasyon sihri sonsuz", "IQ artışı", "Dil sihri", "Motor sihri"], "Etik."),
      F("Titreşim müziği kimde erişimdir?", "İşitme yetersizliği ve bazı OSB profilleri", ["Yalnızca müzisyen", "Yalnızca üstün zekâlı", "Yalnızca kız", "Yalnızca erkek"], "Duyu."),
      F("Kural sadeleştirme örneği nedir?", "Tek kural: topu yuvarla", ["FIFA tam", "Olimpiyat", "WADA", "Ofsayt 5 madde"], "Uyarlama."),
      F("Aileye oyun önerisi nasıl verilir?", "Kısa, ev malzemeli, baskısız", ["2 saat ev ödevi", "Test", "Ceza yazısı", "Kıyas"], "Ev."),
      F("Oyun saatinin iptali neden yanlıştır?", "Gelişim hakkını ceza yapmak", ["Disiplin sihri", "Zaman kazancı meşru her gün", "Öğretmen hakkı tek", "Veli isteği yeter"], "Hak.")]),
    ("Özel Eğitimde Aile Eğitimi",
     "Aile uzman değildir ama ekibin vazgeçilmezidir. Suçluluk dili hizmeti bozar.",
     ["**Yas ve kabullenme** evreleri doğrusal olmayabilir.",
      "**Güçlü yön**.",
      "**Ev programı** kısa, sürdürülebilir.",
      "**Kardeş** duyguları.",
      "**Hak bilgisi** RAM, BEP, rapor.",
      "**Destek grupları**.",
      "**Kriz** nöbet, kaçma.",
      "**Kültürel** inanç ve damga.",
      "**Mahremiyet**.",
      "**Ortakkâr karar**.",
      "Ev ödevi **aile terapistliği değildir**.",
      "Suçlama **işbirliğini öldürür**.",
      "Dil **çeviri**.",
      "Sınav: yas + hak + sürdürülebilir ev programı.",
      "BEP **aile katılımı**."],
     [F("Aile eğitiminin amacı nedir?", "Günlük strateji ve hak bilgisi paylaşmak", ["Aileyi suçlamak", "Aileyi teslim almak", "Çocuğu aileden koparmak", "Gizlemek"], "Ortaklık."),
      F("Sürdürülebilir ev programı nasıl olur?", "Günde birkaç kısa rutin", ["3 saat klinik evde", "20 hedef birden", "Uykusuz gece", "Kardeşi öğretmen yapmak"], "Yük."),
      F("Kardeş duygusu neden konuşulur?", "İhmal ve kıskançlık riski", ["Kardeş yok sayılır", "Kardeş bakıcıdır zorunlu", "Kardeş cezalandırılır", "Kardeş teşhir edilir"], "Aile sistemi."),
      F("Hak bilgisinde ne öğretilir?", "RAM, BEP, itiraz, rapor mahremiyeti", ["Bahşiş", "Torpil", "Sosyal medya linçi", "Komşu baskısı"], "Hukuk."),
      F("Yas sürecinde öğretmen ne yapmaz?", "Hızlı kabullenme dayatması", ["Dinlemek", "Kaynak göstermek", "Zaman tanımak", "Güçlü yön aramak"], "Duygu."),
      F("Kültürel damga ile nasıl çalışılır?", "Saygı+doğru bilgi, utandırmadan", ["Aileyi cahil ilan", "İnançla alay", "Zorla koparma", "Gizleme dayatması utandırarak"], "Kültür."),
      F("Kriz planı aileyle neden paylaşılır?", "Tutarlı ve güvenli yanıt", ["Korkutmak", "Suçlamak", "Tehdit", "Teşhir"], "Güvenlik."),
      F("Ortak karar örneği nedir?", "Amaç önceliğini aileyle seçmek", ["Uzmanın tek imzası", "Öğretmenin tek listesi", "RAM'ın kapalı kutu kararı aile yok", "WhatsApp oylaması sınıf grubu"], "Ekip.")]),
])
