# -*- coding: utf-8 -*-
"""AGS egitim devam + mevzuat."""
from og_data_ags_edu import topic, D, P

M, Q = "AGS Mevzuat", "ags_mevzuat"

TOPICS = [
    topic(D, P, "Eğitimin Ekonomik Temelleri",
          ["İNSAN SERMAYESİ", "KAMU MALİYESİ", "PLANLAMA"],
          ["Eğitim tüketim değil yatırım olarak görülür; fırsat maliyeti boş duran emeği de kapsar."],
          [
              ["**İnsan sermayesi** (Schultz-Becker) eğitimle verimlilik ve gelir artar.",
               "**Dışsallık**: okuryazar toplum sağlık, suç, vatandaşlık kazancı üretir.",
               "**Fırsat maliyeti** okula giden gencin çalışmama kaybıdır.",
               "**Beyin göçü** kamu yatırımının yurt dışına sızmasıdır.",
               "Eğitim **kamu malı** özellikli yarı kamusal maldır; tam piyasaya bırakılmaz."],
              ["**Kamu harcaması / GSYH** eğitim payı politika göstergesidir.",
               "**Özel maliyet** aile; **sosyal maliyet** kamu+aile.",
               "**Getiri oranı** kademeye göre değişir; erken çocukluk yüksek toplumsal getiri tartışılır.",
               "Mesleki eğitim **işgücü piyasası eşleşmesi** ister.",
               "İşsizlik ve **nitelik uyuşmazlığı** (overqualification) ekonomik temel sorusudur."],
              ["Kalkınma planlarında eğitim **nitelikli işgücü** faslıdır.",
               "TYMM **yetkinlik** dili insan sermayesi + değer eğitimini birleştirir.",
               "Eğitim ekonomisi 'okul=fabrika' indirgemesine indirgenemez; hak boyutu vardır.",
               "Kız çocukların okullaşması **toplumsal getiri** açısından kritiktir.",
               "Sınavda ekonomik temel = sermaye, maliyet, dışsallık, planlama."],
          ],
          [
              ("İnsan sermayesi teorisinin özü nedir?", "Eğitime yapılan yatırımın verimlilik ve geliri artırması", ["Toprak reformu", "Tımar", "Kapitülasyon", "Lonca"], "Becker-Schultz."),
              ("Eğitimin olumlu dışsallığına örnek hangisidir?", "Okuryazarlığın kamu sağlığı ve vatandaşlığı güçlendirmesi", ["Sadece özel diploma rantı", "Yalnızca harç", "Yalnızca kıyafet", "Yalnızca servis"], "Sosyal getiri."),
              ("Fırsat maliyeti eğitimde neyi anlatır?", "Okuldayken vazgeçilen kazanç ve zaman", ["Yalnızca kalem masrafı", "Yalnızca harç", "Deprem", "İklim"], "Alternatif maliyet."),
              ("Beyin göçü neden ekonomik kayıptır?", "Kamu eğitim yatırımının başka ülkede kullanılması", ["Turizm geliri", "İhracat artışı zorunlu", "Bor rezervi", "Çay üretimi"], "Beşeri sermaye sızıntısı."),
              ("Eğitim neden tam özel mal sayılmaz?", "Dışsallık ve hak boyutu nedeniyle yarı kamusal kabul edilir", ["Hiç maliyeti yoktur", "Piyasa her zaman yeter", "Devlet yasaktır", "Aile yoktur"], "Kamu finansmanı."),
              ("Nitelik uyuşmazlığı nedir?", "Eğitim düzeyi ile işin gerektirdiği niteliğin tutmaması", ["İklim uyumsuzluğu", "Fay hattı", "Maki", "Bozkır"], "Over/under qualification."),
              ("Erken çocukluk eğitiminin ekonomik gerekçesi nedir?", "Toplumsal getirinin yüksek kabul edilmesi", ["Yalnızca lüks tüketim", "Tımar", "Kapitülasyon", "NATO"], "Heckman tartışması."),
              ("Mesleki eğitimin ekonomik hedefi nedir?", "İşgücü piyasasıyla beceri eşleşmesi", ["Yalnızca ezber", "Yalnızca spor", "Yalnızca turizm yasağı", "Yalnızca Latin"], "Arz-talep."),
              ("Özel maliyet kime aittir?", "Öğrenci ve aileye", ["Yalnızca IMF'ye", "Yalnızca NATO'ya", "Yalnızca belediyeye zorunlu her kalem", "Yalnızca tapuya"], "Kitap, harç, zaman."),
              ("Sosyal maliyet neyi kapsar?", "Kamu ve özel tüm kaynak kullanımını", ["Yalnızca cep harçlığı", "Yalnızca servis", "Yalnızca forma", "Yalnızca kantin"], "Toplumsal kaynak."),
              ("Kızların okullaşmasının ekonomik etkisi nedir?", "Beşeri sermaye ve toplumsal getiri artışı", ["Nüfus yoğunluğunu fay yapar", "İklimi değiştirir", "Maki üretir", "Çığ çıkarır"], "Toplumsal kalkınma."),
              ("Eğitim harcamasının GSYH payı neyi gösterir?", "Kamunun eğitime ayırdığı kaynak önceliğini", ["Deprem şiddetini", "Yağış rejimini", "Fay tipini", "Bitki örtüsünü"], "Politika göstergesi."),
          ]),
    topic(D, P, "Eğitimin Politik Temelleri",
          ["İKTİDAR VE OKUL", "İDEOLOJİ", "KATILIM"],
          ["Eğitim politikası tarafsız teknik iş değil; değer ve iktidar alanıdır."],
          [
              ["Okul **yurttaş üretimi** yapar: müfredat siyasi tercih taşır.",
               "**Merkeziyet-yerinden yönetim** müfredat, atama ve bütçede gerilimdir.",
               "Türkiye'de **MEB** güçlü merkez; il-ilçe milli eğitim taşra örgütüdür.",
               "**Anayasa m.42** eğitim hakkı ve özel okullar çerçevesini çizer.",
               "Öğretmen **kamu görevlisi** olarak siyaset-okul ayrımına tabidir."],
              ["**İdeoloji** gizli müfredatta da işler; eleştirel pedagoji (Freire) ezilenin sözünü arar.",
               "Milli eğitimde **Atatürkçülük** 1739'un değişmez ilkelerindendir.",
               "Laiklik eğitimde **din dersi** ve zorunluluk tartışmalarının anayasal zeminidir.",
               "**Küresel aktörler** (OECD-PISA, AB, UNESCO) politika transferi yapar.",
               "Politika belgesi ≠ sınıf gerçeği; **uygulama açığı** sınavda 'yazılan-yapılan'dır."],
              ["**Veli-öğrenci-öğretmen** katılımı demokratik okul kültürüdür.",
               "Sendika ve meslek kanunu **7528** öğretmenin statüsünü politikalar.",
               "Eğitim politikası **gündem-karar-uygulama-değerlendirme** döngüsüdür.",
               "Çok partili dönemde müfredat **iktidar değişince** revize edilebilir.",
               "Sınavda politik temel = hak, merkez, ideoloji, katılım."],
          ],
          [
              ("Anayasa m.42 neyi düzenler?", "Eğitim ve öğrenim hakkı", ["Vergi istisnası", "Askerlik tecili tek", "Pasaport", "İcra"], "Kimse eğitim hakkından yoksun bırakılamaz."),
              ("Freire'nin eleştirel pedagojisi neye karşıdır?", "Bankacı eğitim modeline", ["İş içinde öğrenmeye", "Proje yöntemine", "Oyun temelli öğrenmeye", "Akran öğretimine"], "Ezberle doldurma eleştirisi."),
              ("MEB teşkilatında merkez-taşra ilişkisi nasıldır?", "Güçlü merkez, il-ilçe taşra", ["Tam kanton federal", "Okul tamamen özerk her karar", "Belediye tek yetkili", "NATO komuta"], "1739 ve teşkilat kanunu."),
              ("PISA gibi taramalar politikalara ne yapar?", "Uluslararası kıyas ve reform baskısı üretir", ["Müfredatı yok eder zorunlu", "Öğretmeni kaldırır", "Okulu kapatır", "Anayasayı ilga eder"], "Politika transferi."),
              ("Öğretmenin kamu görevlisi olmasının politik sonucu nedir?", "Siyasi tarafsızlık ve kanunilik yükümlülüğü", ["Parti militanlığı zorunlu", "Ticaret yasağı yoktur hiç", "Yargı dokunulmazlığı", "Vergi muafiyeti tam"], "657 ve meslek kanunu."),
              ("Uygulama açığı nedir?", "Politika metni ile sınıf pratiğinin farkı", ["Deprem boşluğu", "Fay açıklığı", "Akarsu yatağı", "Heyelan"], "Implementation gap."),
              ("Laikliğin eğitime yansıması nedir?", "Eğitim ve hukukun dünyevi kamu düzenine bağlanması", ["Din dersinin imkânsızlığı her yorumda", "Medresenin zorunluluğu", "Tevhid'in iptali", "1921'e dönüş"], "Tevhid-i Tedrisat hattı."),
              ("Atatürkçülük 1739'da nasıl konumlanır?", "Türk milli eğitiminin temel ilkelerinden", ["Seçmeli kulüp", "Yalnızca lise", "Yalnızca özel okul", "Yasak konu"], "Kanun ilkesi."),
              ("Demokratik okulun göstergesi nedir?", "Paydaş katılımı ve hak temelli iklim", ["Tek sesli ceza", "Keyfi not", "Ayrımcılık", "Gizli kayıt"], "Okul kültürü."),
              ("7528 sayılı kanun politik temelde neyi işler?", "Öğretmenlik mesleğinin statü ve kariyer çerçevesini", ["Orman kadastrosu", "Kapitülasyon", "Tımar defteri", "Lonca nizamı"], "Meslek kanunu."),
              ("Merkezî müfredatın sakıncası ne olabilir?", "Yerel ihtiyaç ve öğretmen özerkliğini kısması", ["Depremi artırması", "İklimi bozması", "Maki yok etmesi", "Çığ"], "Standart vs. bağlam."),
              ("Eğitim hakkı negatif-pozitif boyutta ne ister?", "Müdahale etmeme ve kamu eliyle erişim sağlama", ["Yalnızca harç", "Yalnızca ceza", "Yalnızca sınav", "Yalnızca forma"], "Sosyal hak."),
          ]),
    topic(D, P, "Öğretim Yöntem ve Teknikleri",
          ["YÖNTEM SINIFI", "TEKNİKLER", "SEÇİM"],
          ["Yöntem stratejinin sınıf içi yolu; teknik yöntemin parçasıdır. Sunuş ≠ düz anlatım mecburiyeti."],
          [
              ["**Sunuş** (Ausubel) anlamlı sözel; ön örgütleyici ile kavram haritası.",
               "**Buluş** (Bruner) örnekten kurala; öğrenci keşfeder.",
               "**Araştırma-inceleme** problem çözer, bilimsel süreç becerisi ister.",
               "**Tartışma, örnek olay, problem, proje, işbirlikli** öğrenci merkezli aile.",
               "**Düz anlatım, soru-cevap, gösterip yaptırma** öğretmen ağırlıklıdır."],
              ["Teknik: **beyin fırtınası, altı şapka, istasyon, köşeleme, kartopu, balık kılçığı**.",
               "**Rol oynama ve drama** duyuşsal ve sosyal beceri.",
               "**Mikro öğretim** öğretmen adayında kısa ders+dönüt.",
               "**Anlatım** kalabalık ve zaman darlığında ekonomik, pasiflik riski yüksek.",
               "**İşbirlikli öğrenme** olumlu bağlılık, bireysel hesap verebilirlik ister."],
              ["Yöntem seçiminde **kazanım, süre, hazırbulunuşluk, ortam, maliyet** bakılır.",
               "Bloom'un **bilişsel basamağı** yöntemle eşleşir: analiz için tartışma/proje.",
               "Fen laboratuvarı **gösterip yaptırma + araştırma** ister.",
               "Kalabalık sınıfta **istasyon ve grup** yönetim maliyeti taşır.",
               "Sınav tuzak: yöntem adı ezberi değil **hangi durumda hangisi**."],
          ],
          [
              ("Ausubel'in sunuş yolunda kritik araç nedir?", "Ön örgütleyiciler", ["Ceza", "Kura", "Tımar", "Kapitülasyon"], "Anlamlı öğrenme."),
              ("Bruner'in buluş yoluyla öğrenmesinde akış nasıldır?", "Örneklerden kurala öğrenci keşfi", ["Kuralın ezberletilip uygulanmaması", "Yalnızca düz anlatım", "Yalnızca sınav", "Yalnızca ödev"], "Inductive."),
              ("İşbirlikli öğrenmenin olmazsa olmazı nedir?", "Olumlu bağlılık ve bireysel hesap verebilirlik", ["Tek kişi ödevi tüm grup notu körlemesine", "Yarışmayı kaldırmamak tek", "Sessizlik yasağı", "Öğretmensizlik"], "Johnson kardeşler."),
              ("Mikro öğretimin amacı nedir?", "Kısa ders kaydı ve dönütle öğretmen davranışını düzeltmek", ["Okulu kapatmak", "Müfredatı silmek", "Notu sıfırlamak", "Geziye çıkmak"], "Aday eğitimi."),
              ("Proje yönteminin özelliği nedir?", "Uzun süreli ürün ve araştırma", ["Beş dakikalık quiz", "Tek soru-cevap", "Yoklama", "Dikte"], "Kilpatrick-Dewey hattı."),
              ("Balık kılçığı tekniği ne işe yarar?", "Neden-sonuç analizini görselleştirmek", ["Ritim tutmak", "Harita boyamak", "Spor", "Şarkı"], "Ishikawa."),
              ("Kalabalık ve zaman dar ise ekonomik yöntem hangisidir?", "Düz anlatım / sunuş", ["Birebir klinik", "Uzun proje tek", "Gezi tek", "Laboratuvar tek"], "Maliyet-zaman."),
              ("Gösterip yaptırma hangi alanda sıktır?", "Psikomotor beceri öğretimi", ["Yalnızca felsefe tartışması", "Yalnızca tarih ezberi", "Yalnızca şiir tahlili", "Yalnızca anayasa"], "İş-teknik-fen."),
              ("Örnek olay yönteminde öğrenci ne yapar?", "Gerçekçi bir durumu analiz edip karar üretir", ["Ezber okur", "Sessiz oturur", "Yalnızca dinler", "Kopyalar"], "Case."),
              ("İstasyon tekniğinin riski nedir?", "Sınıf yönetiminin zorlaşması", ["Bilgi hiç oluşmaması zorunlu", "Deprem", "İklim", "Fay"], "Hareket ve gürültü."),
              ("Buluş yolu hangi hazırbulunuşluğu ister?", "Temel kavram ve merak", ["Sıfır ön bilgi her zaman yeter", "Yalnızca ceza", "Yalnızca not kaygısı", "Yalnızca sessizlik"], "Keşif için şema."),
              ("Yöntem seçiminde ilk ölçüt nedir?", "Kazanımın niteliği", ["Öğretmenin alışkanlığı tek", "En kolay yol tek", "En uzun süre tek", "En pahalı araç tek"], "Amaç-araç uyumu."),
          ]),
    topic(D, P, "Sınıf Yönetimi",
          ["MODELLER", "DAVRANIŞ", "İKLİM"],
          ["Sınıf yönetimi disiplin cezası değildir; öğretimi mümkün kılan örgütlemedir."],
          [
              ["**Önleyici** yönetim kural, rutin ve yerleşme ile sorunu doğmadan keser.",
               "**Müdahaleci** model ihlalde sonuç uygular; **gelişimsel** model öz denetim ister.",
               "Kounin: **dalga etkisi, grup odaklılık, eşzamanlılık (overlapping), momentum**.",
               "Gordon: **etkin dinleme, ben dili, kaybeden yok**.",
               "Canter: **iddialı disiplin** net kural ve sonuç."],
              ["Olumlu davranış **pekiştireç**; ceza davranışı baskılar ama alternatif öğretmez.",
               "**Sönme** pekiştirecin kesilmesidir; önce patlama (extinction burst) olabilir.",
               "Kural **az, açık, birlikte konmuş, tutarlı** olmalıdır.",
               "Fiziksel düzen **görüş hattı, hareket alanı, dikkat dağıtmayan uyaran** ister.",
               "Zaman yönetimi **akademik öğrenme zamanını** (time on task) artırır."],
              ["Sınıf iklimi **güven, aidiyet, adil tutum** ile öğrenmeyi taşır.",
               "Öğretmen-öğrenci ilişkisi **sınıf yönetiminin kalbidir**.",
               "Kaynaştırma öğrencisi için **görsel kural, ön uyarı, molalar**.",
               "Krizde **sakin ses, kısa yönerge, güvenli ortam**.",
               "Sınav: yönetim = önlem + ilişki + öğretim sürekliliği."],
          ],
          [
              ("Kounin'in overlapping kavramı nedir?", "İki işi aynı anda yürütebilme", ["Öğrenciyi dışarı atma", "Dersi iptal", "Not kırma", "Veliden gizli ceza"], "Eşzamanlılık."),
              ("Dalga etkisi ne demektir?", "Bir öğrenciye müdahalenin diğerlerini de etkilemesi", ["Deprem dalgası", "Ses fiziği", "Su döngüsü", "Fay"], "Ripple."),
              ("Ben dili kime aittir?", "Thomas Gordon", ["Canter", "Skinner", "Pavlov", "Kounin"], "Etkili öğretmenlik."),
              ("İddialı disiplin yaklaşımı kiminle anılır?", "Canter", ["Rousseau", "Dewey", "Freire", "Bruner"], "Assertive."),
              ("Önleyici sınıf yönetiminin özü nedir?", "Rutin ve kural ile sorunu doğmadan azaltmak", ["Sürekli ceza", "Dersi işlememek", "Yoklama tek", "Kapıyı kilitlemek"], "Proactive."),
              ("Sönme patlaması nedir?", "Pekiştireç kesilince davranışın geçici artışı", ["Deprem", "Heyelan", "Çığ", "Sel"], "Extinction burst."),
              ("Akademik öğrenme zamanı neyi ölçer?", "Öğrencinin kazanımla meşgul olduğu süreyi", ["Teneffüs", "Servis", "Yemek", "Nöbet"], "Time on task."),
              ("İyi kuralın özelliği hangisidir?", "Az sayıda, açık ve tutarlı uygulanır", ["50 maddelik gizli liste", "Günlük değişir", "Yalnızca bağırma", "Keyfi"], "Netlik."),
              ("Ceza neden tek başına yetersizdir?", "İstenen davranışı öğretmez", ["Hiç etki etmez fiziken", "Yasaktır her zaman her kültürde", "Notu yükseltir", "Aidiyet üretir"], "Alternatif davranış gerekir."),
              ("Fiziksel düzenlemede öncelik nedir?", "Öğretmenin tüm sınıfı görebilmesi", ["Pencereleri kapatmak zorunlu", "Sırayı bozmak", "Işığı söndürmek", "Kapıyı açık unutmak"], "Withitness zemini."),
              ("Withitness (farkındalık) ne işe yarar?", "Öğretmenin sınıfta olup biteni fark ettiğini göstermesi", ["Dersi erken bitirmek", "Ödev vermemek", "Sınavı iptal", "Gezi"], "Kounin."),
              ("Kaynaştırma sınıfında yönetim uyarlaması örneği nedir?", "Görsel kural kartı ve ön uyarı", ["Öğrenciyi dışarı daimi çıkarmak", "Notu otomatik sıfır", "İletişimi kesmek", "Aileden gizlemek"], "Erişim."),
          ]),
    topic(D, P, "Program Okuryazarlığı",
          ["ÖGELER", "TASARIM", "TYMM BAĞI"],
          ["Program; amaç, içerik, yaşantı ve değerlendirme bütünüdür. Sadece içerik listesi değildir."],
          [
              ["Tyler: **amaç, içerik, öğrenme yaşantısı, değerlendirme** dört soru.",
               "**Örtük program** yazılmayan etkiler; **ek program** gezi-kulüp.",
               "**İhtiyaç analizi** programın gerekçesidir.",
               "Kazanım **gözlenebilir davranış + içerik + bağlam** taşır.",
               "**Spiral program** (Bruner) aynı kavramı derinleştirerek döner."],
              ["Tasarım: **konu merkezli, öğrenci merkezli, problem merkezli**.",
               "**Doğrusal, sarmal, çekirdek, modüler** örgütleme.",
               "İçerik seçiminde **önem, geçerlilik, ilgi, öğrenilebilirlik, yarar**.",
               "**Yatay bağ** dersler arası; **dikey bağ** kademeler arası.",
               "Uygulayan öğretmen **program okuryazarı** değilse metin kâğıtta kalır."],
              ["TYMM **yetkinlik, erdem-değer-eylem, okuryazarlıklar** ile programı yeniden çerçeveler.",
               "Program okuryazarlığı **kazanımı çözümleme, uyarlama, ölçme aracı üretme**dir.",
               "Öğretmen kılavuzu **sadık uygulama** ile **eleştirel uyarlama** gerilimindedir.",
               "Değerlendirme programın **ayna**sıdır; ölçülmeyen kazanim ihmal edilir.",
               "Sınav: program ≠ yıllık plan ≠ ders kitabı, üçü ilişkili ama özdeş değil."],
          ],
          [
              ("Tyler'ın dört temel sorusundan biri hangisidir?", "Okulun hangi amaçlara ulaşması gerekir", ["Fay hattı nerede", "İklim tipi ne", "Nüfus yoğunluğu", "Bor rezervi"], "Amaç sorusu."),
              ("Örtük program nedir?", "Yazılı olmayan okul etkileri", ["Resmi kazanım listesi", "Ders kitabı indeksi", "Yıllık plan", "Zümre tutanağı"], "Hidden curriculum."),
              ("Sarmal programda kavramlar nasıl işlenir?", "Tekrar ama her seferinde daha derin", ["Bir kez görülüp terk", "Rastgele", "Yalnızca lise", "Yalnızca ezber"], "Bruner spiral."),
              ("Yatay ilişki neyi bağlar?", "Aynı düzeydeki dersleri", ["İlkokulu üniversiteye atlayarak", "Fayları", "İklimleri", "Madenleri"], "Interdisciplinary."),
              ("Dikey ilişki neyi bağlar?", "Kademeler boyunca aynı disiplini", ["İki paralel şubeyi", "Teneffüsü", "Servisi", "Kantin"], "Scope and sequence."),
              ("Kazanımın iyi yazılma ölçütü nedir?", "Gözlenebilir davranış içermesi", ["Belirsiz 'anlar' tek başına", "Öğretmenin keyfi", "Sayfa numarası", "Kitap adı"], "Davranışsal ifade."),
              ("Program ile ders kitabı farkı nedir?", "Kitap programın araçlarından biridir, programın kendisi değil", ["İkisi özdeş", "Kitap anayasadır", "Program yasaktır", "Kitap müfredatı iptal eder"], "Araç-amaç."),
              ("İhtiyaç analizi neden yapılır?", "Programın gerekçesini ve önceliklerini belirlemek", ["Depremi ölçmek", "Yağışı ölçmek", "Nüfusu saymak tek başına yeter", "Maden aramak"], "Tasarımın ilk adımı."),
              ("Çekirdek program neyi ifade eder?", "Herkesin alacağı ortak esaslar", ["Yalnızca seçmeli", "Yalnızca kulüp", "Yalnızca gezi", "Yalnızca sınav"], "Core."),
              ("Modüler örgütlemenin yararı nedir?", "Birimlerin esnek birleştirilmesi", ["Katı tek sıra zorunlu her zaman", "Örtük programı yok eder", "Öğretmeni kaldırır", "Okulu kapatır"], "Esneklik."),
              ("Program okuryazarı öğretmen ne yapar?", "Kazanımı çözer, uyarlar ve ölçer", ["Kitabı satır satır okutur yeter", "Kazanıma bakmaz", "Yalnızca test çözer", "Velisiz karar"], "Literacy."),
              ("Ölçülmeyen kazanım pratikte ne olur?", "İhmal edilme riski artar", ["Otomatik öğrenilir", "Anayasaya girer", "Deprem olur", "İklim değişir"], "Washback."),
          ]),
    topic(D, P, "Ölçme ve Değerlendirme",
          ["TEMEL KAVRAM", "ARAÇLAR", "NOT VE KARAR"],
          ["Ölçme nicelik atar; değerlendirme ölçme sonucunu ölçüte vurup karar verir. İkisini karıştırmayın."],
          [
              ["**Ölçme** bir niteliğe sayı/sembol; **değerlendirme** yargı.",
               "**Dogrudan-dolaylı**, **bağıl-mutlak** ayırımı temel tuzaktır.",
               "**Güvenirlik** tutarlılık; **geçerlik** amaca uygunluk. Güvenirlik geçerliğin önkoşuluna yakındır ama yeterli değildir.",
               "**Duyarlık** birimin inceliği; **objektiflik** puanlayıcıdan bağımsızlık.",
               "**Yordama, görünüş, kapsam, yapı** geçerliği türleridir."],
              ["Madde güçlüğü p; ayırıcılık r. Negatif ayırıcılık madde hatasıdır.",
               "Çoktan seçmeli **kapsam geniş**; yazılı **derinlik**; performans **otantik**.",
               "**Portfolyo** süreç kanıtı; **rubrik** analitik/holistik puanlama.",
               "**Formatif** izleme; **summatif** yargı; **tanılayıcı** ön bilgi.",
               "Klasik test kuramı **gerçek puan + hata**; hata rastgele varsayılır."],
              ["**Bağıl** sınıfa göre; **mutlak** ölçüte göre. TYMM yeterlik dili mutlağa yakındır.",
               "Not vermek değerlendirmedir; ölçme değildir tek başına.",
               "Test planı **belirtke tablosu** ile kapsam geçerliğini korur.",
               "Şans başarısı çoktan seçmelide **düzeltme formülü** tartışmasıdır.",
               "Sınav: 'hangisi güvenirliği artırır' = madde sayısı, açıklık, puanlama anahtarı."],
          ],
          [
              ("Değerlendirme ölçmeden farkı nedir?", "Ölçüte vurup yargı ve karar vermesidir", ["Sayı atamasıdır", "Cetvel tutmaktır", "Şık yazmaktır", "Süre tutmaktır"], "Yargı boyutu."),
              ("Güvenirlik nedir?", "Ölçmenin tutarlılığı", ["Amaca uygunluk", "Kolaylık", "Ucuzluk", "Kısalık"], "Tekrar aynı sonuç."),
              ("Geçerlik nedir?", "Aracın amacı ölçmesi", ["Puanların aynı çıkması", "Şık sayısı", "Yazı punto", "Kağıt rengi"], "Doğru şeyi ölçmek."),
              ("Kapsam geçerliği nasıl korunur?", "Belirtke tablosu ile", ["Rastgele soru", "En zor madde", "En uzun sınav", "Ezber"], "Kazanım-madde matrisi."),
              ("Formatif değerlendirmenin amacı nedir?", "Öğrenmeyi izleyip düzeltmek", ["Karne tek", "Sınıf geçme tek", "Eleme tek", "Kontenjan"], "Biçimlendirici."),
              ("Mutlak değerlendirme neye bakar?", "Önceden konmuş yeterlik ölçütüne", ["Sınıf ortalamasına", "Çan eğrisine", "Kontenjana", "Kura"], "Kriter referans."),
              ("Bağıl değerlendirme neye bakar?", "Grubun dağılımına", ["Sabit baraja yalnızca", "Anayasaya", "Fay hattına", "İklime"], "Norm referans."),
              ("Ayırıcılığı negatif madde neyi gösterir?", "Madde veya anahtar sorununu", ["Mükemmel maddeyi", "Kolaylığı", "Güvenirliği artırdığını", "Geçerliği garantilediğini"], "Üst grup yanlış, alt doğru."),
              ("Rubriğin işlevi nedir?", "Performansı ölçütlere göre puanlamak", ["Yoklama", "Servis listesi", "Nöbet çizelgesi", "Kantin fiyatı"], "Analitik/holistik."),
              ("Portfolyo neyi belgeler?", "Sürece yayılmış ürün ve yansıtmayı", ["Tek sınav kâğıdını", "Ceza defterini", "Yoklamayı", "Servisi"], "Kanıt dosyası."),
              ("Güvenirliği artırmanın yolu hangisidir?", "Madde sayısını ve puanlama nesnelliğini artırmak", ["Sınavı kısaltıp bulanıklaştırmak", "Anahtarsız okumak", "Gürültülü salon", "Zamanı aşırı kısmak"], "Hata azaltma."),
              ("Tanılayıcı değerlendirme ne zaman yapılır?", "Öğretimden önce hazırbulunuşluk için", ["Yalnızca mezuniyette", "Yalnızca emeklilikte", "Yalnızca denetimde", "Yalnızca karnede"], "Diagnostic."),
          ]),
    topic(D, P, "Öğrenme Psikolojisi",
          ["DAVRANIŞÇI", "BİLİŞSEL", "SOSYAL-YAPILANDIRMACI"],
          ["Pekiştireç davranışı artırır; ceza azaltır ama öğrenileni silmeyebilir. Olumsuz pekiştireç ceza değildir."],
          [
              ["**Klasik koşullanma** (Pavlov) nötr uyarıcının koşulsuzla eşlenmesidir.",
               "**Edimsel** (Skinner) sonucun davranışı şekillendirmesidir.",
               "**Olumlu pekiştireç** uyaran ekler; **olumsuz pekiştireç** aversifi kaldırarak artırır.",
               "**Ceza** davranışı azaltır; **sönme** pekiştireci keser.",
               "Thorndike **etki yasası**: doyum veren bağ güçlenir."],
              ["**Gestalt** bütün, içgörü (Köhler); **bilgi işleme** duyusal-kısa-uzun bellek.",
               "Miller **7±2**; **tekrar ve örgütleme** aktarımı sağlar.",
               "Ausubel **anlamlı öğrenme** / ezber karşıtı; şema bağlar.",
               "Piaget **özümseme-uyumsama-denge**; dönemler sınav klasikleridir.",
               "Bloom taksonomisi bilişsel basamak: hatırlama→yaratma."],
              ["Bandura **sosyal öğrenme**: dikkat-hatırda tutma-üretme-güdü; öz yeterlik.",
               "Vygotsky **ZPD** ve **scaffolding**; dil ve sosyal etkileşim.",
               "Yapılandırmacılıkta öğretmen **kolaylaştırıcı**.",
               "Güdü: **içsel-dışsal**; öğrenilmiş çaresizlik (Seligman) güdüyü kırar.",
               "Transfer **yakın-uzak**; olumsuz transfer eski alışkanlığın bozmasıdır."],
          ],
          [
              ("Olumsuz pekiştireç nedir?", "Rahatsız edici uyaranı kaldırarak davranışı artırma", ["Ceza", "Sönme", "Nop", "Klasik koşullanma tek"], "Emniyet kemeri uyarı sesinin kesilmesi."),
              ("Ceza ile olumsuz pekiştireç farkı nedir?", "Ceza azaltır, olumsuz pekiştireç artırır", ["İkisi aynıdır", "Ceza her zaman yasaktır bu yüzden aynıdır", "Pekiştireç azaltır", "Ceza artırır"], "Yön farkı."),
              ("Klasik koşullanmada nötr uyarıcı neye dönüşür?", "Koşullu uyarıcı", ["Pekiştireç", "Ceza", "ZPD", "Şema"], "Zil-salya."),
              ("Bandura'ya göre öğrenme için hangisi gerekir?", "Modelin gözlenmesi ve öz yeterlik-güdü süreçleri", ["Yalnızca pekiştireç laboratuvarı", "Yalnızca salya", "Yalnızca ceza", "Yalnızca gen"], "Sosyal bilişsel."),
              ("ZPD nedir?", "Çocuğun yardımla yapabildiği alan", ["Yetişkinin tek başına yaptığı", "Hayvan içgüdüsü", "Refleks", "Ceza bölgesi"], "Vygotsky."),
              ("7±2 kimin kısa süreli bellek kapasitesidir?", "Miller", ["Pavlov", "Skinner", "Watson", "Thorndike"], "Bilgi işleme."),
              ("Özümseme nedir?", "Yeniyi mevcut şemaya katma", ["Şemayı tamamen yıkma", "Ceza", "Sönme", "Pekiştireç"], "Piaget assimilation."),
              ("Uyumsama nedir?", "Şemayı yeni duruma göre değiştirme", ["Ezber", "Ceza", "Yoklama", "Not"], "Accommodation."),
              ("Öğrenilmiş çaresizlik kime bağlanır?", "Seligman", ["Bruner", "Ausubel", "Kounin", "Canter"], "Kontrol inancı kırılır."),
              ("Anlamlı öğrenme kimin kavramıdır?", "Ausubel", ["Pavlov", "Skinner", "Watson", "Guthrie"], "Ön örgütleyici."),
              ("Olumsuz transfer nedir?", "Eski öğrenmenin yeniyi bozması", ["Yakın transfer", "Pozitif transfer", "Ezber yokluğu", "ZPD"], "Alışkanlık çatışması."),
              ("İçsel güdü örneği hangisidir?", "Merak ve işin kendisinden alınan doyum", ["Not korkusu tek", "Ceza tehdidi", "Hediye tek", "Kıyas tek"], "Intrinsic."),
          ]),
    topic(D, P, "Gelişim Psikolojisi",
          ["İLKELER", "DÖNEMLER", "AHLAK-BAĞLANMA"],
          ["Gelişim süreklidir, basamaklıdır, kalıtım-çevre etkileşimlidir. Kritik dönem ile duyarlı dönemi ayırın."],
          [
              ["İlkeler: **baştan ayağa, içten dışa, genelden özele**.",
               "**Kritik dönem** kaçınca telafisi zor; **duyarlı dönem** öğrenmeye yatkınlık.",
               "Gelişim alanları **bilişsel, dil, sosyal-duygusal, fiziksel** iç içedir.",
               "Olgunlaşma **biyolojik hazırlık**; öğrenme yaşantı ister.",
               "Bireysel fark **tempo ve üslup**ta görünür, gelişim yok sayılmaz."],
              ["Piaget: duyusal-motor, işlem öncesi, somut, soyut işlem.",
               "Ergenlikte **soyut işlem** ve kimlik (Erikson **kimlik-rol karmaşası**).",
               "Erikson 8 evre; okul çağı **başarıya karşı aşağılık**.",
               "Dil: **bebeksi konuşma**, **telegrafik**, Chomsky **dil edinimi donanımı** tartışması.",
               "Oyun: Piaget **alıştırma-sembolik-kurallı**; Vygotsky oyunu ZPD sayar."],
              ["Bağlanma (Bowlby-Ainsworth): **güvenli, kaygılı, kaçınan, dağınık**.",
               "Kohlberg ahlak: **itiat-ceza, araçsal, iyi çocuk, yasa, toplumsal sözleşme, evrensel ilke**.",
               "Gilligan **care** etiği ile Kohlberg'e eleştiri getirir.",
               "Ergen **kişisel efsane ve hayali seyirci** (Elkind).",
               "Sınav: dönem + ilke + kuramcı eşleşmesi."],
          ],
          [
              ("Baştan ayağa gelişim ilkesi hangisidir?", "Sefalokaudal", ["Proksimodistal", "Genelden özele ters", "Yalnızca sosyal", "Yalnızca ahlak"], "Baş kontrolü ayaktan önce."),
              ("Proksimodistal ne demektir?", "İçten dışa (gövdeden parmaklara)", ["Baştan ayağa", "Sondan başa", "Yalnızca dil", "Yalnızca ahlak"], "Kol-el-parmak."),
              ("Piaget'te somut işlemler dönemi kabaca hangi yaştır?", "7-11 yaş", ["0-2", "2-4 yalnızca", "12+ soyut", "Yetişkinlik"], "Korunum."),
              ("Korunum ilkesi hangi dönemde kesinlik kazanır?", "Somut işlemler", ["Duyusal motor", "İşlem öncesi erken", "Yok", "Yaşlılık"], "Sıvı-kütle."),
              ("Erikson'da okul çağı krizi nedir?", "Başarıya karşı aşağılık", ["Güvene karşı güvensizlik", "Kimlik karmaşası", "Durgunluk", "Umutsuzluk"], "Industry vs inferiority."),
              ("Ergenlikte Erikson krizi nedir?", "Kimliğe karşı rol karmaşası", ["Güven", "Özerklik", "Üretkenlik", "Bütünlük"], "Identity."),
              ("Güvenli bağlanmanın temeli nedir?", "Bakımverenin duyarlı ve tutarlı yanıtı", ["İhmal", "Ceza", "Tutarsız reddediş", "Aşırı korkutma"], "Ainsworth."),
              ("Kohlberg'in geleneksel düzeyi hangileridir?", "İyi çocuk ve yasa-düzen", ["İtaat-ceza yalnızca", "Evrensel ilke yalnızca", "Kişisel efsane", "Hayali seyirci"], "Conventional."),
              ("Hayali seyirci kimin kavramıdır?", "Elkind", ["Piaget yalnızca", "Freud yalnızca", "Watson", "Skinner"], "Ergen egosantrizmi."),
              ("Kritik dönem için örnek hangisidir?", "Erken dil maruziyeti kaçınca telafinin zorlaşması", ["Her yaşta eşit kolaylık", "Yalnızca emeklilik", "Yalnızca üniversite", "Yalnızca askerlik"], "Duyarlı/kritik ayrımı."),
              ("Vygotsky oyunu nasıl görür?", "ZPD içinde gelişim ortamı", ["Zaman kaybı", "Ceza", "Yalnızca motor", "Yalnızca Piaget alıştırma"], "Sosyal oyun."),
              ("İşlem öncesi dönemin sınav klasiği nedir?", "Egosantrizm ve animizm", ["Soyut hipotez", "Meslek kimliği", "Korunum kesin", "Üretkenlik"], "Preoperational."),
          ]),
    topic(D, P, "Rehberlik",
          ["HİZMETLER", "İLKELER", "PSİKOLOJİK DANIŞMA"],
          ["Rehberlik tüm öğrencilere gelişimsel hizmettir; yalnızca sorunlu öğrenciye kriz müdahalesi değildir."],
          [
              ["Hizmetler: **eğitsel, mesleki, kişisel-sosyal**.",
               "**Gelişimsel, önleyici, çare bulucu** düzeyler.",
               "Okul psikolojik danışmanı **sınıf rehberliği + bireysel + grup + konsültasyon**.",
               "RAM ve BEP süreçlerinde **ekip** çalışır.",
               "Kriz anında **yöneltme** (referral) etik yükümlülüktür."],
              ["İlkeler: **gönüllülük, gizlilik, kabul, süreklilik, öğrenci merkezlilik**.",
               "Gizliliğin sınırı **kendine/başkasına zarar ve yasal bildirim**.",
               "Testler **karar yerine bilgi**; etiketleme aracı değildir.",
               "Mesleki rehberlikte **Holland** tipleri ve iş değerleri.",
               "Eğitsel rehberlik **ders seçimi, öğrenme stili, sınav kaygısı**."],
              ["Kuramlar: **kişen merkezli (Rogers), bilişsel-davranışçı, gerçeklik (Glasser), adlerian**.",
               "Rogers: **koşulsuz kabul, empati, saydamlık**.",
               "Grupla psikolojik danışma **gizlilik sözleşmesi** ister.",
               "Aile ile çalışma **konsültasyon**; terapi her okulda klinik terapi değildir.",
               "Sınav: rehberlik = gelişimsel + etik + hizmet alanı."],
          ],
          [
              ("Gelişimsel rehberliğin hedef kitlesi kimdir?", "Tüm öğrenciler", ["Yalnızca disiplinlikler", "Yalnızca üstün zekâlılar", "Yalnızca mezunlar", "Yalnızca veliler"], "Kapsayıcı."),
              ("Gizliliğin kırılabileceği durum hangisidir?", "Ciddi zarar riski ve yasal bildirim yükümlülüğü", ["Öğretmen meraki", "Veli ısrarı her konuda", "Not yükseltmek", "Rehber saati dolması"], "Etik sınır."),
              ("Rogers'ın üç koşulu nedir?", "Empati, koşulsuz kabul, saydamlık", ["Ceza, ödül, yoklama", "Test, not, karne", "Vaaz, öğüt, azar", "Kura, çan, zil"], "Kişen merkezli."),
              ("Eğitsel rehberlik örneği hangisidir?", "Ders seçimi ve öğrenme becerisi çalışması", ["Yalnızca iş ilanı", "Yalnızca kriz", "Yalnızca sağlık taraması", "Yalnızca kantin"], "Akademik gelişim."),
              ("Mesleki rehberlikte Holland neyi sınıflar?", "Kişilik-meslek tiplerini", ["İklim tiplerini", "Fayları", "Bitki örtüsünü", "Madenleri"], "RIASEC."),
              ("Konsültasyon nedir?", "Öğretmen-aile ile dolaylı yardım", ["Öğrenciyi cezalandırma", "Not kırma", "Sınıftan atma", "Sınav iptali"], "Indirect service."),
              ("Çare bulucu hizmet ne zaman öne çıkar?", "Sorun ortaya çıktıktan sonra", ["Hiç sorun yokken yalnızca kutlama", "Mezuniyette tek", "Emeklilikte", "Askerde"], "Remedial."),
              ("Önleyici rehberlik örneği nedir?", "Akran zorbalığı farkındalık programı", ["Kriz sonrası yas danışması tek", "Adli vaka tek", "Hastane sevk tek", "Disiplin kurulu tek"], "Preventive."),
              ("Test sonucunun etik kullanımı nasıldır?", "Kararı destekleyen bilgidir, etiket değildir", ["Kader hükmü", "Sınıf dışına atma gerekçesi tek", "Aileye şantaj", "Sosyal medya paylaşımı"], "Assessment."),
              ("Yöneltme (referral) ne demektir?", "Yetkinliğin dışındaki vakayı ilgili birime göndermek", ["Dosyayı gizlemek", "Öğrenciyi yok saymak", "Not şişirmek", "Sınav kaçırmak"], "Yetkinlik sınırı."),
              ("Grupla çalışmada ilk sözleşme maddesi nedir?", "Gizlilik", ["Not", "Disiplin", "Para", "Üniforma"], "Güven."),
              ("Okul danışmanının asıl rolü hangisidir?", "Gelişimsel rehberlik ve psikolojik danışma", ["Müdür yardımcılığı zorunlu", "Nöbet tek iş", "Muhasebe", "Kantincilik"], "PDR."),
          ]),
    topic(D, P, "Eğitim ve Öğretim Teknolojileri",
          ["KAVRAM", "TASARIM", "ETİK"],
          ["Teknoloji araçtır; pedagoji yoksa slayt da düz anlatımdır. TPACK pedagoji+alan+teknoloji kesişimi."],
          [
              ["**Öğretim teknolojisi** öğrenmeyi kolaylaştıran sistematik tasarım ve araçtır.",
               "SAMR: **ikame, artırma, değiştirme, yeniden tanımlama**.",
               "TPACK: alan, pedagoji, teknoloji bilgisi.",
               "ADDIE: analiz, tasarım, geliştirme, uygulama, değerlendirme.",
               "Uzaktan eğitim **eşzamanlı-eşzamansız**; etkileşim üçlüsü öğrenci-içerik-öğretmen."],
              ["Çoklu ortam ilkeleri (Mayer): **gereksiz uyaranı kes, söz+görsel, parça parça**.",
               "Oyunlaştırma **puan-rozet-seviye**; güdü dışsallaşabilir.",
               "Açık kaynak ve **EBA** Türkiye bağlamında içerik havuzu.",
               "Ölçmede **bilgisayar uyarlamalı test** yetenek düzeyine madde seçer.",
               "Erişilebilirlik: altyazı, ekran okuyucu, kontrast."],
              ["Dijital vatandaşlık **etik, güvenlik, telif, mahremiyet**.",
               "Öğrenci verisi **KVKK** çerçevesinde işlenir.",
               "Yapay zekâ ödevde **akademik dürüstlük** politikası ister.",
               "Teknoloji eşitsizliği **dijital uçurum** fırsat eşitsizliğini büyütür.",
               "Sınav: araç adı değil **öğrenme kazanınını nasıl değiştirdiği**."],
          ],
          [
              ("TPACK neyin kesişimidir?", "Teknoloji, pedagoji ve alan bilgisi", ["Yalnızca yazılım", "Yalnızca donanım", "Yalnızca internet hızı", "Yalnızca projeksiyon"], "Mishra-Koehler."),
              ("SAMR'de ikame ne demektir?", "Eski işin aynı şekilde dijital yapılması", ["Öğrenmenin yeniden icadı", "Okulun kapanması", "Öğretmensizlik", "Sınavsızlık"], "Substitution."),
              ("ADDIE'nin ilk basamağı nedir?", "Analiz", ["Değerlendirme", "Uygulama", "Geliştirme", "Yayın"], "İhtiyaç ve bağlam."),
              ("Mayer'in tutarlılık ilkesi nedir?", "Gereksiz ses-görseli çıkarmak", ["Ne kadar süs o kadar iyi", "Müzik zorunlu", "Gif zorunlu", "Otomatik slayt"], "Cognitive load."),
              ("Eşzamansız uzaktan eğitimin özelliği nedir?", "Zaman bağımsız erişim", ["Aynı anda canlı zorunlu", "Yüz yüze tek", "Yoklama yokluğu zorunlu başarı", "Öğretmensizlik"], "Asynchronous."),
              ("Dijital uçurum neyi anlatır?", "Erişim ve beceri eşitsizliğini", ["Fay hattını", "İklimi", "Maki", "Bozkır"], "Fırsat."),
              ("KVKK eğitim teknolojisinde neyi bağlar?", "Öğrenci kişisel verisinin işlenmesini", ["Ders saatini", "Teneffüsü", "Kantini", "Nöbeti"], "Mahremiyet."),
              ("Bilgisayar uyarlamalı test ne yapar?", "Yanıta göre sonraki maddeyi seçer", ["Aynı kâğıdı tarar", "Yoklama alır", "Servis çizer", "Nöbet yazar"], "CAT."),
              ("EBA'nın işlevi nedir?", "Ulusal dijital içerik ve eğitim ağı sunmak", ["Vergi toplamak", "Tapu vermek", "Pasaport basmak", "Asker yazmak"], "MEB."),
              ("Oyunlaştırmanın riski nedir?", "Dışsal güdünün içsel merakı bastırması", ["Öğrenmeyi imkânsız kılması her zaman", "Deprem", "İklim", "Çığ"], "Pointsification."),
              ("Erişilebilir teknoloji örneği nedir?", "Altyazı ve ekran okuyucu desteği", ["Yalnızca yüksek çözünürlük videosu", "Yalnızca otomatik müzik", "Yalnızca reklam", "Yalnızca pop-up"], "Inclusion."),
              ("Pedagojisiz slayt neye dönüşür?", "Dijitalleşmiş düz anlatıma", ["Buluş yoluna", "ZPD'ye", "İşbirlikli öğrenmeye", "Proje yöntemine"], "SAMR ikame."),
          ]),
    topic(D, P, "Türk Millî Eğitim Sisteminin Genel Yapısı",
          ["AMAÇ VE İLKE", "KADEMELER", "TEŞKİLAT"],
          ["1739 hem amaç hem ilkeleri hem de kademeleri çerçeveler. Teşkilat ayrı kanunlarla da yürür."],
          [
              ["Genel amaç: **Atatürk ilke ve inkılapları**, milli-ahlaki-insani değer, beden-zihin-duygu dengesi.",
               "İlkeler: **genellik-eşitlik, planlılık, karma, Atatürkçülük, demokrasi, laiklik, bilim** vb.",
               "Türkçenin **eğitim dili** olması 1739 ilkesidir.",
               "Karma eğitim ilkedir; istisnalar kanunla tartışılır.",
               "Fırsat ve imkân eşitliği taşra ve özel eğitimle somutlanır."],
              ["Okulöncesi, ilkokul, ortaokul, ortaöğretim, yükseköğretim kademeleri.",
               "Zorunlu eğitim **12 yıl kademeli** (4+4+4) güncel çerçevedir.",
               "Mesleki ve teknik, imam hatip, güzel sanatlar, spor liseleri program çeşitliliğidir.",
               "Hayat boyu öğrenme **yaygın eğitim** (halk eğitimi, olgunlaşma) ile yürür.",
               "Özel öğretim kurumları MEB denetiminde kamu hizmeti niteliği taşır."],
              ["MEB merkez-taşra-yurt dışı teşkilatı; Talim ve Terbiye Kurulu program-ders kitabı.",
               "YÖK yükseköğretimi koordine eder; 1739 yükseköğretimi de sistemin parçası sayar.",
               "Rehberlik araştırma merkezleri özel eğitim ve rehberlik destekler.",
               "Öğretmen atama ve adaylık **7528 + mevzuat** ile örülür.",
               "Sınav: kademe adı + zorunluluk + ilke maddesi."],
          ],
          [
              ("1739 sayılı kanun hangisidir?", "Millî Eğitim Temel Kanunu", ["Öğretmenlik Mesleği Kanunu", "İlköğretim ve Eğitim Kanunu", "Anayasa", "TCK"], "1973."),
              ("Türk milli eğitiminin genel amaçlarından biri nedir?", "Atatürk ilke ve inkılaplarına bağlı yurttaş yetiştirmek", ["Tımarı yaşatmak", "Kapitülasyonu genişletmek", "Saltanatı geri getirmek", "Medreseyi tek sistem yapmak"], "1739 amaç."),
              ("Karma eğitim 1739'da nasıl konumlanır?", "Temel ilkelerdendir", ["Yasak", "Yalnızca üniversite", "Yalnızca özel okul", "Yalnızca kurs"], "Kız-erkek birlikte."),
              ("Güncel zorunlu eğitim süresi hangisidir?", "12 yıl kademeli", ["5 yıl", "8 yıl kesintisiz eski tek", "3 yıl", "16 yıl"], "4+4+4."),
              ("TTK'nın klasik işlevi nedir?", "Program ve ders kitabı inceleme-karar", ["Vergi", "Tapu", "Askerlik", "Pasaport"], "Talim Terbiye."),
              ("Yaygın eğitim örneği hangisidir?", "Halk eğitimi merkezi kursları", ["İlkokul 3. sınıf", "Anadolu lisesi 10. sınıf", "Tıp fakültesi", "Hukuk fakültesi"], "Formal dışı."),
              ("RAM'ın rolü nedir?", "Rehberlik ve özel eğitim değerlendirme-destek", ["Vergi denetimi", "İmar", "Trafik", "Gümrük"], "Rehberlik Araştırma Merkezi."),
              ("Özel okullar hukukî olarak nasıl denetlenir?", "MEB mevzuatı ve denetimi altında", ["Tamamen denetimsiz", "Yalnızca belediye", "Yalnızca noter", "Yalnızca oda"], "Kamu hizmeti niteliği."),
              ("Ortaöğretimde program çeşitliliği ne işe yarar?", "İlgi ve meslek yönelimine göre güzergâh", ["Zorunluluğu kaldırmak", "İlkokulu kapatmak", "YÖK'ü ilga", "Anayasayı aşmak"], "Genel-mesleki-imam hatip vb."),
              ("Eğitim dili ilkesi 1739'da nedir?", "Türkçe", ["Yalnızca Osmanlıca", "Yalnızca Arapça", "Yalnızca İngilizce", "Yalnızca Latince"], "Kanun ilkesi."),
              ("Planlılık ilkesi neyi ister?", "Eğitimin kalkınma planlarıyla uyumunu", ["Plansız deneme", "Günlük keyif", "Rastgele okul", "Kura ile müfredat"], "Kalkınma-eğitim bağı."),
              ("Yükseköğretim milli eğitim sistemi içinde nasıl durur?", "Sistemin bir kademesi olup YÖK koordinasyonundadır", ["MEB'in günlük ders çizelgesindedir her fakülte", "Belediye kursudur", "Yaygın eğitimdir", "İlköğretimdir"], "1739 + 2547 hattı."),
          ]),
    topic(D, P, "Türkiye Yüzyılı Maarif Modeli",
          ["ÇERÇEVE", "YETKİNLİK VE DEĞER", "UYGULAMA"],
          ["TYMM 2024 program yenilemesinin adıdır; ezbere madde uydurmayın. AGS 2026'da kapsamı genişleyen başlıktır."],
          [
              ["Model **öğrenci profili**: yetkin, erdemli, eylemli birey tasviri taşır.",
               "**Erdem-değer-eylem** üçlüsü duyuşsal alanı programın omurgasına çeker.",
               "**Okuryazarlıklar** (dijital, finans, sürdürülebilirlik vb.) disiplinlerüstü hedeflerdir.",
               "Program yaklaşımı **sarmal ve bütüncül**; kesik kazanım listesinden sisteme geçer.",
               "Ölçme **süreç + ürün + yeterlik** diline kayar."],
              ["Alan becerileri ile **kavramsal beceriler** (analiz, yorum) birlikte işlenir.",
               "Sosyal-duygusal öğrenme resmi dile girer.",
               "Öğretmen **tasarımıcı ve kolaylaştırıcı**; sadık kitapsever değil.",
               "Ders kitapları modele göre **yeniden yazılır**; eski kitap ezberi yetmez.",
               "Özel eğitim programları da **2024 TYMM** dilinde güncellenir (ÖABT özel eğitim)."],
              ["Uygulama **zümre, ders planı, ölçme aracı** uyumu ister.",
               "Velilere model **değer ve yetkinlik** diliyle anlatılır, sloganla değil.",
               "AGS sorusu modelin **felsefi kökü** (bütüncül insan) ile **ölçme sonucu**nu bağlar.",
               "TYMM, 1739'un amaçlarını iptal etmez; **program katmanında** yeniler.",
               "Ezber tuzak: modelin her cümlesini kanun maddesi sanmak."],
          ],
          [
              ("TYMM'nin duyuşsal omurgası hangi üçlüyle anılır?", "Erdem, değer, eylem", ["Ceza, ödül, yoklama", "Not, karne, belge", "Tımar, iltizam, lonca", "Fay, iklim, maki"], "Program söylemi."),
              ("TYMM öğrenci profilinde öne çıkan nedir?", "Yetkinlik temelli bütüncül gelişim", ["Yalnızca test puanı", "Yalnızca ezber", "Yalnızca spor", "Yalnızca itaat"], "Profil."),
              ("Okuryazarlıklar TYMM'de nasıl konumlanır?", "Disiplinlerüstü yetkinlikler", ["Yalnızca ilkokul okuma", "Yalnızca imla", "Yalnızca hat", "Yalnızca kâğıt"], "Digital vb."),
              ("TYMM ölçmede neye kayar?", "Süreç, ürün ve yeterlik kanıtına", ["Tek çoktan seçmeli kader", "Kura", "Çan eğrisi zorunlu", "Yoklama notu"], "Yetkinlik."),
              ("Öğretmenin modeldeki rolü nasıldır?", "Öğrenme yaşantısını tasarlayan kolaylaştırıcı", ["Kitabı okuyan tek kaynak", "Yok", "Yalnızca bekçi", "Yalnızca not memuru"], "Agency."),
              ("TYMM 1739 ile çelişir mi?", "Hayır, kanun çerçevesinde program yenilemesidir", ["1739'u ilga eder", "Anayasayı aşar", "YÖK'ü kapatır", "MEB'i kaldırır"], "Katman farkı."),
              ("Sosyal-duygusal öğrenme neden modele girer?", "Bütüncül öğrenci profili için", ["Fen laboratuvarı yerine", "Matematik yerine", "Türkçe yerine", "Tarih yerine"], "SEL."),
              ("Özel eğitim 2024 programları neden TYMM ile anılır?", "Aynı model dilinde güncellenmiş olmaları", ["Özel eğitimin kaldırılması", "BEP yasağı", "RAM kapanması", "Kaynaştırma yasağı"], "ÖABT 2026 başlığı."),
              ("Sarmal bütüncül yaklaşım neyi azaltır?", "Kopuk kazanım ezberini", ["Değer eğitimini", "Öğretmen rolünü", "Okulu", "Aileyi"], "Sistemik program."),
              ("AGS'de TYMM'nin önemi nedir?", "2026'da eğitim bilimleri kapsamının genişletilen başlığı olması", ["Sözel mantık yerine geçmesi", "Mevzuatı iptal etmesi", "ÖABT'yi kaldırması", "GY-GK olması"], "MEB duyurusu."),
              ("Ders kitabı-model ilişkisi nasıldır?", "Kitaplar modele göre yenilenir, tek başına program değildir", ["Kitap anayasadır", "Model kitapsızdır zorunlu", "Kitap yasaktır", "Model kâğıtsızdır"], "Araç."),
              ("Erdem-değer-eylem üçlüsünün sınav tuzağı nedir?", "Üçlüyü Bloom taksonomisinin bilişsel basamakları sanmak", ["Değerin duyuşsal oluşu", "Eylemin davranışa dökülmesi", "Erdemin ahlak boyutu", "Bütüncül profil"], "Ayrı çerçevedir."),
          ]),
    topic(M, Q, "T.C. Anayasası",
          ["2709 ÇERÇEVE", "HAKLAR VE EĞİTİM", "KAMU GÖREVI"],
          ["1982 Anayasası 2709 sayılıdır. Eğitim hakkı m.42; sosyal hukuk devleti m.2; değiştirilemez hükümler m.1-3 m.4 koruması."],
          [
              ["**m.1** devlet şekli Cumhuriyet; **m.2** Cumhuriyetin nitelikleri; **m.3** bütünlük, dil, bayrak, milli marş, başkent.",
               "**m.4** ilk üç maddenin değiştirilemeyeceği ve değiştirilmesinin teklif edilemeyeceği.",
               "**Kuvvetler ayrılığı** 1982'de organlar düzeninde; yasama TBMM.",
               "Temel haklar **kanunla sınırlanır**, özüne dokunulamaz (m.13 ölçülülük).",
               "Olağanüstü hallerde sınırlama rejimi ayrıdır; çekirdek haklar korunur."],
              ["**m.42** kimse eğitim ve öğrenim hakkından yoksun bırakılamaz; ilköğretim kız-erkek tüm vatandaşlar için zorunlu ve devlet okullarında parasızdır.",
               "Eğitim Atatürk ilkeleri doğrultusunda, çağdaş bilim ve eğitim esaslarına göre yapılır; bu esaslar dışındaki eğitim-öğretim yapılamaz.",
               "Özel okullar devlet gözetiminde kanunla açılır.",
               "**m.10** kanun önünde eşitlik; **m.24** din ve vicdan hürriyeti, din kültürü zorunlu ders anayasa hükmüdür.",
               "**m.90** usulüne göre yürürlüğe temel hak-hürriyet uluslararası antlaşmalar kanun çatışmasında esas."],
              ["Kamu hizmetine girme **m.70** eşitlik; memurlar **m.128** kanunla düzenlenen statü.",
               "Öğretmen kamu görevlisidir; **ifade hürriyeti** m.26 kamu göreviyle sınırlanabilir.",
               "Aile **m.41** toplumun temeli; çocuk koruma devletin ödevidir.",
               "Sosyal devlet eğitim, sağlık, sosyal güvenlik yükümlülüğü doğurur.",
               "Sınav: madde numarası + öz güvence; uydurma madde yazmayın."],
          ],
          [
              ("1982 Anayasası'nın sayısı nedir?", "2709", ["1739", "222", "7528", "2547"], "Kabul 7.11.1982."),
              ("Değiştirilemez maddeleri koruyan hüküm hangisidir?", "m.4", ["m.42", "m.90", "m.128", "m.24"], "İlk üç madde."),
              ("Eğitim ve öğrenim hakkı hangi maddedir?", "m.42", ["m.2", "m.10", "m.17", "m.90"], "Zorunlu ilköğretim ve parasızlık."),
              ("m.42'ye göre devlet okullarında ilköğretim nasıldır?", "Zorunlu ve parasız", ["İsteğe bağlı ücretli", "Yalnızca erkekler", "Yalnızca özel", "Yalnızca yatılı"], "Kız ve erkek tüm vatandaşlar."),
              ("Kanun önünde eşitlik maddesi hangisidir?", "m.10", ["m.42", "m.24", "m.90", "m.128"], "Ayrımcılık yasağı."),
              ("Usulüne göre yürürlükteki temel hak antlaşmalarının kanunlarla çatışmasında esas hangisidir?", "m.90 son fıkra", ["m.1", "m.3", "m.4", "m.128"], "Uluslararası antlaşma önceliği."),
              ("Din kültürü ve ahlak öğretimi anayasada nasıl geçer?", "m.24'te zorunlu dersler arasında düzenlenir", ["Yasaktır", "Yalnızca imam hatipte", "Yalnızca üniversitede", "Yoktur"], "Anayasa hükmü."),
              ("Sosyal hukuk devleti niteliği hangi maddededir?", "m.2", ["m.42", "m.90", "m.128", "m.70"], "Cumhuriyetin nitelikleri."),
              ("Kamu hizmetine girme hakkı hangisidir?", "m.70", ["m.42", "m.24", "m.13", "m.3"], "Eşitlikle girme."),
              ("Memurların statüsünün kanunla düzenlenmesi hangisine bağlanır?", "m.128", ["m.42", "m.24", "m.1", "m.3"], "Kamu görevlileri."),
              ("Temel hakların sınırlanmasında ölçülülük hangi maddenin özüdür?", "m.13", ["m.3", "m.1", "m.4 bayrak fıkrası", "m.75"], "Öze dokunma yasağı."),
              ("Özel okullar anayasaya göre nasıl açılır?", "Devlet gözetiminde kanunla", ["Hiçbir izne tabi olmadan", "Yalnızca dernek kararı", "Yalnızca noter", "Yalnızca belediye meclisi"], "m.42."),
          ]),
    topic(M, Q, "İnsan Hakları Hukuku",
          ["KAYNAKLAR", "AİHS VE AİHM", "EĞİTİM HAKKI"],
          ["Anayasa m.90 temel hak antlaşmalarını kanunların üstünde tutar. AİHS ek protokol 1 eğitim hakkını korur."],
          [
              ["**BM İnsan Hakları Evrensel Bildirisi (1948)** bağlayıcı sözleşme değil, temel metindir.",
               "**Medeni ve Siyasi Haklar Sözleşmesi** ile **Ekonomik Sosyal Kültürel Haklar Sözleşmesi** bağlayıcıdır.",
               "**Çocuk Hakları Sözleşmesi** eğitim, üstün yarar, katılım haklarını işler.",
               "**Engelli Hakları Sözleşmesi** kapsayıcı eğitimi uluslararası yükümlülük yapar.",
               "İç hukuka aktarım **onay + Resmî Gazete + m.90**."],
              ["**AİHS** Avrupa Konseyi; **AİHM** bireysel başvuru.",
               "Türkiye **2010** sonrası anayasa şikâyeti (m.148) iç yol tüketiminde önem kazandı.",
               "AİHM eğitimde **ayrımcılık yasağı, özel hayat, din hürriyeti** dosyaları üretir.",
               "Kararlar **ihlal-tazmin-yeniden yargılama** etkisi doğurabilir.",
               "Kamu görevlisi hak ihlalinde **rücu** idare hukukuna bağlanır."],
              ["Eğitim hakkı **erişim, kabul edilebilirlik, uyarlanabilirlik, kalite** (4A) ile okunur.",
               "Zorunlu din dersi AİHM içtihadında **muafiyet ve çoğulculuk** tartışmasıdır.",
               "Özel eğitimde **makul uyarlama** ayrımcılık yasağının gereğidir.",
               "İfade ve örgütlenme öğretmen için **görevle sınırlı** haklardır.",
               "Sınav: bildiri ≠ sözleşme; AİHS ≠ BM metni."],
          ],
          [
              ("1948 Evrensel Bildiri hukuken nedir?", "Bağlayıcı olmayan temel bildiri", ["Anayasa maddesi", "TCK", "1739", "AİHS'nin kendisi"], "Soft law kaynak."),
              ("AİHS hangi örgüte bağlıdır?", "Avrupa Konseyi", ["NATO", "AB zorunlu özdeş", "BM Genel Kurulu tek", "OECD"], "Strazburg."),
              ("Anayasa m.90'ın insan hakları antlaşmalarındaki etkisi nedir?", "Kanunlarla çatışmada antlaşmanın esas alınması", ["Antlaşmayı yok saymak", "Yalnızca tavsiye", "Belediye tüzüğü üstünlüğü", "Örf üstünlüğü"], "2004 değişikliği hattı."),
              ("Çocuk Hakları Sözleşmesi'nin eğitimdeki ana ilkesi nedir?", "Çocuğun üstün yararı", ["Devletin gizlilik yararı", "Okulun ticari yararı", "Sınav yararı", "Parti yararı"], "Best interests."),
              ("Kapsayıcı eğitimin uluslararası dayanağı hangisidir?", "Engelli Hakları Sözleşmesi", ["Tımar nizamnamesi", "Lonca", "Kapitülasyon", "Sened-i İttifak"], "CRPD."),
              ("AİHM'e gitmeden önce genellikle ne gerekir?", "İç hukuk yollarının tüketilmesi", ["BM Genel Kurulu kararı", "NATO izni", "Belediye meclisi", "Noter onayı"], "Subsidiarity."),
              ("Eğitim hakkının 4A çerçevesinde uyarlanabilirlik ne demektir?", "Programın çocuğa göre esnemesi", ["Okulu kapatmak", "Hakkı kaldırmak", "Harci artırmak", "Cezayı artırmak"], "Adaptability."),
              ("Makul uyarlama nedir?", "Engelin etkisini gidermek için gerekli ve orantılı düzenleme", ["Ayrımcılık", "Dışlama", "Not kırma", "Kayıt silme"], "CRPD."),
              ("Bildiri ile sözleşme farkı nedir?", "Sözleşme taraf devlet için bağlayıcı yükümlülük doğurur", ["Bildiri daha bağlayıcıdır", "Fark yoktur", "Bildiri TCK'dır", "Sözleşme atasözüdür"], "Hard law."),
              ("Öğretmenin ifade hürriyeti nasıl sınırlanır?", "Kamu görevi, laiklik ve öğrencilerin hakları ölçüsünde", ["Hiç sınır yok", "Tam yasak her söz", "Yalnızca teneffüste serbest", "Yalnızca Twitter'da serbest"], "m.26+görev."),
              ("Anayasa şikâyeti hangi mahkemeyedir?", "Anayasa Mahkemesi", ["AİHM doğrudan ilk yol", "Yargıtay ceza dairesi tek", "Danıştay idari tek", "UYuşmazlık"], "2010 sonrası iç yol."),
              ("Ayrımcılık yasağı eğitimde neyi keser?", "Irk, dil, din, engel, cinsiyet vb. temelli eşitsiz muameleyi", ["Not farkını tamamen", "Şube farkını", "Branş farkını", "Kademe farkını"], "m.10 + AİHS 14."),
          ]),
    topic(M, Q, "1739 Sayılı Kanun",
          ["AMAÇ", "İLKELER", "KADEME VE ÖĞRETMEN"],
          ["1739 = Millî Eğitim Temel Kanunu (1973). 222 ilköğretim özel kanunu, 7528 meslek kanunu; üçü karıştırılmasın."],
          [
              ["Kanunun amacı milli eğitimin **amaç ve ilkelerini, genel yapısını, öğretmenlik mesleğini** çerçevelemektir.",
               "Genel amaçlar **Atatürk inkılapları, milli-insani değer, beden-zihin-duygu, meslek ve yurttaşlık**.",
               "Özel amaçlar kademelere göre ayrı maddelerde açılır.",
               "Kanun **programın anayasası** gibidir; ders içeriğini tek tek yazmaz.",
               "Değişiklikler 4+4+4 ve sonraki reformlarla kademe maddelerini güncelledi."],
              ["İlkeler: genellik-eşitlik, fert ve toplum ihtiyaçları, yöneltme, eğitim hakkı, fırsat-imkân eşitliği, süreklilik, Atatürkçülük, demokrasi, laiklik, bilim, planlılık, karma, okul-aile işbirliği, her yerde eğitim, Türkçe.",
               "**Yöneltme** ilgi ve kabiliyete göre; sınav tek başına yöneltme değildir.",
               "**Ferdin ve toplumun ihtiyaçları** program gerekçesidir.",
               "**Her yerde eğitim** yaygın ve informal öğrenmeyi tanır.",
               "Karma eğitim ilkedir."],
              ["Öğretmenlik 1739'da **uzmanlık mesleği** olarak tanımlanır (7528 bunu ayrıntılandırır).",
               "Eğitim-öğretim **Devlet'in gözetim ve denetiminde**dir.",
               "Yükseköğretim milli eğitimin parçasıdır.",
               "Rehberlik 1739'da sistemin unsuru sayılır.",
               "Sınav: ilke adı + kısa tanım; 1739'u 222 ile karıştırma."],
          ],
          [
              ("1739 sayılı kanun hangi kanundur?", "Millî Eğitim Temel Kanunu", ["İlköğretim ve Eğitim Kanunu", "Öğretmenlik Mesleği Kanunu", "2709 Anayasa", "2547"], "1973."),
              ("1739 öğretmenliği nasıl tanımlar?", "Uzmanlık mesleği", ["Geçici iş", "Tımar görevi", "Lonca ustalığı", "Askerlik"], "7528 ayrıntılandırır."),
              ("Yöneltme ilkesi neye dayanır?", "İlgi, istidat ve kabiliyet", ["Yalnızca puan", "Yalnızca adres", "Yalnızca gelir", "Yalnızca kura"], "Gelişimsel rehberlik."),
              ("Fırsat ve imkân eşitliği ilkesi ne ister?", "Maddi imkânsızlıkların eğitim önünde engel olmaması için tedbir", ["Herkese aynı not", "Okulsuzluk", "Karma yasağı", "Türkçe yasağı"], "Burs, taşıma, pansiyon."),
              ("Her yerde eğitim ilkesi neyi kapsar?", "Okul dışı ve yaygın öğrenmeyi", ["Yalnızca dershane yasağı", "Yalnızca yatılı", "Yalnızca üniversite", "Yalnızca medrese"], "Hayat boyu."),
              ("Atatürkçülük 1739'da nedir?", "Temel ilkelerden biri", ["Seçmeli kulüp", "Yasak", "Yalnızca üniversite tezi", "Yalnızca inkılap dersi kitabı"], "Kanun ilkesi."),
              ("Laiklik ilkesi eğitimde neyi gerektirir?", "Eğitimin dinî vesayetten bağımsız çağdaş bilim esaslı oluşu", ["Din kültürü dersinin yokluğu zorunlu her yorum", "Tevhid'in iptali", "Medrese tek sistem", "Halifelik"], "1739 + anayasa."),
              ("Okul ve ailenin işbirliği neden ilkedir?", "Eğitimin sürekliliği ve tutarlılığı için", ["Aileyi okuldan kovmak için", "Öğretmeni işten çıkarmak için", "Notu gizlemek için", "Kayıt silmek için"], "Paydaş."),
              ("1739 programın ayrıntısını yazar mı?", "Hayır, amaç-ilke-yapı çerçevesi çizer", ["Her kazanımı tek tek yazar 2024 TYMM yerine", "Ders kitabını basar", "YÖK'ü yönetir günlük", "AİHM kararıdır"], "Çerçeve kanun."),
              ("Eğitim Devletin gözetiminde olması ne anlama gelir?", "Özel kurumlar dahil kamu denetimi", ["Özel okul yasağı", "Yalnızca köy enstitüsü", "Yalnızca Enderun", "Denetimsizlik"], "m.42 ile uyum."),
              ("Karma eğitim 1739 ilkesi midir?", "Evet", ["Hayır yasaktır", "Yalnızca 7528'de", "Yalnızca 222'de yok hükmü", "Anayasada yoktur bu yüzden ilke değildir"], "Temel ilke."),
              ("222 ile 1739 farkı nedir?", "222 ilköğretime özgü; 1739 tüm sistemin temel kanunudur", ["İkisi aynı numaradır", "222 anayasadır", "1739 AİHS'tir", "Fark yoktur"], "Kapsam."),
          ]),
    topic(M, Q, "222 Sayılı Kanun",
          ["ZORUNLULUK", "ÇAĞ NÜFUSU", "YÜKÜMLÜLÜK"],
          ["222 sayılı İlköğretim ve Eğitim Kanunu zorunluluk, çağ nüfusu, velinin yükümlülüğü ve ilköğretim kurumlarını düzenler."],
          [
              ["İlköğretim **kız ve erkek bütün Türkler için zorunludur** ve devlet okullarında **parasızdır** (anayasa ile uyum).",
               "Kanun **ilköğretim kurumlarını** ve yönetimini çerçeveler.",
               "**Çağ nüfusu** yaş aralığına giren çocuklardır; tespit ve okula kazandırma yükümlülüğü vardır.",
               "Veli ve kaymakamlık-müdürlük **devamsızlık ve kayıt** zincirinde sorumludur.",
               "Zorunluluğa aykırı tutum **idari yaptırım** konusu olabilir."],
              ["Taşımalı eğitim, yatılı bölge, birleştirilmiş sınıf kırsal erişim araçlarıdır.",
               "İlköğretim kurumları **ilkokul ve ortaokul** kademelerini 4+4 sonrası kapsayacak şekilde yorumlanır.",
               "Özel ilköğretim kurumları da zorunluluk rejimine bağlıdır.",
               "Sağlık ve özel eğitim raporları **erteleme veya özel kurum** yolları açabilir.",
               "Nüfus hizmetleri ile e-okul **çağ nüfusu tespitinde** birlikte işler."],
              ["222, 1739'un ilkelerini ilköğretimde **işletme kanunudur**.",
               "Öğretmen ataması 222'nin özü değil; ama kadro ihtiyacı çağ nüfusundan doğar.",
               "Devamsızlık izleme **rehberlik ve sosyal hizmet** ile bağlanır.",
               "Zorunlu eğitimin 12 yıla uzaması 222'nin lafzı ile sonraki kanunların birlikte okunmasını ister.",
               "Sınav: çağ nüfusu, zorunluluk, parasızlık, veli yükümlülüğü."],
          ],
          [
              ("222 sayılı kanun hangisidir?", "İlköğretim ve Eğitim Kanunu", ["Millî Eğitim Temel Kanunu", "Öğretmenlik Mesleği Kanunu", "Anayasa", "YÖK Kanunu"], "İlköğretime özgü."),
              ("İlköğretim devlet okullarında anayasa ve 222'ye göre nasıldır?", "Zorunlu ve parasız", ["İsteğe bağlı ücretli", "Yalnızca erkek", "Yalnızca kent", "Yalnızca özel"], "Erişim hakkı."),
              ("Çağ nüfusu nedir?", "İlköğretim yaşındaki çocuk kitlesi", ["Öğretmen kadrosu", "Veli derneği", "Mezunlar", "Emekliler"], "Tespit ve kayıt."),
              ("Velinin temel yükümlülüğü nedir?", "Çocuğu okula kaydettirip devamını sağlamak", ["Notu öğretmenin yerine vermek", "Müfredat yazmak", "Kadro atamak", "Denetim raporu yazmak"], "Zorunluluk."),
              ("Taşımalı eğitimin gerekçesi nedir?", "Dağınık yerleşmede okula erişim", ["Turizm", "Spor lisesi zorunluluğu", "YÖK kontenjanı", "AİHM tazminatı"], "Kırsal."),
              ("Birleştirilmiş sınıf neden vardır?", "Az öğrenciyle birden fazla şubeyi tek öğretmende okutmak", ["TYMM yasağı", "1739 iptali", "Anayasa m.4", "NATO"], "Kırsal model."),
              ("Özel ilköğretim zorunluluğu kaldırır mı?", "Hayır, zorunluluk kurum türünden bağımsızdır", ["Evet tamamen kaldırır", "Yalnızca kızlarda", "Yalnızca erkeklerde", "Yalnızca yazın"], "Hak ve ödev."),
              ("Devamsızlıkta kamu idaresi ne yapar?", "İzleme, uyarı ve yaptırım süreçlerini işletir", ["Hiçbir şey", "Okulu kapatır hemen", "Anayasayı değiştirir", "AİHS'ten çıkar"], "Kayıt-devam."),
              ("222 ile 1739 birlikte nasıl okunur?", "1739 çerçeve, 222 ilköğretim işletmesi", ["222 çerçeve 1739 ayrıntı", "İkisi AİHS", "İkisi 7528", "İkisi 2709"], "Lex specialis ilköğretim."),
              ("Yatılı bölge okulu neye hizmet eder?", "Uzak-dağınık yerleşimde barınarak eğitime", ["Üniversite yurduna", "Askerî kışlaya", "Hastaneye", "Cezaevine"], "YBO."),
              ("Sağlık raporu ilköğretimde neyi etkileyebilir?", "Devam, erteleme veya özel eğitim yönlendirmesini", ["Vatandaşlığı", "Anayasa maddesini", "Bayrağı", "Başkenti"], "Bireysel durum."),
              ("e-Okul çağ nüfusunda ne işe yarar?", "Kayıt ve devam verisini izlemek", ["Maaş ödemek", "Vergi toplamak", "Tapu vermek", "Pasaport basmak"], "Bilişim."),
          ]),
    topic(M, Q, "7528 Sayılı Kanun",
          ["STATÜ", "KARİYER", "ADAYLIK"],
          ["7528 Öğretmenlik Mesleği Kanunu 2024'te kabul edilen meslek kanunudur. Öğretmen-uzman öğretmen-başöğretmen basamaklarını çerçeveler; uydurma madde numarası yazmayın."],
          [
              ["Kanun öğretmenliği **meslek** olarak özel statüye bağlar; 1739'daki uzmanlık tanımını işletir.",
               "**Aday öğretmenlik** yetiştirme, değerlendirme ve kadroya geçiş süreci içerir.",
               "Kariyer: **öğretmen, uzman öğretmen, başöğretmen**.",
               "Uzmanlık ve başöğretmenlikte **hizmet süresi, eğitim ve yazılı sınav/dosya** bileşenleri kamuoyuna duyurulduğu çerçevededir.",
               "Meslek kanunu **özlük, etik ve kariyer** dilini bir araya getirir."],
              ["Adaylıkta **mentor/danışman öğretmen** ve performans değerlendirmesi öne çıkar.",
               "Başarısız adaylıkta **ilişik kesme** usulü 1739/657 ile birlikte okunur.",
               "Kanun **öğretmenlik mesleğine kaynaklık eden yükseköğretim** programlarını esas alır.",
               "Sertifika ve pedagojik formasyon tartışmaları meslek kanunu zemininde yürür.",
               "Sendikal haklar 657 ve sendika mevzuatıyla birlikte uygulanır."],
              ["AGS 2026 mevzuat başlığında **7528 resmi konu**dur.",
               "1739 amaç-ilke, 222 ilköğretim zorunluluğu, 7528 meslek; üçlü ayırt edilmelidir.",
               "Kariyer basamağı **maaş ve unvan** etkisi doğurur; pedagojik sihirli değnek değildir.",
               "Etik yükümlülük **öğrenci yararı, adil değerlendirme, gizlilik**.",
               "Sınav: basamak adları + adaylık + 1739 ile ilişki."],
          ],
          [
              ("7528 sayılı kanun hangisidir?", "Öğretmenlik Mesleği Kanunu", ["Millî Eğitim Temel Kanunu", "İlköğretim ve Eğitim Kanunu", "1982 Anayasası", "YÖK Kanunu"], "2024 meslek kanunu."),
              ("7528'deki kariyer basamakları hangileridir?", "Öğretmen, uzman öğretmen, başöğretmen", ["Çırak, kalfa, usta", "Teğmen, yüzbaşı, albay", "Stajyer, kâtip, müdür zorunlu üçlü", "Asistan, doçent, profesör"], "Meslek kariyeri."),
              ("Aday öğretmenliğin işlevi nedir?", "Mesleğe hazırlık, değerlendirme ve asıl öğretmenliğe geçiş", ["Emeklilik", "Müdürlük zorunluluğu", "YÖK üyeliği", "AİHM hâkimliği"], "Yetiştirme."),
              ("7528, 1739'daki hangi tanımı işletir?", "Öğretmenliğin uzmanlık mesleği oluşunu", ["Zorunlu ilköğretimi tek madde", "Çağ nüfusunu", "m.42'yi ilga", "AİHS'i"], "Meslek statüsü."),
              ("Uzman öğretmenlik için tipik bileşen hangisidir?", "Belirli hizmet süresi ve sınav/eğitim şartı", ["Belediye meclisi kararı", "Noter senedi", "NATO belgesi", "Tapu"], "Kariyer."),
              ("AGS 2026 mevzuat konularından yeni öne çıkan hangisidir?", "7528 sayılı Öğretmenlik Mesleği Kanunu", ["Kanun-ı Esasi 1876 tek", "Sened-i İttifak tek", "Tanzimat Fermanı tek", "Islahat Fermanı tek"], "Resmi dağılım."),
              ("Adaylıkta danışman öğretmen ne yapar?", "Mesleki rehberlik ve yetiştirme desteği", ["Maaşı keser", "Kadro iptal eder tek başına yargı gibi", "Anayasa değiştirir", "Okulu satar"], "Mentorluk."),
              ("Meslek kanunu 222'nin yerine geçer mi?", "Hayır, 222 ilköğretim zorunluluğunu; 7528 mesleği düzenler", ["Evet 222 yürürlükten kalkar bu yüzden", "Evet 1739 kalkar", "Evet anayasa kalkar", "Evet AİHS kalkar"], "Farklı konu."),
              ("Kariyer basamağının özlük etkisi nedir?", "Unvan ve malî haklarda iyileşme çerçevesi", ["Branşı değiştirmek zorunlu", "İli değiştirmek zorunlu", "Dersi kaldırmak", "Öğrenciyi seçmek"], "Statü."),
              ("Pedagojik formasyon tartışması neden 7528 zeminindedir?", "Mesleğe kaynaklık eden yetişme yollarını kanun konuşur", ["Coğrafya iklimi", "Fay hattı", "Maki", "Bor madeni"], "Kaynaklık."),
              ("Etik yükümlülüğe örnek hangisidir?", "Adil ölçme ve öğrenci mahremiyeti", ["Notu satmak", "Sınavı sızdırmak", "Ayrımcılık", "Gizli kayıt ifşası"], "Meslek etiği."),
              ("7528'i 2709 ile karıştırmamak neden önemlidir?", "2709 anayasa, 7528 meslek kanunudur", ["İkisi aynı sayıdır", "İkisi AİHS'tir", "İkisi 1739'dur", "İkisi 222'dir"], "Normlar hiyerarşisi."),
          ]),
]
