// sorular/cografya-22.js
window.cografya_22_sorulari = (function () {
    var L = ["A", "B", "C", "D", "E"];
    function q(stem, opts, i, exp) {
        return {
            question: stem,
            options: opts.map(function (t, n) { return L[n] + ") " + t; }),
            correctAnswerIndex: i,
            explanation: exp
        };
    }
    return [
        q("Soru 1: Aşağıdakilerden hangisi Türkiye'de taş kömürünün özelliklerinden biri değildir?",
            ["I. Jeolojik zamanda oluşmuş olması", "Karbonifer Dönemi'nde oluşmuş olması", "Rezervlerinin büyük bölümünün Batı Karadeniz'de bulunması", "Başlıca kullanım alanlarından birinin elektrik üretimi olması", "Türkiye'deki rezervlerinin oldukça fazla olması"],
            4, "Taş kömürü I. jeolojik zaman (Karbonifer) ürünüdür, rezervin neredeyse tamamı Batı Karadeniz'dedir ve elektrik üretiminde kullanılır; ancak rezervi azdır, fazla değildir."),
        q("Soru 2: Türkiye'de taş kömürü çıkarılan alanlarla ilgili aşağıdaki eşleştirmelerden hangisi doğrudur?",
            ["Zonguldak — Kozlu ve Karadon", "Bartın — Soma", "Zonguldak — Afşin-Elbistan", "Bartın — Seyitömer", "Karabük — Amasra"],
            0, "Zonguldak'ta Kozlu ve Karadon; Bartın'da Amasra taş kömürü çıkarılır. Soma, Afşin-Elbistan ve Seyitömer linyit alanlarıdır."),
        q("Soru 3: Türkiye'de yaygın olarak bulunan ve kalitesi düşük olması nedeniyle alt kalorili olarak nitelendirilen kömür türü aşağıdakilerden hangisidir?",
            ["Taş kömürü", "Linyit", "Antrasit", "Asfaltit", "Kok kömürü"],
            1, "Linyit alt kalorili, kalitesiz ve Türkiye'de yaygındır."),
        q("Soru 4: Aşağıdaki enerji kaynaklarından hangisinin oluşum zamanı diğerlerinden farklıdır?",
            ["Linyit", "Petrol", "Doğal gaz", "Taş kömürü", "Asfaltit"],
            3, "Taş kömürü I. jeolojik zaman / Karbonifer'de oluşmuştur. Linyit III. zamanda oluşur; petrol, doğal gaz ve asfaltit de daha genç jeolojik süreçlerle ilişkilendirilir."),
        q("Soru 5: Türkiye'nin en büyük linyit santrali aşağıdakilerden hangisidir?",
            ["Soma Termik Santrali", "Seyitömer Termik Santrali", "Afşin-Elbistan Termik Santrali", "Tunçbilek Termik Santrali", "Yatağan Termik Santrali"],
            2, "En büyük linyit santrali Kahramanmaraş'taki Afşin-Elbistan Termik Santrali'dir."),
        q("Soru 6: Türkiye'nin enerji ihtiyacı ile ilgili aşağıdaki bilgilerden hangisi doğrudur?",
            ["Petrol ihtiyacının yaklaşık %10'u ithalatla karşılanmaktadır.", "Doğal gaz ihtiyacının tamamı Türkiye'deki üretimden karşılanmaktadır.", "Petrol ihtiyacının yaklaşık %90'ı ithal edilmektedir.", "Doğal gaz ihtiyacının yaklaşık %50'si ithal edilmektedir.", "Türkiye petrol ihtiyacında dışa bağımlı değildir."],
            2, "Petrolün yaklaşık %90'ı, doğal gazın yaklaşık %99,98'i ithal edilir."),
        q("Soru 7: Türkiye'de petrolün ilk bulunduğu yer aşağıdakilerden hangisidir?",
            ["Adana", "Batman", "İzmit", "İzmir", "Şırnak"],
            1, "İlk petrol Batman'da bulunmuştur. İzmit ve İzmir rafineri merkezleridir."),
        q("Soru 8: Aşağıdakilerden hangisi Türkiye'deki başlıca petrol rafinerilerinden biri değildir?",
            ["İzmit", "İzmir-Aliağa", "Batman", "Afşin-Elbistan", "Batman Rafinerisi"],
            3, "İzmit, İzmir-Aliağa ve Batman petrol rafinerileridir. Afşin-Elbistan linyit termik santralidir."),
        q("Soru 9: Aşağıdaki petrol boru hatlarından hangisi Azerbaycan petrolünün Türkiye üzerinden Akdeniz'e taşınmasında kullanılan hattır?",
            ["Kerkük-Yumurtalık", "Bakü-Tiflis-Ceyhan", "Mavi Akım", "TANAP", "Bakü-Tiflis-Erzurum"],
            1, "BTC Azerbaycan petrolünü Ceyhan'a (Akdeniz) taşır. BTE ve TANAP doğal gaz; Kerkük-Yumurtalık Irak petrolüdür."),
        q("Soru 10: Kerkük-Yumurtalık Boru Hattı aşağıdaki ülkelerden hangisiyle ilişkilidir?",
            ["İran", "Rusya", "Azerbaycan", "Irak", "Türkmenistan"],
            3, "Kerkük-Yumurtalık hattı Irak petrolünü taşır."),
        q("Soru 11: Türkiye'nin doğal gaz ihtiyacının yaklaşık %99,98'ini ithal etmesi aşağıdakilerden hangisini göstermektedir?",
            ["Doğal gazda dışa bağımlılığın çok yüksek olduğunu", "Türkiye'nin doğal gaz üretiminde dünya lideri olduğunu", "Doğal gazın yalnızca konutlarda kullanıldığını", "Doğal gazın yenilenebilir bir kaynak olduğunu", "Türkiye'de doğal gaz rezervinin bulunmadığını"],
            0, "Neredeyse tamamının ithal edilmesi dışa bağımlılığın çok yüksek olduğunu gösterir. Tuna-1 gibi sahalar vardır; sıfır rezerv anlamına gelmez."),
        q("Soru 12: Türkiye'de doğal gaz bulunan ilk saha aşağıdakilerden hangisidir?",
            ["Tuna-1", "Germencik", "Karapınar", "Silopi", "Ovaakça"],
            0, "İlk saha Tuna-1'dir. Germencik jeotermal, Karapınar GES, Silopi asfaltit, Ovaakça gaz santralidir."),
        q("Soru 13: Aşağıdakilerden hangisi doğal gazın Türkiye'deki kullanım alanlarından biri olup bu amaçla kurulan ilk santrallerden biridir?",
            ["Bursa-Ovaakça Doğal Gaz Kombine Çevrim Santrali", "Mersin-Akkuyu Nükleer Santrali", "Konya-Karapınar GES", "İzmir-Çeşme Rüzgâr Santrali", "Aydın-Germencik Jeotermal Santrali"],
            0, "Elektrik üretimi amacıyla kurulan ilk doğal gaz kombine çevrim santrallerinden biri Bursa-Ovaakça'dır."),
        q("Soru 14: Aşağıdaki doğal gaz boru hattı ve kaynak ülke eşleştirmelerinden hangisi yanlıştır?",
            ["Batı Hattı — Rusya", "Doğu Hattı — İran", "Mavi Akım — Rusya", "Bakü-Tiflis-Erzurum — Azerbaycan", "TANAP — İran"],
            4, "TANAP Azerbaycan gazını taşır; kaynak ülke İran değildir (Doğu Hattı İran'dır)."),
        q("Soru 15: Rusya'dan gelen doğal gazın Karadeniz'in altından geçirilerek Samsun'a ulaştırıldığı boru hattı aşağıdakilerden hangisidir?",
            ["TANAP", "Türk Akımı", "Mavi Akım", "Doğu Hattı", "Bakü-Tiflis-Erzurum"],
            2, "Mavi Akım Karadeniz altından Samsun'a çıkar. Türk Akımı Trakya üzerinden Avrupa'ya yöneliktir."),
        q("Soru 16: Türk Akımı ile ilgili aşağıdaki bilgilerden hangisi doğrudur?",
            ["Azerbaycan'dan Türkiye'ye doğal gaz taşır.", "İran'dan Türkiye'ye doğal gaz taşır.", "Rusya'dan gelen doğal gazın Türkiye üzerinden Avrupa'ya ulaştırılmasında kullanılır.", "Irak petrolünün Akdeniz'e taşınmasını sağlar.", "Azerbaycan petrolünün Ceyhan'a taşınmasını sağlar."],
            2, "Türk Akımı Rusya kaynaklıdır ve Avrupa'nın gaz ihtiyacı için Türkiye üzerinden geçer."),
        q("Soru 17: Aşağıdaki boru hatlarından hangisi Azerbaycan kaynaklı doğal gazın Türkiye üzerinden Avrupa'ya taşınmasıyla ilişkilidir?",
            ["TANAP", "Kerkük-Yumurtalık", "Mavi Akım", "Doğu Hattı", "Türk Akımı"],
            0, "TANAP Azerbaycan gazını Trans Anadolu hattıyla Avrupa'ya taşır. BTE de Azerbaycan gazıdır ancak Avrupa bağlantısı TANAP ile anılır."),
        q("Soru 18: Aşağıdakilerden hangisi asfaltitle ilgili doğru bir bilgidir?",
            ["Sıvı petrolün rafine edilmesiyle oluşur.", "Türkiye'de yalnızca Batı Karadeniz'de çıkarılır.", "Katı petrol olarak da bilinir.", "Yenilenebilir enerji kaynağıdır.", "En önemli kullanım alanı konut ısıtmasıdır."],
            2, "Asfaltit katı petrol olarak bilinir; Şırnak-Silopi'dedir ve başlıca elektrik üretiminde kullanılır."),
        q("Soru 19: Türkiye'de asfaltit aşağıdaki yerlerden hangisinde bulunmaktadır?",
            ["Zonguldak", "Şırnak-Silopi", "Konya-Karapınar", "Aydın-Germencik", "Erzurum"],
            1, "Asfaltit Şırnak (Silopi) civarındadır."),
        q("Soru 20: Türkiye'de hidroelektrik enerji potansiyelinin en fazla olduğu bölge aşağıdakilerden hangisidir?",
            ["Marmara", "Ege", "Akdeniz", "Doğu Anadolu", "Güneydoğu Anadolu"],
            3, "Potansiyel en fazla Doğu Anadolu'dadır; üretim ise Güneydoğu'da en fazladır."),
        q("Soru 21: Türkiye'de hidroelektrik enerji üretiminin en fazla olduğu bölge aşağıdakilerden hangisidir?",
            ["Doğu Anadolu", "Güneydoğu Anadolu", "Marmara", "İç Anadolu", "Ege"],
            1, "Üretim en fazla Güneydoğu Anadolu'dadır (Atatürk, Karakaya, Ilısu vb.)."),
        q("Soru 22: Türkiye'de hidroelektrik enerji potansiyeli ve üretiminin en az olduğu bölge aşağıdakilerden hangisidir?",
            ["Marmara", "Karadeniz", "Akdeniz", "Ege", "İç Anadolu"],
            0, "Hem potansiyel hem üretim Marmara'da en azdır."),
        q("Soru 23: Aşağıdaki hidroelektrik santrallerden hangileri Dicle Nehri üzerinde bulunmaktadır?",
            ["Atatürk — Karakaya — Keban", "Devegeçidi — Kralkızı — Ilısu", "Altınkaya — Kesikköprü — Deriner", "Yusufeli — Hasan Uğurlu — Suat Uğurlu", "Birecik — Keban — Ilısu"],
            1, "Dicle: Devegeçidi, Kralkızı, Ilısu. Fırat: Atatürk, Karakaya, Keban, Birecik."),
        q("Soru 24: Aşağıdaki HES-nehir eşleştirmelerinden hangisi yanlıştır?",
            ["Atatürk — Fırat", "Karakaya — Fırat", "Altınkaya — Kızılırmak", "Deriner — Çoruh", "Hasan Uğurlu — Kızılırmak"],
            4, "Hasan Uğurlu Yeşilırmak üzerindedir, Kızılırmak üzerinde değildir."),
        q("Soru 25: Aşağıdaki santrallerden hangisi Fırat Nehri üzerinde yer almaz?",
            ["Atatürk", "Karakaya", "Keban", "Birecik", "Ilısu"],
            4, "Ilısu Dicle üzerindedir."),
        q("Soru 26: Aşağıdaki HES'lerden hangisi Kızılırmak Nehri üzerinde bulunmaktadır?",
            ["Ilısu", "Altınkaya", "Yusufeli", "Keban", "Kralkızı"],
            1, "Kızılırmak: Altınkaya ve Kesikköprü."),
        q("Soru 27: Çoruh Nehri üzerinde bulunan hidroelektrik santraller aşağıdakilerden hangisidir?",
            ["Deriner — Yusufeli", "Keban — Karakaya", "Altınkaya — Kesikköprü", "Kralkızı — Ilısu", "Hasan Uğurlu — Suat Uğurlu"],
            0, "Çoruh: Deriner ve Yusufeli."),
        q("Soru 28: Yeşilırmak Nehri üzerinde bulunan hidroelektrik santraller aşağıdakilerden hangisidir?",
            ["Atatürk — Birecik", "Deriner — Yusufeli", "Hasan Uğurlu — Suat Uğurlu", "Altınkaya — Kesikköprü", "Kralkızı — Ilısu"],
            2, "Yeşilırmak: Hasan Uğurlu ve Suat Uğurlu."),
        q("Soru 29: Türkiye'nin ilk rüzgâr santrali aşağıdaki merkezlerden hangisinde kurulmuştur?",
            ["İzmir-Çeşme-Alaçatı", "Balıkesir-Bandırma", "Çanakkale", "İzmir-Aliağa", "Muğla-Bodrum"],
            0, "İlk rüzgâr santrali İzmir Çeşme-Alaçatı'dadır."),
        q("Soru 30: Türkiye'de rüzgâr enerjisi potansiyeli ve üretiminin bölgelere göre sıralaması aşağıdakilerden hangisinde doğru verilmiştir?",
            ["Marmara > Ege > Akdeniz", "Ege > Marmara > Akdeniz", "Akdeniz > Ege > Marmara", "Ege > Akdeniz > Marmara", "Marmara > Akdeniz > Ege"],
            1, "Ege > Marmara > Akdeniz."),
        q("Soru 31: Rüzgâr enerjisinden elektrik üretiminde üretim miktarını doğrudan etkileyen temel unsur aşağıdakilerden hangisidir?",
            ["Toprak türü", "Rüzgârın hızı ve sürekliliği", "Kayaçların yaşı", "Yer altı suyu seviyesi", "Tarım alanlarının genişliği"],
            1, "Üretim iklim koşullarına, özellikle rüzgâr hızı ve sürekliliğine bağlıdır."),
        q("Soru 32: Rüzgâr enerjisi temiz bir enerji kaynağı olmakla birlikte bazı çevresel sorunlara neden olabilmektedir. Buna göre aşağıdakilerden hangisi bu sorunlardan biridir?",
            ["Yer altı suyunun tamamen tükenmesi", "Kuşların göç yollarındaki risklerin artması", "Toprağın tuzlaşmasının hızlanması", "Volkanik faaliyetlerin artması", "Akarsu rejimlerinin tamamen değişmesi"],
            1, "Göç yolları üzerindeki türbinler kuşlara zarar verebilir."),
        q("Soru 33: Türkiye'nin ilk güneş tarlası aşağıdaki merkezlerden hangisinde kurulmuştur?",
            ["Konya-Karapınar", "Şanlıurfa-Birecik", "Mersin", "Antalya", "İzmir"],
            1, "İlk GES (güneş tarlası) Şanlıurfa-Birecik'tedir. Karapınar en büyük GES'tir."),
        q("Soru 34: Türkiye'nin en büyük güneş enerji santrali aşağıdakilerden hangisidir?",
            ["Şanlıurfa-Birecik GES", "Konya-Karapınar GES", "Mersin Kule Tipi GES", "İzmir-Aliağa GES", "Aydın-Germencik GES"],
            1, "En büyük GES Konya-Karapınar'dadır."),
        q("Soru 35: Türkiye'deki ilk kule tipi güneş enerji santrali aşağıdaki illerden hangisindedir?",
            ["Konya", "Şanlıurfa", "Mersin", "İzmir", "Antalya"],
            2, "İlk kule tipi GES Mersin'dedir."),
        q("Soru 36: Türkiye'de güneş enerjisi potansiyelinin en fazla ve en az olduğu bölgeler aşağıdakilerden hangisinde doğru verilmiştir?",
            ["Ege — Marmara", "Akdeniz — Doğu Karadeniz", "Güneydoğu Anadolu — Doğu Karadeniz", "İç Anadolu — Marmara", "Güneydoğu Anadolu — Marmara"],
            2, "En fazla Güneydoğu Anadolu, en az Doğu Karadeniz."),
        q("Soru 37: Türkiye'de jeotermal enerji potansiyelinin en fazla olduğu bölge aşağıdakilerden hangisidir?",
            ["Doğu Anadolu", "Güneydoğu Anadolu", "Ege", "Karadeniz", "Marmara"],
            2, "Jeotermal potansiyel Ege'de en fazladır."),
        q("Soru 38: Ege Bölgesi'nin jeotermal enerji potansiyelinin yüksek olmasında aşağıdakilerden hangisi temel etkendir?",
            ["Yağış miktarının fazla olması", "Kırıklı yer yapısı ve aktif fay hatlarının bulunması", "Ortalama yükseltinin düşük olması", "Geniş delta ovalarının bulunması", "Akarsu sayısının fazla olması"],
            1, "Horst-graben / kırıklı yapı ve aktif faylar jeotermal kaynakları artırır."),
        q("Soru 39: Jeotermal enerji üretiminin diğer bazı yenilenebilir enerji kaynaklarından farklı olarak iklim koşullarından büyük ölçüde etkilenmemesinin temel sonucu aşağıdakilerden hangisidir?",
            ["Sürekli ve güvenilir bir enerji kaynağı olması", "Yalnızca yaz mevsiminde kullanılabilmesi", "Üretimin rüzgâr hızına bağlı olması", "Güneşlenme süresine bağlı olması", "Akarsu rejimine bağlı olması"],
            0, "İklimden etkilenmemesi sürekli ve güvenilir üretim sağlar."),
        q("Soru 40: Aşağıdakilerden hangisi Türkiye'deki başlıca jeotermal enerji santrallerinden biridir?",
            ["Aydın-Germencik", "Zonguldak-Kozlu", "Şanlıurfa-Birecik", "Mersin-Akkuyu", "Samsun"],
            0, "Aydın-Germencik ve Denizli-Sarayköy jeotermal santrallerdir."),
        q("Soru 41: Denizli-Sarayköy aşağıdaki enerji kaynaklarından hangisiyle ilişkilidir?",
            ["Rüzgâr", "Güneş", "Jeotermal", "Hidroelektrik", "Nükleer"],
            2, "Denizli-Sarayköy jeotermal santraldir."),
        q("Soru 42: Biyokütle enerjisi aşağıdakilerden hangisinin enerjiye dönüştürülmesiyle elde edilebilir?",
            ["Yalnızca uranyum cevherinin", "Evsel, hayvansal ve bitkisel atıkların", "Yalnızca petrol ürünlerinin", "Yalnızca akarsu sularının", "Yalnızca rüzgâr hareketinin"],
            1, "Biyokütle evsel, hayvansal ve bitkisel atıklardan elde edilir."),
        q("Soru 43: Biyokütle enerjisiyle ilgili aşağıdaki ifadelerden hangisi doğrudur?",
            ["Yalnızca katı yakıt şeklinde kullanılabilir.", "Yalnızca tarımsal ürünlerden elde edilir.", "Atıkların katı, sıvı veya gaz hâline dönüştürülmesiyle enerji elde edilebilir.", "Yenilenemeyen enerji kaynakları arasında yer alır.", "Oluşumu yalnızca jeolojik süreçlere bağlıdır."],
            2, "Atıklar katı, sıvı veya gaz forma dönüştürülerek enerjiye çevrilebilir; yenilenebilir kaynaktır."),
        q("Soru 44: Nükleer enerji aşağıdaki elementlerden hangilerinin radyoaktif özelliklerinden yararlanılarak elde edilir?",
            ["Demir ve bakır", "Uranyum ve toryum", "Kalsiyum ve magnezyum", "Sodyum ve potasyum", "Silisyum ve alüminyum"],
            1, "Nükleer enerji uranyum ve toryum gibi radyoaktif elementlerden elde edilir."),
        q("Soru 45: Türkiye'nin ilk nükleer enerji santrali aşağıdakilerden hangisidir?",
            ["Sinop NGS", "Akkuyu NGS", "İğneada NGS", "Karapınar GES", "Germencik JES"],
            1, "İlk NGS Mersin Akkuyu'dur (inşaatı devam etmektedir)."),
        q("Soru 46: Türkiye'nin ilk nükleer enerji santrali olan Akkuyu NGS aşağıdaki illerden hangisindedir?",
            ["Sinop", "Kırklareli", "Mersin", "İzmir", "Antalya"],
            2, "Akkuyu Mersin'dedir."),
        q("Soru 47: Türkiye'deki nükleer enerji santralleriyle ilgili aşağıdaki eşleştirmelerden hangisi yanlıştır?",
            ["Akkuyu — Mersin", "Sinop — Planlanan nükleer santral", "İğneada — Kırklareli", "Akkuyu — Türkiye'nin ilk nükleer enerji santrali", "İğneada — İşletmede olan nükleer santral"],
            4, "İğneada planlama aşamasındadır; işletmede değildir. Akkuyu da henüz inşaat aşamasındadır."),
        q("Soru 48: Türkiye'de planlanan nükleer santraller aşağıdakilerden hangisinde doğru verilmiştir?",
            ["Sinop ve Kırklareli-İğneada", "İzmir ve Manisa", "Konya ve Şanlıurfa", "Batman ve Zonguldak", "Aydın ve Denizli"],
            0, "Akkuyu'nun ardından Sinop (çalışmalar) ve Kırklareli-İğneada (plan) gelir."),
        q("Soru 49: Türkiye'de elektrik üretiminin enerji kaynaklarına göre dağılımında ilk üç sırada aşağıdakilerden hangisi yer almaktadır?",
            ["Hidrolik — Kömür — Rüzgâr", "Kömür — Hidrolik — Doğal gaz", "Doğal gaz — Kömür — Güneş", "Kömür — Rüzgâr — Hidrolik", "Hidrolik — Doğal gaz — Kömür"],
            1, "1. kömür, 2. hidrolik, 3. doğal gaz."),
        q("Soru 50: Türkiye'de elektrik üretiminin kaynaklara göre sıralaması aşağıdakilerden hangisinde doğru verilmiştir?",
            ["Kömür → Hidrolik → Doğal gaz → Rüzgâr → Güneş → Jeotermal → Diğer", "Hidrolik → Kömür → Rüzgâr → Doğal gaz → Güneş → Diğer → Jeotermal", "Kömür → Doğal gaz → Hidrolik → Güneş → Rüzgâr → Jeotermal → Diğer", "Doğal gaz → Kömür → Hidrolik → Rüzgâr → Güneş → Diğer → Jeotermal", "Hidrolik → Doğal gaz → Kömür → Rüzgâr → Jeotermal → Güneş → Diğer"],
            0, "Kömür, hidrolik, doğal gaz, rüzgâr, güneş, jeotermal, diğer."),
        q("Soru 51: Türkiye'de elektrik üretiminin kaynaklara göre sıralamasında 6. sırada yer alan kaynak aşağıdakilerden hangisidir?",
            ["Rüzgâr", "Güneş", "Jeotermal", "Hidrolik", "Doğal gaz"],
            2, "Sıra: kömür, hidrolik, doğal gaz, rüzgâr, güneş, jeotermal, diğer. 6. sıra jeotermaldir."),
        q("Soru 52: Türkiye'nin elektrik üretiminde kömürün ilk sırada yer alması, hidrolik enerjinin ikinci sırada bulunması ve doğal gazın üçüncü sırada yer alması dikkate alındığında aşağıdakilerden hangisine ulaşılabilir?",
            ["Türkiye'de yenilenebilir kaynakların tamamı elektrik üretiminde ilk sıradadır.", "Elektrik üretiminde hem yenilenebilir hem de yenilenemeyen kaynaklardan yararlanılmaktadır.", "Türkiye'de fosil yakıtların elektrik üretimindeki payı yok denecek kadar azdır.", "Hidroelektrik enerji Türkiye'de hiç kullanılmamaktadır.", "Güneş enerjisi elektrik üretiminde ilk sıradadır."],
            1, "Kömür ve doğal gaz yenilenemez, hidrolik yenilenebilirdir; her iki grup birlikte kullanılır."),
        q("Soru 53: Aşağıdaki enerji kaynağı — Türkiye'deki önemli merkezi eşleştirmelerinden hangisi yanlıştır?",
            ["Taş kömürü — Zonguldak", "Linyit — Afşin-Elbistan", "Petrol — Batman", "Asfaltit — Silopi", "Jeotermal — Zonguldak"],
            4, "Zonguldak taş kömürüyle anılır. Jeotermal Ege'de (Germencik, Sarayköy) öne çıkar."),
        q("Soru 54: Aşağıdaki enerji kaynaklarından hangisinin potansiyelinin en yüksek olduğu bölge ile elektrik üretiminin en yüksek olduğu bölge aynı değildir?",
            ["Hidroelektrik", "Rüzgâr", "Güneş", "Jeotermal", "Nükleer"],
            0, "Hidroelektrikte potansiyel Doğu Anadolu'da, üretim Güneydoğu Anadolu'da en fazladır. Rüzgârda potansiyel ve üretim sıralaması aynıdır (Ege > Marmara > Akdeniz)."),
        q("Soru 55: Aşağıdaki enerji kaynaklarından hangisi ile ilgili verilen merkez, enerji kaynağının Türkiye'deki önemli kullanım alanlarından biriyle doğru eşleştirilmiştir?",
            ["Güneş — Zonguldak", "Jeotermal — Aydın-Germencik", "Taş kömürü — Konya-Karapınar", "Asfaltit — İzmir-Çeşme", "Nükleer — Batman"],
            1, "Aydın-Germencik jeotermal santraldir. Karapınar güneş, Çeşme rüzgâr, Batman petrol, Zonguldak taş kömürüdür."),
        q("Soru 56: Aşağıdaki enerji kaynaklarından hangisi diğerlerinden farklı olarak yenilenemeyen enerji kaynağıdır?",
            ["Rüzgâr", "Güneş", "Jeotermal", "Biyokütle", "Linyit"],
            4, "Linyit fosil yakıttır; diğerleri yenilenebilir kaynaktır."),
        q("Soru 57: Aşağıdaki enerji kaynaklarından hangisinin üretimi iklim koşullarından doğrudan etkilenirken jeotermal enerjinin üretimi bu koşullardan büyük ölçüde etkilenmez?",
            ["Rüzgâr", "Nükleer", "Petrol", "Linyit", "Asfaltit"],
            0, "Rüzgâr üretimi hız ve sürekliliğe bağlıdır; jeotermal iklimden etkilenmez."),
        q("Soru 58: Bir öğrenci Türkiye'nin enerji kaynaklarını çalışırken şu bilgileri not etmiştir:\nI. Türkiye'nin ilk rüzgâr santrali Çeşme-Alaçatı'dadır.\nII. Türkiye'nin en büyük GES'i Karapınar'dadır.\nIII. Türkiye'nin ilk nükleer enerji santrali Sinop'tadır.\nIV. Türkiye'nin ilk petrolü Batman'da bulunmuştur.\nBu bilgilerden hangileri doğrudur?",
            ["I ve II", "I ve III", "II ve III", "I, II ve IV", "II, III ve IV"],
            3, "I, II ve IV doğrudur. İlk NGS Sinop değil Mersin-Akkuyu'dur."),
        q("Soru 59: Aşağıdaki enerji kaynaklarından hangisi için verilen yer–özellik eşleştirmesi doğrudur?",
            ["Mersin — İlk kule tipi güneş enerji santrali", "Batman — İlk nükleer enerji santrali", "Zonguldak — Türkiye'nin en büyük GES'i", "Kırklareli — İlk rüzgâr santrali", "Konya — İlk petrol sahası"],
            0, "İlk kule tipi GES Mersin'dedir. Akkuyu da Mersin'dedir ancak ilk petrol Batman, en büyük GES Karapınar, ilk rüzgâr Alaçatı'dır."),
        q("Soru 60: Türkiye'nin enerji kaynaklarıyla ilgili aşağıdaki ifadelerden hangisi yanlıştır?",
            ["Taş kömürü rezervlerinin büyük bölümü Batı Karadeniz'dedir.", "Linyit Türkiye'de yaygın olarak bulunur.", "Türkiye petrol ihtiyacının yaklaşık %90'ını ithal etmektedir.", "Türkiye doğal gaz ihtiyacının yaklaşık %99,98'ini ithal etmektedir.", "Türkiye'de jeotermal potansiyelin en yüksek olduğu bölge Doğu Karadeniz'dir."],
            4, "Jeotermal potansiyel Ege'de en yüksektir. Doğu Karadeniz güneş potansiyelinin en az olduğu bölgedir.")
    ];
})();
