// sorular/cografya-25.js
window.cografya_25_sorulari = (function () {
    var L = ["A", "B", "C", "D", "E"];
    function q(stem, opts, i, exp) {
        return {
            question: stem,
            options: opts.map(function (t, n) { return L[n] + ") " + t; }),
            correctAnswerIndex: i,
            explanation: exp
        };
    }
    return [
        q("Türkiye'de yaz turizminin özellikle Ege ve Akdeniz kıyılarında gelişmesinde aşağıdakilerden hangisinin etkisi daha fazladır?",
            ["Kış sıcaklıklarının düşük olması", "Yaz sıcaklıklarının yüksek olması", "Yükseltinin kısa mesafede artması", "Kar yağışlı gün sayısının fazla olması", "Günlük sıcaklık farklarının fazla olması"],
            1, "Yaz sıcaklığının yüksek olması Ege ve Akdeniz kıyılarında deniz turizmini kolaylaştırmıştır."),
        q("Aşağıdaki merkezlerden hangisi Türkiye'nin yaz turizmi açısından öne çıkan merkezleri arasında yer almaz?",
            ["Didim", "Kuşadası", "Marmaris", "Palandöken", "Bodrum"],
            3, "Palandöken Erzurum'daki kayak merkezidir; yaz (deniz-kum-güneş) turizmi merkezi değildir."),
        q("Aşağıdaki eşleştirmelerden hangisi yaz turizmi açısından yanlıştır?",
            ["Antalya – Kemer", "Muğla – Marmaris", "Aydın – Didim", "Antalya – Alanya", "Bursa – Bodrum"],
            4, "Bodrum Muğla'dadır; Bursa yaz turizmi merkezi olarak Bodrum ile eşleştirilmez."),
        q("Aşağıdaki merkezlerden hangisi Muğla'nın yaz turizmi merkezlerinden biridir?",
            ["Didim", "Kemer", "Gökova", "Kuşadası", "Finike"],
            2, "Muğla'nın yaz turizmi merkezleri Bodrum, Marmaris ve Gökova'dır."),
        q("Kemer, Side, Alanya ve Finike aşağıdaki illerden hangisinin yaz turizmi merkezleridir?",
            ["Muğla", "Antalya", "Aydın", "İzmir", "Mersin"],
            1, "Kemer, Side, Alanya ve Finike Antalya'nın yaz turizmi merkezleridir."),
        q("Aşağıdaki merkez–il eşleştirmelerinden hangisi doğrudur?",
            ["Didim – Antalya", "Bodrum – Aydın", "Kuşadası – Aydın", "Marmaris – Antalya", "Kemer – Muğla"],
            2, "Kuşadası ve Didim Aydın'a; Bodrum ve Marmaris Muğla'ya; Kemer Antalya'ya aittir."),
        q("Aşağıdaki kayak merkezi–il eşleştirmelerinden hangisi yanlıştır?",
            ["Uludağ – Bursa", "Erciyes – Kayseri", "Palandöken – Erzurum", "Sarıkamış – Kars", "Kartalkaya – Kastamonu"],
            4, "Kartalkaya Bolu'dadır. Kastamonu'daki kayak merkezi Ilgaz'dır."),
        q("Türkiye'deki kayak merkezlerinden hangisi Erzurum'da bulunmaktadır?",
            ["Ilgaz", "Elmadağ", "Palandöken", "Davras", "Sarıkamış"],
            2, "Palandöken Erzurum'dadır."),
        q("Aşağıdaki kayak merkezi–il eşleştirmelerinden hangisi doğrudur?",
            ["Davras – Isparta", "Saklıkent – Bolu", "Ladik – Kastamonu", "Ilgaz – Ankara", "Elmadağ – Antalya"],
            0, "Davras Isparta'dadır. Saklıkent Antalya, Ladik Samsun, Ilgaz Kastamonu, Elmadağ Ankara'dadır."),
        q("Uludağ, Erciyes, Palandöken ve Sarıkamış aşağıdaki illerden hangileriyle doğru eşleştirilmiştir?",
            ["Bolu – Kayseri – Kars – Erzurum", "Bursa – Konya – Erzurum – Ardahan", "Bursa – Kayseri – Erzurum – Kars", "Bursa – Ankara – Erzurum – Kars", "Bursa – Kayseri – Sivas – Kars"],
            2, "Uludağ Bursa, Erciyes Kayseri, Palandöken Erzurum, Sarıkamış Kars'tadır."),
        q("Aşağıdakilerden hangisi Ankara'daki kayak merkezidir?",
            ["Kartalkaya", "Ilgaz", "Elmadağ", "Davras", "Ladik"],
            2, "Ankara'daki kayak merkezi Elmadağ'dır."),
        q("Aşağıdaki kayak merkezlerinden hangisi Karadeniz Bölgesi'nde yer alan illerden biriyle eşleştirilmiştir?",
            ["Erciyes – Kayseri", "Palandöken – Erzurum", "Kartalkaya – Bolu", "Davras – Isparta", "Sarıkamış – Kars"],
            2, "Kartalkaya Bolu'dadır ve Bolu Karadeniz Bölgesi'ndedir."),
        q("Saklıkent ve Davras kayak merkezleri aşağıdaki illerden hangileriyle eşleştirilmelidir?",
            ["Antalya – Isparta", "Antalya – Burdur", "Muğla – Isparta", "Antalya – Afyonkarahisar", "İzmir – Isparta"],
            0, "Saklıkent Antalya, Davras Isparta'dadır."),
        q("Aşağıdaki kayak merkezlerinden hangisi Samsun ilinde bulunmaktadır?",
            ["Ilgaz", "Ladik", "Elmadağ", "Kartalkaya", "Davras"],
            1, "Ladik Samsun'dadır."),
        q("Kastamonu'daki kayak merkezi aşağıdakilerden hangisidir?",
            ["Kartalkaya", "Uludağ", "Ilgaz", "Sarıkamış", "Erciyes"],
            2, "Kastamonu'daki kayak merkezi Ilgaz'dır."),
        q("Aşağıdaki eşleştirmelerden hangisi inanç turizmi açısından doğrudur?",
            ["Akdamar Kilisesi – Mardin", "Balıklıgöl – Konya", "Mevlana Müzesi – Van", "Meryem Ana Evi – İzmir", "Deyrülzafaran Manastırı – Trabzon"],
            3, "Meryem Ana Evi İzmir'dedir. Balıklıgöl Şanlıurfa, Mevlana Konya, Akdamar Van, Deyrülzafaran Mardin'dedir."),
        q("Hristiyanlık açısından kutsal kabul edilen Meryem Ana Evi aşağıdaki illerden hangisindedir?",
            ["Antalya", "İzmir", "Trabzon", "Van", "Mardin"],
            1, "Meryem Ana Evi İzmir'dedir."),
        q("Noel Baba olarak bilinen Aziz Nikolaos ile ilişkilendirilen kilise aşağıdaki merkezlerden hangisindedir?",
            ["Demre", "Kuşadası", "Söğüt", "Safranbolu", "Tuşpa"],
            0, "St. Nicholas Kilisesi Antalya'nın Demre ilçesindedir."),
        q("Hz. İbrahim'in ateşe atıldığı yer olduğuna inanılan Balıklıgöl aşağıdaki illerden hangisindedir?",
            ["Mardin", "Şanlıurfa", "Konya", "Adıyaman", "Gaziantep"],
            1, "Balıklıgöl Şanlıurfa'dadır."),
        q("Aşağıdaki inanç turizmi merkezi–il eşleştirmelerinden hangisi yanlıştır?",
            ["Sümela Manastırı – Trabzon", "Mevlana Müzesi – Konya", "Akdamar Kilisesi – Van", "Deyrülzafaran Manastırı – Mardin", "Balıklıgöl – Antalya"],
            4, "Balıklıgöl Şanlıurfa'dadır, Antalya'da değildir."),
        q("Mevlana Celaleddin-i Rumi'nin türbesinin bulunduğu Mevlana Müzesi aşağıdaki illerden hangisindedir?",
            ["Kayseri", "Aksaray", "Nevşehir", "Çorum", "Konya"],
            4, "Mevlana Müzesi Konya'dadır."),
        q("Akdamar Kilisesi aşağıdaki illerden hangisinde bulunmaktadır?",
            ["Trabzon", "Mardin", "Van", "İzmir", "Şanlıurfa"],
            2, "Akdamar Kilisesi Van'dadır."),
        q("Deyrülzafaran Manastırı aşağıdaki kültürel unsurlardan hangisiyle doğru biçimde ilişkilendirilmiştir?",
            ["İzmir – Hristiyanlık merkezi", "Van – Ermeni mimarisi", "Trabzon – Karadeniz manastırı", "Mardin – Süryani kadim manastırı", "Konya – Mevlevilik merkezi"],
            3, "Deyrülzafaran, Mardin'deki Süryani kadim manastırıdır."),
        q("Manyas Gölü ve Kızılırmak Deltası aşağıdaki turizm türlerinden hangisiyle daha çok ilişkilidir?",
            ["Golf turizmi", "Kuş gözlemciliği", "Kongre turizmi", "Yat turizmi", "Termal turizm"],
            1, "Manyas Gölü ve Kızılırmak Deltası kuş gözlemciliği alanlarıdır."),
        q("Antalya'nın Toroslar kesimi ile Doğu Karadeniz aşağıdaki alternatif turizm türlerinden hangisi için öne çıkar?",
            ["Kongre turizmi", "Kruvaziyer turizmi", "Botanik turizmi", "Golf turizmi", "Sağlık turizmi"],
            2, "Botanik turizmi Antalya (Toroslar) ve Doğu Karadeniz'de öne çıkar."),
        q("Aşağıdakilerden hangisi trekking turizminin Türkiye'deki önemli alanlarından biridir?",
            ["Ergene Havzası", "Güneydoğu Anadolu'nun ovaları", "Tuz Gölü çevresi", "Konya Ovası", "Karadeniz Bölgesi"],
            4, "Trekking (doğa yürüyüşü) özellikle Karadeniz Bölgesi'nde gelişmiştir."),
        q("Aşağıdaki akarsulardan hangisi Türkiye'de rafting turizmiyle ilişkilendirilen akarsulardan biri değildir?",
            ["Çoruh", "Manavgat", "Dalaman", "Fırtına", "Meriç"],
            4, "Rafting: Çoruh, Manavgat, Dalaman, Fırtına, Fırat, Kızılırmak. Meriç bu listede yoktur."),
        q("Çoruh, Manavgat, Dalaman, Fırtına, Fırat ve Kızılırmak aşağıdaki turizm türlerinden hangisiyle ilişkilidir?",
            ["Yat turizmi", "Rafting", "Golf", "Termal turizm", "Kongre turizmi"],
            1, "Bu akarsular rafting turizmiyle ilişkilendirilir."),
        q("Türkiye'de golf turizmi açısından öne çıkan merkezlerden biri aşağıdakilerden hangisidir?",
            ["Tuşpa", "Sarıkamış", "Demre", "Belek", "Söğüt"],
            3, "Golf turizminde Antalya-Belek öne çıkar; ayrıca Ankara, İstanbul ve İzmir de verilir."),
        q("Aşağıdakilerden hangisi Türkiye'de golf turizminin geliştiği merkezlerden biri değildir?",
            ["Antalya", "Ankara", "İstanbul", "İzmir", "Trabzon"],
            4, "Türkiye'de golf turizmi başta Antalya'nın Belek çevresi olmak üzere İstanbul, Ankara ve İzmir'deki tesislerde gelişmiştir. Trabzon'da ise yayla ve doğa turizmi öne çıkar; bu ilde golf turizmi gelişmemiştir."),
        q("\"Yüzen otel\" ifadesi aşağıdaki turizm türlerinden hangisini tanımlamak için kullanılmaktadır?",
            ["Yat turizmi", "Kruvaziyer turizmi", "Kongre turizmi", "Sağlık turizmi", "Termal turizm"],
            1, "Kruvaziyer turizmi yüzen otel olarak tanımlanır."),
        q("İstanbul ve Kuşadası aşağıdaki alternatif turizm türlerinden hangisinin önemli merkezleri arasında gösterilebilir?",
            ["Trekking", "Botanik turizmi", "Termal turizm", "Kruvaziyer turizmi", "Golf turizmi"],
            3, "Kruvaziyer turizminin önemli merkezleri İstanbul ve Kuşadası'dır."),
        q("Bodrum, Marmaris ve Göcek aşağıdaki turizm türlerinden hangisi açısından özellikle önemlidir?",
            ["Yat turizmi", "İnanç turizmi", "Termal turizm", "Kongre turizmi", "Kuş gözlemciliği"],
            0, "Yat turizmi güneybatı Ege kıyılarında (Bodrum, Marmaris, Göcek) yoğundur."),
        q("Aşağıdakilerden hangisi Türkiye'nin önemli termal turizm merkezlerinden biri değildir?",
            ["Yalova", "Bursa", "Afyon", "Kütahya", "Kars"],
            4, "Yalova (Termal), Bursa (Çekirge), Afyonkarahisar ve Kütahya (Yoncalı) sıcak su kaynaklarıyla Türkiye'nin başlıca termal turizm merkezleridir. Kars'ta ise kış ve kültür turizmi öne çıkar; önemli bir termal merkez değildir."),
        q("Yalova, Bursa, Afyon, İzmir ve Kütahya aşağıdaki turizm türlerinden hangisiyle ilişkilidir?",
            ["Termal turizm", "Yat turizmi", "Golf turizmi", "Kruvaziyer turizmi", "Kuş gözlemciliği"],
            0, "Bu iller termal turizm merkezleridir."),
        q("Türkiye'de sağlık (medikal) turizminde ilk sırada yer alan il aşağıdakilerden hangisidir?",
            ["İstanbul", "Kars", "Çorum", "Kastamonu", "Burdur"],
            0, "İstanbul; uluslararası akreditasyona sahip hastane ve klinik sayısının fazlalığı, yoğun hava yolu bağlantıları ve ağırladığı medikal turist sayısıyla Türkiye'de sağlık turizminde ilk sırada yer alır. Kars, Çorum, Kastamonu ve Burdur'da bu ölçekte bir sağlık turizmi altyapısı bulunmaz."),
        q("İstanbul ve Antalya'nın ortak olarak öne çıktığı alternatif turizm türü aşağıdakilerden hangisidir?",
            ["Kongre turizmi", "Rafting", "Kuş gözlemciliği", "Termal turizm", "Botanik turizmi"],
            0, "Kongre turizminin öne çıkan merkezleri İstanbul ve Antalya'dır."),
        q("Urartu turizm gelişim bölgesi aşağıdaki merkezlerden hangisiyle ilişkilendirilmiştir?",
            ["Çorum", "Van (Tuşpa)", "Çanakkale", "Bursa", "Aydın"],
            1, "Urartu turizm gelişim bölgesi Van (Tuşpa) ile ilişkilidir."),
        q("Aşağıdaki turizm gelişim bölgesi–il eşleştirmelerinden hangisi doğrudur?",
            ["Kapadokya – Çorum", "Hitit – Nevşehir", "Troya – Çanakkale", "Aphrodisias – Bursa", "Urartu – Aydın"],
            2, "Troya Çanakkale'dedir. Kapadokya Nevşehir, Hitit Çorum, Aphrodisias Aydın, Urartu Van'dadır."),
        q("Gaziantep, Adıyaman, Mardin ve Şanlıurfa aşağıdaki turizm gelişim bölgelerinden hangisiyle ilişkilendirilmiştir?",
            ["Frigya", "Urartu", "GAP", "Troya", "Kapadokya"],
            2, "GAP turizm gelişim bölgesi Gaziantep, Adıyaman, Mardin ve Şanlıurfa'yı kapsar."),
        q("Kapadokya turizm gelişim bölgesi aşağıdaki illerden hangisiyle eşleştirilmiştir?",
            ["Van", "Çorum", "Aydın", "Nevşehir", "Manisa"],
            3, "Kapadokya turizm gelişim bölgesi Nevşehir ile eşleştirilmiştir."),
        q("Hitit turizm gelişim bölgesi aşağıdaki illerden hangisiyle ilişkilendirilmiştir?",
            ["Kütahya", "Çorum", "Bursa", "Antalya", "Malatya"],
            1, "Hitit turizm gelişim bölgesi Çorum'dadır."),
        q("Aşağıdaki turizm gelişim bölgelerinden hangisi birden fazla ili kapsayan Batı Anadolu merkezli bir tarihî-kültürel alan olarak verilmiştir?",
            ["Frigya", "Urartu", "Kapadokya", "Hitit", "Troya"],
            0, "Frigya Kütahya, Uşak ve Afyon'u kapsar."),
        q("Kütahya, Uşak ve Afyon aşağıdaki turizm gelişim bölgelerinden hangisinin kapsamındadır?",
            ["GAP", "Frigya", "Urartu", "Kapadokya", "Aphrodisias"],
            1, "Frigya: Kütahya, Uşak, Afyon."),
        q("Aşağıdaki eşleştirmelerden hangisi yanlıştır?",
            ["Söğüt – Bilecik", "Aphrodisias – Aydın", "Troya – Çanakkale", "Göller Yöresi Ekoturizm – Isparta ve Burdur civarı", "Urartu – Aydın"],
            4, "Urartu uygarlığının merkezi Tuşpa Van'dadır; bu nedenle 'Urartu – Aydın' eşleştirmesi yanlıştır. Söğüt ilçesi Bilecik'te, Aphrodisias Aydın'da, Troya ise Çanakkale'dedir."),
        q("Kastamonu, Karabük, Bartın ve Sinop çevresini kapsayan ekoturizm gelişim bölgesi aşağıdakilerden hangisidir?",
            ["Göller Yöresi Ekoturizm Bölgesi", "Frigya Kültür ve Turizm Bölgesi", "GAP Kültür ve Turizm Bölgesi", "Kapadokya Kültür ve Turizm Bölgesi", "Batı Karadeniz Ekoturizm Bölgesi"],
            4, "Küre Dağları Millî Parkı, Yenice ormanları ve Safranbolu çevresini içine alan Kastamonu-Karabük-Bartın-Sinop hattı Batı Karadeniz Ekoturizm Gelişim Bölgesi içinde yer alır. Göller Yöresi Isparta-Burdur, Frigya Afyonkarahisar-Kütahya-Eskişehir, GAP Güneydoğu Anadolu, Kapadokya ise Nevşehir çevresini kapsar."),
        q("Isparta ve Burdur civarını kapsayan turizm gelişim bölgesi aşağıdakilerden hangisidir?",
            ["Batı Karadeniz Ekoturizm", "Göller Yöresi Ekoturizm", "Frigya", "GAP", "Urartu"],
            1, "Göller Yöresi Ekoturizm Isparta ve Burdur civarını kapsar."),
        q("Aşağıdaki UNESCO Dünya Kültür Mirası alanlarından hangisi Çorum ilinde bulunmaktadır?",
            ["Gordion", "Göbeklitepe", "Arslantepe", "Hattuşaş", "Troya"],
            3, "Hattuşaş (Hitit başkenti) Çorum'dadır."),
        q("Safranbolu Şehri aşağıdaki illerden hangisindedir?",
            ["Kastamonu", "Karabük", "Bolu", "Çorum", "Zonguldak"],
            1, "Safranbolu Karabük'tedir."),
        q("Aşağıdaki UNESCO miras alanlarından hangisi Adıyaman ilindedir?",
            ["Nemrut Dağı", "Göbeklitepe", "Arslantepe", "Gordion", "Çatalhöyük"],
            0, "Nemrut Dağı Adıyaman'dadır."),
        q("Xanthos-Letoon aşağıdaki illerden hangileriyle ilişkilendirilmiştir?",
            ["Çanakkale – Balıkesir", "İzmir – Aydın", "Antalya – Burdur", "Muğla – Aydın", "Antalya – Muğla"],
            4, "Xanthos-Letoon Antalya–Muğla ile ilişkilidir."),
        q("Divriği Ulu Camii ve Darüşşifası aşağıdaki illerden hangisinde bulunmaktadır?",
            ["Erzincan", "Sivas", "Malatya", "Kayseri", "Tokat"],
            1, "Divriği Ulu Camii ve Darüşşifası Sivas'tadır."),
        q("Truva (Troya) Antik Kenti aşağıdaki illerden hangisindedir?",
            ["İzmir", "Muğla", "Çanakkale", "Antalya", "Aydın"],
            2, "Troya Antik Kenti Çanakkale'dedir."),
        q("Çatalhöyük aşağıdaki illerden hangisinde bulunmaktadır?",
            ["Konya", "Nevşehir", "Ankara", "Çorum", "Aksaray"],
            0, "Çatalhöyük Konya'dadır."),
        q("Cumalıkızık aşağıdaki illerden hangisiyle ilişkilendirilmiştir?",
            ["Kütahya", "Bilecik", "Balıkesir", "Bursa", "Sakarya"],
            3, "Cumalıkızık Bursa'dadır."),
        q("Pamukkale (Hierapolis) aşağıdaki illerden hangisindedir?",
            ["Aydın", "İzmir", "Denizli", "Muğla", "Manisa"],
            2, "Pamukkale (Hierapolis) Denizli'dedir."),
        q("Göreme Milli Parkı ve Kapadokya aşağıdaki illerden hangisiyle ilişkilendirilmiştir?",
            ["Nevşehir", "Niğde", "Kayseri", "Aksaray", "Konya"],
            0, "Göreme Milli Parkı (Kapadokya) Nevşehir ile ilişkilendirilmiştir."),
        q("Bergama Çok Katmanlı Kültürel Peyzajı aşağıdaki illerden hangisindedir?",
            ["Manisa", "Çanakkale", "Aydın", "Muğla", "İzmir"],
            4, "Bergama İzmir'dedir."),
        q("Hevsel Bahçeleri ve tarihî surlarıyla UNESCO Dünya Mirası Listesi'nde yer alan il aşağıdakilerden hangisidir?",
            ["Mardin", "Şanlıurfa", "Diyarbakır", "Adıyaman", "Gaziantep"],
            2, "Diyarbakır Kalesi ve Hevsel Bahçeleri Kültürel Peyzajı 2015 yılında UNESCO Dünya Mirası Listesi'ne alınmıştır; bu alan Dicle Nehri kıyısında, Diyarbakır il merkezindedir."),
        q("Afrodisias Antik Kenti aşağıdaki illerden hangisindedir?",
            ["Manisa", "Denizli", "İzmir", "Aydın", "Muğla"],
            3, "Afrodisias Aydın'dadır."),
        q("Göbeklitepe aşağıdaki illerden hangisinde bulunmaktadır?",
            ["Adıyaman", "Şanlıurfa", "Mardin", "Gaziantep", "Diyarbakır"],
            1, "Göbeklitepe Şanlıurfa'dadır."),
        q("Arslantepe aşağıdaki illerden hangisiyle eşleştirilmiştir?",
            ["Elazığ", "Malatya", "Tunceli", "Adıyaman", "Erzincan"],
            1, "Arslantepe Malatya'dadır."),
        q("Gordion Antik Kenti aşağıdaki illerden hangisinin sınırları içerisindedir?",
            ["Ankara", "Eskişehir", "Kütahya", "Çorum", "Konya"],
            0, "Gordion Ankara (Polatlı) sınırlarındadır."),
        q("Sardes Antik Kenti aşağıdaki illerden hangisinde bulunmaktadır?",
            ["Aydın", "İzmir", "Manisa", "Denizli", "Muğla"],
            2, "Sardes Manisa'dadır."),
        q("Aşağıdaki UNESCO miras alanı–il eşleştirmelerinden hangisi yanlıştır?",
            ["Çatalhöyük – Konya", "Göbeklitepe – Şanlıurfa", "Arslantepe – Malatya", "Gordion – Ankara", "Sardes – Aydın"],
            4, "Sardes Manisa'dadır, Aydın'da değildir."),
        q("Aşağıdakilerden hangisi UNESCO Dünya Kültür Mirası Listesi'nde yer alan alanlardan biriyle doğru eşleştirilmiştir?",
            ["Arslantepe – Elazığ", "Nemrut Dağı – Şanlıurfa", "Göbeklitepe – Adıyaman", "Hattuşaş – Çorum", "Troya – İzmir"],
            3, "Hattuşaş Çorum'dadır. Nemrut Adıyaman, Göbeklitepe Şanlıurfa, Arslantepe Malatya, Troya Çanakkale'dedir."),
        q("Aşağıdakilerden hangisi Anadolu'nun Ortaçağ Dönemi Ahşap Hipostil Camileri arasında gösterilen yapılardan biridir?",
            ["Yeni Camii", "Selimiye Camii", "Süleymaniye Camii", "Hacı Bayram Camii", "Eşrefoğlu Camii"],
            4, "Eşrefoğlu Camii (Konya) ahşap hipostil camilerdendir."),
        q("Eşrefoğlu Camii aşağıdaki illerden hangisindedir?",
            ["Afyonkarahisar", "Eskişehir", "Kastamonu", "Konya", "Ankara"],
            3, "Eşrefoğlu Camii Konya'dadır."),
        q("Aşağıdaki cami–il eşleştirmelerinden hangisi doğrudur?",
            ["Afyonkarahisar Ulu Camii – Ankara", "Eşrefoğlu Camii – Kastamonu", "Mahmutbey Camii – Konya", "Ahi Şerafettin Camii – Ankara", "Ahi Şerafettin Camii – Afyonkarahisar"],
            3, "Ahi Şerafettin (Arslanhane) Camii Ankara'dadır. Afyonkarahisar Ulu Camii Afyonkarahisar'da, Eşrefoğlu Camii Konya'nın Beyşehir ilçesinde, Mahmutbey Camii ise Kastamonu'dadır."),
        q("Mahmutbey Camii aşağıdaki illerden hangisinde bulunmaktadır?",
            ["Bolu", "Eskişehir", "Çorum", "Kastamonu", "Bursa"],
            3, "Mahmutbey Camii Kastamonu'dadır."),
        q("Aşağıdakilerden hangisi Anadolu'nun Ortaçağ Dönemi Ahşap Hipostil Camileri arasında yer alan yapılardan değildir?",
            ["Eşrefoğlu Camii", "Ahi Şerafettin Camii", "Afyonkarahisar Ulu Camii", "Mahmutbey Camii", "Divriği Ulu Camii"],
            4, "Divriği Ulu Camii UNESCO Dünya Mirası'dır; ahşap hipostil camiler listesinde yoktur."),
        q("Aşağıdaki ahşap hipostil (ahşap direkli) camilerden hangisi Ege Bölgesi'nde yer alır?",
            ["Eşrefoğlu Camii", "Ahi Şerafettin Camii", "Afyonkarahisar Ulu Camii", "Mahmutbey Camii", "Sivrihisar Ulu Camii"],
            2, "Afyonkarahisar Ulu Camii, Ege Bölgesi'nin İç Batı Anadolu bölümündeki Afyonkarahisar'dadır. Eşrefoğlu Camii Konya'nın Beyşehir ilçesinde, Ahi Şerafettin Camii Ankara'da, Mahmutbey Camii Kastamonu'da, Sivrihisar Ulu Camii ise Eskişehir'dedir."),
        q("Aşağıdaki eşleştirmelerden hangisinde verilen yer ile turizm türü yanlış eşleştirilmiştir?",
            ["Manyas Gölü – Kuş gözlemciliği", "Belek – Golf", "Bodrum – Yat turizmi", "Yalova – Termal turizm", "Palandöken – Kruvaziyer turizmi"],
            4, "Palandöken kış (kayak) turizmidir; kruvaziyer İstanbul ve Kuşadası ile ilişkilidir."),
        q("Aşağıdaki seçeneklerin hangisinde üç farklı turizm türüne ait merkezler birlikte verilmiştir?",
            ["Hattuşaş – Troya – Göbeklitepe", "Uludağ – Erciyes – Palandöken", "Demre – Mevlana – Akdamar", "Belek – Manyas – Bodrum", "Safranbolu – Çatalhöyük – Arslantepe"],
            3, "Belek golf, Manyas kuş gözlemciliği, Bodrum yat turizmidir."),
        q("Aşağıdakilerden hangisinde verilen merkezlerin tamamı inanç turizmi kapsamında değerlendirilmiştir?",
            ["Balıklıgöl – Mevlana Müzesi – Akdamar Kilisesi", "Bodrum – Marmaris – Göcek", "Belek – Ankara – İstanbul", "Manyas – Kızılırmak Deltası – Çoruh", "Yalova – Bursa – Afyon"],
            0, "Balıklıgöl, Mevlana Müzesi ve Akdamar Kilisesi inanç turizmi merkezleridir."),
        q("Aşağıdakilerden hangisinde verilen merkezlerin tamamı kış turizmi ile ilişkilidir?",
            ["Manyas – Kızılırmak Deltası – Fırtına", "Bodrum – Marmaris – Göcek", "Belek – İstanbul – İzmir", "Uludağ – Erciyes – Palandöken", "Yalova – Bursa – Afyon"],
            3, "Uludağ, Erciyes ve Palandöken kayak merkezleridir."),
        q("Aşağıdaki seçeneklerin hangisinde verilen yerlerin tamamı UNESCO Dünya Kültür Mirası Listesi'nde bulunan alanlarla ilişkilidir?",
            ["Hattuşaş – Göbeklitepe – Troya", "Palandöken – Erciyes – Uludağ", "Bodrum – Marmaris – Göcek", "Belek – Ankara – İzmir", "Balıklıgöl – Demre – Göcek"],
            0, "Hattuşaş, Göbeklitepe ve Troya UNESCO Dünya Kültür Mirası alanlarıdır."),
        q("Aşağıdakilerden hangisinde turizm gelişim bölgesi ile UNESCO miras alanı doğru eşleştirilmiştir?",
            ["Troya – Efes Antik Kenti", "GAP – Uludağ", "Frigya – Göbeklitepe", "Urartu – Pamukkale", "Hitit – Hattuşaş"],
            4, "Hitit turizm gelişim bölgesinin merkezindeki Hattuşaş (Boğazkale/Çorum) UNESCO Dünya Mirası Listesi'ndedir. Efes, Çanakkale'deki Troya bölgesinde değil İzmir'dedir; Uludağ Bursa'da, Göbeklitepe Frigya'da değil Şanlıurfa'da, Pamukkale ise Van çevresindeki Urartu bölgesinde değil Denizli'dedir."),
        q("Aşağıdaki illerden hangisi hem kıyı (deniz) turizmi hem de kayak merkeziyle kış turizmi bakımından öne çıkar?",
            ["Bursa", "Aydın", "Muğla", "Antalya", "Kars"],
            3, "Antalya, yaz turizminde Kemer, Side ve Alanya kıyılarıyla; kış turizminde ise Bey Dağları'ndaki Saklıkent Kayak Merkezi ile öne çıkar."),
        q("Hattuşaş'ın bulunduğu ve aynı zamanda Hitit turizm gelişim bölgesi içinde yer alan il aşağıdakilerden hangisidir?",
            ["Çorum", "Van", "Manisa", "Kars", "Kütahya"],
            0, "Hitit uygarlığının başkenti Hattuşaş, Çorum'un Boğazkale ilçesindedir ve UNESCO Dünya Mirası Listesi'nde yer alır; Çorum aynı zamanda Hitit turizm gelişim bölgesi içindedir.")
    ];
})();
