// sorular/cografya-24.js
window.cografya_24_sorulari = (function () {
    var L = ["A", "B", "C", "D", "E"];
    function q(stem, opts, i, exp) {
        return {
            question: stem,
            options: opts.map(function (t, n) { return L[n] + ") " + t; }),
            correctAnswerIndex: i,
            explanation: exp
        };
    }
    return [
        q("Soru 1: Türkiye topraklarında kurulan ilk demir yolu hattı aşağıdakilerden hangisidir?",
            ["Ankara – Yerköy", "Ankara – Eskişehir", "İzmir – Aydın", "İstanbul – İzmit", "Sivas – Erzurum"],
            2, "İlk hat İzmir–Aydın'dır. Ankara–Yerköy Cumhuriyet'in ilk hattıdır."),
        q("Soru 2: Cumhuriyet Dönemi'nde inşa edilen ilk demir yolu hattı aşağıdakilerden hangisidir?",
            ["Ankara – Yerköy", "Ankara – Eskişehir", "İzmir – Aydın", "İstanbul – Ankara", "Sivas – Kayseri"],
            0, "Cumhuriyet'in ilk hattı Ankara–Yozgat (Yerköy)'dür."),
        q("Soru 3: Türkiye'de demir yolu hatlarının genel olarak doğu-batı doğrultusunda uzanmasında aşağıdakilerden hangisinin etkisi daha fazladır?",
            ["Nüfusun kıyılarda yoğunlaşmasının", "Dağların genel uzanış doğrultusunun", "Limanların kıyılarda bulunmasının", "Tarım alanlarının geniş olmasının", "Akarsuların rejimlerinin"],
            1, "Dağlar doğu-batı uzandığı için hatlar da bu doğrultuda gelişmiştir."),
        q("Soru 4: Türkiye'de kara üzerindeki yük ve yolcu taşımacılığında maliyet açısından en avantajlı ulaşım türü aşağıdakilerden hangisidir?",
            ["Hava yolu", "Kara yolu", "Deniz yolu", "Demir yolu", "Boru hattı"],
            3, "Kara üzerindeki taşımacılıkta en ucuz tür demir yoludur. Deniz yolu genel olarak en ucuzdur ama kara üzerinde değildir."),
        q("Soru 5: Aşağıdaki yörelerden hangisine, engebeli ve dağlık arazi yapısının ulaşımı zorlaştırması nedeniyle demir yolu ulaşımı ulaşmamıştır?",
            ["Çukurova", "Doğu Karadeniz", "Konya Ovası", "Ergene Havzası", "Ankara çevresi"],
            1, "Doğu Karadeniz demir yolu gitmeyen yerlerdendir."),
        q("Soru 6: Aşağıdaki yörelerden hangisinde demir yolu ulaşımının gelişmemesinde yer şekillerinin engebeli olması daha belirleyici olmuştur?",
            ["Hakkâri", "Konya", "Ergene", "Harran", "Çukurova"],
            0, "Hakkâri Yöresi engebeli olduğu için demir yolu yoktur."),
        q("Soru 7: Aşağıdakilerden hangisi Türkiye'de demir yolu ulaşımının ulaşmadığı yerlerden biri değildir?",
            ["Menteşe Yöresi", "Hakkâri Yöresi", "Doğu Karadeniz", "Teke Platosu", "İç Anadolu'nun büyük bölümü"],
            4, "İç Anadolu'nun büyük bölümünde demir yolu vardır; diğerleri notlardaki engebeli sahalardır."),
        q("Soru 8: Aşağıdaki yerlerden hangisinde demir yolu ulaşımının gelişmemesinde yer şekillerinin engebeli olması temel bir etkendir?",
            ["Gelibolu – Biga yarımadaları", "Ergene Havzası", "Konya Ovası", "Harran Ovası", "Tuz Gölü çevresi"],
            0, "Gelibolu–Biga yarımadalarına demir yolu gitmez."),
        q("Soru 9: Türkiye'de yüksek hızlı tren işletmeciliğinin başladığı ilk hat aşağıdakilerden hangisidir?",
            ["Ankara – Konya", "Ankara – İstanbul", "Ankara – Eskişehir", "Ankara – Sivas", "İstanbul – Konya"],
            2, "İlk YHT hattı Ankara–Eskişehir'dir."),
        q("Soru 10: Türkiye'nin ilk Yüksek Hızlı Tren hattı hangi yılda hizmete girmiştir?",
            ["2003", "2005", "2007", "2009", "2011"],
            3, "Ankara–Eskişehir YHT 2009'da açılmıştır."),
        q("Soru 11: Aşağıdakilerden hangisi Türkiye'deki aktif YHT hatlarından biri değildir?",
            ["Ankara – Konya", "Ankara – Sivas", "Ankara – Eskişehir", "Konya – Karaman", "Ankara – Erzurum"],
            4, "Ankara–Erzurum aktif YHT listesinde yoktur."),
        q("Soru 12: İstanbul'dan Konya'ya YHT ile ulaşım sağlanırken aşağıdaki şehirlerden hangisinin üzerinden geçilir?",
            ["Eskişehir", "Kayseri", "Kütahya", "Afyonkarahisar", "Karaman"],
            0, "İstanbul–Konya hattı Eskişehir ve Bilecik üzerinden geçer. Karaman ayrı bir Konya–Karaman hattıdır."),
        q("Soru 13: Aşağıdaki YHT hatlarından hangisi doğrudan Ankara merkezli bir hat değildir?",
            ["Ankara – Eskişehir", "Ankara – Konya", "Ankara – Sivas", "Ankara – İstanbul", "İstanbul – Konya"],
            4, "İstanbul–Konya Ankara merkezli bir hat olarak verilmez."),
        q("Soru 14: Aşağıdaki YHT güzergâhlarından hangisi İç Anadolu'daki iki merkez arasında ulaşım sağlamaktadır?",
            ["Ankara – Sivas", "İstanbul – Sivas", "İstanbul – Konya", "Ankara – İstanbul", "İstanbul – Eskişehir"],
            0, "Ankara ve Sivas İç Anadolu merkezleridir."),
        q("Soru 15: Aşağıdaki ülke – sınır kapısı eşleştirmelerinden hangisi doğrudur?",
            ["Bulgaristan – Kapıköy", "İran – Kapıkule", "Gürcistan – Canbaz", "Yunanistan – Akyaka", "Ermenistan – Uzunköprü"],
            2, "Gürcistan bağlantısı Canbaz'dır (BTK). İran Kapıköy, Bulgaristan Kapıkule, Yunanistan Uzunköprü, Ermenistan Akyaka'dır."),
        q("Soru 16: Türkiye'nin Bulgaristan ile demir yolu bağlantısında kullanılan sınır kapısı aşağıdakilerden hangisidir?",
            ["Kapıköy", "Kapıkule", "Uzunköprü", "Akyaka", "Nusaybin"],
            1, "Bulgaristan: Kapıkule."),
        q("Soru 17: Türkiye'nin İran ile demir yolu bağlantısında aşağıdaki sınır kapılarından hangisi kullanılmaktadır?",
            ["Kapıkule", "Uzunköprü", "Kapıköy", "Canbaz", "İslahiye"],
            2, "İran: Kapıköy (Van)."),
        q("Soru 18: Bakü-Tiflis-Kars demir yolu hattı kapsamında Türkiye'nin Gürcistan ile bağlantısında aşağıdaki sınır kapılarından hangisi yer almaktadır?",
            ["Akyaka", "Kapıköy", "Canbaz", "Uzunköprü", "Çobanbey"],
            2, "BTK hattında Canbaz kapısı kullanılır."),
        q("Soru 19: Aşağıdaki sınır kapılarından hangisi Ermenistan ile demir yolu bağlantısında bulunmakla birlikte siyasi nedenlerle kapalıdır?",
            ["Akyaka", "Kapıkule", "Kapıköy", "Canbaz", "Uzunköprü"],
            0, "Akyaka (Kars) Ermenistan hattıdır ve kapalıdır."),
        q("Soru 20: Aşağıdakilerden hangisi Türkiye'nin Suriye ile demir yolu bağlantısında kullanılan sınır kapılarından biri değildir?",
            ["İslahiye", "Çobanbey", "Nusaybin", "Kapıköy", "İslahiye (Suriye hattı)"],
            3, "Kapıköy İran kapısıdır. Suriye: İslahiye, Çobanbey, Nusaybin."),
        q("Soru 21: Türkiye'de kara yolu ulaşımının büyük gelişme gösterdiği dönem aşağıdakilerden hangisidir?",
            ["1920'li yıllar", "1930'lu yıllar", "1940'lı yıllar", "1950'li yıllardan sonrası", "1990'lı yıllardan sonrası"],
            3, "Kara yolu 1950'lerden sonra büyük gelişme göstermiştir."),
        q("Soru 22: Türkiye'de iç ticarette en fazla kullanılan ulaşım türü aşağıdakilerden hangisidir?",
            ["Demir yolu", "Deniz yolu", "Hava yolu", "Kara yolu", "Boru hattı"],
            3, "İç ticarette kara yolu, dış ticarette deniz yolu öne çıkar."),
        q("Soru 23: Kara yolu ulaşımının Türkiye'de hemen her yere ulaşabilmesinde aşağıdakilerden hangisi temel bir avantaj sağlamaktadır?",
            ["Sadece düz arazilerde kullanılabilmesi", "Güzergâh esnekliğinin yüksek olması", "Yüksek maliyetli olması", "Limanlara bağımlı olması", "Hava koşullarından hiç etkilenmemesi"],
            1, "Kara yolu güzergâh esnekliğiyle hemen her yere ulaşır."),
        q("Soru 24: Türkiye'nin kuzey ve güney kesimleri arasındaki kara yolu ulaşımında aşağıdakilerden hangisinin kullanılması zorunludur?",
            ["Limanlar", "Geçit ve boğazlar", "Havalimanları", "Ovalar", "Akarsular"],
            1, "Kuzey ve güneyde dağlar nedeniyle geçit ve boğazlar kullanılır."),
        q("Soru 25: Aşağıdakilerden hangisi Akdeniz Bölgesi'nde yer alan önemli geçitlerden biridir?",
            ["Ilgaz", "Kop", "Zigana", "Sertavul", "Ecevit"],
            3, "Sertavul Akdeniz'dedir. Diğerleri Karadeniz geçitleridir."),
        q("Soru 26: Aşağıdaki geçitlerden hangisi Akdeniz Bölgesi'nde yer almaz?",
            ["Çubuk", "Sertavul", "Gürlek", "Belen", "Ilgaz"],
            4, "Ilgaz Karadeniz / Çankırı geçididir. ÇSGB: Çubuk, Sertavul, Gürlek, Belen."),
        q("Soru 27: Aşağıdaki eşleştirmelerden hangisi doğrudur?",
            ["Ecevit – Kastamonu", "Ilgaz – Antalya", "Zigana – Muğla", "Kop – Çanakkale", "Belen – Çankırı"],
            0, "Ecevit Kastamonu'dadır. Ilgaz Çankırı, Zigana Trabzon, Belen Hatay'dır."),
        q("Soru 28: Karadeniz Bölgesi'nde ulaşım açısından önemli olan geçitler arasında aşağıdakilerden hangisi bulunmaz?",
            ["Ecevit", "Ilgaz", "Zigana", "Kop", "Sertavul"],
            4, "Sertavul Akdeniz geçididir."),
        q("Soru 29: Aşağıdakilerden hangisi Marmara Bölgesi'nde yer alan önemli ulaşım geçitlerinden biridir?",
            ["Belen Geçidi", "Kop Geçidi", "Geyve Boğazı", "Zigana Geçidi", "Sertavul Geçidi"],
            2, "Marmara: Geyve Boğazı ve Bolu Dağı Geçidi."),
        q("Soru 30: Aşağıdaki geçit – bölge eşleştirmelerinden hangisi yanlıştır?",
            ["Belen – Akdeniz", "Zigana – Karadeniz", "Geyve – Marmara", "Kop – Karadeniz", "Sertavul – Marmara"],
            4, "Sertavul Akdeniz'dedir, Marmara'da değil."),
        q("Soru 31: Aşağıdaki ulaşım türlerinden hangisi maliyet bakımından en pahalı olanıdır?",
            ["Deniz yolu", "Demir yolu", "Kara yolu", "Hava yolu", "Boru hattı"],
            3, "Hava yolu en pahalıdır."),
        q("Soru 32: Türkiye'de günümüzde gelişme hızı en yüksek ulaşım türü aşağıdakilerden hangisidir?",
            ["Demir yolu", "Kara yolu", "Deniz yolu", "Hava yolu", "Akarsu yolu"],
            3, "En çok gelişen tür hava yoludur."),
        q("Soru 33: Türkiye'nin en büyük havalimanı aşağıdakilerden hangisidir?",
            ["Esenboğa Havalimanı", "Adnan Menderes Havalimanı", "İstanbul Havalimanı", "Antalya Havalimanı", "Sabiha Gökçen Havalimanı"],
            2, "En büyük havalimanı İstanbul Havalimanı'dır. En büyük kargo ise Şanlıurfa GAP'tır."),
        q("Soru 34: Aşağıdakilerden hangisi hava yolu ulaşımının Türkiye'deki genel özelliklerinden biridir?",
            ["İç ticarette en fazla kullanılan ulaşım türüdür.", "En ucuz ulaşım türüdür.", "Günümüzde gelişme hızı en yüksek ulaşım türüdür.", "Yük taşımacılığında temel ulaşım türüdür.", "Limanlara bağlı olarak gelişir."],
            2, "Hava yolu en pahalıdır ve en hızlı gelişendir. İç ticaret kara yoludur."),
        q("Soru 35: Deniz yolu ulaşımının maliyetinin düşük olmasının temel nedeni aşağıdakilerden hangisidir?",
            ["Her yere ulaşabilmesi", "Hava koşullarından etkilenmemesi", "Bir seferde çok fazla yük taşıyabilmesi", "Hızlı olması", "Kara yollarıyla bağlantılı olması"],
            2, "Bir seferde çok yük taşındığı için birim maliyet düşüktür."),
        q("Soru 36: Türkiye'nin dış ticaretinde en fazla kullanılan ulaşım türü aşağıdakilerden hangisidir?",
            ["Kara yolu", "Demir yolu", "Hava yolu", "Deniz yolu", "Boru hattı"],
            3, "Dış ticarette deniz yolu hâkimdir."),
        q("Soru 37: Aşağıdakilerden hangisi deniz yolu taşımacılığının kara yolu taşımacılığına göre temel üstünlüklerinden biridir?",
            ["Her yerleşim merkezine ulaşabilmesi", "Daha hızlı olması", "Bir seferde daha fazla yük taşıyabilmesi", "Dağlık alanlarda daha kolay kullanılabilmesi", "Hava koşullarından etkilenmemesi"],
            2, "Deniz yolu büyük hacimli yükte üstündür; her yere ulaşmak kara yolunun avantajıdır."),
        q("Soru 38: Bir limanın gelişmesini sağlayan ve limanın etki alanını oluşturan ekonomik ve coğrafi özelliklerin tümüne aşağıdakilerden hangisi denir?",
            ["Rıhtım", "Hinterland", "Delta", "Boğaz", "Plato"],
            1, "Hinterland (ard bölge) limanın etki alanıdır."),
        q("Soru 39: Aşağıdaki limanlardan hangisinin hinterlandı geniştir?",
            ["Sinop", "Hopa", "Cide", "İzmir", "Cide (dar hinterland)"],
            3, "İzmir geniş hinterlandlıdır. Sinop, Hopa, Cide dardır."),
        q("Soru 40: Aşağıdakilerden hangisi hinterlandı geniş olan limanlardan biridir?",
            ["İstanbul", "Sinop", "Hopa", "Cide", "Hopa Limanı"],
            0, "İstanbul, Kocaeli, İzmir, Mersin, Samsun geniş hinterlandlıdır."),
        q("Soru 41: Aşağıdaki limanlardan hangisinin hinterlandı dar olduğu için gelişme düzeyi sınırlıdır?",
            ["İzmir", "Mersin", "Kocaeli", "Samsun", "Sinop"],
            4, "Sinop doğal limandır ama hinterlandı dardır."),
        q("Soru 42: Sinop Limanı'nın doğal liman özelliğine sahip olmasına rağmen yeterince gelişememesinin temel nedeni aşağıdakilerden hangisidir?",
            ["Hinterlandının dar olması", "Kıyı uzunluğunun fazla olması", "Deniz ulaşımına kapalı olması", "Demir yolu ağının çok gelişmiş olması", "Büyük bir sanayi bölgesinde bulunması"],
            0, "Küre Dağları / dar hinterland gelişmeyi sınırlar. Sinop'a demir yolu da gitmez."),
        q("Soru 43: Aşağıdaki limanlardan hangisinin hinterlandı dar olan limanlar arasında yer aldığı söylenebilir?",
            ["İstanbul", "Kocaeli", "İzmir", "Hopa", "Mersin"],
            3, "Hopa dar hinterlandlıdır."),
        q("Soru 44: Aşağıdaki limanlardan hangisinin hinterlandı geniş değildir?",
            ["Samsun", "Mersin", "Kocaeli", "Cide", "İstanbul"],
            3, "Cide dar hinterlandlıdır."),
        q("Soru 45: Kamyon, TIR ve benzeri tekerlekli araçların gemilerle taşınmasına verilen ad aşağıdakilerden hangisidir?",
            ["Konteyner taşımacılığı", "Ro-Ro taşımacılığı", "Transit taşımacılık", "Kombine taşımacılık", "Boru hattı taşımacılığı"],
            1, "Ro-Ro: tekerlekli araçların gemiyle taşınmasıdır."),
        q("Soru 46: Bir TIR'ın yükü boşaltılmadan doğrudan gemiye alınarak başka bir ülkeye taşınması aşağıdaki ulaşım yöntemlerinden hangisine örnek gösterilebilir?",
            ["Ro-Ro taşımacılığı", "Hava kargo taşımacılığı", "Boru hattı taşımacılığı", "Demir yolu taşımacılığı", "Akarsu taşımacılığı"],
            0, "TIR'ın gemiye binmesi Ro-Ro örneğidir."),
        q("Soru 47: Türkiye'deki ulaşım sistemleriyle ilgili aşağıdaki bilgilerden hangisi yanlıştır?",
            ["Kara yolu iç ticarette önemli bir yere sahiptir.", "Deniz yolu dış ticarette önemli bir yere sahiptir.", "Hava yolu günümüzde hızlı gelişen ulaşım türlerinden biridir.", "Demir yolu, kara üzerindeki yük ve yolcu taşımacılığında maliyet açısından avantajlıdır.", "Hava yolu ulaşımı en ucuz ulaşım türüdür."],
            4, "Hava yolu en pahalıdır; en ucuz genel olarak deniz yoludur."),
        q("Soru 48: Aşağıdaki ulaşım türlerinden hangisi ile ilgili verilen bilgi yanlıştır?",
            ["Kara yolu → İç ticarette yaygın kullanım", "Deniz yolu → Dış ticarette yaygın kullanım", "Hava yolu → En pahalı ulaşım türü", "Demir yolu → Kara üzerindeki taşımacılıkta düşük maliyet", "Deniz yolu → En pahalı ulaşım türü"],
            4, "Deniz yolu en ucuz türdür, en pahalı değil."),
        q("Soru 49: Aşağıdaki limanlardan hangisinin gelişmişlik düzeyi ile hinterlandı arasında doğrudan bir ilişki kurulabilir?",
            ["Sinop", "Hopa", "Cide", "İzmir", "Tümü"],
            4, "Dar hinterland (Sinop, Hopa, Cide) gelişememeyi; geniş hinterland (İzmir) gelişmeyi açıklar. Dört örnek de ilişkiyi gösterir."),
        q("Soru 50: Türkiye'de ulaşım sistemlerinin gelişimiyle ilgili;\nI. Kara yolu ulaşımı 1950'lerden sonra önemli ölçüde gelişmiştir.\nII. Demir yolu hatlarının uzanışında yer şekilleri etkili olmuştur.\nIII. Hava yolu ulaşımı günümüzde gelişme gösteren ulaşım türlerinden biridir.\nIV. Deniz yolu dış ticarette önemli bir yere sahiptir.\nyargılarından hangilerine ulaşılabilir?",
            ["Yalnız I", "I ve II", "II ve III", "I, II ve IV", "I, II, III ve IV"],
            4, "Dört yargı da notlarla uyumludur."),
        q("Soru 51: Aşağıdaki ulaşım türlerinden hangisi ile kullanım alanı arasında yanlış bir eşleştirme yapılmıştır?",
            ["Kara yolu – İç ticaret", "Deniz yolu – Dış ticaret", "Hava yolu – Hızlı ulaşım", "Demir yolu – Kara üzerindeki düşük maliyetli taşımacılık", "Deniz yolu – Her yere doğrudan ulaşım"],
            4, "Her yere ulaşmak kara yolunun özelliğidir; deniz yolu kıyı ve limana bağlıdır."),
        q("Soru 52: Türkiye'de aşağıdaki ulaşım sistemlerinden hangisinin gelişmesinde yer şekillerinin etkisi diğerlerine göre daha belirgindir?",
            ["Hava yolu", "Deniz yolu", "Kara yolu", "Demir yolu", "Boru hattı"],
            3, "Demir yolu hem uzanış doğrultusunda hem de gitmediği engebeli yörelerde yer şekillerine daha bağımlıdır."),
        q("Soru 53: Bir araştırmacı Türkiye'deki ulaşım sistemleriyle ilgili şu sonuçlara ulaşmıştır:\n• İç ticarette en fazla kullanılan ulaşım sistemidir.\n• Ülkenin hemen her yerine ulaşabilmektedir.\n• 1950'li yıllardan sonra hızlı bir gelişme göstermiştir.\n• Kuzey ve güney yönlü ulaşımda geçitlerden yararlanılır.\nBu araştırmacının incelediği ulaşım türü aşağıdakilerden hangisidir?",
            ["Demir yolu", "Kara yolu", "Deniz yolu", "Hava yolu", "Boru hattı"],
            1, "Dört özellik birden kara yoluna aittir."),
        q("Soru 54: Bir limanın doğal liman olmasına rağmen ticari açıdan beklenen düzeyde gelişmemesinde aşağıdakilerden hangisinin etkili olması beklenir?",
            ["Hinterlandının dar olması", "Kıyıda bulunması", "Deniz ulaşımına uygun olması", "Liman alanının bulunması", "Deniz taşımacılığının yapılabilmesi"],
            0, "Sinop örneğinde olduğu gibi dar hinterland gelişmeyi sınırlar."),
        q("Soru 55: Aşağıdaki merkezlerden hangisi geniş hinterlandıyla gelişmiş limanlara örnek gösterilebilir?",
            ["Cide", "Hopa", "Sinop", "Mersin", "Cide Limanı"],
            3, "Mersin geniş hinterlandlıdır."),
        q("Soru 56: Türkiye'deki ulaşım sistemleri dikkate alındığında aşağıdaki yargılardan hangisine ulaşılabilir?",
            ["Hava yolu en düşük maliyetli ulaşım türüdür.", "Kara yolu dış ticarette en fazla kullanılan ulaşım türüdür.", "Deniz yolu, yüksek miktarda yük taşıyabilmesi nedeniyle düşük maliyetlidir.", "Demir yolu Türkiye'nin tüm dağlık bölgelerine ulaşmıştır.", "Limanların gelişmesinde hinterlandın hiçbir etkisi yoktur."],
            2, "Deniz yolu yüksek yük kapasitesiyle ucuzdur."),
        q("Soru 57: Türkiye'nin en büyük kargo havalimanı aşağıdakilerden hangisidir?",
            ["İstanbul Havalimanı", "Şanlıurfa (GAP) Havalimanı", "Esenboğa Havalimanı", "Adnan Menderes Havalimanı", "Sabiha Gökçen Havalimanı"],
            1, "En büyük kargo havalimanı Şanlıurfa GAP'tır; en büyük yolcu havalimanı İstanbul'dur."),
        q("Soru 58: Türkiye'nin Yunanistan ile demir yolu bağlantısında kullanılan sınır kapısı aşağıdakilerden hangisidir?",
            ["Kapıkule", "Uzunköprü", "Canbaz", "Akyaka", "Kapıköy"],
            1, "Yunanistan: Uzunköprü. Kapıkule Bulgaristan'dır."),
        q("Soru 59: Aşağıdakilerden hangisi Marmara Bölgesi'ndeki önemli kara yolu geçitlerinden biridir?",
            ["Bolu Dağı Geçidi", "Sertavul Geçidi", "Zigana Geçidi", "Belen Geçidi", "Kop Geçidi"],
            0, "Marmara: Geyve Boğazı ve Bolu Dağı Geçidi."),
        q("Soru 60: Aşağıdakilerden hangisi demir yolu ulaşımının ulaşmadığı yerlerden biridir?",
            ["Teke ve Taşeli platoları", "Konya Ovası", "Ergene Havzası", "Ankara çevresi", "Çukurova"],
            0, "Teke ve Taşeli platolarına demir yolu gitmez.")
    ];
})();
