// sorular/cografya-26.js
window.cografya_26_sorulari = (function () {
    var L = ["A", "B", "C", "D", "E"];
    function q(stem, opts, i, exp) {
        return {
            question: stem,
            options: opts.map(function (t, n) { return L[n] + ") " + t; }),
            correctAnswerIndex: i,
            explanation: exp
        };
    }
    return [
        q("Türkiye'nin Ege Denizi'ndeki sorunları arasında;\nI. Kıta sahanlığı\nII. Karasuları\nIII. FIR hattı\nIV. SAR bölgesi\nV. Adaların silahsızlandırılması\nkonularından hangileri yer almaktadır?",
            ["I ve II", "I, II ve III", "II, III ve IV", "I, II, III, IV ve V", "I, III, IV ve V"],
            3, "Ege sorunları arasında kıta sahanlığı, karasuları, FIR hattı, SAR bölgesi ve adaların silahsızlandırılması yer alır."),
        q("Aşağıdakilerden hangisi Ege Denizi'nde Türkiye ile Yunanistan arasında yaşanan sorunlardan biri değildir?",
            ["Kıta sahanlığı", "Karasuları", "FIR hattı", "SAR bölgesi", "Fırat Nehri'nin kullanımı"],
            4, "Fırat Nehri'nin kullanımı Ege sorunu değildir."),
        q("Arama-kurtarma faaliyetlerinin yürütüldüğü bölge aşağıdakilerden hangisidir?",
            ["FIR", "SAR", "Kıta sahanlığı", "Karasuları", "Münhasır ekonomik bölge"],
            1, "SAR, arama-kurtarma faaliyetlerinin yürütüldüğü bölgedir."),
        q("Türkiye'nin doğrudan sorunları arasında aşağıdakilerden hangisinin Yunanistan ile ilişkili olduğu söylenebilir?",
            ["Batı Trakya Türkleri", "Irak'ın işgali", "Suriye meselesi", "Ermeni Tehciri", "Irak sınır kapıları"],
            0, "Batı Trakya Türkleri Yunanistan ile ilişkilidir."),
        q("Aşağıdaki sınır kapısı–ülke eşleştirmelerinden hangisi yanlıştır?",
            ["Bulgaristan – Kapıkule", "Yunanistan – İpsala", "Gürcistan – Sarp", "İran – Habur", "Irak – Habur"],
            3, "Habur Irak kapısıdır; İran kapısı Gürbulak'tır."),
        q("Türkiye'nin Avrupa'ya giden en kısa yol üzerinde bulunan ve en işlek sınır kapısı olarak belirtilen sınır kapısı aşağıdakilerden hangisidir?",
            ["İpsala", "Sarp", "Kapıkule", "Dilucu", "Habur"],
            2, "Kapıkule Avrupa'ya en kısa yol üzerindedir ve en işlek sınır kapısıdır."),
        q("Türkiye ile Yunanistan arasındaki kara sınırının belirlenmesinde aşağıdaki akarsulardan hangisi sınır kabul edilmiştir?",
            ["Meriç", "Kızılırmak", "Sakarya", "Gediz", "Büyük Menderes"],
            0, "Türkiye–Yunanistan kara sınırı Meriç Nehri ile belirlenmiştir."),
        q("Aşağıdaki ülke–sınır kapısı eşleştirmelerinden hangisi doğrudur?",
            ["Gürcistan – Dilucu", "Nahçıvan – Gürbulak", "Ermenistan – Akyaka", "İran – Sarp", "Irak – İpsala"],
            2, "Ermenistan sınır kapısı Akyaka'dır."),
        q("Türkiye'nin Nahçıvan ile olan sınırında bulunan sınır kapısı aşağıdakilerden hangisidir?",
            ["Habur", "Dilucu", "Gürbulak", "Kapıkule", "Cilvegözü"],
            1, "Nahçıvan sınır kapısı Dilucu'dur."),
        q("İran ile ilgili aşağıdaki bilgilerden hangisi doğrudur?",
            ["Türkiye'nin en kısa kara sınırına sahip komşusudur.", "Türkiye'nin yüz ölçümü ve nüfus bakımından kendisinden büyük olan tek komşusudur.", "Türkiye'nin Avrupa'ya açılan en önemli komşusudur.", "Türkiye ile arasındaki sınır Meriç Nehri ile belirlenmiştir.", "Türkiye ile arasında Kapıkule Sınır Kapısı bulunmaktadır."],
            1, "İran hem yüz ölçümü hem nüfus bakımından Türkiye'den büyük olan tek komşudur."),
        q("Türkiye'nin İran sınırının ana hatlarının belirlenmesinde etkili olan antlaşma aşağıdakilerden hangisidir?",
            ["Lozan Antlaşması", "Ankara Antlaşması", "Kasr-ı Şirin Antlaşması", "Gümrü Antlaşması", "Kars Antlaşması"],
            2, "İran sınırının ana hatları Kasr-ı Şirin Antlaşması ile belirlenmiştir."),
        q("Aşağıdaki sınır kapılarından hangisi Irak ile Türkiye arasındaki sınırda bulunmaktadır?",
            ["Habur", "Sarp", "Akyaka", "İpsala", "Gürbulak"],
            0, "Irak sınır kapısı Habur'dur."),
        q("Türkiye'nin Suriye sınırında bulunan;\nI. Ceylanpınar\nII. Öncüpınar\nIII. Mürşitpınar\nIV. Cilvegözü\nsınır kapılarından hangileri verilenler arasında yer almaktadır?",
            ["Yalnız I", "I ve II", "II ve III", "I, II ve IV", "I, II, III ve IV"],
            4, "Dört kapı da Suriye sınırında verilmiştir."),
        q("Türkiye'nin komşuları arasında ihracatta birinci sırada yer alan ülke ve bu ülkeye açılan önemli sınır kapısı aşağıdakilerin hangisinde birlikte verilmiştir?",
            ["İran – Gürbulak", "Irak – Habur", "Gürcistan – Sarp", "Yunanistan – İpsala", "Bulgaristan – Kapıkule"],
            1, "İhracatta 1. sıradaki komşu Irak'tır; kapısı Habur'dur."),
        q("Türkiye'nin kara sınırlarıyla ilgili aşağıdaki bilgilerden hangisi yanlıştır?",
            ["En uzun kara sınırı Suriye ile olan sınırdır.", "En kısa kara sınırı Nahçıvan ile olan sınırdır.", "En yeni sınır Hatay'ın Türkiye'ye katılmasıyla oluşmuştur.", "İran sınırının ana hatları Kasr-ı Şirin Antlaşması ile belirlenmiştir.", "En uzun kara sınırı İran ile olan sınırdır."],
            4, "En uzun kara sınırı Suriye iledir, İran ile değildir."),
        q("Türkiye'nin en yeni kara sınırının ortaya çıkmasında aşağıdaki gelişmelerden hangisi etkili olmuştur?",
            ["Musul'un Türkiye'ye bağlanması", "Kars'ın Türkiye'ye katılması", "Hatay'ın 1939'da Türkiye'ye katılması", "Kıbrıs'ın Türkiye'ye katılması", "Batum'un Türkiye'ye katılması"],
            2, "En yeni sınır Hatay'ın 1939'da katılmasıyla oluşmuştur."),
        q("Aşağıdaki eşleştirmelerden hangisi Türkiye'nin uç noktaları bakımından doğrudur?",
            ["Kuzey – Hatay", "Güney – Sinop", "Doğu – Iğdır", "Batı – Iğdır", "Doğu – Çanakkale"],
            2, "En doğu uç nokta Iğdır – Dilucu'dur."),
        q("Türkiye'nin en kuzey uç noktası aşağıdakilerden hangisidir?",
            ["Gökçeada", "Dilucu", "Beysun Köyü", "İnceburun", "Kapıkule"],
            3, "En kuzey: Sinop – İnceburun."),
        q("Türkiye'nin en güney uç noktası aşağıdakilerden hangisidir?",
            ["Sinop – İnceburun", "Hatay – Beysun Köyü", "Iğdır – Dilucu", "Çanakkale – Gökçeada", "Muğla – Bodrum"],
            1, "En güney: Hatay – Beysun Köyü."),
        q("Türkiye'nin en batı uç noktası aşağıdakilerden hangisidir?",
            ["Iğdır – Dilucu", "Sinop – İnceburun", "Hatay – Beysun Köyü", "Çanakkale – Gökçeada", "Edirne – Kapıkule"],
            3, "En batı: Çanakkale – Gökçeada."),
        q("Aşağıdaki gümrük kapılarından hangisinin demir yolu bağlantısı bulunduğu belirtilmiştir?",
            ["Kapıkule", "Cilvegözü", "Habur", "Gürbulak", "Dilucu"],
            0, "Kapıkule demir yolu bağlantılı gümrük kapılarındandır."),
        q("Aşağıdakilerden hangisi demir yolu bağlantısı bulunan gümrük kapılarından biri değildir?",
            ["Kapıkule", "Uzunköprü", "Nusaybin", "İslahiye", "Habur"],
            4, "Habur demir yolu bağlantılı gümrük kapıları arasında verilmemiştir."),
        q("Türkiye'nin demir yolu bağlantısı bulunan gümrük kapılarıyla ilgili aşağıdaki eşleştirmelerden hangisi doğrudur?",
            ["Bulgaristan – Kapıkule", "Yunanistan – İpsala", "Gürcistan – Sarp", "İran – Gürbulak", "Irak – Habur"],
            0, "Demiryolu: Yunanistan Uzunköprü, Gürcistan Canbaz'dır. Kapıkule–Bulgaristan doğrudur."),
        q("Aşağıdaki sınır kapılarından hangisi Ermenistan sınırında bulunmakta ve notlarda kapalı olduğu belirtilmektedir?",
            ["Uzunköprü", "Dilucu", "Sarp", "Akyaka", "Nusaybin"],
            3, "Akyaka Ermenistan sınırındadır ve kapalıdır."),
        q("Aşağıdakilerden hangisi Türkiye'deki dağlık bölgelerden biri olarak verilen alanlardan değildir?",
            ["Hakkâri", "Menteşe", "Doğu Karadeniz", "Çukurova", "Yıldız"],
            3, "Çukurova ovalık bölgedir."),
        q("Hakkâri Dağlık Bölgesi'nin konumuyla ilgili aşağıdakilerden hangisi doğrudur?",
            ["Marmara'nın kuzeybatısında yer alır.", "Ege'nin güneybatısında bulunur.", "Irak ve İran sınırında yer alır.", "Gürcistan sınırına kadar uzanır.", "Adana ve Mersin çevresini kapsar."],
            2, "Hakkâri dağlık bölgesi Irak ve İran sınırındadır."),
        q("Menteşe Dağlık Bölgesi aşağıdaki illerden hangisi ve çevresiyle daha yakından ilişkilidir?",
            ["Kars", "Muğla", "Kırklareli", "Hakkâri", "Konya"],
            1, "Menteşe Muğla ve çevresini kapsar."),
        q("Aşağıdaki dağlık bölge–özellik eşleştirmelerinden hangisi yanlıştır?",
            ["Hakkâri – Irak ve İran sınırı", "Menteşe – Muğla ve çevresi", "Doğu Karadeniz – Gürcistan sınırına kadar", "Hakkâri – Kırklareli", "Yıldız – Kırklareli"],
            3, "Yıldız Kırklareli ile ilişkilidir; Hakkâri değil."),
        q("Aşağıdaki ovalık bölgelerden hangisi Akdeniz Bölgesi'nde, Adana ve Mersin il sınırları içerisinde yer almaktadır?",
            ["Konya Ovası", "Şanlıurfa Ovası", "Çukurova", "İzmir Ovası", "Erzurum Ovası"],
            2, "Çukurova Adana ve Mersin'dedir."),
        q("Konya Ovası ile ilgili aşağıdakilerden hangisi doğrudur?",
            ["Güneydoğu Anadolu'dadır.", "Kıyı Ege'de bulunur.", "İç Anadolu'nun güneyinde yer alır.", "Doğu Karadeniz'de bulunur.", "Akdeniz kıyısında yer alır."],
            2, "Konya Ovası İç Anadolu'nun güneyindedir."),
        q("Aşağıdaki ovalık bölge–konum eşleştirmelerinden hangisi doğrudur?",
            ["Çukurova – İç Anadolu", "Konya Ovası – Güneydoğu Anadolu", "Şanlıurfa – Güneydoğu Anadolu", "İzmir – Doğu Karadeniz", "Şanlıurfa – Marmara"],
            2, "Şanlıurfa ovalık bölgesi Güneydoğu Anadolu'dadır."),
        q("Akdeniz ikliminin Türkiye'de görüldüğü alanlarla ilgili aşağıdakilerden hangisi yanlıştır?",
            ["Akdeniz kıyıları", "Ege kıyıları", "Marmara'nın güney kıyıları", "Marmara'nın batı kıyıları", "Erzurum-Kars platosu"],
            4, "Erzurum-Kars platosu Erzurum-Kars ikliminin alanıdır."),
        q("Karadeniz iklimi aşağıdaki alanların hangisinde etkili olmaktadır?",
            ["Karadeniz kıyıları ve Doğu Karadeniz'in iç kesimleri", "İç Anadolu'nun tamamı ve Güneydoğu Anadolu", "Akdeniz kıyıları ve Ege kıyıları", "Erzurum, Kars ve Ardahan'ın tamamı", "Yalnızca Batı Karadeniz kıyıları"],
            0, "Karadeniz iklimi kıyı şeridinde ve Doğu Karadeniz'in iç kesimlerinde etkilidir."),
        q("İç Anadolu ikliminin görüldüğü alanlarla ilgili aşağıdakilerden hangisi doğrudur?",
            ["Yalnızca İç Anadolu'da görülür.", "İç Anadolu'nun yanı sıra Doğu ve Güneydoğu Anadolu'nun iç kesimlerinde görülür.", "Yalnızca Karadeniz kıyılarında görülür.", "Akdeniz ve Ege kıyılarında görülür.", "Yalnızca Erzurum-Kars çevresinde görülür."],
            1, "İç Anadolu iklimi İç Anadolu ile Doğu ve Güneydoğu'nun iç kesimlerinde görülür."),
        q("Erzurum-Kars iklimi aşağıdaki merkezlerden hangisinin çevresinde görülmez?",
            ["Erzurum", "Kars", "Ardahan", "İzmir", "Hiçbiri"],
            3, "Erzurum-Kars iklimi İzmir çevresinde görülmez."),
        q("Türkiye'de ormanların yaygın olarak görüldüğü alanlar aşağıdakilerin hangisinde birlikte verilmiştir?",
            ["İç Anadolu – Güneydoğu Anadolu – Doğu Anadolu çukur alanları", "Karadeniz kıyıları – yüksek Akdeniz – yüksek Doğu Anadolu", "Akdeniz kıyıları – Ege kıyıları – Marmara kıyıları", "Erzurum-Kars platoları – Konya Ovası – Çukurova", "Yalnızca Karadeniz kıyıları"],
            1, "Orman: Karadeniz kıyıları, yüksek Akdeniz ve yüksek Doğu Anadolu."),
        q("Aşağıdakilerden hangisi ormanlarda görülen başlıca ağaç türlerinden biri değildir?",
            ["Kayın", "Gürgen", "Ladin", "Göknar", "Çoban yastığı"],
            4, "Çoban yastığı bozkır türüdür."),
        q("Aşağıdaki bitki türlerinden hangisinin orman topluluğuyla ilişkilendirilmesi daha uygundur?",
            ["Yavşan otu", "Geven", "Çoban yastığı", "Kayın", "Üçgül"],
            3, "Kayın orman ağacıdır."),
        q("Maki bitki topluluğuyla ilgili aşağıdakilerden hangisi doğrudur?",
            ["Kuraklığın olmadığı yüksek platolarda yaygındır.", "Özellikle Akdeniz ikliminin etkili olduğu kıyı kesimlerinde yaygındır.", "Yalnızca İç Anadolu'da görülür.", "Yalnızca Doğu Anadolu'nun kuzeydoğusunda görülür.", "Karadeniz'in nemli kıyılarının karakteristik bitkisidir."],
            1, "Maki Akdeniz ikliminin etkili olduğu kıyılarda yaygındır."),
        q("Aşağıdakilerden hangisi maki bitki topluluğunun görüldüğü alanlardan biri değildir?",
            ["Akdeniz kıyıları", "Ege kıyıları", "Marmara kıyıları", "Deniz seviyesinden daha yüksek alanlar", "Erzurum-Kars yüksek platoları"],
            4, "Erzurum-Kars yüksek platoları çayır alanıdır."),
        q("Aşağıdakilerden hangisi maki türlerinden biridir?",
            ["Sarıçam", "Ladin", "Zeytin", "Göknar", "Çayır otu"],
            2, "Zeytin maki türüdür."),
        q("Aşağıdaki bitki türlerinden hangisi maki topluluğuyla ilişkilendirilemez?",
            ["Defne", "Mersin", "Kermes meşesi", "Yavşan otu", "Keçiboynuzu"],
            3, "Yavşan otu bozkır türüdür."),
        q("Bozkır bitki topluluğunun Türkiye'de yaygın olduğu alanlar aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Karadeniz kıyıları – Akdeniz kıyıları", "İç Anadolu – Güneydoğu Anadolu – Doğu Anadolu'nun çukur alanları", "Ege kıyıları – Marmara kıyıları", "Erzurum-Kars yüksek platoları", "Yalnızca Doğu Karadeniz"],
            1, "Bozkır İç Anadolu, Güneydoğu ve Doğu Anadolu'nun çukur alanlarındadır."),
        q("Aşağıdakilerden hangisi bozkır bitki topluluğunun başlıca türlerinden biridir?",
            ["Geven", "Ladin", "Kayın", "Kestane", "Göknar"],
            0, "Geven bozkır türüdür."),
        q("Aşağıdaki bitki türlerinden hangileri bozkır topluluğuyla ilişkilendirilebilir?",
            ["Kayın – gürgen – kestane", "Zeytin – defne – mersin", "Geven – yavşan otu – çoban yastığı", "Ladin – göknar – sarıçam", "Yonca – üçgül – ladin"],
            2, "Geven, yavşan otu ve çoban yastığı bozkır türleridir."),
        q("Çayır bitki topluluğunun özellikle geliştiği alan aşağıdakilerden hangisidir?",
            ["Akdeniz kıyıları", "Ege kıyıları", "Erzurum-Kars yüksek platoları", "Güneydoğu Anadolu ovaları", "İç Anadolu'nun alçak ovaları"],
            2, "Çayır Erzurum-Kars yüksek platolarında gelişir."),
        q("Çayırlarla ilgili aşağıdakilerden hangisi doğrudur?",
            ["Yağışın ve nemin fazla olduğu yüksek alanlarda gelişir.", "Yaz kuraklığına dayanıklı çalı topluluğudur.", "Kurak alanlarda yaygınlaşan otsu bitkilerdir.", "Yalnızca Akdeniz kıyılarında görülür.", "Karadeniz kıyılarındaki ormanların yerini alır."],
            0, "Çayırlar yağış ve nemin fazla olduğu yüksek alanlarda gelişir."),
        q("Aşağıdaki bitki topluluğu–alan eşleştirmelerinden hangisi yanlıştır?",
            ["Orman – Karadeniz kıyıları", "Maki – Akdeniz kıyıları", "Bozkır – İç Anadolu", "Çayır – Erzurum-Kars yüksek platoları", "Maki – Erzurum-Kars yüksek platoları"],
            4, "Erzurum-Kars yüksek platolarında çayır görülür, maki değil."),
        q("Aşağıdaki eşleştirmelerden hangisi verilen bitki topluluğunun karakteristik özellikleri bakımından doğrudur?",
            ["Orman – geven, yavşan otu", "Maki – zeytin, defne, mersin", "Bozkır – ladin, göknar", "Çayır – kızılçam, sarıçam", "Orman – çoban yastığı, kekik"],
            1, "Maki: zeytin, defne, mersin."),
        q("Aşağıdaki ifadelerden hangisi yüksek Akdeniz ile kıyı Akdeniz arasındaki bitki örtüsü farklılığını doğru yansıtmaktadır?",
            ["Yüksek kesimlerde maki, kıyılarda orman görülür.", "Yüksek kesimlerde bozkır, kıyılarda çayır görülür.", "Yüksek kesimlerde orman, kıyılarda maki görülür.", "Yüksek kesimlerde çayır, kıyılarda bozkır görülür.", "Her iki kesimde de yalnızca bozkır görülür."],
            2, "Yüksek Akdeniz orman, kıyı Akdeniz maki alanıdır."),
        q("Güneydoğu Anadolu Projesi (GAP) kapsamında aşağıdaki alanlardan hangilerine yönelik yatırımlar yapılmıştır?",
            ["Yalnızca turizm ve madencilik", "Tarım, ulaşım, enerji ve sanayi", "Yalnızca hayvancılık ve kış turizmi", "Yalnızca tarımsal sulama", "Yalnızca taş kömürü işletmeciliği"],
            1, "GAP'ta tarım, ulaşım, enerji ve sanayi yatırımları vardır."),
        q("GAP'ın bölge üzerindeki önemli sonuçlarından biri aşağıdakilerden hangisidir?",
            ["Bölge dışına olan göçün azaltılmasına katkı sağlaması", "Taş kömürü üretiminin artırılması", "Karadeniz'deki sel ve taşkınların önlenmesi", "Kış turizminin geliştirilmesi", "Ereğli Limanı'nın büyütülmesi"],
            0, "GAP bölge dışına göçün azalmasına katkı sağlamıştır."),
        q("Aşağıdakilerden hangisi GAP kapsamında yer alan illerden biri değildir?",
            ["Gaziantep", "Diyarbakır", "Mardin", "Şırnak", "Erzurum"],
            4, "Erzurum DAP ilidir, GAP ili değildir."),
        q("Aşağıdaki illerden hangisi GAP kapsamındaki iller arasında yer alır?",
            ["Kilis", "Kars", "Bayburt", "Tokat", "Karabük"],
            0, "Kilis GAP illerindendir."),
        q("Aşağıdakilerden hangisi GAP kapsamındaki illerin tamamını doğru biçimde veren seçenektir?",
            ["Gaziantep – Kilis – Adıyaman – Diyarbakır – Batman – Siirt – Şanlıurfa – Mardin – Şırnak", "Gaziantep – Kars – Ağrı – Van – Bitlis – Muş – Siirt – Şanlıurfa – Mardin", "Adana – Mersin – Hatay – Gaziantep – Kilis – Şanlıurfa – Mardin – Batman – Siirt", "Diyarbakır – Erzurum – Erzincan – Malatya – Elazığ – Tunceli – Bingöl – Muş – Bitlis", "Samsun – Çorum – Amasya – Tokat – Ordu – Giresun – Trabzon – Rize – Artvin"],
            0, "GAP illeri: Gaziantep, Kilis, Adıyaman, Diyarbakır, Batman, Siirt, Şanlıurfa, Mardin, Şırnak."),
        q("Doğu Anadolu Projesi (DAP) ile ilgili aşağıdakilerden hangisi doğrudur?",
            ["Yeşilırmak Havzası'nda uygulanmaktadır.", "Temel olarak taş kömürü işletmeciliğine yöneliktir.", "Yalnızca tarımsal sulamayı amaçlamaktadır.", "Türkiye'nin yüz ölçümü bakımından en büyük bölgesel kalkınma projesidir.", "Temel amacı Karadeniz'deki taşkınları önlemektir."],
            3, "DAP yüz ölçümü en büyük bölgesel kalkınma projesidir."),
        q("DAP kapsamında özellikle aşağıdaki ekonomik faaliyetlerden hangilerinin geliştirilmesi amaçlanmaktadır?",
            ["Tarım, hayvancılık ve kış turizmi", "Taş kömürü, demir ve bakır", "Deniz turizmi, balıkçılık ve limancılık", "Sanayi, ticaret ve dış satım", "Ormancılık, çay ve fındık"],
            0, "DAP: tarım, hayvancılık ve kış turizmi."),
        q("Aşağıdakilerden hangisi DAP kapsamındaki illerden biri değildir?",
            ["Erzurum", "Van", "Malatya", "Samsun", "Tunceli"],
            3, "Samsun YGHP ilidir, DAP ili değildir."),
        q("DAP kapsamında yer alan illerle ilgili aşağıdaki bilgilerden hangisi doğrudur?",
            ["Sivas projeye sonradan eklenmiştir.", "Samsun projeye sonradan eklenmiştir.", "Karabük projeye sonradan eklenmiştir.", "Çorum projeye sonradan eklenmiştir.", "Amasya projeye sonradan eklenmiştir."],
            0, "Sivas DAP'a sonradan eklenmiştir."),
        q("Aşağıdakilerden hangisi DAP kapsamındaki illerden biri olarak verilmiştir?",
            ["Ardahan", "Amasya", "Bartın", "Zonguldak", "Konya"],
            0, "Ardahan DAP ilidir."),
        q("Doğu Karadeniz Projesi (DOKAP) ile ilgili aşağıdakilerden hangisi doğrudur?",
            ["Konya Ovası merkezlidir.", "Doğu Karadeniz'deki ekonomik geri kalmışlığı azaltmayı amaçlar.", "Taş kömürü yataklarının işletilmesine yöneliktir.", "Güneydoğu Anadolu'daki göçü azaltmayı temel amaç edinmiştir.", "Yalnızca tarımsal sulama amacı taşır."],
            1, "DOKAP Doğu Karadeniz'de ekonomik geri kalmışlığı azaltmayı amaçlar."),
        q("DOKAP'ın uygulanmasında aşağıdaki sorunlardan hangisinin giderilmesine özellikle önem verilmektedir?",
            ["Kuraklık", "Engebeli yapı nedeniyle kamu hizmetlerinin yetersizliği", "Taş kömürü rezervlerinin azalması", "Sınır kapılarının yetersizliği", "Çölleşme"],
            1, "DOKAP engebeli yapıdan kaynaklanan kamu hizmeti yetersizliğine yöneliktir."),
        q("Aşağıdaki illerden hangisi DOKAP kapsamında yer alan iller arasında verilenlerden biridir?",
            ["Bayburt", "Şanlıurfa", "Mardin", "Kars", "Konya"],
            0, "Bayburt DOKAP kapsamında verilmiştir."),
        q("Konya Ovası Projesi (KOP) ile ilgili aşağıdakilerden hangisi doğrudur?",
            ["Temel olarak taş kömürü işletmeciliğine yöneliktir.", "Yeşilırmak Havzası'nda uygulanır.", "Merkezinde Konya Ovası bulunur.", "Doğu Anadolu'da uygulanır.", "Temel amacı sel ve taşkınları önlemektir."],
            2, "KOP'un merkezinde Konya Ovası vardır."),
        q("Notlara göre Türkiye'nin ikinci tarımsal sulama projesi aşağıdakilerden hangisidir?",
            ["GAP", "DAP", "DOKAP", "KOP", "ZBK"],
            3, "KOP ikinci tarımsal sulama projesidir."),
        q("Aşağıdaki proje–amaç eşleştirmelerinden hangisi yanlıştır?",
            ["GAP – Tarım, enerji, ulaşım ve sanayi", "DAP – Tarım, hayvancılık ve kış turizmi", "DOKAP – Ekonomik geri kalmışlığı azaltma", "KOP – Tarımsal sulama", "ZBK – Sel ve taşkınları önleme"],
            4, "Sel-taşkın YGHP'nin amacıdır; ZBK madencilik projesidir."),
        q("Yeşilırmak Havza Gelişim Projesi'nin (YGHP) kapsadığı iller aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Gaziantep – Kilis – Şanlıurfa – Mardin", "Erzurum – Kars – Ağrı – Iğdır", "Zonguldak – Bartın – Karabük – Bolu", "Samsun – Çorum – Amasya – Tokat", "Konya – Karaman – Aksaray – Niğde"],
            3, "YGHP: Samsun, Çorum, Amasya, Tokat."),
        q("YGHP'nin temel amaçlarından biri aşağıdakilerden hangisidir?",
            ["Taş kömürü yataklarını işletmek", "Kış turizmini geliştirmek", "Sel ve taşkınları önlemek", "Bölge dışına göçü artırmak", "Tarımsal sulamayı tamamen ortadan kaldırmak"],
            2, "YGHP'nin temel amacı sel ve taşkınları önlemektir."),
        q("Bir öğrencinin YGHP'nin illerini hatırlamak için «Sel taştı, toka-t» kodlamasını kullandığı bilinmektedir. Bu kodlamadaki iller aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Samsun – Çorum – Amasya – Tokat", "Sivas – Çorum – Ardahan – Tokat", "Samsun – Çankırı – Amasya – Kars", "Sinop – Çorum – Amasya – Tokat", "Samsun – Çorum – Artvin – Trabzon"],
            0, "Sel-taştı-toka-t: Samsun, Çorum, Amasya, Tokat."),
        q("Zonguldak-Bartın-Karabük (ZBK) Projesi'nin temel özelliklerinden biri aşağıdakilerden hangisidir?",
            ["Tarımsal sulamaya dayanması", "Madenciliğe ve taş kömürüne dayalı olması", "Sel ve taşkınları önlemeye yönelik olması", "Kış turizmini geliştirmesi", "Güneydoğu Anadolu'da uygulanması"],
            1, "ZBK taş kömürü ve madenciliğe dayalıdır."),
        q("ZBK Projesi kapsamında aşağıdakilerden hangisinin yapılması öngörülmektedir?",
            ["Ereğli Limanı'nın büyütülmesi", "GAP sulama kanallarının genişletilmesi", "Kars kış turizm merkezlerinin geliştirilmesi", "Yeşilırmak'ın taşkın yatağının değiştirilmesi", "Konya Ovası'nda yeni sınır kapısı açılması"],
            0, "ZBK kapsamında Ereğli Limanı'nın büyütülmesi vardır."),
        q("Aşağıdakilerden hangisi ZBK Projesi'nin amaçları arasında yer almaz?",
            ["Taş kömürü yataklarının işletilmesi", "Madenlerin etkin ve verimli kullanılması", "Özel sektöre yeni yatırım alanları açılması", "Ereğli Limanı'nın büyütülmesi", "Erzurum-Kars çevresinde kış turizmini geliştirmek"],
            4, "Kış turizmi DAP'ın amacıdır."),
        q("Notlara göre madene dayalı tek bölgesel kalkınma projesi aşağıdakilerden hangisidir?",
            ["GAP", "ZBK", "DOKAP", "KOP", "DAP"],
            1, "Madene dayalı tek proje ZBK'dır."),
        q("Aşağıdaki bölgesel kalkınma projelerinden hangisi ile ilgili verilen anahtar kavram yanlıştır?",
            ["GAP – Enerji", "DAP – Hayvancılık", "DOKAP – Engebeli arazi", "KOP – Tarımsal sulama", "YGHP – Taş kömürü"],
            4, "YGHP sel-taşkın ile ilişkilidir; taş kömürü ZBK'dır."),
        q("Aşağıdaki proje–alan eşleştirmelerinden hangisi doğrudur?",
            ["GAP – Doğu Anadolu", "DAP – Güneydoğu Anadolu", "DOKAP – Doğu Karadeniz", "KOP – Zonguldak-Bartın-Karabük", "ZBK – Konya Ovası"],
            2, "DOKAP Doğu Karadeniz'de uygulanır."),
        q("Aşağıdaki projelerden hangisinin temel özelliği diğerlerinden farklıdır?",
            ["GAP", "DAP", "DOKAP", "KOP", "ZBK"],
            4, "ZBK madencilik ve taş kömürüne dayalı tek projedir."),
        q("Aşağıdaki eşleştirmelerden hangisi tamamen doğrudur?",
            ["GAP – Güneydoğu Anadolu – Tarım/Enerji", "DAP – Doğu Anadolu – Hayvancılık/Kış turizmi", "DOKAP – Doğu Karadeniz – Engebeli arazi", "KOP – Konya – Tarımsal sulama", "Hepsi"],
            4, "A–D seçeneklerinin tümü doğrudur."),
        q("Aşağıdaki projelerden hangisi Yeşilırmak Havzası ile ilişkilidir?",
            ["GAP", "DAP", "DOKAP", "YGHP", "ZBK"],
            3, "YGHP Yeşilırmak Havza Gelişim Projesi'dir."),
        q("Aşağıdaki proje ve özelliklerinden hangisi eşleştirilemez?",
            ["GAP → Bölge dışına göçün azaltılmasına katkı", "DAP → Tarım ve hayvancılığın geliştirilmesi", "DOKAP → Engebeli arazi nedeniyle hizmet yetersizliği", "ZBK → Sel ve taşkınların önlenmesi", "KOP → Tarımsal sulama"],
            3, "Sel-taşkın YGHP'ye aittir."),
        q("Türkiye'deki bölgesel kalkınma projeleriyle ilgili;\nI. GAP, Güneydoğu Anadolu'da uygulanmaktadır.\nII. DAP, Doğu Anadolu'da uygulanmaktadır.\nIII. DOKAP, Doğu Karadeniz'de uygulanmaktadır.\nIV. KOP'un merkezinde Konya Ovası bulunmaktadır.\nV. ZBK, taş kömürü ve madencilikle ilişkilidir.\nifadelerinden hangileri doğrudur?",
            ["I ve II", "II ve III", "I, II ve III", "I, II, III ve IV", "I, II, III, IV ve V"],
            4, "Beş ifade de doğrudur."),
        q("Türkiye'nin sınırları, uç noktaları ve sınır kapıları birlikte değerlendirildiğinde aşağıdaki bilgilerden hangisi doğrudur?",
            ["En uzun sınır Nahçıvan ile, en kısa sınır Suriye ile oluşturulmuştur.", "En yeni sınır Hatay'ın 1939'da Türkiye'ye katılmasıyla oluşmuştur.", "Türkiye'nin en doğu noktası Çanakkale-Gökçeada'dır.", "İran sınırında Habur Sınır Kapısı bulunur.", "Bulgaristan sınırında Sarp Sınır Kapısı bulunur."],
            1, "En yeni sınır Hatay'ın 1939'da katılmasıyla oluşmuştur."),
        q("Bir öğrenci Türkiye'nin bitki bölgelerini çalışırken aşağıdaki eşleştirmeleri yapmıştır:\nI. Karadeniz → Orman\nII. Akdeniz kıyıları → Maki\nIII. İç Anadolu → Bozkır\nIV. Erzurum-Kars → Çayır\nBu eşleştirmelerden hangileri doğrudur?",
            ["Yalnız I", "I ve II", "II ve III", "I, II ve III", "I, II, III ve IV"],
            4, "Dört eşleştirme de doğrudur."),
        q("Aşağıdakilerden hangisi Türkiye'nin jeopolitik sorunları ile bölgesel kalkınma projelerinin ortak özelliği değildir?",
            ["Türkiye'nin belirli bölgeleriyle ilişkilidir.", "Ekonomik veya siyasi sonuçlar doğurabilir.", "Türkiye'nin coğrafi konumuyla ilişkilendirilebilir.", "Her biri doğrudan sınır kapılarının açılması amacıyla uygulanmaktadır.", "Türkiye'nin bölgesel özelliklerinin bilinmesini gerektirir."],
            3, "Kalkınma projeleri sınır kapısı açmak için uygulanmaz."),
        q("Aşağıdaki seçeneklerin hangisinde bir sınır kapısı, bağlı olduğu ülke ve kalkınma projesi doğru eşleştirilmiştir?",
            ["Gürbulak – Gürcistan – DOKAP", "Sarp – İran – DAP", "Kapıkule – Irak – ZBK", "Habur – Irak – GAP", "Dilucu – Suriye – KOP"],
            3, "Habur Irak kapısıdır; Irak Güneydoğu komşusudur ve GAP Güneydoğu'dadır."),
        q("Türkiye'nin doğal ve beşerî özellikleriyle ilgili aşağıdaki eşleştirmelerden hangisi doğrudur?",
            ["Erzurum-Kars – Çayır – DAP", "Konya Ovası – Maki – DOKAP", "Zonguldak – Çayır – KOP", "Çukurova – Bozkır – ZBK", "Karadeniz kıyıları – Maki – GAP"],
            0, "Erzurum-Kars çayır alanıdır ve DAP kapsamındadır."),
        q("Aşağıdaki ifadelerden hangisi diğerlerinden farklı bir bölgesel kalkınma projesini tanımlamaktadır?",
            ["Tarımsal sulama", "Konya Ovası", "KOP", "İç Anadolu", "Taş kömürü işletmeciliği"],
            4, "A–D KOP'u tanımlar; taş kömürü ZBK'dır."),
        q("Bir sınav sorusunda aşağıdaki bilgiler verilmiştir:\n• Türkiye'nin en işlek sınır kapısıdır.\n• Avrupa'ya giden en kısa yol üzerindedir.\n• Bulgaristan sınırında bulunur.\n• Demir yolu bağlantısı vardır.\nBu bilgiler aşağıdaki sınır kapılarından hangisini tanımlamaktadır?",
            ["İpsala", "Sarp", "Kapıkule", "Habur", "Gürbulak"],
            2, "Kapıkule bu dört özelliği birden karşılar."),
        q("Bir başka soruda;\n• Tarım\n• Hayvancılık\n• Kış turizmi\n• Doğu Anadolu\n• Sivas'ın sonradan eklenmesi\nbilgileri verilmiştir. Bu bilgiler aşağıdaki projelerden hangisine aittir?",
            ["GAP", "DAP", "DOKAP", "KOP", "ZBK"],
            1, "Bu özellikler DAP'a aittir."),
        q("Bir bölgesel kalkınma projesiyle ilgili olarak «engebeli arazi, kamu hizmetlerinin yetersizliği ve ekonomik geri kalmışlığın azaltılması» ifadeleri kullanılmıştır. Bu proje aşağıdakilerden hangisidir?",
            ["GAP", "DAP", "DOKAP", "KOP", "YGHP"],
            2, "Bu ifadeler DOKAP'ı tanımlar."),
        q("Bir proje için;\n• Zonguldak\n• Bartın\n• Karabük\n• Taş kömürü\n• Ereğli Limanı\n• Madencilik\nbilgileri verilmiştir. Bu proje aşağıdakilerden hangisidir?",
            ["DAP", "DOKAP", "KOP", "YGHP", "ZBK"],
            4, "ZBK: Zonguldak–Bartın–Karabük, taş kömürü ve Ereğli Limanı.")
    ];
})();
