// sorular/cografya-23.js
window.cografya_23_sorulari = (function () {
    var L = ["A", "B", "C", "D", "E"];
    function q(stem, opts, i, exp) {
        return {
            question: stem,
            options: opts.map(function (t, n) { return L[n] + ") " + t; }),
            correctAnswerIndex: i,
            explanation: exp
        };
    }
    return [
        q("Türkiye'de sanayi faaliyetlerinin en fazla geliştiği bölge Marmara Bölgesi'dir. Bu durum üzerinde aşağıdakilerden hangisinin etkili olduğu söylenemez?",
            ["Ulaşım olanaklarının gelişmiş olması", "Sermaye birikiminin fazla olması", "Teknolojik kullanımının yaygın olması", "Büyük pazarlara yakın olması", "Maden çeşitliliğinin diğer tüm bölgelere göre fazla olması"],
            4, "Marmara ulaşım, sermaye, teknoloji, Ar-Ge ve pazarla öne çıkar. Maden çeşitliliği Doğu Anadolu'nun özelliğidir."),
        q("Marmara Bölgesi'nin Türkiye'nin sanayileşmesinde öne çıkmasında;\nI. ulaşım olanaklarının gelişmiş olması,\nII. sermaye birikiminin fazla olması,\nIII. Ar-Ge faaliyetlerinin gelişmiş olması,\nIV. büyük pazarlara yakın olması\nözelliklerinden hangileri etkili olmuştur?",
            ["Yalnız I", "I ve II", "II ve III", "I, II ve IV", "I, II, III ve IV"],
            4, "Dört özellik de Marmara'nın sanayileşme faktörlerindendir."),
        q("Doğu Anadolu Bölgesi'nde sanayi faaliyetlerinin geliştirilmesinde aşağıdakilerden hangisinin etkili olduğu söylenemez?",
            ["Maden çeşitliliğinin fazla olması", "Tarımsal üretimin bulunması", "Hayvansal üretimin fazla olması", "Ucuz iş gücünün bulunması", "Büyük tüketim pazarlarının yoğunlaşması"],
            4, "Büyük pazarlar Marmara'nın avantajıdır; Doğu Anadolu'da sanayiyi destekleyen temel faktörler arasında yer almaz."),
        q("Doğu Anadolu Bölgesi'nde sanayinin gelişmesini destekleyen özelliklerden biri de geniş yerleşim alanlarının bulunmasıdır. Buna göre aşağıdakilerden hangisi Doğu Anadolu Bölgesi'nin sanayileşme faktörleri arasında gösterilemez?",
            ["Ucuz iş gücü", "Maden çeşitliliği", "Tarımsal üretim", "Hayvansal üretim", "Ar-Ge faaliyetlerinin Türkiye'de en yüksek düzeyde olması"],
            4, "En yüksek Ar-Ge Marmara'dadır."),
        q("Aşağıdakilerden hangisi Marmara Bölgesi ile Doğu Anadolu Bölgesi'nin sanayileşme süreçlerinde ortak bir faktör olarak gösterilebilir?",
            ["Gelişmiş Ar-Ge faaliyetleri", "Büyük pazarlara yakınlık", "Ucuz iş gücü", "Hammadde kaynaklarının varlığı", "Sermaye fazlalığı"],
            3, "Doğu Anadolu'da maden/tarım-hayvancılık hammaddesi; Marmara'da da sanayi hammaddesi ve tarımsal işleme (yağ, tekstil vb.) vardır. Ar-Ge, pazar ve sermaye Marmara'ya; ucuz iş gücü Doğu Anadolu'ya özgüdür."),
        q("Aşağıdaki eşleştirmelerden hangisi yağ sanayisinin kuruluş yerleri bakımından doğrudur?",
            ["Ayçiçeği yağı — Aydın", "Zeytinyağı — Edirne", "Mısırözü yağı — Adana", "Ayçiçeği yağı — İzmir", "Mısırözü yağı — Balıkesir"],
            2, "Mısırözü yağı Adana'dadır. Ayçiçeği Tekirdağ-Edirne; zeytin Aydın-İzmir-Balıkesir-Bursa."),
        q("Türkiye'de ayçiçeği yağı sanayisinin Trakya'da gelişmesinde aşağıdakilerden hangisi öncelikle etkili olmuştur?",
            ["Ayçiçeğinin bölgede yetiştirilmesi", "Maden çeşitliliğinin fazla olması", "Liman sayısının fazla olması", "Hayvancılığın gelişmiş olması", "Enerji kaynaklarının çeşitliliği"],
            0, "Yağ sanayisi hammaddenin (ayçiçeği) Trakya'da yetişmesine bağlıdır."),
        q("Aşağıdaki sanayi kolu–yer eşleştirmelerinden hangisi yanlıştır?",
            ["Zeytinyağı — Aydın", "Ayçiçeği yağı — Tekirdağ", "Mısırözü yağı — Adana", "Zeytinyağı — İzmir", "Ayçiçeği yağı — Antalya"],
            4, "Ayçiçeği yağı Trakya'dadır (Tekirdağ, Edirne); Antalya bu kolun kuruluş yeri değildir."),
        q("Aşağıdakilerden hangisi zeytinyağı sanayisinin yoğunlaştığı merkezlerden biri değildir?",
            ["Aydın", "İzmir", "Edirne", "Bursa", "Balıkesir"],
            2, "Edirne ayçiçeği yağı merkezidir; zeytinyağı Aydın, İzmir, Balıkesir, Bursa'dadır."),
        q("Unlu mamuller sanayisinin kuruluş yerleri arasında aşağıdakilerden hangisi bulunur?",
            ["Rize", "Konya", "Batman", "Artvin", "Kırşehir"],
            1, "Unlu mamuller: Konya, Eskişehir, Ankara."),
        q("Aşağıdaki merkezlerden hangisinde et kombinalarının bulunduğu belirtilmiştir?",
            ["Erzurum", "Rize", "Tekirdağ", "Giresun", "Edirne"],
            0, "Et kombinaları: Erzurum, Kars, Konya, İzmir."),
        q("Et kombinalarının kuruluş yerleri arasında;\nI. Erzurum\nII. Kars\nIII. Konya\nIV. İzmir\nmerkezlerinden hangileri bulunmaktadır?",
            ["Yalnız I", "I ve II", "II ve III", "I, II ve III", "I, II, III ve IV"],
            4, "Dört merkez de et kombinası yeri olarak verilmiştir."),
        q("Türkiye'deki çay fabrikalarının tamamının Doğu Karadeniz Bölgesi'nde bulunması aşağıdakilerden hangisiyle öncelikle açıklanabilir?",
            ["Çay tarımının bu bölgede yapılması", "Bölgede sermaye birikiminin fazla olması", "Tüketici nüfusunun fazla olması", "Ulaşım ağlarının Türkiye'nin en gelişmiş ağı olması", "Maden çeşitliliğinin fazla olması"],
            0, "Çay hammaddesi Doğu Karadeniz'de yetiştiği için fabrikalar oradadır."),
        q("Aşağıdaki merkezlerden hangisi çay fabrikalarının bulunduğu Doğu Karadeniz merkezlerinden biri değildir?",
            ["Rize", "Trabzon", "Artvin", "Giresun", "Rize (çay tarımı alanı)"],
            3, "Çay fabrikaları Rize, Trabzon ve Artvin'dedir. Giresun kâğıt (Aksu) ile anılır."),
        q("Orman ürünleri sanayisiyle ilgili aşağıdaki bilgilerden hangisi doğrudur?",
            ["Kereste ve tomruk fabrikaları Ege'de yoğunlaşmıştır.", "Kâğıt fabrikalarının tamamı Marmara'da toplanmıştır.", "Giresun'da Aksu kâğıt sanayisi bulunmaktadır.", "Kastamonu'da Taşköprü kâğıt sanayisi bulunmaz.", "Orman ürünleri sanayisi hammadde kaynaklarından bağımsızdır."],
            2, "Kâğıt: Giresun-Aksu ve Kastamonu-Taşköprü. Kereste-tomruk Karadeniz'de yoğunlaşır."),
        q("Aşağıdakilerden hangisi orman ürünleri sanayisi kapsamında verilen merkezlerden biridir?",
            ["Şırnak", "Adana", "Kırıkkale", "Kastamonu", "Kırşehir"],
            3, "Kastamonu (Taşköprü) kâğıt sanayisidir."),
        q("Deniz mahsulleri işleme tesislerinin bulunduğu merkezler arasında aşağıdakilerden hangisi yer alır?",
            ["Çanakkale", "Konya", "Kütahya", "Ankara", "Kırıkkale"],
            0, "Deniz mahsulleri: Çanakkale ve Trabzon."),
        q("Aşağıdaki sanayi kolu–merkez eşleştirmelerinden hangisi yanlıştır?",
            ["Deniz mahsulleri — Çanakkale", "Deniz mahsulleri — Trabzon", "Tuğla-kiremit — Çorum", "Tuğla-kiremit — Eskişehir", "Tuğla-kiremit — Rize"],
            4, "Tuğla-kiremit Çorum ve Eskişehir'dedir; Rize çay ile anılır."),
        q("Aşağıdakilerden hangisi seramik sanayisinin kuruluş merkezlerinden biridir?",
            ["Kütahya", "Erzurum", "Kars", "Kırıkkale", "Şırnak"],
            0, "Seramik: Kütahya, Çanakkale, İzmir."),
        q("Aşağıdaki sanayi kolu–merkez eşleştirmelerinden hangisi doğrudur?",
            ["Tuğla-kiremit — Artvin", "Pamuklu dokuma — Rize", "Petro-kimya — Kars", "Seramik — Kütahya", "Çay — Konya"],
            3, "Kütahya seramik merkezidir."),
        q("Pamuklu dokuma sanayisinin kuruluş yerleri arasında aşağıdakilerden hangisi bulunur?",
            ["Adana", "Rize", "Kars", "Kastamonu", "Kütahya"],
            0, "Pamuklu dokuma: Adana, İzmir, Denizli."),
        q("Aşağıdakilerden hangisi pamuklu dokuma sanayisinin verilen merkezlerinden biri değildir?",
            ["Adana", "İzmir", "Denizli", "Rize", "Adana (Çukurova)"],
            3, "Rize çay bölgesidir; pamuklu dokuma Adana, İzmir ve Denizli'dedir."),
        q("Petro-kimya sanayisiyle ilgili aşağıdakilerden hangisi doğrudur?",
            ["Batman Rafinerisi, pamuk üretimine bağlı olarak kurulmuştur.", "Batman Rafinerisi, tüketim merkezlerine bağlı olarak kurulmuştur.", "Petro-kimya tesisleri yalnızca kıyı bölgelerinde bulunur.", "Batman Rafinerisi, hammaddeye bağlı olarak kurulmuştur.", "Petro-kimya sanayisinin temel hammaddesi çaydır."],
            3, "Batman, petrole (hammaddeye) bağlı kurulan tek petro-kimya tesisidir."),
        q("Bir sanayi tesisinin kuruluş yerinin belirlenmesinde hammaddenin çabuk bozulabilir olması önemli bir etkendir. Buna göre aşağıdaki sanayi kollarından hangisinin kuruluşunda bu durum daha belirleyicidir?",
            ["Savunma", "Otomotiv", "Uçak", "Şeker", "Gemi yapımı"],
            3, "Şeker pancarı çabuk bozulduğu için fabrikalar üretim alanlarına yakın kurulur."),
        q("Şeker fabrikalarının üretim alanlarına yakın kurulmasının temel nedeni aşağıdakilerden hangisidir?",
            ["Şeker pancarının çabuk bozulması", "Şekerin ağır bir tüketim malı olması", "Fabrikaların yalnızca kıyıda kurulabilmesi", "Şeker pancarının yalnızca Karadeniz'de yetişmesi", "Şeker üretiminde deniz ulaşımının zorunlu olması"],
            0, "Pancar çabuk bozulur; bu yüzden tarım bölgelerine yakın işlenir."),
        q("Şeker fabrikalarının Türkiye'de en fazla bulunduğu bölge aşağıdakilerden hangisidir?",
            ["Marmara", "Ege", "Orta Anadolu", "Doğu Karadeniz", "Güneydoğu Anadolu"],
            2, "En fazla Orta Anadolu'dadır."),
        q("Aşağıdaki sanayi kollarından hangisinin kuruluş yerleri arasında Kayseri, Ankara ve İzmir bulunmaktadır?",
            ["Mobilya", "İlaç", "Uçak", "Lastik", "Tekstil"],
            0, "Mobilya: Kayseri, Ankara, İzmir."),
        q("İstanbul ve Tekirdağ aşağıdaki sanayi kollarından hangisinin kuruluş merkezleri arasında verilmiştir?",
            ["Lastik", "Uçak", "Savunma sanayi", "İlaç", "Mobilya"],
            3, "İlaç: İstanbul ve Tekirdağ."),
        q("Aşağıdaki eşleştirmelerden hangisi yanlıştır?",
            ["Uçak — Ankara", "Uçak — Eskişehir", "İlaç — İstanbul", "İlaç — Tekirdağ", "Uçak — Kütahya"],
            4, "Uçak Ankara ve Eskişehir'dedir; Kütahya seramik ile anılır."),
        q("Halı-kilim sanayisinin kuruluş yerleri arasında aşağıdakilerden hangisi bulunur?",
            ["Erzurum", "Rize", "Batman", "Uşak", "Trabzon"],
            3, "Halı-kilim: Uşak, Manisa, Denizli, Hereke."),
        q("Aşağıdaki merkezlerden hangisi halı-kilim sanayisiyle ilişkilendirilen merkezlerden biridir?",
            ["Tuzla", "Gürbulak", "Hereke", "Pendik", "Taşköprü"],
            2, "Hereke halı-kilim; Tuzla-Pendik gemi; Taşköprü kâğıt; Gürbulak sınır kapısıdır."),
        q("Lastik sanayisinin kuruluş merkezleri arasında aşağıdakilerden hangisi bulunmaktadır?",
            ["Kırşehir", "Rize", "Aydın", "Erzurum", "Giresun"],
            0, "Lastik: Kırşehir ve Adapazarı."),
        q("Kırıkkale, Ankara ve Eskişehir aşağıdaki sanayi kollarından hangisiyle ilişkilendirilmektedir?",
            ["Zeytinyağı sanayisi", "Tekstil sanayisi", "Çay sanayisi", "Savunma sanayisi", "Seramik sanayisi"],
            3, "Savunma: Kırıkkale, Ankara, Eskişehir."),
        q("İstanbul'da Tuzla, Haliç ve Pendik çevresinde gelişen sanayi kolu aşağıdakilerden hangisidir?",
            ["Uçak sanayisi", "Gemi yapımı", "Savunma sanayisi", "Otomotiv sanayisi", "Petro-kimya sanayisi"],
            1, "Gemi yapımı Tuzla, Haliç ve Pendik'tedir."),
        q("Aşağıdaki sanayi kollarından hangisinin İstanbul'da geliştiği belirtilmiştir?",
            ["Seramik", "Çay", "Şeker", "Tekstil", "Tuğla-kiremit"],
            3, "Tekstil (ve tütün) İstanbul'dadır."),
        q("Türkiye'de verilen bilgilere göre tütün sanayisinin kuruluş merkezi aşağıdakilerden hangisidir?",
            ["Konya", "İstanbul", "Erzurum", "Kütahya", "Adana"],
            1, "Tütün sanayisi İstanbul'dadır."),
        q("Türkiye'nin en büyük sanayi kolu olarak belirtilen ve \"sanayinin lokomotifi\" şeklinde nitelendirilen sektör aşağıdakilerden hangisidir?",
            ["Tekstil", "Otomotiv", "Demir-çelik", "Petro-kimya", "Gıda"],
            1, "Otomotiv sanayinin lokomotifi ve en büyük sanayi koludur."),
        q("Türkiye'nin dış satımında sanayi ürünlerinin payı yaklaşık olarak aşağıdakilerden hangisidir?",
            ["%2", "%4", "%25", "%75", "%94"],
            4, "İhracatta sanayi ürünleri yaklaşık %94'tür."),
        q("Türkiye'nin ihracatında tarım ürünlerinin payı yaklaşık olarak aşağıdakilerden hangisidir?",
            ["%2", "%4", "%10", "%25", "%94"],
            1, "Tarım ürünleri yaklaşık %4'tür."),
        q("Türkiye'nin ihracatında madenlerin payı yaklaşık olarak aşağıdakilerden hangisidir?",
            ["%2", "%4", "%10", "%25", "%94"],
            0, "Madenler yaklaşık %2'dir."),
        q("Aşağıdakilerden hangisi Türkiye'nin ihraç ettiği sanayi ürünleri arasında gösterilen ürünlerden biri değildir?",
            ["Otomotiv", "Tekstil", "Demir-çelik ürünleri", "Beyaz eşya", "Doğal gaz"],
            4, "Doğal gaz ithalat kalemidir; sanayi ihracatı otomotiv, tekstil, demir-çelik ve beyaz eşyadır."),
        q("Aşağıdakilerden hangisi Türkiye'nin ihracatında yer alan tarım ürünlerinden biri değildir?",
            ["İncir", "Fındık", "Kayısı", "Üzüm", "Bakır"],
            4, "Bakır maden ihracatındadır; tarım ürünleri incir, fındık, kayısı, üzüm, tütün, pamuktur."),
        q("Türkiye'nin ihracatında yer alan madenler arasında aşağıdakilerden hangisi bulunmaktadır?",
            ["Pamuk", "Çay", "Bor", "Fındık", "Üzüm"],
            2, "İhraç madenler: demir cevheri, krom, bakır, bor."),
        q("Türkiye'nin ihracatında önde gelen ülkelerin sıralaması aşağıdakilerden hangisinde doğru verilmiştir?",
            ["Çin – Almanya – Rusya – ABD", "Almanya – İngiltere – ABD – İtalya", "ABD – Almanya – İngiltere – İtalya", "Almanya – Çin – Rusya – İngiltere", "Rusya – Çin – Almanya – ABD"],
            1, "İhracat: Almanya, İngiltere, ABD, İtalya. Çin ithalatta birincidir."),
        q("Türkiye'nin ithalatında aşağıdakilerden hangisinin önemli bir yer tuttuğu belirtilmiştir?",
            ["İncir", "Fındık", "Petrol ve doğal gaz", "Kayısı", "Üzüm"],
            2, "İthalatta petrol ve doğal gaz (mineral yağlar ve yakıtlar) öne çıkar."),
        q("Aşağıdakilerden hangisi Türkiye'nin ithalat kalemlerinden biri olarak verilmiştir?",
            ["Bor", "Tütün", "Sanayi yatırım malları", "Krom", "Pamuk"],
            2, "Sanayi yatırım malları (makine, teçhizat) ithalat kalemidir. Tütün, bor, krom, pamuk ihracat tarafındadır."),
        q("Türkiye'nin ithalatında yer alan sanayi yatırım malları arasında aşağıdakilerden hangisi bulunmaktadır?",
            ["Makine ve teçhizat", "Fındık ve incir", "Krom ve bakır", "Pamuk ve üzüm", "Çay ve tütün"],
            0, "Yatırım malları makine ve teçhizattır."),
        q("Türkiye'nin ithalatında aşağıdakilerden hangisinin yer aldığı belirtilmiştir?",
            ["Fındık", "İncir", "Kıymetli taşlar", "Kayısı", "Bor"],
            2, "Kıymetli taşlar (altın, mücevher) ithalat kalemidir."),
        q("Türkiye'nin ithalatında önde gelen ülkelerin sıralaması aşağıdakilerden hangisidir?",
            ["Almanya – Çin – ABD – Rusya", "Çin – Almanya – Rusya – ABD", "Rusya – Çin – Almanya – ABD", "ABD – Rusya – Almanya – Çin", "Çin – Rusya – ABD – Almanya"],
            1, "İthalat: Çin, Almanya, Rusya, ABD."),
        q("Türkiye'nin dış ticaretiyle ilgili;\nI. İhracatta sanayi ürünleri önemli bir paya sahiptir.\nII. İhracatta tarım ürünlerinin payı %4'tür.\nIII. İthalatta petrol ve doğal gaz önemli kalemlerdendir.\nIV. İthalatta Çin ilk sıradadır.\nyargılarından hangileri doğrudur?",
            ["Yalnız I", "I ve II", "II ve III", "I, III ve IV", "I, II, III ve IV"],
            4, "Dört yargı da notlarla uyumludur."),
        q("İran'ın Karadeniz üzerinden dünya pazarlarına ulaşmasında kullanılan transit ticaret güzergâhı aşağıdakilerden hangisidir?",
            ["Habur – Kapıkule", "Gürbulak – Trabzon", "Kapıkule – Habur", "Cilvegözü – Mersin", "Sarp – Samsun"],
            1, "Gürbulak (Ağrı) – Trabzon Limanı İran'ın Karadeniz kapısıdır."),
        q("Gürbulak – Trabzon transit ticaret yoluyla ilgili aşağıdakilerden hangisi doğrudur?",
            ["Irak ile Bulgaristan arasındaki ticareti sağlar.", "İran'ın Karadeniz'e ulaşmasını sağlayan güzergâhlardan biridir.", "Yalnızca Türkiye'nin iç ticaretinde kullanılır.", "Türkiye'nin batı sınırından başlayıp doğu sınırında sona erer.", "Avrupa ile Orta Doğu arasındaki en uzun kara yoludur."],
            1, "Irak–Avrupa hattı Habur–Kapıkule'dir. Gürbulak–Trabzon İran'ı Karadeniz'e bağlar."),
        q("Gürbulak – Trabzon transit ticaret yolunda aşağıdaki sınır kapılarından hangisi kullanılmaktadır?",
            ["Habur", "Kapıkule", "Gürbulak", "Sarp", "Cilvegözü"],
            2, "Doğu kapısı Ağrı'daki Gürbulak'tır."),
        q("İran'dan gelen ticari yüklerin Gürbulak'tan Türkiye'ye girerek Trabzon Limanı'na ulaştırılmasının temel amacı aşağıdakilerden hangisidir?",
            ["Türkiye'nin petrol ihtiyacını karşılamak", "Türkiye'nin iç kesimlerine tarım ürünü taşımak", "Avrupa ülkelerinden İran'a kara yoluyla ulaşmak", "İran'ın Karadeniz ve dünya pazarlarına ulaşmasını kolaylaştırmak", "Karadeniz'deki balıkçılık faaliyetlerini geliştirmek"],
            3, "Amaç İran yükünü Karadeniz üzerinden dünya pazarlarına aktarmaktır."),
        q("Gürbulak – Trabzon güzergâhının önem kazanmasında aşağıdakilerden hangisi etkili olmuştur?",
            ["İran'ın Karadeniz'e açılmasını sağlayan kısa lojistik güzergâhlardan biri olması", "Türkiye'nin en büyük petrol üretim alanlarını birbirine bağlaması", "Avrupa ile Afrika arasındaki deniz ulaşımını sağlaması", "Marmara Bölgesi'ndeki sanayi tesislerini birbirine bağlaması", "İç Anadolu'daki tarım alanlarına ulaşım sağlaması"],
            0, "Hürmüz/Basra'yı baypas eden kısa Karadeniz çıkışıdır."),
        q("Habur – Kapıkule transit ticaret yolu aşağıdaki ülkelerden hangileri arasındaki ticarette önemli bir koridor niteliğindedir?",
            ["İran – Rusya", "Irak/Orta Doğu – Avrupa", "Gürcistan – İran", "Yunanistan – Suriye", "Bulgaristan – Gürcistan"],
            1, "Habur Irak/Orta Doğu, Kapıkule Avrupa (Bulgaristan) tarafıdır."),
        q("Habur – Kapıkule transit ticaret yolu aşağıdaki sınır kapılarından hangilerini birbirine bağlar?",
            ["Gürbulak – Sarp", "Kapıkule – Sarp", "Habur – Kapıkule", "Cilvegözü – Kapıkule", "Sarp – Habur"],
            2, "Şırnak-Habur ile Edirne-Kapıkule bağlanır."),
        q("Türkiye'nin en uzun ve en yüksek işlem hacmine sahip uluslararası transit koridoru olarak verilen güzergâh aşağıdakilerden hangisidir?",
            ["Gürbulak – Trabzon", "Habur – Kapıkule", "Sarp – İstanbul", "Cilvegözü – İzmir", "Kapıkule – Trabzon"],
            1, "En uzun ve en yüksek hacimli koridor Habur–Kapıkule'dir."),
        q("Habur – Kapıkule transit ticaret yolunun Türkiye açısından önemini en iyi açıklayan ifade aşağıdakilerden hangisidir?",
            ["Yalnızca Türkiye'nin iç bölgelerindeki sanayiyi desteklemesi", "İran'ın Karadeniz'e en kısa yoldan ulaşmasını sağlaması", "Türkiye'nin doğu-batı yönlü ticari geçişlerde köprü konumunu güçlendirmesi", "Karadeniz'deki limanların tamamını birbirine bağlaması", "Türkiye'nin petrol üretimini artırması"],
            2, "Doğu-batı köprü konumu Habur–Kapıkule ile somutlaşır. İran-Karadeniz Gürbulak–Trabzon'dur."),
        q("Aşağıdaki transit ticaret yollarından hangisi Orta Doğu ile Avrupa arasındaki kara yolu ticaretinin ana damarlarından biri olarak belirtilmiştir?",
            ["Gürbulak – Trabzon", "Habur – Kapıkule", "Sarp – Trabzon", "Kapıkule – Gürbulak", "Samsun – Habur"],
            1, "Orta Doğu–Avrupa karayolu ana damarı Habur–Kapıkule'dir.")
    ];
})();
