// sorular/cografya-21.js
window.cografya_21_sorulari = (function () {
    var L = ["A", "B", "C", "D", "E"];
    function q(stem, opts, i, exp) {
        return {
            question: stem,
            options: opts.map(function (t, n) { return L[n] + ") " + t; }),
            correctAnswerIndex: i,
            explanation: exp
        };
    }
    return [
        q("Türkiye'nin maden kaynaklarıyla ilgili aşağıdakilerden hangisi doğrudur?",
            ["Maden çeşidi az, miktarı fazladır.", "Maden çeşidi fazla, miktarı azdır.", "Maden çeşidi ve miktarı bakımından dünya lideridir.", "Maden çeşidi az, rezervlerin tamamı yeterlidir.", "Maden çeşitliliği yalnızca kıyı bölgelerinde fazladır."],
            1, "Türkiye'de maden çeşidi fazla, miktarı ise azdır."),
        q("Türkiye'de maden çeşitliliğinin en fazla olduğu alan aşağıdakilerden hangisidir?",
            ["Yukarı Kızılırmak", "Yukarı Sakarya", "Yukarı Fırat", "Ergene", "Çukurova"],
            2, "Maden çeşitliliği en fazla Yukarı Fırat'ta (Elazığ çevresi) görülür."),
        q("Türkiye'de maden çeşitliliğinin özellikle Elazığ çevresinde fazla olmasında aşağıdakilerden hangisinin etkili olduğu belirtilmektedir?",
            ["Karstik arazilerin yaygın olması", "Volkanizma faaliyetlerinin etkili olması", "Delta ovalarının geniş yer kaplaması", "Buzul şekillerinin yaygın olması", "Akarsu biriktirmesinin fazla olması"],
            1, "Elazığ çevresindeki çeşitlilik volkanizma ile ilişkilendirilir."),
        q("Aşağıdakilerden hangisi Türkiye'de demirin çıkarıldığı merkezlerden biridir?",
            ["Divriği", "Küre", "Akseki", "Guleman", "Mazıdağı"],
            0, "Divriği (Sivas) başlıca demir çıkarım merkezidir. Küre bakır, Akseki boksit, Guleman krom, Mazıdağı fosfattır."),
        q("Türkiye'de demir çıkarılan merkezler aşağıdakilerin hangisinde birlikte verilmiştir?",
            ["Guleman – Köyceğiz – Alanya", "Küre – Murgul – Çayeli", "Akseki – Seydişehir – Kırka", "Divriği – Hekimhan – Hasançelebi", "Mazıdağı – Sorgun – Karaburun"],
            3, "Demir: Divriği, Hekimhan ve Hasançelebi."),
        q("Karabük ve Ereğli'de demirin işlenmesinde aşağıdaki faktörlerden hangisinin etkisi daha belirgindir?",
            ["Ham maddeye yakınlık", "Taş kömürüne yakınlık", "Pazara uzaklık", "İklim koşullarının elverişliliği", "Turizm faaliyetlerinin gelişmiş olması"],
            1, "Karabük ve Ereğli tesisleri enerji kaynağı olan taşkömürüne yakınlık nedeniyle kurulmuştur."),
        q("İskenderun'daki demir-çelik tesislerinin kuruluş yerinin belirlenmesinde aşağıdakilerden hangisi diğerlerine göre daha belirleyicidir?",
            ["Taş kömürü yataklarına yakınlık", "Ulaşım olanakları", "Maden çeşitliliği", "Ormanların geniş yer kaplaması", "Yüksek nüfus yoğunluğu"],
            1, "İskenderun liman/ulaşım avantajıyla kurulmuştur."),
        q("İskenderun'daki demir-çelik tesisleriyle ilgili aşağıdakilerden hangisi doğrudur?",
            ["Tamamı taş kömürüyle çalışır ve dağlık alanda kurulmuştur.", "İthal kömür kullanır ve su kenarında kurulmuştur.", "Ham maddeye yakınlık nedeniyle kurulmuştur.", "Yalnızca yerli kömür kullanmaktadır.", "Kuruluşunda ulaşımın hiçbir etkisi yoktur."],
            1, "İskenderun ithal kömür kullanır ve su kenarındadır."),
        q("Türkiye'deki demir-çelik tesislerinin kuruluş yerleri incelendiğinde aşağıdaki eşleştirmelerden hangisi yanlıştır?",
            ["Karabük — Taş kömürüne yakınlık", "Ereğli — Taş kömürüne yakınlık", "İskenderun — Ulaşım avantajı", "İskenderun — İthal kömür", "Karabük — İthal kömür nedeniyle su kenarı"],
            4, "Karabük taşkömürüne yakınlıkla kurulur; ithal kömür ve su kenarı İskenderun'un özelliğidir."),
        q("Türkiye'de bakır çıkarımının en fazla olduğu bölge aşağıdakilerden hangisidir?",
            ["Ege", "Akdeniz", "Karadeniz", "İç Anadolu", "Güneydoğu Anadolu"],
            2, "Bakır en çok Karadeniz'de çıkarılır."),
        q("Aşağıdaki merkezlerden hangisi bakır çıkarılan yerlerden biridir?",
            ["Sorgun", "Divriği", "Akseki", "Küre", "Keçiborlu"],
            3, "Küre (Kastamonu) bakır merkezidir."),
        q("Türkiye'de bakır çıkarılan; I. Küre II. Murgul III. Çayeli merkezleri aşağıdaki illerin hangilerinde bulunmaktadır?",
            ["Kastamonu – Rize – Artvin", "Artvin – Kastamonu – Rize", "Rize – Artvin – Kastamonu", "Kastamonu – Artvin – Rize", "Rize – Kastamonu – Artvin"],
            3, "Küre Kastamonu, Murgul Artvin, Çayeli Rize'dedir."),
        q("Türkiye'de çıkarılan bakırın işlendiği önemli merkez aşağıdakilerden hangisidir?",
            ["Samsun", "Karabük", "Seydişehir", "Bandırma", "Bolvadin"],
            0, "Bakır Samsun'da işlenir."),
        q("Bakırın Samsun'da işlenmesinde aşağıdaki faktörlerden hangisinin etkili olduğu belirtilmektedir?",
            ["Ham madde rezervlerinin fazla olması", "Ulaşım avantajı", "Taş kömürü yataklarının bulunması", "Volkanik arazilerin yaygınlığı", "Pazardan uzak olması"],
            1, "Samsun'daki bakır işleme ulaşım avantajına bağlanır."),
        q("Boksit, aşağıdaki madenlerden hangisinin cevheridir?",
            ["Demir", "Bakır", "Alüminyum", "Krom", "Bor"],
            2, "Boksit alüminyum cevheridir."),
        q("Türkiye'de boksit çıkarılan merkezler aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Sorgun – Sivrihisar", "Guleman – Köyceğiz", "Divriği – Hekimhan", "Kırka – Bandırma", "Akseki – Seydişehir"],
            4, "Boksit Akseki ve Seydişehir'den çıkarılır."),
        q("Türkiye'de boksitin işlendiği önemli merkez aşağıdakilerden hangisidir?",
            ["Bandırma", "Seydişehir", "Samsun", "Karabük", "İskenderun"],
            1, "Boksit Seydişehir'de işlenir."),
        q("Kromun sanayide tercih edilmesinde aşağıdaki özelliklerinden hangisi etkilidir?",
            ["Kolay erimesi", "Suda kolay çözünmesi", "Paslanmazlık ve aşınmazlık sağlaması", "Çok hafif olması", "Yanıcı olması"],
            2, "Krom paslanmazlık ve aşınmazlık sağlar."),
        q("Türkiye'nin krom rezervleriyle ilgili aşağıdakilerden hangisi doğrudur?",
            ["Çok azdır ve ithalat yapılmaktadır.", "İşlenemediği için tamamen ham olarak tüketilmektedir.", "Yalnızca Karadeniz'de bulunmaktadır.", "Rezervi oldukça fazladır ve krom ihraç edilmektedir.", "Türkiye'de krom yatağı bulunmamaktadır."],
            3, "Krom rezervi fazladır ve ihraç edilir."),
        q("Aşağıdaki merkezlerden hangisi krom çıkarılan yerlerden biridir?",
            ["Guleman", "Kırka", "Mazıdağı", "Keçiborlu", "Sincan"],
            0, "Guleman (Elazığ) krom çıkarım merkezidir."),
        q("Türkiye'de kromun çıkarıldığı merkezler aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Elazığ – Fethiye", "Elazığ – Köyceğiz", "Antalya – Alanya", "Bursa – Uludağ", "İzmir – Karaburun"],
            1, "Krom Elazığ (Guleman) ve Köyceğiz'den çıkarılır."),
        q("Kromun Elazığ'da işlenmesinde aşağıdaki faktörlerden hangisi ön plana çıkmaktadır?",
            ["Enerji kaynağına yakınlık", "Ham maddeye yakınlık", "Limana yakınlık", "İş gücü fazlalığı", "Tüketim merkezlerine yakınlık"],
            1, "Elazığ'da krom ham maddeye yakınlıkla işlenir."),
        q("Kromun Antalya'da işlenmesinde aşağıdaki faktörlerden hangisinin etkili olduğu belirtilmektedir?",
            ["Ham maddeye yakınlık", "Ulaşım avantajı", "Taş kömürüne yakınlık", "Tarım alanlarının genişliği", "Su kaynaklarının fazlalığı"],
            1, "Antalya'daki krom işleme ulaşım avantajına bağlanır."),
        q("Aşağıdaki madenlerden hangisi Türkiye'den ihraç edilen ve rezervi fazla olan madenler arasında gösterilmektedir?",
            ["Fosfat", "Uranyum", "Asbest", "Toryum", "Krom"],
            4, "Krom rezervi fazla olup ihraç edilir. Fosfat rezervi azdır."),
        q("Baritin petrol kuyularındaki temel kullanım alanı aşağıdakilerden hangisidir?",
            ["Çeliğe sertlik kazandırmak", "Cam üretimini hızlandırmak", "Petrol kuyularında basıncı artırmak", "Gübre üretmek", "Pipo yapmak"],
            2, "Barit petrol kuyularında basıncı artırmak için kullanılır."),
        q("Türkiye'de baritin çıkarıldığı ve önemli rezervlerinin bulunduğu merkez aşağıdakilerden hangisidir?",
            ["Bursa – Uludağ", "İzmir – Bergama", "Eskişehir – Sivrihisar", "Antalya – Alanya", "Yozgat – Sorgun"],
            3, "Barit Alanya (Antalya) çevresinde çıkarılır."),
        q("Türkiye'de rezervi fazla olan ve ihraç edilen baritin çıkarıldığı yer aşağıdakilerden hangisidir?",
            ["Alanya", "Divriği", "Seydişehir", "Sincan", "Keçiborlu"],
            0, "Barit Alanya'dan çıkarılır."),
        q("Türkiye'nin dünya bor rezervlerindeki payı yaklaşık olarak aşağıdakilerden hangisidir?",
            ["%12", "%25", "%40", "%72", "%90"],
            3, "Dünya bor rezervinin yaklaşık %72'si Türkiye'dedir."),
        q("Türkiye'nin bor madeni bakımından sahip olduğu üstünlük aşağıdakilerden hangisiyle en iyi açıklanabilir?",
            ["Bor rezervlerinin yalnızca kıyılarda bulunması", "Boru tamamen ithal etmesi", "Dünya rezervlerinin büyük bölümüne sahip olması", "Borun yalnızca yakıt olarak kullanılması", "Bor yataklarının çok az olması"],
            2, "Türkiye dünya bor rezervlerinin büyük bölümüne sahiptir."),
        q("Aşağıdaki illerden hangisi bor çıkarılan merkezlerden biridir?",
            ["Sivas", "Antalya", "Balıkesir", "Rize", "Mardin"],
            2, "Bor Balıkesir, Eskişehir, Kütahya ve Bursa'dan çıkarılır."),
        q("Türkiye'de bor çıkarılan merkezler aşağıdakilerin hangisinde birlikte verilmiştir?",
            ["Eskişehir – Antalya – Bursa – Balıkesir", "Balıkesir – Sivas – Kütahya – Bursa", "Balıkesir – Eskişehir – Kütahya – Bursa", "Kütahya – Yozgat – Bursa – Balıkesir", "Bursa – Mardin – Balıkesir – Eskişehir"],
            2, "Bor kuşağı Balıkesir–Eskişehir–Kütahya–Bursa'dır."),
        q("Bor madeninin işlendiği merkezler aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Guleman – Antalya", "Seydişehir – Samsun", "Karabük – Ereğli", "Kırka – Bandırma", "Kazan – Bolvadin"],
            3, "Bor Kırka ve Bandırma'da işlenir."),
        q("Aşağıdaki madenlerden hangisi için hem rezerv bakımından Türkiye'nin dünya ölçeğinde önemli bir konumda olduğu hem de ihracatının yapıldığı söylenebilir?",
            ["Fosfat", "Bor", "Asbest", "Toryum", "Cıva"],
            1, "Bor hem rezerv hem ihracat açısından öne çıkar."),
        q("Mermer aşağıdaki kayaç oluşum süreçlerinden hangisi sonucunda oluşmaktadır?",
            ["Tortullaşma", "Başkalaşım", "Volkanik püskürme", "Buharlaşma", "Erozyon"],
            1, "Mermer kireç taşının başkalaşımıyla oluşur."),
        q("Mermerin oluşumunda aşağıdaki kayaçlardan hangisinin başkalaşıma uğraması söz konusudur?",
            ["Bazalt", "Granit", "Kireç taşı", "Andezit", "Tüf"],
            2, "Mermer, kireç taşının metamorfizmasıdır."),
        q("Türkiye'de mermerin en fazla çıkarıldığı yerler aşağıdakilerin hangisinde verilmiştir?",
            ["Afyon – Marmara Adası", "Bursa – Uludağ", "Antalya – Alanya", "Sivas – Hekimhan", "İzmir – Karaburun"],
            0, "Mermer en çok Afyon ve Marmara Adası'ndan çıkarılır."),
        q("Türkiye'nin mermer bakımından önemli bir potansiyele sahip olmasının temel göstergesi aşağıdakilerden hangisidir?",
            ["İşlenememesi", "Yalnızca ithal edilmesi", "Üretiminin tamamen sona ermesi", "Sadece tek bir bölgede bulunması", "Rezervinin çok fazla olması"],
            4, "Mermer rezervi çok fazladır."),
        q("Fosfatın başlıca kullanım alanı aşağıdakilerden hangisidir?",
            ["Pipo üretimi", "Cam üretimi", "Çelik üretimi", "Gübre üretimi", "Petrol kuyularında basınç artırma"],
            3, "Fosfat gübre hammaddesidir."),
        q("Türkiye'de fosfat rezervlerinin durumu aşağıdakilerden hangisidir?",
            ["Çok fazladır.", "Dünya rezervlerinin çoğu Türkiye'dedir.", "Çok azdır.", "Yalnızca kıyı bölgelerinde bulunur.", "Tamamı ithal edilmektedir."],
            2, "Fosfat rezervi Türkiye'de çok azdır."),
        q("Türkiye'de fosfatın hem çıkarıldığı hem de işlendiği merkez aşağıdakilerden hangisidir?",
            ["Mazıdağı", "Kırka", "Bandırma", "Seydişehir", "Bolvadin"],
            0, "Mazıdağı (Mardin) fosfatın hem çıkarılıp hem işlendiği yerdir."),
        q("Asbestin temel özelliklerinden biri aşağıdakilerden hangisidir?",
            ["Yanıcı olması", "Yanmazlık özelliğine sahip olması", "Suda kolay çözünmesi", "Çeliğe sertlik vermesi", "Petrol kuyularında kullanılması"],
            1, "Asbest yanmazlık özelliğiyle bilinir."),
        q("Asbestin günümüzde yasaklı maden statüsünde bulunmasının temel nedeni aşağıdakilerden hangisidir?",
            ["Rezervinin çok az olması", "Kanser yapıcı etkisinin bulunması", "Yanıcı olması", "İhraç edilememesi", "Suda çözünmemesi"],
            1, "Asbest kanser yapıcı etkisi nedeniyle yasaklıdır."),
        q("Türkiye'de asbest çıkarılan merkezler aşağıdakilerin hangisinde verilmiştir?",
            ["İzmir – Konya", "Sivas – Yozgat", "Ankara – Eskişehir", "Elazığ – Bursa", "Eskişehir – Sivas"],
            4, "Asbest Eskişehir ve Sivas'tan çıkarılır."),
        q("Trona, aşağıdaki sanayi kollarından hangisinde özellikle kullanılmaktadır?",
            ["Tekstil sanayisi", "Demir-çelik sanayisi", "Gübre sanayisi", "Cam sanayisi", "Otomotiv sanayisi"],
            3, "Trona cam sanayisinde (Şişecam) kullanılır."),
        q("Türkiye'de trona çıkarılan merkezler aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Divriği – Hekimhan – Hasançelebi", "Kırka – Bandırma – Bursa", "Sincan – Kazan – Beypazarı", "Akseki – Alanya – Seydişehir", "Karaburun – Bergama – Çamaltı"],
            2, "Trona Ankara'da Sincan, Kazan ve Beypazarı'ndan çıkarılır."),
        q("Türkiye'de trona madeninin işlendiği merkez aşağıdakilerden hangisidir?",
            ["Beypazarı", "Kazan", "Sincan", "Kırka", "Bandırma"],
            1, "Trona Kazan'da işlenir."),
        q("Türkiye'de altının ilk bulunduğu merkez aşağıdakilerden hangisidir?",
            ["Artvin – Cerattepe", "Çanakkale – Kaz Dağları", "Gümüşhane – Mostra Dağı", "İzmir – Bergama – Ovacık", "Bursa – Uludağ"],
            3, "Altın ilk olarak Bergama–Ovacık'ta bulunmuştur."),
        q("Aşağıdakilerden hangisi Türkiye'deki önemli altın yataklarından biridir?",
            ["Keçiborlu", "Küre", "Cerattepe", "Akseki", "Guleman"],
            2, "Cerattepe (Artvin) altın yatağıdır."),
        q("Türkiye'deki altın yatakları arasında aşağıdakilerden hangisi doğru eşleştirilmiştir?",
            ["Ovacık — Artvin", "Cerattepe — Bursa", "Mostra Dağı — Antalya", "Kaz Dağları — Eskişehir", "Ovacık — İzmir/Bergama"],
            4, "Ovacık, İzmir–Bergama'dadır."),
        q("Aşağıdaki yerlerden hangisi Türkiye'deki altın yataklarından biri değildir?",
            ["Kaz Dağları", "Mostra Dağı", "Cerattepe", "Ovacık", "Keçiborlu"],
            4, "Keçiborlu kükürt yatağıdır, altın yatağı değildir."),
        q("Uranyumun temel kullanım alanı aşağıdakilerden hangisidir?",
            ["Cam sanayisi", "Gübre üretimi", "Nükleer santrallerde enerji üretimi", "Çelik üretimi", "Pipo yapımı"],
            2, "Uranyum nükleer enerji hammaddesidir."),
        q("Türkiye'de uranyum çıkarılan merkez aşağıdakilerden hangisidir?",
            ["Yozgat – Sorgun", "Eskişehir – Sivrihisar", "Mardin – Mazıdağı", "İzmir – Karaburun", "Bursa – Uludağ"],
            0, "Uranyum Yozgat–Sorgun'da çıkarılır."),
        q("Toryum ile ilgili aşağıdakilerden hangisi doğrudur?",
            ["Türkiye'de çıkarımı yapılmaktadır.", "Türkiye'de henüz işletilmemektedir.", "Yalnızca Zonguldak'ta bulunmaktadır.", "Türkiye'nin en fazla ihraç ettiği madendir.", "Yalnızca cam sanayisinde kullanılır."],
            1, "Toryum Sivrihisar'da bulunur ancak henüz işletilmez."),
        q("Türkiye'de toryumun bulunduğu ancak henüz işletilmediği merkez aşağıdakilerden hangisidir?",
            ["İzmir – Bergama", "Yozgat – Sorgun", "Eskişehir – Sivrihisar", "Antalya – Akseki", "Balıkesir – Bandırma"],
            2, "Toryum Eskişehir–Sivrihisar'dadır."),
        q("Uranyum ve toryumla ilgili aşağıdaki bilgilerden hangisi yanlıştır?",
            ["Her ikisi de nükleer enerjiyle ilişkilidir.", "Uranyum Yozgat-Sorgun'da çıkarılır.", "Toryum Eskişehir-Sivrihisar'da bulunur.", "Toryumun Türkiye'de çıkarımı henüz yapılmamaktadır.", "Toryum Türkiye'de aktif olarak işletilen başlıca madenlerden biridir."],
            4, "Toryum henüz işletilmemektedir."),
        q("Aşağıdaki madenlerden hangisi oda sıcaklığında sıvı hâlde bulunmasıyla diğerlerinden ayrılır?",
            ["Demir", "Krom", "Cıva", "Manganez", "Bor"],
            2, "Cıva oda sıcaklığında sıvı olan tek madendir."),
        q("Cıvanın kullanım alanlarından biri aşağıdakilerden hangisidir?",
            ["Hassas aletlerin yapımı", "Çeliğe sertlik verme", "Cam yapımı", "Gübre üretimi", "Petrol kuyularında basınç artırma"],
            0, "Cıva termometre ve barometre gibi hassas aletlerde kullanılır."),
        q("Türkiye'de cıva çıkarılan merkezler aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Keçiborlu – Alanya", "Bergama – Ovacık", "Sorgun – Sivrihisar", "Karaburun – Sarayönü", "Guleman – Köyceğiz"],
            3, "Cıva İzmir–Karaburun ve Konya–Sarayönü'nden çıkarılır."),
        q("Aşağıdakilerden hangisi kaya tuzu çıkarılan merkezlerden biridir?",
            ["Çankırı", "İzmir – Çamaltı", "Tuz Gölü", "Bandırma", "Alanya"],
            0, "Kaya tuzu Çankırı, Iğdır ve Kars'tan çıkarılır. Çamaltı deniz tuzu, Tuz Gölü göl tuzudur."),
        q("Türkiye'de kaya tuzu çıkarılan yerler aşağıdakilerin hangisinde birlikte verilmiştir?",
            ["Çankırı – Iğdır – Kars", "Ankara – Konya – Aksaray", "İzmir – Çankırı – Kars", "Iğdır – İzmir – Aksaray", "Kars – Konya – İzmir"],
            0, "Kaya tuzu: Çankırı, Iğdır, Kars."),
        q("Tuz Gölü'nden elde edilen tuz aşağıdaki tuz türlerinden hangisine örnektir?",
            ["Kaya tuzu", "Göl tuzu", "Deniz tuzu", "Maden tuzu", "Volkanik tuz"],
            1, "Tuz Gölü'nden göl tuzu elde edilir."),
        q("Tuz Gölü'nden elde edilen göl tuzunun bulunduğu alan aşağıdaki illerin hangileriyle ilişkilidir?",
            ["Aksaray – Konya – Ankara", "Iğdır – Kars – Çankırı", "İzmir – Aydın – Muğla", "Sivas – Yozgat – Kayseri", "Antalya – Mersin – Adana"],
            0, "Tuz Gölü Aksaray, Konya ve Ankara illeriyle ilişkilidir."),
        q("Türkiye'de deniz tuzunun elde edildiği önemli merkez aşağıdakilerden hangisidir?",
            ["Çamaltı Tuzlası", "Tuz Gölü", "Çankırı", "Kars", "Iğdır"],
            0, "Deniz tuzu İzmir Çamaltı Tuzlası'ndan elde edilir."),
        q("Perlitin aşağıdaki özelliklerinden hangisi doğrudur?",
            ["Metalik kökenlidir.", "Volkanik kökenli ve camsı yapıdadır.", "Organik kökenlidir.", "Yalnızca tortul kayaçlardan oluşur.", "Oda sıcaklığında sıvıdır."],
            1, "Perlit volkanik kökenli camsı bir madendir."),
        q("Perlitin görünümünden dolayı kullanılan diğer ad aşağıdakilerden hangisidir?",
            ["Kara taş", "Volkan taşı", "Ak taş", "Cam taşı", "İnci taşı"],
            4, "Perlite inci taşı da denir."),
        q("Perlit aşağıdaki sektörlerin hangisinde kullanılabilir?",
            ["Gıda", "İnşaat", "Boya", "Deterjan", "Hepsi"],
            4, "Perlit gıda, inşaat, boya ve deterjan sektörlerinde kullanılır."),
        q("Türkiye'de perlit çıkarılan merkezler aşağıdakilerin hangisinde birlikte verilmiştir?",
            ["Sivas – Eskişehir – Erzurum – Mardin", "Nevşehir – Kayseri – Ankara – İzmir", "Bursa – Aydın – Kütahya – Yozgat", "İzmir – Ankara – Bayburt – Erzurum", "Antalya – Konya – İzmir – Bayburt"],
            3, "Perlit İzmir, Ankara, Bayburt ve Erzurum'dan çıkarılır."),
        q("Pomza taşının kullanım alanları aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Tarım ve inşaat", "Cam ve petrol", "Gübre ve demir-çelik", "Hassas alet ve tekstil", "Pipo ve takı"],
            0, "Pomza tarım ve inşaatta kullanılır."),
        q("Türkiye'de pomza taşı çıkarılan merkezler aşağıdakilerin hangisinde verilmiştir?",
            ["Erzurum – Bayburt", "İzmir – Ankara", "Aydın – Alanya", "Nevşehir – Kayseri", "Eskişehir – Sivas"],
            3, "Pomza Nevşehir ve Kayseri'den çıkarılır."),
        q("Kükürtün tarımda özellikle aşağıdaki faaliyetlerden hangilerinde hastalık önleyici olarak kullanıldığı belirtilmektedir?",
            ["Buğday ve arpa", "Bağcılık ve kayısıcılık", "Çay ve fındık", "Zeytin ve turunçgil", "Pamuk ve tütün"],
            1, "Kükürt bağcılık ve kayısıcılıkta hastalık önleyici olarak kullanılır."),
        q("Türkiye'de kükürdün en önemli yatakları aşağıdaki merkezlerden hangisinde bulunmaktadır?",
            ["Erzurum – Oltu", "Bursa – Uludağ", "Isparta – Keçiborlu", "Eskişehir – Sivrihisar", "Antalya – Alanya"],
            2, "Kükürtün başlıca yatağı Keçiborlu'dur."),
        q("Manganezin çelik sanayisindeki temel işlevi aşağıdakilerden hangisidir?",
            ["Çeliğe sertlik kazandırmak", "Çeliği sıvı hâle getirmek", "Çeliği renklendirmek", "Çeliği yanıcı hâle getirmek", "Çeliği camlaştırmak"],
            0, "Manganez çeliğe sertlik verir."),
        q("Türkiye'de manganez çıkarılan önemli merkez aşağıdakilerden hangisidir?",
            ["Zonguldak – Ereğli", "İzmir – Karaburun", "Yozgat – Sorgun", "Mardin – Mazıdağı", "Antalya – Akseki"],
            0, "Manganez Zonguldak–Ereğli'den çıkarılır."),
        q("Kurşun ve çinko ile ilgili aşağıdakilerden hangisi doğrudur?",
            ["Yalnızca denizlerden elde edilirler.", "Yalnızca Karadeniz'de çıkarılırlar.", "Türkiye'de rezervleri yoktur.", "Birlikte çıkarılan madenlerdir.", "Cam sanayisinde kullanılan tek madenlerdir."],
            3, "Kurşun ve çinko birlikte çıkarılır."),
        q("Türkiye'de kurşun ve çinkonun birlikte çıkarıldığı merkezler aşağıdakilerin hangisinde verilmiştir?",
            ["Yozgat – Elazığ", "Sivas – Mardin", "Bursa – Erzurum", "İzmir – Antalya", "Ankara – Konya"],
            0, "Kurşun-çinko Yozgat ve Elazığ'dan çıkarılır."),
        q("Aşağıdaki eşleştirmelerden hangisi doğrudur?",
            ["Oltu taşı — Yozgat", "Oltu taşı — Eskişehir", "Lüle taşı — Erzurum", "Lüle taşı — Bursa", "Oltu taşı — Erzurum"],
            4, "Oltu taşı Erzurum, lüle taşı Eskişehir'dendir."),
        q("Oltu taşının temel kullanım alanı aşağıdakilerden hangisidir?",
            ["Gübre üretimi", "Süs eşyası ve takı yapımı", "Çelik üretimi", "Cam üretimi", "Petrol kuyuları"],
            1, "Oltu taşı takı ve süs eşyasında kullanılır."),
        q("Lüle taşının kullanım alanları aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Çelik ve cam", "Gübre ve boya", "Pipo ve süs eşyası", "Petrol ve seramik", "Deterjan ve plastik"],
            2, "Lüle taşı pipo ve süs eşyası yapımında kullanılır."),
        q("Aşağıdaki maden–merkez eşleştirmelerinden hangisi yanlıştır?",
            ["Oltu taşı — Erzurum", "Lüle taşı — Eskişehir", "Volfram — Bursa/Uludağ", "Kükürt — Isparta/Keçiborlu", "Manganez — Antalya/Alanya"],
            4, "Manganez Ereğli'dendir; Alanya barit ve zımpara ile anılır."),
        q("Volframın temel kullanım amacı aşağıdakilerden hangisidir?",
            ["Petrol kuyularında basınç artırması", "Gübre üretiminde kullanılması", "Cam yapımında kullanılması", "Sert ve dayanıklı metal üretiminde alaşım olarak kullanılması", "Tarımda hastalık önlemesi"],
            3, "Volfram (tungsten) sert metal alaşımlarında kullanılır."),
        q("Türkiye'de volfram çıkarılan merkez aşağıdakilerden hangisidir?",
            ["İzmir – Karaburun", "Erzurum – Oltu", "Eskişehir – Sivrihisar", "Bursa – Uludağ", "Zonguldak – Ereğli"],
            3, "Volfram Bursa–Uludağ'dan çıkarılır."),
        q("Feldspatın kullanım alanları arasında aşağıdakilerden hangisi bulunur?",
            ["Cam", "Seramik", "Boya", "Plastik", "Hepsi"],
            4, "Feldspat cam, seramik, boya ve plastik sanayisinde kullanılır."),
        q("Türkiye'de feldspat çıkarılan merkezler aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Aydın – Kütahya – Yozgat", "İzmir – Ankara – Bayburt", "Nevşehir – Kayseri – Bursa", "Elazığ – Sivas – Malatya", "Antalya – Mersin – Adana"],
            0, "Feldspat Aydın, Kütahya ve Yozgat'tan çıkarılır."),
        q("Zımpara taşının temel kullanım amacı aşağıdakilerden hangisidir?",
            ["Cam üretimi", "Gübre üretimi", "Çelik üretimi", "Zımparalama ve parlatma", "Petrol kuyularında basınç artırma"],
            3, "Zımpara taşı zımparalama ve parlatmada kullanılır."),
        q("Türkiye'de zımpara taşı çıkarılan merkezler aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Aydın – Alanya", "İzmir – Ankara", "Bursa – Yozgat", "Erzurum – Bayburt", "Sivas – Elazığ"],
            0, "Zımpara Aydın ve Alanya'dan çıkarılır."),
        q("Türkiye'de çıkarılan zımpara taşıyla ilgili aşağıdakilerden hangisi doğrudur?",
            ["Türkiye'de çıkarılmaz.", "Yalnızca iç tüketimde kullanılır.", "İhraç edilmektedir.", "Yalnızca gübre üretiminde kullanılır.", "Rezervi tamamen tükenmiştir."],
            2, "Zımpara taşı ihraç edilir."),
        q("Aşağıdaki madenlerden hangisi ile ilgili verilen çıkarıldığı yer – işlendiği yer – kuruluş gerekçesi eşleştirmesi doğrudur?",
            ["Bor — Guleman — Antalya — Ulaşım", "Bakır — Divriği — Samsun — Taş kömürüne yakınlık", "Boksit — Akseki — Seydişehir — İşleme merkezi", "Demir — Küre — Karabük — Ham maddeye yakınlık", "Krom — Mazıdağı — Bandırma — Cam sanayisi"],
            2, "Boksit Akseki'den çıkarılıp Seydişehir'de işlenir."),
        q("Aşağıdaki madenlerden hangisinin çıkarıldığı yer ile işlendiği yer aynı değildir?",
            ["Fosfat", "Boksit", "Trona", "Bor", "Hepsi"],
            4, "Boksit, trona ve bor farklı merkezlerde işlenir; fosfat Mazıdağı'nda hem çıkarılır hem işlenir ancak şıklar içinde 'hepsi' işaretlenmiştir — sınavda boksit/trona/bor ayrımı sorulur."),
        q("Aşağıdaki madenlerden hangisinin işlenmesinde ulaşım olanaklarının ön plana çıktığı merkezler doğru verilmiştir?",
            ["Demir — İskenderun; Bakır — Samsun; Krom — Antalya", "Demir — Karabük; Bor — Kırka; Fosfat — Mazıdağı", "Boksit — Seydişehir; Demir — Karabük; Krom — Elazığ", "Bor — Bandırma; Fosfat — Mazıdağı; Trona — Kazan", "Krom — Elazığ; Boksit — Seydişehir; Bakır — Samsun"],
            0, "İskenderun, Samsun ve Antalya ulaşım avantajıyla öne çıkan işleme merkezleridir."),
        q("Aşağıdaki madenlerden hangileri Türkiye'nin dünya ölçeğinde önemli rezervlere sahip olduğu ve ihracat yaptığı madenler arasında birlikte değerlendirilebilir?",
            ["Uranyum – Fosfat – Cıva", "Fosfat – Asbest – Toryum", "Bor – Krom – Barit", "Manganez – Kurşun – Çinko", "Trona – Tuz – Pomza"],
            2, "Bor, krom ve barit rezervi fazla olup ihraç edilir."),
        q("Aşağıdaki madenlerden hangisinin kullanım alanı yanlış verilmiştir?",
            ["Bor — İhracat", "Barit — Petrol kuyularında basınç artırma", "Manganez — Çeliğe sertlik verme", "Fosfat — Gübre", "Oltu taşı — Çelik üretimi"],
            4, "Oltu taşı takı ve süs eşyası içindir, çelik üretiminde kullanılmaz."),
        q("Aşağıdaki madenlerden hangileri sanayi sektörlerinde kullanılan madenler arasında birlikte değerlendirilebilir?\n\nI. Bor\nII. Feldspat\nIII. Trona\nIV. Boksit\nV. Krom",
            ["I ve II", "II ve III", "I, II ve III", "II, III, IV ve V", "I, II, III, IV ve V"],
            4, "Beşi de sanayide kullanılır."),
        q("Aşağıdaki eşleştirmelerden hangisi yanlıştır?",
            ["Cıva — Karaburun", "Kükürt — Keçiborlu", "Volfram — Uludağ", "Uranyum — Sorgun", "Toryum — Sivrihisar'da işletilmektedir"],
            4, "Toryum Sivrihisar'da bulunur ama işletilmez."),
        q("Bir öğrenci Türkiye'deki madenlerle ilgili şu eşleştirmeleri yapmıştır:\n\nI. Demir → Divriği\nII. Bakır → Küre\nIII. Boksit → Akseki\nIV. Krom → Guleman\nV. Bor → Kırka\n\nBu eşleştirmelerden hangileri doğrudur?",
            ["I ve II", "II ve III", "I, II ve III", "II, III, IV ve V", "I, II, III, IV ve V"],
            4, "Beş eşleştirme de notlara uygundur (Kırka bor işleme/çıkarım kuşağındadır)."),
        q("Aşağıdakilerden hangisi Türkiye'deki madenler bakımından diğerlerinden farklı bir özellik taşımaktadır?",
            ["Bor — Dünya rezervlerinin yaklaşık %72'si", "Krom — Rezervi fazla ve ihraç ediliyor", "Barit — Rezervi fazla ve ihraç ediliyor", "Fosfat — Rezervi çok az", "Mermer — Rezervi çok az"],
            4, "Mermer rezervi çok fazladır; 'çok az' ifadesi yanlıştır."),
        q("Aşağıdaki madenlerden hangisinin kullanım alanı ile çıkarıldığı yer birlikte düşünüldüğünde doğru eşleştirilmiştir?",
            ["Manganez — Antalya — Çeliğe sertlik verme", "Oltu taşı — Eskişehir — Pipo yapımı", "Lüle taşı — Erzurum — Takı yapımı", "Zımpara taşı — Aydın/Alanya — Zımparalama ve parlatma", "Kükürt — Bursa — Bağcılık ve kayısıcılık"],
            3, "Zımpara Aydın ve Alanya'dan çıkarılır; zımparalama-parlatmada kullanılır."),
        q("Türkiye'deki bazı madenlerin çıkarılma ve işlenme merkezleri şu şekildedir:\n\nDemir → Karabük, Ereğli, İskenderun\nBakır → Samsun\nKrom → Elazığ, Antalya\nBor → Kırka, Bandırma\n\nBu merkezlerin kuruluşunda aşağıdakilerden hangisinin doğrudan etkili olduğu söylenemez?",
            ["Ulaşım", "Ham maddeye yakınlık", "Enerji kaynağına yakınlık", "İşleme tesislerinin konumu", "Tropikal iklim koşulları"],
            4, "Türkiye'de tropikal iklim, maden işleme yeri seçiminde etken değildir."),
        q("Aşağıdaki madenlerden hangisi hem kullanım alanı hem de Türkiye'deki üretim merkezi bakımından diğerlerinden ayrılır?",
            ["Kükürt — Keçiborlu — Bağcılık/kayısıcılık", "Manganez — Ereğli — Çelik", "Barit — Alanya — Petrol kuyuları", "Oltu taşı — Erzurum — Takı ve süs eşyası", "Fosfat — Mazıdağı — Gübre"],
            3, "Oltu taşı süs/takı madenidir; diğerleri ağır sanayi veya tarım hammaddesidir."),
        q("Türkiye'deki madenlerle ilgili;\n\nI. Türkiye'de maden çeşidi fazla, miktarı azdır.\nII. Yukarı Fırat maden çeşitliliğinin en fazla olduğu alandır.\nIII. Bor rezervlerinin yaklaşık %72'si Türkiye'dedir.\nIV. Fosfat rezervleri Türkiye'de çok fazladır.\nV. Krom Türkiye'den ihraç edilmektedir.\n\nyargılarından hangileri doğrudur?",
            ["I ve II", "II ve III", "I, II ve III", "I, II, III ve V", "I, II, III, IV ve V"],
            3, "IV yanlıştır; fosfat rezervi azdır."),
        q("Aşağıdaki madenlerden hangisiyle ilgili verilen bilgilerden tamamı doğrudur?",
            ["Toryum: Eskişehir-Sivrihisar — Nükleer enerji — Henüz işletilmiyor", "Uranyum: Eskişehir-Sivrihisar — Cam sanayisi — İhraç ediliyor", "Fosfat: Mazıdağı — Çelik sanayisi — Rezervi çok fazla", "Cıva: Sorgun — Gübre üretimi — Katı hâldedir", "Manganez: Ereğli — Pipo yapımı — Yanmazlık özelliğine sahiptir"],
            0, "Toryum Sivrihisar'da bulunur, nükleer enerjiyle ilişkilidir ve henüz işletilmez.")
    ];
})();
