// sorular/cografya-24.js
window.cografya_24_sorulari = (function () {
    var L = ["A", "B", "C", "D", "E"];
    function q(stem, opts, i, exp) {
        return {
            question: stem,
            options: opts.map(function (t, n) { return L[n] + ") " + t; }),
            correctAnswerIndex: i,
            explanation: exp
        };
    }
    return [
        q("Türkiye topraklarında kurulan ilk demir yolu hattı aşağıdakilerden hangisidir?",
            ["Ankara – Yerköy", "Ankara – Eskişehir", "İzmir – Aydın", "İstanbul – İzmit", "Sivas – Erzurum"],
            2, "İlk hat İzmir–Aydın'dır. Ankara–Yerköy Cumhuriyet'in ilk hattıdır."),
        q("Cumhuriyet Dönemi'nde inşa edilen ilk demir yolu hattı aşağıdakilerden hangisidir?",
            ["Ankara – Yerköy", "Ankara – Eskişehir", "İzmir – Aydın", "İstanbul – Ankara", "Sivas – Kayseri"],
            0, "Cumhuriyet'in ilk hattı Ankara–Yozgat (Yerköy)'dür."),
        q("Türkiye'de demir yolu hatlarının genel olarak doğu-batı doğrultusunda uzanmasında aşağıdakilerden hangisinin etkisi daha fazladır?",
            ["Nüfusun kıyılarda yoğunlaşmasının", "Dağların genel uzanış doğrultusunun", "Limanların kıyılarda bulunmasının", "Tarım alanlarının geniş olmasının", "Akarsuların rejimlerinin"],
            1, "Dağlar doğu-batı uzandığı için hatlar da bu doğrultuda gelişmiştir."),
        q("Türkiye'de kara üzerindeki yük ve yolcu taşımacılığında maliyet açısından en avantajlı ulaşım türü aşağıdakilerden hangisidir?",
            ["Hava yolu", "Kara yolu", "Deniz yolu", "Demir yolu", "Boru hattı"],
            3, "Kara üzerindeki taşımacılıkta en ucuz tür demir yoludur. Deniz yolu genel olarak en ucuzdur ama kara üzerinde değildir."),
        q("Aşağıdaki yörelerden hangisine, engebeli ve dağlık arazi yapısının ulaşımı zorlaştırması nedeniyle demir yolu ulaşımı ulaşmamıştır?",
            ["Çukurova", "Doğu Karadeniz", "Konya Ovası", "Ergene Havzası", "Ankara çevresi"],
            1, "Doğu Karadeniz demir yolu gitmeyen yerlerdendir."),
        q("Aşağıdaki yörelerden hangisinde demir yolu ulaşımının gelişmemesinde yer şekillerinin engebeli olması daha belirleyici olmuştur?",
            ["Hakkâri", "Konya", "Ergene", "Harran", "Çukurova"],
            0, "Hakkâri Yöresi engebeli olduğu için demir yolu yoktur."),
        q("Aşağıdakilerden hangisi Türkiye'de demir yolu ulaşımının ulaşmadığı yerlerden biri değildir?",
            ["Menteşe Yöresi", "Hakkâri Yöresi", "Doğu Karadeniz", "Teke Platosu", "İç Anadolu'nun büyük bölümü"],
            4, "Menteşe Yöresi, Hakkâri Yöresi, Doğu Karadeniz ve Teke Platosu engebeli ve yüksek arazi yapıları nedeniyle demir yolu ağının dışında kalmıştır. İç Anadolu ise düz ve az engebeli yapısı sayesinde yoğun bir demir yolu ağına sahiptir; bu nedenle demir yolu ulaşımının ulaşmadığı yerlerden biri değildir."),
        q("Aşağıdaki yerlerden hangisinde demir yolu ulaşımının gelişmemesinde yer şekillerinin engebeli olması temel bir etkendir?",
            ["Gelibolu – Biga yarımadaları", "Ergene Havzası", "Konya Ovası", "Harran Ovası", "Tuz Gölü çevresi"],
            0, "Gelibolu–Biga yarımadalarına demir yolu gitmez."),
        q("Türkiye'de yüksek hızlı tren işletmeciliğinin başladığı ilk hat aşağıdakilerden hangisidir?",
            ["Ankara – Konya", "Ankara – İstanbul", "Ankara – Eskişehir", "Ankara – Sivas", "İstanbul – Konya"],
            2, "İlk YHT hattı Ankara–Eskişehir'dir."),
        q("Türkiye'nin ilk Yüksek Hızlı Tren hattı hangi yılda hizmete girmiştir?",
            ["2003", "2005", "2007", "2009", "2011"],
            3, "Ankara–Eskişehir YHT 2009'da açılmıştır."),
        q("Aşağıdakilerden hangisi Türkiye'deki aktif YHT hatlarından biri değildir?",
            ["Ankara – Konya", "Ankara – Sivas", "Ankara – Eskişehir", "Konya – Karaman", "Ankara – Erzurum"],
            4, "Ankara–Erzurum aktif YHT listesinde yoktur."),
        q("İstanbul'dan Konya'ya YHT ile ulaşım sağlanırken aşağıdaki şehirlerden hangisinin üzerinden geçilir?",
            ["Eskişehir", "Kayseri", "Kütahya", "Afyonkarahisar", "Karaman"],
            0, "İstanbul–Konya hattı Eskişehir ve Bilecik üzerinden geçer. Karaman ayrı bir Konya–Karaman hattıdır."),
        q("Aşağıdaki YHT hatlarından hangisi doğrudan Ankara merkezli bir hat değildir?",
            ["Ankara – Eskişehir", "Ankara – Konya", "Ankara – Sivas", "Ankara – İstanbul", "İstanbul – Konya"],
            4, "İstanbul–Konya Ankara merkezli bir hat olarak verilmez."),
        q("Aşağıdaki YHT güzergâhlarından hangisi İç Anadolu'daki iki merkez arasında ulaşım sağlamaktadır?",
            ["Ankara – Sivas", "İstanbul – Sivas", "İstanbul – Konya", "Ankara – İstanbul", "İstanbul – Eskişehir"],
            0, "Ankara ve Sivas İç Anadolu merkezleridir."),
        q("Aşağıdaki ülke – sınır kapısı eşleştirmelerinden hangisi doğrudur?",
            ["Bulgaristan – Kapıköy", "İran – Kapıkule", "Gürcistan – Türkgözü", "Yunanistan – Akyaka", "Ermenistan – Uzunköprü"],
            2, "Türkiye'nin Gürcistan sınırındaki kapısı Ardahan'ın Posof ilçesindeki Türkgözü Sınır Kapısı'dır. Diğer eşleştirmeler yer değiştirmiştir: Kapıköy (Van) İran, Kapıkule (Edirne) Bulgaristan, Uzunköprü (Edirne) Yunanistan, Akyaka (Kars) ise Ermenistan sınır kapısıdır."),
        q("Türkiye'nin Bulgaristan ile demir yolu bağlantısında kullanılan sınır kapısı aşağıdakilerden hangisidir?",
            ["Kapıköy", "Kapıkule", "Uzunköprü", "Akyaka", "Nusaybin"],
            1, "Bulgaristan: Kapıkule."),
        q("Türkiye'nin İran ile demir yolu bağlantısında aşağıdaki sınır kapılarından hangisi kullanılmaktadır?",
            ["Kapıkule", "Uzunköprü", "Kapıköy", "Canbaz", "İslahiye"],
            2, "İran: Kapıköy (Van)."),
        q("Bakü-Tiflis-Kars demir yolu hattı kapsamında Türkiye'nin Gürcistan ile bağlantısında aşağıdaki sınır kapılarından hangisi yer almaktadır?",
            ["Akyaka", "Kapıköy", "Türkgözü", "Uzunköprü", "Çobanbey"],
            2, "Bakü-Tiflis-Kars demir yolu hattı, Türkiye'den Gürcistan'a Ardahan'ın Posof ilçesindeki Türkgözü sınır kapısı üzerinden geçer. Akyaka Ermenistan, Kapıköy İran, Uzunköprü Yunanistan, Çobanbey ise Suriye sınırındaki kapılardır."),
        q("Aşağıdaki sınır kapılarından hangisi Ermenistan ile demir yolu bağlantısında bulunmakla birlikte siyasi nedenlerle kapalıdır?",
            ["Kapıköy", "Kapıkule", "Akyaka", "Canbaz", "Uzunköprü"],
            2, "Akyaka (Kars) Ermenistan hattıdır ve kapalıdır."),
        q("Aşağıdakilerden hangisi Türkiye'nin Suriye ile demir yolu bağlantısında kullanılan sınır kapılarından biridir?",
            ["Kapıkule", "Nusaybin", "Kapıköy", "Uzunköprü", "Akyaka"],
            1, "Türkiye'nin Suriye ile demir yolu bağlantısı İslahiye, Çobanbey ve Nusaybin sınır kapıları üzerinden sağlanır. Kapıkule Bulgaristan, Kapıköy İran, Uzunköprü Yunanistan, Akyaka ise Ermenistan sınırındaki kapılardır."),
        q("Türkiye'de kara yolu ulaşımının büyük gelişme gösterdiği dönem aşağıdakilerden hangisidir?",
            ["1920'li yıllar", "1930'lu yıllar", "1940'lı yıllar", "1950'li yıllardan sonrası", "1990'lı yıllardan sonrası"],
            3, "Kara yolu 1950'lerden sonra büyük gelişme göstermiştir."),
        q("Türkiye'de iç ticarette en fazla kullanılan ulaşım türü aşağıdakilerden hangisidir?",
            ["Demir yolu", "Deniz yolu", "Hava yolu", "Kara yolu", "Boru hattı"],
            3, "İç ticarette kara yolu, dış ticarette deniz yolu öne çıkar."),
        q("Kara yolu ulaşımının Türkiye'de hemen her yere ulaşabilmesinde aşağıdakilerden hangisi temel bir avantaj sağlamaktadır?",
            ["Sadece düz arazilerde kullanılabilmesi", "Güzergâh esnekliğinin yüksek olması", "Yüksek maliyetli olması", "Limanlara bağımlı olması", "Hava koşullarından hiç etkilenmemesi"],
            1, "Kara yolu güzergâh esnekliğiyle hemen her yere ulaşır."),
        q("Türkiye'nin kuzey ve güney kesimleri arasındaki kara yolu ulaşımında aşağıdakilerden hangisinin kullanılması zorunludur?",
            ["Limanlar", "Geçit ve boğazlar", "Havalimanları", "Ovalar", "Akarsular"],
            1, "Kuzey ve güneyde dağlar nedeniyle geçit ve boğazlar kullanılır."),
        q("Aşağıdakilerden hangisi Akdeniz Bölgesi'nde yer alan önemli geçitlerden biridir?",
            ["Ilgaz", "Kop", "Zigana", "Sertavul", "Ecevit"],
            3, "Sertavul Akdeniz'dedir. Diğerleri Karadeniz geçitleridir."),
        q("Aşağıdaki geçitlerden hangisi Akdeniz Bölgesi'nde yer almaz?",
            ["Çubuk", "Sertavul", "Gülek", "Belen", "Ilgaz"],
            4, "Ilgaz Geçidi, Çankırı ile Kastamonu arasında Küre Dağları üzerinde yer alır ve Karadeniz Bölgesi'ndedir. Çubuk, Sertavul, Gülek ve Belen geçitleri ise Toroslar ile Amanoslar üzerinde bulunan Akdeniz Bölgesi geçitleridir."),
        q("Aşağıdaki eşleştirmelerden hangisi doğrudur?",
            ["Ecevit – Kastamonu", "Ilgaz – Antalya", "Zigana – Muğla", "Kop – Çanakkale", "Belen – Çankırı"],
            0, "Ecevit Kastamonu'dadır. Ilgaz Çankırı, Zigana Trabzon, Belen Hatay'dır."),
        q("Karadeniz Bölgesi'nde ulaşım açısından önemli olan geçitler arasında aşağıdakilerden hangisi bulunmaz?",
            ["Ecevit", "Ilgaz", "Zigana", "Kop", "Sertavul"],
            4, "Sertavul Akdeniz geçididir."),
        q("Aşağıdakilerden hangisi Marmara Bölgesi'nde yer alan önemli ulaşım geçitlerinden biridir?",
            ["Belen Geçidi", "Kop Geçidi", "Geyve Boğazı", "Zigana Geçidi", "Sertavul Geçidi"],
            2, "Marmara: Geyve Boğazı ve Bolu Dağı Geçidi."),
        q("Aşağıdaki geçit – bölge eşleştirmelerinden hangisi yanlıştır?",
            ["Belen – Akdeniz", "Zigana – Karadeniz", "Geyve – Marmara", "Kop – Karadeniz", "Sertavul – Marmara"],
            4, "Sertavul Akdeniz'dedir, Marmara'da değil."),
        q("Aşağıdaki ulaşım türlerinden hangisi maliyet bakımından en pahalı olanıdır?",
            ["Deniz yolu", "Demir yolu", "Kara yolu", "Hava yolu", "Boru hattı"],
            3, "Hava yolu en pahalıdır."),
        q("Türkiye'de günümüzde gelişme hızı en yüksek ulaşım türü aşağıdakilerden hangisidir?",
            ["Demir yolu", "Kara yolu", "Deniz yolu", "Hava yolu", "Akarsu yolu"],
            3, "En çok gelişen tür hava yoludur."),
        q("Türkiye'nin en büyük havalimanı aşağıdakilerden hangisidir?",
            ["Esenboğa Havalimanı", "Adnan Menderes Havalimanı", "İstanbul Havalimanı", "Antalya Havalimanı", "Sabiha Gökçen Havalimanı"],
            2, "Yolcu ve uçak trafiği bakımından Türkiye'nin en büyük havalimanı İstanbul Havalimanı'dır. Terminal kapasitesi, pist sayısı ve sefer sayısıyla diğer havalimanlarının açık farkla önündedir; hava kargo taşımacılığında da ilk sırada yer alır."),
        q("Aşağıdakilerden hangisi hava yolu ulaşımının Türkiye'deki genel özelliklerinden biridir?",
            ["İç ticarette en fazla kullanılan ulaşım türüdür.", "En ucuz ulaşım türüdür.", "Günümüzde gelişme hızı en yüksek ulaşım türüdür.", "Yük taşımacılığında temel ulaşım türüdür.", "Limanlara bağlı olarak gelişir."],
            2, "Hava yolu en pahalıdır ve en hızlı gelişendir. İç ticaret kara yoludur."),
        q("Deniz yolu ulaşımının maliyetinin düşük olmasının temel nedeni aşağıdakilerden hangisidir?",
            ["Her yere ulaşabilmesi", "Hava koşullarından etkilenmemesi", "Bir seferde çok fazla yük taşıyabilmesi", "Hızlı olması", "Kara yollarıyla bağlantılı olması"],
            2, "Bir seferde çok yük taşındığı için birim maliyet düşüktür."),
        q("Türkiye'nin dış ticaretinde en fazla kullanılan ulaşım türü aşağıdakilerden hangisidir?",
            ["Kara yolu", "Demir yolu", "Hava yolu", "Deniz yolu", "Boru hattı"],
            3, "Dış ticarette deniz yolu hâkimdir."),
        q("Aşağıdakilerden hangisi deniz yolu taşımacılığının kara yolu taşımacılığına göre temel üstünlüklerinden biridir?",
            ["Her yerleşim merkezine ulaşabilmesi", "Daha hızlı olması", "Bir seferde daha fazla yük taşıyabilmesi", "Dağlık alanlarda daha kolay kullanılabilmesi", "Hava koşullarından etkilenmemesi"],
            2, "Deniz yolu büyük hacimli yükte üstündür; her yere ulaşmak kara yolunun avantajıdır."),
        q("Bir limanın gelişmesini sağlayan ve limanın etki alanını oluşturan ekonomik ve coğrafi özelliklerin tümüne aşağıdakilerden hangisi denir?",
            ["Rıhtım", "Hinterland", "Delta", "Boğaz", "Plato"],
            1, "Hinterland (ard bölge) limanın etki alanıdır."),
        q("Aşağıdaki limanlardan hangisinin hinterlandı geniştir?",
            ["Sinop", "İzmir", "Cide", "Hopa", "İnebolu"],
            1, "İzmir Limanı'nın gerisinde verimli Ege ovaları, yoğun nüfus ve gelişmiş sanayi alanları bulunur; iç kesimlere uzanan kara ve demir yolu bağlantıları sayesinde hinterlandı geniştir. Sinop, Cide, Hopa ve İnebolu limanlarının ardında ise Kuzey Anadolu Dağları kıyıya paralel uzandığından iç kesimlerle bağlantı zayıftır ve hinterlandları dardır."),
        q("Aşağıdakilerden hangisi hinterlandı geniş olan limanlardan biridir?",
            ["İstanbul", "Sinop", "Hopa", "Cide", "İnebolu"],
            0, "İstanbul Limanı'nın gerisinde yoğun nüfuslu ve sanayileşmiş bir alan ile ülkenin iç kesimlerine uzanan güçlü bir ulaşım ağı bulunduğundan hinterlandı geniştir. Sinop, Hopa, Cide ve İnebolu limanlarının ardında ise Kuzey Anadolu Dağları kıyıya paralel uzandığı için hinterlandları dardır."),
        q("Aşağıdaki limanlardan hangisinin hinterlandı dar olduğu için gelişme düzeyi sınırlıdır?",
            ["İzmir", "Mersin", "Kocaeli", "Samsun", "Sinop"],
            4, "Sinop doğal limandır ama hinterlandı dardır."),
        q("Sinop Limanı'nın doğal liman özelliğine sahip olmasına rağmen yeterince gelişememesinin temel nedeni aşağıdakilerden hangisidir?",
            ["Hinterlandının dar olması", "Kıyı uzunluğunun fazla olması", "Deniz ulaşımına kapalı olması", "Demir yolu ağının çok gelişmiş olması", "Büyük bir sanayi bölgesinde bulunması"],
            0, "Küre Dağları / dar hinterland gelişmeyi sınırlar. Sinop'a demir yolu da gitmez."),
        q("Aşağıdaki limanlardan hangisinin hinterlandı dar olan limanlar arasında yer aldığı söylenebilir?",
            ["İstanbul", "Kocaeli", "İzmir", "Hopa", "Mersin"],
            3, "Hopa dar hinterlandlıdır."),
        q("Aşağıdaki limanlardan hangisinin hinterlandı geniş değildir?",
            ["Samsun", "Mersin", "Kocaeli", "Cide", "İstanbul"],
            3, "Cide dar hinterlandlıdır."),
        q("Kamyon, TIR ve benzeri tekerlekli araçların gemilerle taşınmasına verilen ad aşağıdakilerden hangisidir?",
            ["Konteyner taşımacılığı", "Ro-Ro taşımacılığı", "Transit taşımacılık", "Kombine taşımacılık", "Boru hattı taşımacılığı"],
            1, "Ro-Ro: tekerlekli araçların gemiyle taşınmasıdır."),
        q("Bir TIR'ın yükü boşaltılmadan doğrudan gemiye alınarak başka bir ülkeye taşınması aşağıdaki ulaşım yöntemlerinden hangisine örnek gösterilebilir?",
            ["Ro-Ro taşımacılığı", "Hava kargo taşımacılığı", "Boru hattı taşımacılığı", "Demir yolu taşımacılığı", "Akarsu taşımacılığı"],
            0, "TIR'ın gemiye binmesi Ro-Ro örneğidir."),
        q("Türkiye'deki ulaşım sistemleriyle ilgili aşağıdaki bilgilerden hangisi yanlıştır?",
            ["Kara yolu iç ticarette önemli bir yere sahiptir.", "Deniz yolu dış ticarette önemli bir yere sahiptir.", "Hava yolu günümüzde hızlı gelişen ulaşım türlerinden biridir.", "Demir yolu, kara üzerindeki yük ve yolcu taşımacılığında maliyet açısından avantajlıdır.", "Hava yolu ulaşımı en ucuz ulaşım türüdür."],
            4, "Hava yolu en pahalıdır; en ucuz genel olarak deniz yoludur."),
        q("Aşağıdaki ulaşım türlerinden hangisi ile ilgili verilen bilgi yanlıştır?",
            ["Kara yolu → İç ticarette yaygın kullanım", "Deniz yolu → Dış ticarette yaygın kullanım", "Hava yolu → En pahalı ulaşım türü", "Demir yolu → Kara üzerindeki taşımacılıkta düşük maliyet", "Deniz yolu → En pahalı ulaşım türü"],
            4, "Deniz yolu en ucuz türdür, en pahalı değil."),
        q("Sinop, Hopa ve Cide limanlarının gelişememesinin temel nedeni aşağıdakilerden hangisidir?",
            ["Hinterlandlarının dar olması", "Kıyılarında gelgit olayının etkili olması", "Kış aylarında limanların donması", "Doğal koy ve körfezlerin hiç bulunmaması", "Deniz suyu tuzluluğunun çok yüksek olması"],
            0, "Bu limanların gerisinde Kuzey Anadolu Dağları kıyıya paralel uzandığı için art bölgeleriyle (hinterland) ulaşım bağlantıları zayıftır; dar hinterland liman trafiğini ve gelişimini sınırlar. Türkiye kıyılarında belirgin gelgit görülmez, limanlar kışın donmaz, bu kıyılarda doğal koylar bulunur ve Karadeniz'in tuzluluğu düşüktür; bu nedenle diğer seçenekler limanların gelişememesini açıklamaz."),
        q("Türkiye'de ulaşım sistemlerinin gelişimiyle ilgili;\nI. Kara yolu ulaşımı 1950'lerden sonra önemli ölçüde gelişmiştir.\nII. Demir yolu hatlarının uzanışında yer şekilleri etkili olmuştur.\nIII. Hava yolu ulaşımı günümüzde gelişme gösteren ulaşım türlerinden biridir.\nIV. Deniz yolu dış ticarette önemli bir yere sahiptir.\nyargılarından hangilerine ulaşılabilir?",
            ["Yalnız I", "I ve II", "II ve III", "I, II ve IV", "I, II, III ve IV"],
            4, "I. 1950'den sonra kara yolu yapımına ağırlık verilmiş, kara yolu yük ve yolcu taşımacılığında ilk sıraya yerleşmiştir. II. Ülke arazisi engebeli olduğundan demir yolu hatları genellikle vadileri ve ovaları izleyerek dolambaçlı biçimde uzanır. III. Havalimanı ve sefer sayısının artmasıyla hava yolu ulaşımı hızla gelişmektedir. IV. Ucuz ve çok yüklü taşıma imkânı verdiği için dış ticaret taşımalarının büyük bölümü deniz yoluyla yapılır. Bu nedenle dört yargıya da ulaşılabilir."),
        q("Aşağıdaki ulaşım türlerinden hangisi ile kullanım alanı arasında yanlış bir eşleştirme yapılmıştır?",
            ["Kara yolu – İç ticaret", "Deniz yolu – Dış ticaret", "Hava yolu – Hızlı ulaşım", "Demir yolu – Kara üzerindeki düşük maliyetli taşımacılık", "Deniz yolu – Her yere doğrudan ulaşım"],
            4, "Her yere ulaşmak kara yolunun özelliğidir; deniz yolu kıyı ve limana bağlıdır."),
        q("Türkiye'de aşağıdaki ulaşım sistemlerinden hangisinin gelişmesinde yer şekillerinin etkisi diğerlerine göre daha belirgindir?",
            ["Hava yolu", "Deniz yolu", "Kara yolu", "Demir yolu", "Boru hattı"],
            3, "Demir yolu hem uzanış doğrultusunda hem de gitmediği engebeli yörelerde yer şekillerine daha bağımlıdır."),
        q("Bir araştırmacı Türkiye'deki ulaşım sistemleriyle ilgili şu sonuçlara ulaşmıştır:\n• İç ticarette en fazla kullanılan ulaşım sistemidir.\n• Ülkenin hemen her yerine ulaşabilmektedir.\n• 1950'li yıllardan sonra hızlı bir gelişme göstermiştir.\n• Kuzey ve güney yönlü ulaşımda geçitlerden yararlanılır.\nBu araştırmacının incelediği ulaşım türü aşağıdakilerden hangisidir?",
            ["Demir yolu", "Kara yolu", "Deniz yolu", "Hava yolu", "Boru hattı"],
            1, "Dört özellik birden kara yoluna aittir."),
        q("Bir limanın doğal liman olmasına rağmen ticari açıdan beklenen düzeyde gelişmemesinde aşağıdakilerden hangisinin etkili olması beklenir?",
            ["Hinterlandının dar olması", "Kıyıda bulunması", "Deniz ulaşımına uygun olması", "Liman alanının bulunması", "Deniz taşımacılığının yapılabilmesi"],
            0, "Sinop örneğinde olduğu gibi dar hinterland gelişmeyi sınırlar."),
        q("Aşağıdaki merkezlerden hangisi geniş hinterlandıyla gelişmiş limanlara örnek gösterilebilir?",
            ["Cide", "Hopa", "Sinop", "Mersin", "İnebolu"],
            3, "Mersin Limanı'nın gerisinde Çukurova ve İç Anadolu'ya uzanan geniş, üretken bir art bölge (hinterland) bulunduğundan gelişmiş bir limandır. Cide, Hopa, Sinop ve İnebolu limanlarının ardında ise Kuzey Anadolu Dağları kıyıya paralel uzandığı için hinterlandları dardır."),
        q("Türkiye'deki ulaşım sistemleri dikkate alındığında aşağıdaki yargılardan hangisine ulaşılabilir?",
            ["Hava yolu en düşük maliyetli ulaşım türüdür.", "Kara yolu dış ticarette en fazla kullanılan ulaşım türüdür.", "Deniz yolu, yüksek miktarda yük taşıyabilmesi nedeniyle düşük maliyetlidir.", "Demir yolu Türkiye'nin tüm dağlık bölgelerine ulaşmıştır.", "Limanların gelişmesinde hinterlandın hiçbir etkisi yoktur."],
            2, "Deniz yolu yüksek yük kapasitesiyle ucuzdur."),
        q("Türkiye'nin en büyük kargo havalimanı aşağıdakilerden hangisidir?",
            ["İstanbul Havalimanı", "Şanlıurfa (GAP) Havalimanı", "Esenboğa Havalimanı", "Adnan Menderes Havalimanı", "Sabiha Gökçen Havalimanı"],
            0, "Türkiye'de hava kargo taşımacılığının büyük bölümü İstanbul Havalimanı üzerinden gerçekleşir; taşınan kargo miktarı bakımından açık farkla ilk sıradadır. Sabiha Gökçen, Esenboğa, Adnan Menderes ve Şanlıurfa GAP havalimanlarının kargo hacmi çok daha düşüktür."),
        q("Türkiye'nin Yunanistan ile demir yolu bağlantısında kullanılan sınır kapısı aşağıdakilerden hangisidir?",
            ["Kapıkule", "Uzunköprü", "Canbaz", "Akyaka", "Kapıköy"],
            1, "Yunanistan: Uzunköprü. Kapıkule Bulgaristan'dır."),
        q("Marmara Bölgesi ile İç Anadolu arasındaki kara yolu ulaşımında kullanılan önemli geçit aşağıdakilerden hangisidir?",
            ["Bolu Dağı Geçidi", "Sertavul Geçidi", "Zigana Geçidi", "Belen Geçidi", "Kop Geçidi"],
            0, "Bolu Dağı Geçidi, İstanbul-Ankara kara yolu üzerinde yer alır ve Marmara Bölgesi ile İç Anadolu arasındaki ulaşımı sağlar. Sertavul Geçidi Akdeniz kıyısını İç Anadolu'ya, Zigana ve Kop geçitleri Doğu Karadeniz ile iç kesimleri, Belen Geçidi ise Amanoslar üzerinden İskenderun ile Antakya çevresini birbirine bağlar."),
        q("Aşağıdakilerden hangisi demir yolu ulaşımının ulaşmadığı yerlerden biridir?",
            ["Teke ve Taşeli platoları", "Konya Ovası", "Ergene Havzası", "Ankara çevresi", "Çukurova"],
            0, "Teke ve Taşeli platolarına demir yolu gitmez.")
    ];
})();
