// sorular/cografya-21.js
window.cografya_21_sorulari = (function () {
    var L = ["A", "B", "C", "D", "E"];
    function q(stem, opts, i, exp) {
        return {
            question: stem,
            options: opts.map(function (t, n) { return L[n] + ") " + t; }),
            correctAnswerIndex: i,
            explanation: exp
        };
    }
    return [
        q("Soru 1: Türkiye'nin maden kaynaklarıyla ilgili aşağıdakilerden hangisi doğrudur?",
            ["Maden çeşidi az, miktarı fazladır.", "Maden çeşidi fazla, miktarı azdır.", "Maden çeşidi ve miktarı bakımından dünya lideridir.", "Maden çeşidi az, rezervlerin tamamı yeterlidir.", "Maden çeşitliliği yalnızca kıyı bölgelerinde fazladır."],
            1, "Türkiye'de maden çeşidi fazla, miktarı ise azdır."),
        q("Soru 2: Türkiye'de maden çeşitliliğinin en fazla olduğu alan aşağıdakilerden hangisidir?",
            ["Yukarı Kızılırmak", "Yukarı Sakarya", "Yukarı Fırat", "Ergene", "Çukurova"],
            2, "Maden çeşitliliği en fazla Yukarı Fırat'ta (Elazığ çevresi) görülür."),
        q("Soru 3: Türkiye'de maden çeşitliliğinin özellikle Elazığ çevresinde fazla olmasında aşağıdakilerden hangisinin etkili olduğu belirtilmektedir?",
            ["Karstik arazilerin yaygın olması", "Volkanizma faaliyetlerinin etkili olması", "Delta ovalarının geniş yer kaplaması", "Buzul şekillerinin yaygın olması", "Akarsu biriktirmesinin fazla olması"],
            1, "Elazığ çevresindeki çeşitlilik volkanizma ile ilişkilendirilir."),
        q("Soru 4: Aşağıdakilerden hangisi Türkiye'de demirin çıkarıldığı merkezlerden biridir?",
            ["Divriği", "Küre", "Akseki", "Guleman", "Mazıdağı"],
            0, "Divriği (Sivas) başlıca demir çıkarım merkezidir. Küre bakır, Akseki boksit, Guleman krom, Mazıdağı fosfattır."),
        q("Soru 5: Türkiye'de demir çıkarılan merkezler aşağıdakilerin hangisinde birlikte verilmiştir?",
            ["Divriği – Hekimhan – Hasançelebi", "Küre – Murgul – Çayeli", "Akseki – Seydişehir – Kırka", "Guleman – Köyceğiz – Alanya", "Mazıdağı – Sorgun – Karaburun"],
            0, "Demir: Divriği, Hekimhan ve Hasançelebi."),
        q("Soru 6: Karabük ve Ereğli'de demirin işlenmesinde aşağıdaki faktörlerden hangisinin etkisi daha belirgindir?",
            ["Ham maddeye yakınlık", "Taş kömürüne yakınlık", "Pazara uzaklık", "İklim koşullarının elverişliliği", "Turizm faaliyetlerinin gelişmiş olması"],
            1, "Karabük ve Ereğli tesisleri enerji kaynağı olan taşkömürüne yakınlık nedeniyle kurulmuştur."),
        q("Soru 7: İskenderun'daki demir-çelik tesislerinin kuruluş yerinin belirlenmesinde aşağıdakilerden hangisi diğerlerine göre daha belirleyicidir?",
            ["Taş kömürü yataklarına yakınlık", "Ulaşım olanakları", "Maden çeşitliliği", "Ormanların geniş yer kaplaması", "Yüksek nüfus yoğunluğu"],
            1, "İskenderun liman/ulaşım avantajıyla kurulmuştur."),
        q("Soru 8: İskenderun'daki demir-çelik tesisleriyle ilgili aşağıdakilerden hangisi doğrudur?",
            ["Tamamı taş kömürüyle çalışır ve dağlık alanda kurulmuştur.", "İthal kömür kullanır ve su kenarında kurulmuştur.", "Ham maddeye yakınlık nedeniyle kurulmuştur.", "Yalnızca yerli kömür kullanmaktadır.", "Kuruluşunda ulaşımın hiçbir etkisi yoktur."],
            1, "İskenderun ithal kömür kullanır ve su kenarındadır."),
        q("Soru 9: Türkiye'deki demir-çelik tesislerinin kuruluş yerleri incelendiğinde aşağıdaki eşleştirmelerden hangisi yanlıştır?",
            ["Karabük — Taş kömürüne yakınlık", "Ereğli — Taş kömürüne yakınlık", "İskenderun — Ulaşım avantajı", "İskenderun — İthal kömür", "Karabük — İthal kömür nedeniyle su kenarı"],
            4, "Karabük taşkömürüne yakınlıkla kurulur; ithal kömür ve su kenarı İskenderun'un özelliğidir."),
        q("Soru 10: Türkiye'de bakır çıkarımının en fazla olduğu bölge aşağıdakilerden hangisidir?",
            ["Ege", "Akdeniz", "Karadeniz", "İç Anadolu", "Güneydoğu Anadolu"],
            2, "Bakır en çok Karadeniz'de çıkarılır."),
        q("Soru 11: Aşağıdaki merkezlerden hangisi bakır çıkarılan yerlerden biridir?",
            ["Küre", "Divriği", "Akseki", "Sorgun", "Keçiborlu"],
            0, "Küre (Kastamonu) bakır merkezidir."),
        q("Soru 12: Türkiye'de bakır çıkarılan; I. Küre II. Murgul III. Çayeli merkezleri aşağıdaki illerin hangilerinde bulunmaktadır?",
            ["Kastamonu – Artvin – Rize", "Artvin – Kastamonu – Rize", "Rize – Artvin – Kastamonu", "Kastamonu – Rize – Artvin", "Rize – Kastamonu – Artvin"],
            0, "Küre Kastamonu, Murgul Artvin, Çayeli Rize'dedir."),
        q("Soru 13: Türkiye'de çıkarılan bakırın işlendiği önemli merkez aşağıdakilerden hangisidir?",
            ["Samsun", "Karabük", "Seydişehir", "Bandırma", "Bolvadin"],
            0, "Bakır Samsun'da işlenir."),
        q("Soru 14: Bakırın Samsun'da işlenmesinde aşağıdaki faktörlerden hangisinin etkili olduğu belirtilmektedir?",
            ["Ham madde rezervlerinin fazla olması", "Ulaşım avantajı", "Taş kömürü yataklarının bulunması", "Volkanik arazilerin yaygınlığı", "Pazardan uzak olması"],
            1, "Samsun'daki bakır işleme ulaşım avantajına bağlanır."),
        q("Soru 15: Boksit, aşağıdaki madenlerden hangisinin cevheridir?",
            ["Demir", "Bakır", "Alüminyum", "Krom", "Bor"],
            2, "Boksit alüminyum cevheridir."),
        q("Soru 16: Türkiye'de boksit çıkarılan merkezler aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Akseki – Seydişehir", "Guleman – Köyceğiz", "Divriği – Hekimhan", "Kırka – Bandırma", "Sorgun – Sivrihisar"],
            0, "Boksit Akseki ve Seydişehir'den çıkarılır."),
        q("Soru 17: Türkiye'de boksitin işlendiği önemli merkez aşağıdakilerden hangisidir?",
            ["Bandırma", "Seydişehir", "Samsun", "Karabük", "İskenderun"],
            1, "Boksit Seydişehir'de işlenir."),
        q("Soru 18: Kromun sanayide tercih edilmesinde aşağıdaki özelliklerinden hangisi etkilidir?",
            ["Kolay erimesi", "Paslanmazlık ve aşınmazlık sağlaması", "Suda kolay çözünmesi", "Çok hafif olması", "Yanıcı olması"],
            1, "Krom paslanmazlık ve aşınmazlık sağlar."),
        q("Soru 19: Türkiye'nin krom rezervleriyle ilgili aşağıdakilerden hangisi doğrudur?",
            ["Çok azdır ve ithalat yapılmaktadır.", "Rezervi oldukça fazladır ve krom ihraç edilmektedir.", "Yalnızca Karadeniz'de bulunmaktadır.", "İşlenemediği için tamamen ham olarak tüketilmektedir.", "Türkiye'de krom yatağı bulunmamaktadır."],
            1, "Krom rezervi fazladır ve ihraç edilir."),
        q("Soru 20: Aşağıdaki merkezlerden hangisi krom çıkarılan yerlerden biridir?",
            ["Guleman", "Kırka", "Mazıdağı", "Keçiborlu", "Sincan"],
            0, "Guleman (Elazığ) krom çıkarım merkezidir."),
        q("Soru 21: Türkiye'de kromun çıkarıldığı merkezler aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Elazığ – Fethiye", "Elazığ – Köyceğiz", "Antalya – Alanya", "Bursa – Uludağ", "İzmir – Karaburun"],
            1, "Krom Elazığ (Guleman) ve Köyceğiz'den çıkarılır."),
        q("Soru 22: Kromun Elazığ'da işlenmesinde aşağıdaki faktörlerden hangisi ön plana çıkmaktadır?",
            ["Enerji kaynağına yakınlık", "Ham maddeye yakınlık", "Limana yakınlık", "İş gücü fazlalığı", "Tüketim merkezlerine yakınlık"],
            1, "Elazığ'da krom ham maddeye yakınlıkla işlenir."),
        q("Soru 23: Kromun Antalya'da işlenmesinde aşağıdaki faktörlerden hangisinin etkili olduğu belirtilmektedir?",
            ["Ham maddeye yakınlık", "Ulaşım avantajı", "Taş kömürüne yakınlık", "Tarım alanlarının genişliği", "Su kaynaklarının fazlalığı"],
            1, "Antalya'daki krom işleme ulaşım avantajına bağlanır."),
        q("Soru 24: Aşağıdaki madenlerden hangisi Türkiye'den ihraç edilen ve rezervi fazla olan madenler arasında gösterilmektedir?",
            ["Fosfat", "Krom", "Asbest", "Toryum", "Uranyum"],
            1, "Krom rezervi fazla olup ihraç edilir. Fosfat rezervi azdır."),
        q("Soru 25: Baritin petrol kuyularındaki temel kullanım alanı aşağıdakilerden hangisidir?",
            ["Petrol kuyularında basıncı artırmak", "Cam üretimini hızlandırmak", "Çeliğe sertlik kazandırmak", "Gübre üretmek", "Pipo yapmak"],
            0, "Barit petrol kuyularında basıncı artırmak için kullanılır."),
        q("Soru 26: Türkiye'de baritin çıkarıldığı ve önemli rezervlerinin bulunduğu merkez aşağıdakilerden hangisidir?",
            ["Antalya – Alanya", "İzmir – Bergama", "Eskişehir – Sivrihisar", "Bursa – Uludağ", "Yozgat – Sorgun"],
            0, "Barit Alanya (Antalya) çevresinde çıkarılır."),
        q("Soru 27: Türkiye'de rezervi fazla olan ve ihraç edilen baritin çıkarıldığı yer aşağıdakilerden hangisidir?",
            ["Alanya", "Divriği", "Seydişehir", "Sincan", "Keçiborlu"],
            0, "Barit Alanya'dan çıkarılır."),
        q("Soru 28: Türkiye'nin dünya bor rezervlerindeki payı yaklaşık olarak aşağıdakilerden hangisidir?",
            ["%12", "%25", "%40", "%72", "%90"],
            3, "Dünya bor rezervinin yaklaşık %72'si Türkiye'dedir."),
        q("Soru 29: Türkiye'nin bor madeni bakımından sahip olduğu üstünlük aşağıdakilerden hangisiyle en iyi açıklanabilir?",
            ["Dünya rezervlerinin büyük bölümüne sahip olması", "Boru tamamen ithal etmesi", "Bor rezervlerinin yalnızca kıyılarda bulunması", "Borun yalnızca yakıt olarak kullanılması", "Bor yataklarının çok az olması"],
            0, "Türkiye dünya bor rezervlerinin büyük bölümüne sahiptir."),
        q("Soru 30: Aşağıdaki illerden hangisi bor çıkarılan merkezlerden biridir?",
            ["Balıkesir", "Antalya", "Sivas", "Rize", "Mardin"],
            0, "Bor Balıkesir, Eskişehir, Kütahya ve Bursa'dan çıkarılır."),
        q("Soru 31: Türkiye'de bor çıkarılan merkezler aşağıdakilerin hangisinde birlikte verilmiştir?",
            ["Balıkesir – Eskişehir – Kütahya – Bursa", "Balıkesir – Sivas – Kütahya – Bursa", "Eskişehir – Antalya – Bursa – Balıkesir", "Kütahya – Yozgat – Bursa – Balıkesir", "Bursa – Mardin – Balıkesir – Eskişehir"],
            0, "Bor kuşağı Balıkesir–Eskişehir–Kütahya–Bursa'dır."),
        q("Soru 32: Bor madeninin işlendiği merkezler aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Kırka – Bandırma", "Seydişehir – Samsun", "Karabük – Ereğli", "Guleman – Antalya", "Kazan – Bolvadin"],
            0, "Bor Kırka ve Bandırma'da işlenir."),
        q("Soru 33: Aşağıdaki madenlerden hangisi için hem rezerv bakımından Türkiye'nin dünya ölçeğinde önemli bir konumda olduğu hem de ihracatının yapıldığı söylenebilir?",
            ["Fosfat", "Bor", "Asbest", "Toryum", "Cıva"],
            1, "Bor hem rezerv hem ihracat açısından öne çıkar."),
        q("Soru 34: Mermer aşağıdaki kayaç oluşum süreçlerinden hangisi sonucunda oluşmaktadır?",
            ["Tortullaşma", "Başkalaşım", "Volkanik püskürme", "Buharlaşma", "Erozyon"],
            1, "Mermer kireç taşının başkalaşımıyla oluşur."),
        q("Soru 35: Mermerin oluşumunda aşağıdaki kayaçlardan hangisinin başkalaşıma uğraması söz konusudur?",
            ["Bazalt", "Granit", "Kireç taşı", "Andezit", "Tüf"],
            2, "Mermer, kireç taşının metamorfizmasıdır."),
        q("Soru 36: Türkiye'de mermerin en fazla çıkarıldığı yerler aşağıdakilerin hangisinde verilmiştir?",
            ["Afyon – Marmara Adası", "Bursa – Uludağ", "Antalya – Alanya", "Sivas – Hekimhan", "İzmir – Karaburun"],
            0, "Mermer en çok Afyon ve Marmara Adası'ndan çıkarılır."),
        q("Soru 37: Türkiye'nin mermer bakımından önemli bir potansiyele sahip olmasının temel göstergesi aşağıdakilerden hangisidir?",
            ["Rezervinin çok fazla olması", "Yalnızca ithal edilmesi", "Üretiminin tamamen sona ermesi", "Sadece tek bir bölgede bulunması", "İşlenememesi"],
            0, "Mermer rezervi çok fazladır."),
        q("Soru 38: Fosfatın başlıca kullanım alanı aşağıdakilerden hangisidir?",
            ["Gübre üretimi", "Cam üretimi", "Çelik üretimi", "Pipo üretimi", "Petrol kuyularında basınç artırma"],
            0, "Fosfat gübre hammaddesidir."),
        q("Soru 39: Türkiye'de fosfat rezervlerinin durumu aşağıdakilerden hangisidir?",
            ["Çok fazladır.", "Dünya rezervlerinin çoğu Türkiye'dedir.", "Çok azdır.", "Yalnızca kıyı bölgelerinde bulunur.", "Tamamı ithal edilmektedir."],
            2, "Fosfat rezervi Türkiye'de çok azdır."),
        q("Soru 40: Türkiye'de fosfatın hem çıkarıldığı hem de işlendiği merkez aşağıdakilerden hangisidir?",
            ["Mazıdağı", "Kırka", "Bandırma", "Seydişehir", "Bolvadin"],
            0, "Mazıdağı (Mardin) fosfatın hem çıkarılıp hem işlendiği yerdir."),
        q("Soru 41: Asbestin temel özelliklerinden biri aşağıdakilerden hangisidir?",
            ["Yanıcı olması", "Yanmazlık özelliğine sahip olması", "Suda kolay çözünmesi", "Çeliğe sertlik vermesi", "Petrol kuyularında kullanılması"],
            1, "Asbest yanmazlık özelliğiyle bilinir."),
        q("Soru 42: Asbestin günümüzde yasaklı maden statüsünde bulunmasının temel nedeni aşağıdakilerden hangisidir?",
            ["Rezervinin çok az olması", "Kanser yapıcı etkisinin bulunması", "Yanıcı olması", "İhraç edilememesi", "Suda çözünmemesi"],
            1, "Asbest kanser yapıcı etkisi nedeniyle yasaklıdır."),
        q("Soru 43: Türkiye'de asbest çıkarılan merkezler aşağıdakilerin hangisinde verilmiştir?",
            ["Eskişehir – Sivas", "Sivas – Yozgat", "Ankara – Eskişehir", "Elazığ – Bursa", "İzmir – Konya"],
            0, "Asbest Eskişehir ve Sivas'tan çıkarılır."),
        q("Soru 44: Trona, aşağıdaki sanayi kollarından hangisinde özellikle kullanılmaktadır?",
            ["Cam sanayisi", "Demir-çelik sanayisi", "Gübre sanayisi", "Tekstil sanayisi", "Otomotiv sanayisi"],
            0, "Trona cam sanayisinde (Şişecam) kullanılır."),
        q("Soru 45: Türkiye'de trona çıkarılan merkezler aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Sincan – Kazan – Beypazarı", "Kırka – Bandırma – Bursa", "Divriği – Hekimhan – Hasançelebi", "Akseki – Alanya – Seydişehir", "Karaburun – Bergama – Çamaltı"],
            0, "Trona Ankara'da Sincan, Kazan ve Beypazarı'ndan çıkarılır."),
        q("Soru 46: Türkiye'de trona madeninin işlendiği merkez aşağıdakilerden hangisidir?",
            ["Beypazarı", "Kazan", "Sincan", "Kırka", "Bandırma"],
            1, "Trona Kazan'da işlenir."),
        q("Soru 47: Türkiye'de altının ilk bulunduğu merkez aşağıdakilerden hangisidir?",
            ["İzmir – Bergama – Ovacık", "Çanakkale – Kaz Dağları", "Gümüşhane – Mostra Dağı", "Artvin – Cerattepe", "Bursa – Uludağ"],
            0, "Altın ilk olarak Bergama–Ovacık'ta bulunmuştur."),
        q("Soru 48: Aşağıdakilerden hangisi Türkiye'deki önemli altın yataklarından biridir?",
            ["Cerattepe", "Küre", "Keçiborlu", "Akseki", "Guleman"],
            0, "Cerattepe (Artvin) altın yatağıdır."),
        q("Soru 49: Türkiye'deki altın yatakları arasında aşağıdakilerden hangisi doğru eşleştirilmiştir?",
            ["Ovacık — İzmir/Bergama", "Cerattepe — Bursa", "Mostra Dağı — Antalya", "Kaz Dağları — Eskişehir", "Ovacık — Artvin"],
            0, "Ovacık, İzmir–Bergama'dadır."),
        q("Soru 50: Aşağıdaki yerlerden hangisi Türkiye'deki altın yataklarından biri değildir?",
            ["Kaz Dağları", "Mostra Dağı", "Cerattepe", "Ovacık", "Keçiborlu"],
            4, "Keçiborlu kükürt yatağıdır, altın yatağı değildir."),
        q("Soru 51: Uranyumun temel kullanım alanı aşağıdakilerden hangisidir?",
            ["Cam sanayisi", "Nükleer santrallerde enerji üretimi", "Gübre üretimi", "Çelik üretimi", "Pipo yapımı"],
            1, "Uranyum nükleer enerji hammaddesidir."),
        q("Soru 52: Türkiye'de uranyum çıkarılan merkez aşağıdakilerden hangisidir?",
            ["Yozgat – Sorgun", "Eskişehir – Sivrihisar", "Mardin – Mazıdağı", "İzmir – Karaburun", "Bursa – Uludağ"],
            0, "Uranyum Yozgat–Sorgun'da çıkarılır."),
        q("Soru 53: Toryum ile ilgili aşağıdakilerden hangisi doğrudur?",
            ["Türkiye'de çıkarımı yapılmaktadır.", "Türkiye'de henüz işletilmemektedir.", "Yalnızca Zonguldak'ta bulunmaktadır.", "Türkiye'nin en fazla ihraç ettiği madendir.", "Yalnızca cam sanayisinde kullanılır."],
            1, "Toryum Sivrihisar'da bulunur ancak henüz işletilmez."),
        q("Soru 54: Türkiye'de toryumun bulunduğu ancak henüz işletilmediği merkez aşağıdakilerden hangisidir?",
            ["Eskişehir – Sivrihisar", "Yozgat – Sorgun", "İzmir – Bergama", "Antalya – Akseki", "Balıkesir – Bandırma"],
            0, "Toryum Eskişehir–Sivrihisar'dadır."),
        q("Soru 55: Uranyum ve toryumla ilgili aşağıdaki bilgilerden hangisi yanlıştır?",
            ["Her ikisi de nükleer enerjiyle ilişkilidir.", "Uranyum Yozgat-Sorgun'da çıkarılır.", "Toryum Eskişehir-Sivrihisar'da bulunur.", "Toryumun Türkiye'de çıkarımı henüz yapılmamaktadır.", "Toryum Türkiye'de aktif olarak işletilen başlıca madenlerden biridir."],
            4, "Toryum henüz işletilmemektedir."),
        q("Soru 56: Aşağıdaki madenlerden hangisi oda sıcaklığında sıvı hâlde bulunmasıyla diğerlerinden ayrılır?",
            ["Cıva", "Krom", "Demir", "Manganez", "Bor"],
            0, "Cıva oda sıcaklığında sıvı olan tek madendir."),
        q("Soru 57: Cıvanın kullanım alanlarından biri aşağıdakilerden hangisidir?",
            ["Hassas aletlerin yapımı", "Çeliğe sertlik verme", "Cam yapımı", "Gübre üretimi", "Petrol kuyularında basınç artırma"],
            0, "Cıva termometre ve barometre gibi hassas aletlerde kullanılır."),
        q("Soru 58: Türkiye'de cıva çıkarılan merkezler aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Karaburun – Sarayönü", "Bergama – Ovacık", "Sorgun – Sivrihisar", "Keçiborlu – Alanya", "Guleman – Köyceğiz"],
            0, "Cıva İzmir–Karaburun ve Konya–Sarayönü'nden çıkarılır."),
        q("Soru 59: Aşağıdakilerden hangisi kaya tuzu çıkarılan merkezlerden biridir?",
            ["Çankırı", "İzmir – Çamaltı", "Tuz Gölü", "Bandırma", "Alanya"],
            0, "Kaya tuzu Çankırı, Iğdır ve Kars'tan çıkarılır. Çamaltı deniz tuzu, Tuz Gölü göl tuzudur."),
        q("Soru 60: Türkiye'de kaya tuzu çıkarılan yerler aşağıdakilerin hangisinde birlikte verilmiştir?",
            ["Çankırı – Iğdır – Kars", "Ankara – Konya – Aksaray", "İzmir – Çankırı – Kars", "Iğdır – İzmir – Aksaray", "Kars – Konya – İzmir"],
            0, "Kaya tuzu: Çankırı, Iğdır, Kars."),
        q("Soru 61: Tuz Gölü'nden elde edilen tuz aşağıdaki tuz türlerinden hangisine örnektir?",
            ["Kaya tuzu", "Göl tuzu", "Deniz tuzu", "Maden tuzu", "Volkanik tuz"],
            1, "Tuz Gölü'nden göl tuzu elde edilir."),
        q("Soru 62: Tuz Gölü'nden elde edilen göl tuzunun bulunduğu alan aşağıdaki illerin hangileriyle ilişkilidir?",
            ["Aksaray – Konya – Ankara", "Iğdır – Kars – Çankırı", "İzmir – Aydın – Muğla", "Sivas – Yozgat – Kayseri", "Antalya – Mersin – Adana"],
            0, "Tuz Gölü Aksaray, Konya ve Ankara illeriyle ilişkilidir."),
        q("Soru 63: Türkiye'de deniz tuzunun elde edildiği önemli merkez aşağıdakilerden hangisidir?",
            ["Çamaltı Tuzlası", "Tuz Gölü", "Çankırı", "Kars", "Iğdır"],
            0, "Deniz tuzu İzmir Çamaltı Tuzlası'ndan elde edilir."),
        q("Soru 64: Perlitin aşağıdaki özelliklerinden hangisi doğrudur?",
            ["Metalik kökenlidir.", "Volkanik kökenli ve camsı yapıdadır.", "Organik kökenlidir.", "Yalnızca tortul kayaçlardan oluşur.", "Oda sıcaklığında sıvıdır."],
            1, "Perlit volkanik kökenli camsı bir madendir."),
        q("Soru 65: Perlitin görünümünden dolayı kullanılan diğer ad aşağıdakilerden hangisidir?",
            ["Kara taş", "İnci taşı", "Ak taş", "Cam taşı", "Volkan taşı"],
            1, "Perlite inci taşı da denir."),
        q("Soru 66: Perlit aşağıdaki sektörlerin hangisinde kullanılabilir?",
            ["Gıda", "İnşaat", "Boya", "Deterjan", "Hepsi"],
            4, "Perlit gıda, inşaat, boya ve deterjan sektörlerinde kullanılır."),
        q("Soru 67: Türkiye'de perlit çıkarılan merkezler aşağıdakilerin hangisinde birlikte verilmiştir?",
            ["İzmir – Ankara – Bayburt – Erzurum", "Nevşehir – Kayseri – Ankara – İzmir", "Bursa – Aydın – Kütahya – Yozgat", "Sivas – Eskişehir – Erzurum – Mardin", "Antalya – Konya – İzmir – Bayburt"],
            0, "Perlit İzmir, Ankara, Bayburt ve Erzurum'dan çıkarılır."),
        q("Soru 68: Pomza taşının kullanım alanları aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Tarım ve inşaat", "Cam ve petrol", "Gübre ve demir-çelik", "Hassas alet ve tekstil", "Pipo ve takı"],
            0, "Pomza tarım ve inşaatta kullanılır."),
        q("Soru 69: Türkiye'de pomza taşı çıkarılan merkezler aşağıdakilerin hangisinde verilmiştir?",
            ["Nevşehir – Kayseri", "İzmir – Ankara", "Aydın – Alanya", "Erzurum – Bayburt", "Eskişehir – Sivas"],
            0, "Pomza Nevşehir ve Kayseri'den çıkarılır."),
        q("Soru 70: Kükürtün tarımda özellikle aşağıdaki faaliyetlerden hangilerinde hastalık önleyici olarak kullanıldığı belirtilmektedir?",
            ["Buğday ve arpa", "Bağcılık ve kayısıcılık", "Çay ve fındık", "Zeytin ve turunçgil", "Pamuk ve tütün"],
            1, "Kükürt bağcılık ve kayısıcılıkta hastalık önleyici olarak kullanılır."),
        q("Soru 71: Türkiye'de kükürdün en önemli yatakları aşağıdaki merkezlerden hangisinde bulunmaktadır?",
            ["Isparta – Keçiborlu", "Bursa – Uludağ", "Erzurum – Oltu", "Eskişehir – Sivrihisar", "Antalya – Alanya"],
            0, "Kükürtün başlıca yatağı Keçiborlu'dur."),
        q("Soru 72: Manganezin çelik sanayisindeki temel işlevi aşağıdakilerden hangisidir?",
            ["Çeliğe sertlik kazandırmak", "Çeliği sıvı hâle getirmek", "Çeliği renklendirmek", "Çeliği yanıcı hâle getirmek", "Çeliği camlaştırmak"],
            0, "Manganez çeliğe sertlik verir."),
        q("Soru 73: Türkiye'de manganez çıkarılan önemli merkez aşağıdakilerden hangisidir?",
            ["Zonguldak – Ereğli", "İzmir – Karaburun", "Yozgat – Sorgun", "Mardin – Mazıdağı", "Antalya – Akseki"],
            0, "Manganez Zonguldak–Ereğli'den çıkarılır."),
        q("Soru 74: Kurşun ve çinko ile ilgili aşağıdakilerden hangisi doğrudur?",
            ["Birlikte çıkarılan madenlerdir.", "Yalnızca Karadeniz'de çıkarılırlar.", "Türkiye'de rezervleri yoktur.", "Yalnızca denizlerden elde edilirler.", "Cam sanayisinde kullanılan tek madenlerdir."],
            0, "Kurşun ve çinko birlikte çıkarılır."),
        q("Soru 75: Türkiye'de kurşun ve çinkonun birlikte çıkarıldığı merkezler aşağıdakilerin hangisinde verilmiştir?",
            ["Yozgat – Elazığ", "Sivas – Mardin", "Bursa – Erzurum", "İzmir – Antalya", "Ankara – Konya"],
            0, "Kurşun-çinko Yozgat ve Elazığ'dan çıkarılır."),
        q("Soru 76: Aşağıdaki eşleştirmelerden hangisi doğrudur?",
            ["Oltu taşı — Erzurum", "Oltu taşı — Eskişehir", "Lüle taşı — Erzurum", "Lüle taşı — Bursa", "Oltu taşı — Yozgat"],
            0, "Oltu taşı Erzurum, lüle taşı Eskişehir'dendir."),
        q("Soru 77: Oltu taşının temel kullanım alanı aşağıdakilerden hangisidir?",
            ["Gübre üretimi", "Süs eşyası ve takı yapımı", "Çelik üretimi", "Cam üretimi", "Petrol kuyuları"],
            1, "Oltu taşı takı ve süs eşyasında kullanılır."),
        q("Soru 78: Lüle taşının kullanım alanları aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Pipo ve süs eşyası", "Gübre ve boya", "Çelik ve cam", "Petrol ve seramik", "Deterjan ve plastik"],
            0, "Lüle taşı pipo ve süs eşyası yapımında kullanılır."),
        q("Soru 79: Aşağıdaki maden–merkez eşleştirmelerinden hangisi yanlıştır?",
            ["Oltu taşı — Erzurum", "Lüle taşı — Eskişehir", "Volfram — Bursa/Uludağ", "Kükürt — Isparta/Keçiborlu", "Manganez — Antalya/Alanya"],
            4, "Manganez Ereğli'dendir; Alanya barit ve zımpara ile anılır."),
        q("Soru 80: Volframın temel kullanım amacı aşağıdakilerden hangisidir?",
            ["Sert ve dayanıklı metal üretiminde alaşım olarak kullanılması", "Gübre üretiminde kullanılması", "Cam yapımında kullanılması", "Petrol kuyularında basınç artırması", "Tarımda hastalık önlemesi"],
            0, "Volfram (tungsten) sert metal alaşımlarında kullanılır."),
        q("Soru 81: Türkiye'de volfram çıkarılan merkez aşağıdakilerden hangisidir?",
            ["Bursa – Uludağ", "Erzurum – Oltu", "Eskişehir – Sivrihisar", "İzmir – Karaburun", "Zonguldak – Ereğli"],
            0, "Volfram Bursa–Uludağ'dan çıkarılır."),
        q("Soru 82: Feldspatın kullanım alanları arasında aşağıdakilerden hangisi bulunur?",
            ["Cam", "Seramik", "Boya", "Plastik", "Hepsi"],
            4, "Feldspat cam, seramik, boya ve plastik sanayisinde kullanılır."),
        q("Soru 83: Türkiye'de feldspat çıkarılan merkezler aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Aydın – Kütahya – Yozgat", "İzmir – Ankara – Bayburt", "Nevşehir – Kayseri – Bursa", "Elazığ – Sivas – Malatya", "Antalya – Mersin – Adana"],
            0, "Feldspat Aydın, Kütahya ve Yozgat'tan çıkarılır."),
        q("Soru 84: Zımpara taşının temel kullanım amacı aşağıdakilerden hangisidir?",
            ["Zımparalama ve parlatma", "Gübre üretimi", "Çelik üretimi", "Cam üretimi", "Petrol kuyularında basınç artırma"],
            0, "Zımpara taşı zımparalama ve parlatmada kullanılır."),
        q("Soru 85: Türkiye'de zımpara taşı çıkarılan merkezler aşağıdakilerin hangisinde doğru verilmiştir?",
            ["Aydın – Alanya", "İzmir – Ankara", "Bursa – Yozgat", "Erzurum – Bayburt", "Sivas – Elazığ"],
            0, "Zımpara Aydın ve Alanya'dan çıkarılır."),
        q("Soru 86: Türkiye'de çıkarılan zımpara taşıyla ilgili aşağıdakilerden hangisi doğrudur?",
            ["İhraç edilmektedir.", "Yalnızca iç tüketimde kullanılır.", "Türkiye'de çıkarılmaz.", "Yalnızca gübre üretiminde kullanılır.", "Rezervi tamamen tükenmiştir."],
            0, "Zımpara taşı ihraç edilir."),
        q("Soru 87: Aşağıdaki madenlerden hangisi ile ilgili verilen çıkarıldığı yer – işlendiği yer – kuruluş gerekçesi eşleştirmesi doğrudur?",
            ["Boksit — Akseki — Seydişehir — İşleme merkezi", "Bakır — Divriği — Samsun — Taş kömürüne yakınlık", "Bor — Guleman — Antalya — Ulaşım", "Demir — Küre — Karabük — Ham maddeye yakınlık", "Krom — Mazıdağı — Bandırma — Cam sanayisi"],
            0, "Boksit Akseki'den çıkarılıp Seydişehir'de işlenir."),
        q("Soru 88: Aşağıdaki madenlerden hangisinin çıkarıldığı yer ile işlendiği yer aynı değildir?",
            ["Fosfat", "Boksit", "Trona", "Bor", "Hepsi"],
            4, "Boksit, trona ve bor farklı merkezlerde işlenir; fosfat Mazıdağı'nda hem çıkarılır hem işlenir ancak şıklar içinde 'hepsi' işaretlenmiştir — sınavda boksit/trona/bor ayrımı sorulur."),
        q("Soru 89: Aşağıdaki madenlerden hangisinin işlenmesinde ulaşım olanaklarının ön plana çıktığı merkezler doğru verilmiştir?",
            ["Demir — İskenderun; Bakır — Samsun; Krom — Antalya", "Demir — Karabük; Bor — Kırka; Fosfat — Mazıdağı", "Boksit — Seydişehir; Demir — Karabük; Krom — Elazığ", "Bor — Bandırma; Fosfat — Mazıdağı; Trona — Kazan", "Krom — Elazığ; Boksit — Seydişehir; Bakır — Samsun"],
            0, "İskenderun, Samsun ve Antalya ulaşım avantajıyla öne çıkan işleme merkezleridir."),
        q("Soru 90: Aşağıdaki madenlerden hangileri Türkiye'nin dünya ölçeğinde önemli rezervlere sahip olduğu ve ihracat yaptığı madenler arasında birlikte değerlendirilebilir?",
            ["Bor – Krom – Barit", "Fosfat – Asbest – Toryum", "Uranyum – Fosfat – Cıva", "Manganez – Kurşun – Çinko", "Trona – Tuz – Pomza"],
            0, "Bor, krom ve barit rezervi fazla olup ihraç edilir."),
        q("Soru 91: Aşağıdaki madenlerden hangisinin kullanım alanı yanlış verilmiştir?",
            ["Bor — İhracat", "Barit — Petrol kuyularında basınç artırma", "Manganez — Çeliğe sertlik verme", "Fosfat — Gübre", "Oltu taşı — Çelik üretimi"],
            4, "Oltu taşı takı ve süs eşyası içindir, çelik üretiminde kullanılmaz."),
        q("Soru 92: Aşağıdaki madenlerden hangileri sanayi sektörlerinde kullanılan madenler arasında birlikte değerlendirilebilir?\n\nI. Bor\nII. Feldspat\nIII. Trona\nIV. Boksit\nV. Krom",
            ["I ve II", "II ve III", "I, II ve III", "II, III, IV ve V", "I, II, III, IV ve V"],
            4, "Beşi de sanayide kullanılır."),
        q("Soru 93: Aşağıdaki eşleştirmelerden hangisi yanlıştır?",
            ["Cıva — Karaburun", "Kükürt — Keçiborlu", "Volfram — Uludağ", "Uranyum — Sorgun", "Toryum — Sivrihisar'da işletilmektedir"],
            4, "Toryum Sivrihisar'da bulunur ama işletilmez."),
        q("Soru 94: Bir öğrenci Türkiye'deki madenlerle ilgili şu eşleştirmeleri yapmıştır:\n\nI. Demir → Divriği\nII. Bakır → Küre\nIII. Boksit → Akseki\nIV. Krom → Guleman\nV. Bor → Kırka\n\nBu eşleştirmelerden hangileri doğrudur?",
            ["I ve II", "II ve III", "I, II ve III", "II, III, IV ve V", "I, II, III, IV ve V"],
            4, "Beş eşleştirme de notlara uygundur (Kırka bor işleme/çıkarım kuşağındadır)."),
        q("Soru 95: Aşağıdakilerden hangisi Türkiye'deki madenler bakımından diğerlerinden farklı bir özellik taşımaktadır?",
            ["Bor — Dünya rezervlerinin yaklaşık %72'si", "Krom — Rezervi fazla ve ihraç ediliyor", "Barit — Rezervi fazla ve ihraç ediliyor", "Fosfat — Rezervi çok az", "Mermer — Rezervi çok az"],
            4, "Mermer rezervi çok fazladır; 'çok az' ifadesi yanlıştır."),
        q("Soru 96: Aşağıdaki madenlerden hangisinin kullanım alanı ile çıkarıldığı yer birlikte düşünüldüğünde doğru eşleştirilmiştir?",
            ["Zımpara taşı — Aydın/Alanya — Zımparalama ve parlatma", "Oltu taşı — Eskişehir — Pipo yapımı", "Lüle taşı — Erzurum — Takı yapımı", "Manganez — Antalya — Çeliğe sertlik verme", "Kükürt — Bursa — Bağcılık ve kayısıcılık"],
            0, "Zımpara Aydın ve Alanya'dan çıkarılır; zımparalama-parlatmada kullanılır."),
        q("Soru 97: Türkiye'deki bazı madenlerin çıkarılma ve işlenme merkezleri şu şekildedir:\n\nDemir → Karabük, Ereğli, İskenderun\nBakır → Samsun\nKrom → Elazığ, Antalya\nBor → Kırka, Bandırma\n\nBu merkezlerin kuruluşunda aşağıdakilerden hangisinin doğrudan etkili olduğu söylenemez?",
            ["Ulaşım", "Ham maddeye yakınlık", "Enerji kaynağına yakınlık", "İşleme tesislerinin konumu", "Tropikal iklim koşulları"],
            4, "Türkiye'de tropikal iklim, maden işleme yeri seçiminde etken değildir."),
        q("Soru 98: Aşağıdaki madenlerden hangisi hem kullanım alanı hem de Türkiye'deki üretim merkezi bakımından diğerlerinden ayrılır?",
            ["Kükürt — Keçiborlu — Bağcılık/kayısıcılık", "Manganez — Ereğli — Çelik", "Barit — Alanya — Petrol kuyuları", "Oltu taşı — Erzurum — Takı ve süs eşyası", "Fosfat — Mazıdağı — Gübre"],
            3, "Oltu taşı süs/takı madenidir; diğerleri ağır sanayi veya tarım hammaddesidir."),
        q("Soru 99: Türkiye'deki madenlerle ilgili;\n\nI. Türkiye'de maden çeşidi fazla, miktarı azdır.\nII. Yukarı Fırat maden çeşitliliğinin en fazla olduğu alandır.\nIII. Bor rezervlerinin yaklaşık %72'si Türkiye'dedir.\nIV. Fosfat rezervleri Türkiye'de çok fazladır.\nV. Krom Türkiye'den ihraç edilmektedir.\n\nyargılarından hangileri doğrudur?",
            ["I ve II", "II ve III", "I, II ve III", "I, II, III ve V", "I, II, III, IV ve V"],
            3, "IV yanlıştır; fosfat rezervi azdır."),
        q("Soru 100: Aşağıdaki madenlerden hangisiyle ilgili verilen bilgilerden tamamı doğrudur?",
            ["Toryum: Eskişehir-Sivrihisar — Nükleer enerji — Henüz işletilmiyor", "Uranyum: Eskişehir-Sivrihisar — Cam sanayisi — İhraç ediliyor", "Fosfat: Mazıdağı — Çelik sanayisi — Rezervi çok fazla", "Cıva: Sorgun — Gübre üretimi — Katı hâldedir", "Manganez: Ereğli — Pipo yapımı — Yanmazlık özelliğine sahiptir"],
            0, "Toryum Sivrihisar'da bulunur, nükleer enerjiyle ilişkilidir ve henüz işletilmez.")
    ];
})();
