// sorular/cografya-25.js
window.cografya_25_sorulari = (function () {
    var L = ["A", "B", "C", "D", "E"];
    function q(stem, opts, i, exp) {
        return {
            question: stem,
            options: opts.map(function (t, n) { return L[n] + ") " + t; }),
            correctAnswerIndex: i,
            explanation: exp
        };
    }
    return [
        q("Soru 1: Türkiye'de yaz turizminin özellikle Ege ve Akdeniz kıyılarında gelişmesinde aşağıdakilerden hangisinin etkisi daha fazladır?",
            ["Kış sıcaklıklarının düşük olması", "Yaz sıcaklıklarının yüksek olması", "Yükseltinin kısa mesafede artması", "Kar yağışlı gün sayısının fazla olması", "Günlük sıcaklık farklarının fazla olması"],
            1, "Yaz sıcaklığının yüksek olması Ege ve Akdeniz kıyılarında deniz turizmini kolaylaştırmıştır."),
        q("Soru 2: Aşağıdaki merkezlerden hangisi Türkiye'nin yaz turizmi açısından öne çıkan merkezleri arasında yer almaz?",
            ["Didim", "Kuşadası", "Marmaris", "Palandöken", "Bodrum"],
            3, "Palandöken Erzurum'daki kayak merkezidir; yaz (deniz-kum-güneş) turizmi merkezi değildir."),
        q("Soru 3: Aşağıdaki eşleştirmelerden hangisi yaz turizmi açısından yanlıştır?",
            ["Antalya – Kemer", "Muğla – Marmaris", "Aydın – Didim", "Antalya – Alanya", "Bursa – Bodrum"],
            4, "Bodrum Muğla'dadır; Bursa yaz turizmi merkezi olarak Bodrum ile eşleştirilmez."),
        q("Soru 4: Aşağıdaki merkezlerden hangisi Muğla'nın yaz turizmi merkezlerinden biridir?",
            ["Didim", "Kemer", "Gökova", "Kuşadası", "Finike"],
            2, "Muğla'nın yaz turizmi merkezleri Bodrum, Marmaris ve Gökova'dır."),
        q("Soru 5: Kemer, Side, Alanya ve Finike aşağıdaki illerden hangisinin yaz turizmi merkezleridir?",
            ["Muğla", "Antalya", "Aydın", "İzmir", "Mersin"],
            1, "Kemer, Side, Alanya ve Finike Antalya'nın yaz turizmi merkezleridir."),
        q("Soru 6: Aşağıdaki merkez–il eşleştirmelerinden hangisi doğrudur?",
            ["Didim – Antalya", "Bodrum – Aydın", "Kuşadası – Aydın", "Marmaris – Antalya", "Kemer – Muğla"],
            2, "Kuşadası ve Didim Aydın'a; Bodrum ve Marmaris Muğla'ya; Kemer Antalya'ya aittir."),
        q("Soru 7: Aşağıdaki kayak merkezi–il eşleştirmelerinden hangisi yanlıştır?",
            ["Uludağ – Bursa", "Erciyes – Kayseri", "Palandöken – Erzurum", "Sarıkamış – Kars", "Kartalkaya – Kastamonu"],
            4, "Kartalkaya Bolu'dadır. Kastamonu'daki kayak merkezi Ilgaz'dır."),
        q("Soru 8: Türkiye'deki kayak merkezlerinden hangisi Erzurum'da bulunmaktadır?",
            ["Ilgaz", "Elmadağ", "Palandöken", "Davras", "Sarıkamış"],
            2, "Palandöken Erzurum'dadır."),
        q("Soru 9: Aşağıdaki kayak merkezi–il eşleştirmelerinden hangisi doğrudur?",
            ["Davras – Isparta", "Saklıkent – Bolu", "Ladik – Kastamonu", "Ilgaz – Ankara", "Elmadağ – Antalya"],
            0, "Davras Isparta'dadır. Saklıkent Antalya, Ladik Samsun, Ilgaz Kastamonu, Elmadağ Ankara'dadır."),
        q("Soru 10: Uludağ, Erciyes, Palandöken ve Sarıkamış aşağıdaki illerden hangileriyle doğru eşleştirilmiştir?",
            ["Bursa – Kayseri – Erzurum – Kars", "Bursa – Konya – Erzurum – Ardahan", "Bolu – Kayseri – Kars – Erzurum", "Bursa – Ankara – Erzurum – Kars", "Bursa – Kayseri – Sivas – Kars"],
            0, "Uludağ Bursa, Erciyes Kayseri, Palandöken Erzurum, Sarıkamış Kars'tadır."),
        q("Soru 11: Aşağıdakilerden hangisi Ankara'daki kayak merkezidir?",
            ["Kartalkaya", "Elmadağ", "Ilgaz", "Davras", "Ladik"],
            1, "Ankara'daki kayak merkezi Elmadağ'dır."),
        q("Soru 12: Aşağıdaki kayak merkezlerinden hangisi Karadeniz Bölgesi'nde yer alan illerden biriyle eşleştirilmiştir?",
            ["Erciyes – Kayseri", "Palandöken – Erzurum", "Kartalkaya – Bolu", "Davras – Isparta", "Sarıkamış – Kars"],
            2, "Kartalkaya Bolu'dadır ve Bolu Karadeniz Bölgesi'ndedir."),
        q("Soru 13: Saklıkent ve Davras kayak merkezleri aşağıdaki illerden hangileriyle eşleştirilmelidir?",
            ["Antalya – Isparta", "Antalya – Burdur", "Muğla – Isparta", "Antalya – Afyonkarahisar", "İzmir – Isparta"],
            0, "Saklıkent Antalya, Davras Isparta'dadır."),
        q("Soru 14: Aşağıdaki kayak merkezlerinden hangisi Samsun ilinde bulunmaktadır?",
            ["Ilgaz", "Ladik", "Elmadağ", "Kartalkaya", "Davras"],
            1, "Ladik Samsun'dadır."),
        q("Soru 15: Kastamonu'daki kayak merkezi aşağıdakilerden hangisidir?",
            ["Kartalkaya", "Uludağ", "Ilgaz", "Sarıkamış", "Erciyes"],
            2, "Kastamonu'daki kayak merkezi Ilgaz'dır."),
        q("Soru 16: Aşağıdaki eşleştirmelerden hangisi inanç turizmi açısından doğrudur?",
            ["Meryem Ana Evi – İzmir", "Balıklıgöl – Konya", "Mevlana Müzesi – Van", "Akdamar Kilisesi – Mardin", "Deyrülzafaran Manastırı – Trabzon"],
            0, "Meryem Ana Evi İzmir'dedir. Balıklıgöl Şanlıurfa, Mevlana Konya, Akdamar Van, Deyrülzafaran Mardin'dedir."),
        q("Soru 17: Hristiyanlık açısından kutsal kabul edilen Meryem Ana Evi aşağıdaki illerden hangisindedir?",
            ["Antalya", "İzmir", "Trabzon", "Van", "Mardin"],
            1, "Meryem Ana Evi İzmir'dedir."),
        q("Soru 18: Noel Baba olarak bilinen Aziz Nikolaos ile ilişkilendirilen kilise aşağıdaki merkezlerden hangisindedir?",
            ["Demre", "Kuşadası", "Söğüt", "Safranbolu", "Tuşpa"],
            0, "St. Nicholas Kilisesi Antalya'nın Demre ilçesindedir."),
        q("Soru 19: Hz. İbrahim'in ateşe atıldığı yer olduğuna inanılan Balıklıgöl aşağıdaki illerden hangisindedir?",
            ["Mardin", "Şanlıurfa", "Konya", "Adıyaman", "Gaziantep"],
            1, "Balıklıgöl Şanlıurfa'dadır."),
        q("Soru 20: Aşağıdaki inanç turizmi merkezi–il eşleştirmelerinden hangisi yanlıştır?",
            ["Sümela Manastırı – Trabzon", "Mevlana Müzesi – Konya", "Akdamar Kilisesi – Van", "Deyrülzafaran Manastırı – Mardin", "Balıklıgöl – Antalya"],
            4, "Balıklıgöl Şanlıurfa'dadır, Antalya'da değildir."),
        q("Soru 21: Mevlana Celaleddin-i Rumi'nin türbesinin bulunduğu Mevlana Müzesi aşağıdaki illerden hangisindedir?",
            ["Kayseri", "Konya", "Nevşehir", "Çorum", "Aksaray"],
            1, "Mevlana Müzesi Konya'dadır."),
        q("Soru 22: Akdamar Kilisesi aşağıdaki illerden hangisinde bulunmaktadır?",
            ["Van", "Mardin", "Trabzon", "İzmir", "Şanlıurfa"],
            0, "Akdamar Kilisesi Van'dadır."),
        q("Soru 23: Deyrülzafaran Manastırı aşağıdaki kültürel unsurlardan hangisiyle doğru biçimde ilişkilendirilmiştir?",
            ["Mardin – Süryani kadim manastırı", "Van – Ermeni mimarisi", "Trabzon – Karadeniz manastırı", "İzmir – Hristiyanlık merkezi", "Konya – Mevlevilik merkezi"],
            0, "Deyrülzafaran, Mardin'deki Süryani kadim manastırıdır."),
        q("Soru 24: Manyas Gölü ve Kızılırmak Deltası aşağıdaki turizm türlerinden hangisiyle daha çok ilişkilidir?",
            ["Golf turizmi", "Kuş gözlemciliği", "Kongre turizmi", "Yat turizmi", "Termal turizm"],
            1, "Manyas Gölü ve Kızılırmak Deltası kuş gözlemciliği alanlarıdır."),
        q("Soru 25: Antalya'nın Toroslar kesimi ile Doğu Karadeniz aşağıdaki alternatif turizm türlerinden hangisi için öne çıkar?",
            ["Botanik turizmi", "Kruvaziyer turizmi", "Kongre turizmi", "Golf turizmi", "Sağlık turizmi"],
            0, "Botanik turizmi Antalya (Toroslar) ve Doğu Karadeniz'de öne çıkar."),
        q("Soru 26: Aşağıdakilerden hangisi trekking turizminin Türkiye'deki önemli alanlarından biridir?",
            ["Karadeniz Bölgesi", "Güneydoğu Anadolu'nun ovaları", "Tuz Gölü çevresi", "Konya Ovası", "Ergene Havzası"],
            0, "Trekking (doğa yürüyüşü) özellikle Karadeniz Bölgesi'nde gelişmiştir."),
        q("Soru 27: Aşağıdaki akarsulardan hangisi Türkiye'de rafting turizmiyle ilişkilendirilen akarsulardan biri değildir?",
            ["Çoruh", "Manavgat", "Dalaman", "Fırtına", "Meriç"],
            4, "Rafting: Çoruh, Manavgat, Dalaman, Fırtına, Fırat, Kızılırmak. Meriç bu listede yoktur."),
        q("Soru 28: Çoruh, Manavgat, Dalaman, Fırtına, Fırat ve Kızılırmak aşağıdaki turizm türlerinden hangisiyle ilişkilidir?",
            ["Yat turizmi", "Rafting", "Golf", "Termal turizm", "Kongre turizmi"],
            1, "Bu akarsular rafting turizmiyle ilişkilendirilir."),
        q("Soru 29: Türkiye'de golf turizmi açısından öne çıkan merkezlerden biri aşağıdakilerden hangisidir?",
            ["Belek", "Sarıkamış", "Demre", "Tuşpa", "Söğüt"],
            0, "Golf turizminde Antalya-Belek öne çıkar; ayrıca Ankara, İstanbul ve İzmir de verilir."),
        q("Soru 30: Aşağıdakilerden hangisi verilen bilgilere göre golf turizmiyle ilişkilendirilen merkezlerden biri değildir?",
            ["Antalya", "Ankara", "İstanbul", "İzmir", "Trabzon"],
            4, "Golf: Antalya (Belek), Ankara, İstanbul, İzmir. Trabzon bu listede yoktur."),
        q("Soru 31: \"Yüzen otel\" ifadesi aşağıdaki turizm türlerinden hangisini tanımlamak için kullanılmaktadır?",
            ["Yat turizmi", "Kruvaziyer turizmi", "Kongre turizmi", "Sağlık turizmi", "Termal turizm"],
            1, "Kruvaziyer turizmi yüzen otel olarak tanımlanır."),
        q("Soru 32: İstanbul ve Kuşadası aşağıdaki alternatif turizm türlerinden hangisinin önemli merkezleri arasında gösterilebilir?",
            ["Kruvaziyer turizmi", "Botanik turizmi", "Termal turizm", "Trekking", "Golf turizmi"],
            0, "Kruvaziyer turizminin önemli merkezleri İstanbul ve Kuşadası'dır."),
        q("Soru 33: Bodrum, Marmaris ve Göcek aşağıdaki turizm türlerinden hangisi açısından özellikle önemlidir?",
            ["Yat turizmi", "İnanç turizmi", "Termal turizm", "Kongre turizmi", "Kuş gözlemciliği"],
            0, "Yat turizmi güneybatı Ege kıyılarında (Bodrum, Marmaris, Göcek) yoğundur."),
        q("Soru 34: Aşağıdakilerden hangisi Türkiye'deki termal turizm merkezlerinden biri olarak verilen yerlerden değildir?",
            ["Yalova", "Bursa", "Afyon", "Kütahya", "Kars"],
            4, "Termal turizm: Yalova, Bursa, Afyon, İzmir, Kütahya. Kars bu listede yoktur."),
        q("Soru 35: Yalova, Bursa, Afyon, İzmir ve Kütahya aşağıdaki turizm türlerinden hangisiyle ilişkilidir?",
            ["Termal turizm", "Yat turizmi", "Golf turizmi", "Kruvaziyer turizmi", "Kuş gözlemciliği"],
            0, "Bu iller termal turizm merkezleridir."),
        q("Soru 36: Verilen bilgilere göre sağlık turizmi açısından öne çıkan il aşağıdakilerden hangisidir?",
            ["İstanbul", "Kars", "Çorum", "Kastamonu", "Burdur"],
            0, "Sağlık turizmi açısından öne çıkan il İstanbul'dur."),
        q("Soru 37: İstanbul ve Antalya'nın ortak olarak öne çıktığı alternatif turizm türü aşağıdakilerden hangisidir?",
            ["Kongre turizmi", "Rafting", "Kuş gözlemciliği", "Termal turizm", "Botanik turizmi"],
            0, "Kongre turizminin öne çıkan merkezleri İstanbul ve Antalya'dır."),
        q("Soru 38: Urartu turizm gelişim bölgesi aşağıdaki merkezlerden hangisiyle ilişkilendirilmiştir?",
            ["Çorum", "Van (Tuşpa)", "Çanakkale", "Bursa", "Aydın"],
            1, "Urartu turizm gelişim bölgesi Van (Tuşpa) ile ilişkilidir."),
        q("Soru 39: Aşağıdaki turizm gelişim bölgesi–il eşleştirmelerinden hangisi doğrudur?",
            ["Kapadokya – Çorum", "Hitit – Nevşehir", "Troya – Çanakkale", "Aphrodisias – Bursa", "Urartu – Aydın"],
            2, "Troya Çanakkale'dedir. Kapadokya Nevşehir, Hitit Çorum, Aphrodisias Aydın, Urartu Van'dadır."),
        q("Soru 40: Gaziantep, Adıyaman, Mardin ve Şanlıurfa aşağıdaki turizm gelişim bölgelerinden hangisiyle ilişkilendirilmiştir?",
            ["Frigya", "GAP", "Urartu", "Troya", "Kapadokya"],
            1, "GAP turizm gelişim bölgesi Gaziantep, Adıyaman, Mardin ve Şanlıurfa'yı kapsar."),
        q("Soru 41: Kapadokya turizm gelişim bölgesi aşağıdaki illerden hangisiyle eşleştirilmiştir?",
            ["Nevşehir", "Çorum", "Aydın", "Van", "Manisa"],
            0, "Kapadokya turizm gelişim bölgesi Nevşehir ile eşleştirilmiştir."),
        q("Soru 42: Hitit turizm gelişim bölgesi aşağıdaki illerden hangisiyle ilişkilendirilmiştir?",
            ["Kütahya", "Çorum", "Bursa", "Antalya", "Malatya"],
            1, "Hitit turizm gelişim bölgesi Çorum'dadır."),
        q("Soru 43: Aşağıdaki turizm gelişim bölgelerinden hangisi birden fazla ili kapsayan Batı Anadolu merkezli bir tarihî-kültürel alan olarak verilmiştir?",
            ["Frigya", "Urartu", "Kapadokya", "Hitit", "Troya"],
            0, "Frigya Kütahya, Uşak ve Afyon'u kapsar."),
        q("Soru 44: Kütahya, Uşak ve Afyon aşağıdaki turizm gelişim bölgelerinden hangisinin kapsamındadır?",
            ["GAP", "Frigya", "Urartu", "Kapadokya", "Aphrodisias"],
            1, "Frigya: Kütahya, Uşak, Afyon."),
        q("Soru 45: Aşağıdaki eşleştirmelerden hangisi yanlıştır?",
            ["Söğüt – Bursa", "Aphrodisias – Aydın", "Troya – Çanakkale", "Göller Yöresi Ekoturizm – Isparta ve Burdur civarı", "Söğüt – Van"],
            4, "Söğüt Bursa ile ilişkilidir; Van Urartu (Tuşpa) alanıdır."),
        q("Soru 46: Batı Karadeniz Ekoturizm gelişim bölgesi aşağıdaki alanlardan hangisiyle ilişkilidir?",
            ["Batı Karadeniz Bölgesi", "Güneydoğu Anadolu Bölgesi", "İç Anadolu'nun güneyi", "Doğu Anadolu'nun doğusu", "Ege kıyıları"],
            0, "Batı Karadeniz Ekoturizm, Batı Karadeniz Bölgesi ile ilişkilidir."),
        q("Soru 47: Isparta ve Burdur civarını kapsayan turizm gelişim bölgesi aşağıdakilerden hangisidir?",
            ["Batı Karadeniz Ekoturizm", "Göller Yöresi Ekoturizm", "Frigya", "GAP", "Urartu"],
            1, "Göller Yöresi Ekoturizm Isparta ve Burdur civarını kapsar."),
        q("Soru 48: Aşağıdaki UNESCO Dünya Kültür Mirası alanlarından hangisi Çorum ilinde bulunmaktadır?",
            ["Hattuşaş", "Göbeklitepe", "Arslantepe", "Gordion", "Troya"],
            0, "Hattuşaş (Hitit başkenti) Çorum'dadır."),
        q("Soru 49: Safranbolu Şehri aşağıdaki illerden hangisindedir?",
            ["Kastamonu", "Karabük", "Bolu", "Çorum", "Zonguldak"],
            1, "Safranbolu Karabük'tedir."),
        q("Soru 50: Aşağıdaki UNESCO miras alanlarından hangisi Adıyaman ilindedir?",
            ["Nemrut Dağı", "Göbeklitepe", "Arslantepe", "Gordion", "Çatalhöyük"],
            0, "Nemrut Dağı Adıyaman'dadır."),
        q("Soru 51: Xanthos-Letoon aşağıdaki illerden hangileriyle ilişkilendirilmiştir?",
            ["Antalya – Muğla", "İzmir – Aydın", "Antalya – Burdur", "Muğla – Aydın", "Çanakkale – Balıkesir"],
            0, "Xanthos-Letoon Antalya–Muğla ile ilişkilidir."),
        q("Soru 52: Divriği Ulu Camii ve Darüşşifası aşağıdaki illerden hangisinde bulunmaktadır?",
            ["Erzincan", "Sivas", "Malatya", "Kayseri", "Tokat"],
            1, "Divriği Ulu Camii ve Darüşşifası Sivas'tadır."),
        q("Soru 53: Truva (Troya) Antik Kenti aşağıdaki illerden hangisindedir?",
            ["İzmir", "Muğla", "Çanakkale", "Antalya", "Aydın"],
            2, "Troya Antik Kenti Çanakkale'dedir."),
        q("Soru 54: Çatalhöyük aşağıdaki illerden hangisinde bulunmaktadır?",
            ["Konya", "Nevşehir", "Ankara", "Çorum", "Aksaray"],
            0, "Çatalhöyük Konya'dadır."),
        q("Soru 55: Cumalıkızık aşağıdaki illerden hangisiyle ilişkilendirilmiştir?",
            ["Bursa", "Bilecik", "Balıkesir", "Kütahya", "Sakarya"],
            0, "Cumalıkızık Bursa'dadır."),
        q("Soru 56: Pamukkale (Hierapolis) aşağıdaki illerden hangisindedir?",
            ["Aydın", "Denizli", "İzmir", "Muğla", "Manisa"],
            1, "Pamukkale (Hierapolis) Denizli'dedir."),
        q("Soru 57: Göreme Milli Parkı ve Kapadokya aşağıdaki illerden hangisiyle ilişkilendirilmiştir?",
            ["Nevşehir", "Niğde", "Kayseri", "Aksaray", "Konya"],
            0, "Göreme Milli Parkı (Kapadokya) Nevşehir ile ilişkilendirilmiştir."),
        q("Soru 58: Bergama Çok Katmanlı Kültürel Peyzajı aşağıdaki illerden hangisindedir?",
            ["Manisa", "İzmir", "Aydın", "Muğla", "Çanakkale"],
            1, "Bergama İzmir'dedir."),
        q("Soru 59: Diyarbakır Kalesi ve Surları ile Hevsel Bahçeleri aşağıdaki illerden hangisiyle ilişkilidir?",
            ["Mardin", "Şanlıurfa", "Diyarbakır", "Adıyaman", "Gaziantep"],
            2, "Diyarbakır Kalesi, surları ve Hevsel Bahçeleri Diyarbakır'dadır."),
        q("Soru 60: Afrodisias Antik Kenti aşağıdaki illerden hangisindedir?",
            ["Aydın", "Denizli", "İzmir", "Manisa", "Muğla"],
            0, "Afrodisias Aydın'dadır."),
        q("Soru 61: Göbeklitepe aşağıdaki illerden hangisinde bulunmaktadır?",
            ["Adıyaman", "Şanlıurfa", "Mardin", "Gaziantep", "Diyarbakır"],
            1, "Göbeklitepe Şanlıurfa'dadır."),
        q("Soru 62: Arslantepe aşağıdaki illerden hangisiyle eşleştirilmiştir?",
            ["Elazığ", "Malatya", "Tunceli", "Adıyaman", "Erzincan"],
            1, "Arslantepe Malatya'dadır."),
        q("Soru 63: Gordion Antik Kenti aşağıdaki illerden hangisinin sınırları içerisindedir?",
            ["Ankara", "Eskişehir", "Kütahya", "Çorum", "Konya"],
            0, "Gordion Ankara (Polatlı) sınırlarındadır."),
        q("Soru 64: Sardes Antik Kenti aşağıdaki illerden hangisinde bulunmaktadır?",
            ["Aydın", "İzmir", "Manisa", "Denizli", "Muğla"],
            2, "Sardes Manisa'dadır."),
        q("Soru 65: Aşağıdaki UNESCO miras alanı–il eşleştirmelerinden hangisi yanlıştır?",
            ["Çatalhöyük – Konya", "Göbeklitepe – Şanlıurfa", "Arslantepe – Malatya", "Gordion – Ankara", "Sardes – Aydın"],
            4, "Sardes Manisa'dadır, Aydın'da değildir."),
        q("Soru 66: Aşağıdakilerden hangisi UNESCO Dünya Kültür Mirası Listesi'nde yer alan alanlardan biriyle doğru eşleştirilmiştir?",
            ["Hattuşaş – Çorum", "Nemrut Dağı – Şanlıurfa", "Göbeklitepe – Adıyaman", "Arslantepe – Elazığ", "Troya – İzmir"],
            0, "Hattuşaş Çorum'dadır. Nemrut Adıyaman, Göbeklitepe Şanlıurfa, Arslantepe Malatya, Troya Çanakkale'dedir."),
        q("Soru 67: Aşağıdakilerden hangisi Anadolu'nun Ortaçağ Dönemi Ahşap Hipostil Camileri arasında gösterilen yapılardan biridir?",
            ["Eşrefoğlu Camii", "Selimiye Camii", "Süleymaniye Camii", "Hacı Bayram Camii", "Yeni Camii"],
            0, "Eşrefoğlu Camii (Konya) ahşap hipostil camilerdendir."),
        q("Soru 68: Eşrefoğlu Camii aşağıdaki illerden hangisindedir?",
            ["Konya", "Eskişehir", "Kastamonu", "Afyonkarahisar", "Ankara"],
            0, "Eşrefoğlu Camii Konya'dadır."),
        q("Soru 69: Aşağıdaki cami–il eşleştirmelerinden hangisi doğrudur?",
            ["Ahi Şerafettin Camii – Eskişehir", "Eşrefoğlu Camii – Kastamonu", "Mahmutbey Camii – Konya", "Afyonkarahisar Ulu Camii – Ankara", "Ahi Şerafettin Camii – Afyonkarahisar"],
            0, "Ahi Şerafettin Camii Eskişehir'dedir."),
        q("Soru 70: Mahmutbey Camii aşağıdaki illerden hangisinde bulunmaktadır?",
            ["Bolu", "Kastamonu", "Çorum", "Eskişehir", "Bursa"],
            1, "Mahmutbey Camii Kastamonu'dadır."),
        q("Soru 71: Aşağıdakilerden hangisi Anadolu'nun Ortaçağ Dönemi Ahşap Hipostil Camileri arasında yer alan yapılardan değildir?",
            ["Eşrefoğlu Camii", "Ahi Şerafettin Camii", "Afyonkarahisar Ulu Camii", "Mahmutbey Camii", "Divriği Ulu Camii"],
            4, "Divriği Ulu Camii UNESCO Dünya Mirası'dır; ahşap hipostil camiler listesinde yoktur."),
        q("Soru 72: Aşağıdaki camilerden hangisi Afyonkarahisar ilindedir?",
            ["Eşrefoğlu Camii", "Ahi Şerafettin Camii", "Afyonkarahisar Ulu Camii", "Mahmutbey Camii", "Ulucami-i Kebir"],
            2, "Afyonkarahisar Ulu Camii ilin adıyla anılan ahşap hipostil camidir."),
        q("Soru 73: Aşağıdaki eşleştirmelerden hangisinde verilen yer ile turizm türü yanlış eşleştirilmiştir?",
            ["Manyas Gölü – Kuş gözlemciliği", "Belek – Golf", "Bodrum – Yat turizmi", "Yalova – Termal turizm", "Palandöken – Kruvaziyer turizmi"],
            4, "Palandöken kış (kayak) turizmidir; kruvaziyer İstanbul ve Kuşadası ile ilişkilidir."),
        q("Soru 74: Aşağıdaki seçeneklerin hangisinde üç farklı turizm türüne ait merkezler birlikte verilmiştir?",
            ["Belek – Manyas – Bodrum", "Uludağ – Erciyes – Palandöken", "Demre – Mevlana – Akdamar", "Hattuşaş – Troya – Göbeklitepe", "Safranbolu – Çatalhöyük – Arslantepe"],
            0, "Belek golf, Manyas kuş gözlemciliği, Bodrum yat turizmidir."),
        q("Soru 75: Aşağıdakilerden hangisinde verilen merkezlerin tamamı inanç turizmi kapsamında değerlendirilmiştir?",
            ["Balıklıgöl – Mevlana Müzesi – Akdamar Kilisesi", "Bodrum – Marmaris – Göcek", "Belek – Ankara – İstanbul", "Manyas – Kızılırmak Deltası – Çoruh", "Yalova – Bursa – Afyon"],
            0, "Balıklıgöl, Mevlana Müzesi ve Akdamar Kilisesi inanç turizmi merkezleridir."),
        q("Soru 76: Aşağıdakilerden hangisinde verilen merkezlerin tamamı kış turizmi ile ilişkilidir?",
            ["Uludağ – Erciyes – Palandöken", "Bodrum – Marmaris – Göcek", "Belek – İstanbul – İzmir", "Manyas – Kızılırmak Deltası – Fırtına", "Yalova – Bursa – Afyon"],
            0, "Uludağ, Erciyes ve Palandöken kayak merkezleridir."),
        q("Soru 77: Aşağıdaki seçeneklerin hangisinde verilen yerlerin tamamı UNESCO Dünya Kültür Mirası Listesi'nde bulunan alanlarla ilişkilidir?",
            ["Hattuşaş – Göbeklitepe – Troya", "Palandöken – Erciyes – Uludağ", "Bodrum – Marmaris – Göcek", "Belek – Ankara – İzmir", "Balıklıgöl – Demre – Göcek"],
            0, "Hattuşaş, Göbeklitepe ve Troya UNESCO Dünya Kültür Mirası alanlarıdır."),
        q("Soru 78: Aşağıdakilerden hangisinde turizm gelişim bölgesi ile UNESCO miras alanı doğru eşleştirilmiştir?",
            ["Troya – Troya Antik Kenti", "GAP – Uludağ", "Frigya – Göbeklitepe", "Urartu – Pamukkale", "Kapadokya – Sardes"],
            0, "Troya hem turizm gelişim bölgesi hem UNESCO mirasıdır (Çanakkale)."),
        q("Soru 79: Aşağıdaki illerden hangisi verilen notlarda hem yaz turizmi hem de kış turizmi ile ilişkilendirilmiştir?",
            ["Antalya", "Aydın", "Muğla", "Bursa", "Kars"],
            0, "Antalya yaz turizminde Kemer-Side-Alanya; kış turizminde Saklıkent ile ilişkilidir."),
        q("Soru 80: Aşağıdaki illerden hangisi verilen bilgilerde hem UNESCO Dünya Kültür Mirası hem de turizm gelişim bölgesi ile ilişkilendirilmiştir?",
            ["Çorum", "Van", "Bursa", "Aydın", "Kütahya"],
            0, "Çorum hem Hattuşaş (UNESCO) hem Hitit turizm gelişim bölgesidir.")
    ];
})();
